cooperative-computing-lab/cctools

dttools/src/Makefile
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/src/jx_match.h
dttools/src/jx_print.c
dttools/src/jx_print.h
dttools/src/jx_query.c
dttools/src/jx_querytools.c
dttools/src/jx_querytools.h

Adds JX fetch by URL or path
Adds JX select by boolean query
Adds JX project by arbitrary query
Adds JX schema retrieval
Adds JX object type-to-string
Fixes mislabeling of header file
Currently implemented functionality:
```
fetch(URL); || fetch(path);
select(bool-expr, [obj1, obj2, ...]);
project(expr, [obj1, obj2, ...]);
schema([obj1, obj2, ...]);
```

Adds JX querying functionality

---

work_queue/src/work_queue.c

A small thing, but it's bugging me:
Renamed unprotected symbols:
SUCCESS -> WQ_SUCCESS
WORKER_FAILURE -> WQ_WORKER_FAILURE
APP_FAILURE -> WQ_APP_FAILURE

WQ: Rename Unprotected Symbols

---

dttools/src/rmsummary.c

Fixes conversion factor. bps/1000 was incorrectly reported as Mbps. Now using /1000000.

fix Kbps -> Mbps in print rmonitor summary

---

dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll_internal.h
dttools/src/rmonitor_types.h
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor.c

The motivation is to discriminate slowdowns caused by machine load, IO, and memory swap. The implementation follows cpu_time, where at each time step we compute the change from accumulated values.

adds context switches to the resource_monitor

---

parrot/src/parrot_helper.c
work_queue/src/.gitignore

Pulling this out of the other PR, as it's higher priority (hard error blocking compilation). See #2327 for discussion

Fix for gettimeofday()

---

apps/wq_bwa_json/wq_bwa_json.py
work_queue/src/clients/python3/work_queue_server.py
work_queue/src/work_queue_json.c
work_queue/src/work_queue_json.h
work_queue/src/work_queue_server.c

Addresses the stats operation aspect of issue #2321 
Uses work_queue_get_stats to obtain some of the worker and task stats.

add status operation to WQ-JSON API

---

dttools/src/jx_parse.c
dttools/src/jx_test.c

Updated list and object parsing to be iterative instead of recursive.
This should reduce stack depth and address crashes in parsing large datasets per #2341
Still has a bug I haven't sorted out yet...

JX Iterative Parsing

---

dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/src/jx_parse.c
dttools/src/jx_test.c
dttools/test/jx.expected
dttools/test/jx.input

This turned into a semi-major refactor of JX functions. The main architectural change is in the way functions are evaluated. The function call operator is now oblivious to the particulars of different functions. The operation from `jx_eval_operator()` is immediately dispatched to `jx_eval_call()` with no further eval/checks. The latter was already switching on function name and all that, so this PR keeps all the function-related activities there. I also changed the convention for calling the C implementation of functions. Argument lists are **always** owned by the callee. In practice, this means that most functions have a `jx_eval()` as part of their dispatch, and each function implementation is responsible for deleting the arg list. The notable exceptions are @nkremerh's new functions, …

Refactor JX functions

---

batch_job/src/batch_job_cluster.c
doc/manuals/makeflow/index.md
dttools/src/rmsummary.h
makeflow/src/dag.c
makeflow/src/parser.c
makeflow/src/parser_make.c

Correctly set number of MPI processes for slurm

---

python_environments/python_package_run

When the environment directory is reused, this reduces the overhead of setting the environment by about 2 seconds.

python_package_run  do not perform unpack step every time

---

batch_job/src/batch_job_work_queue.c
dttools/src/Makefile
dttools/src/address.c
dttools/src/address.h
dttools/src/debug.c
dttools/src/debug.h
dttools/src/tlq_config.c
dttools/src/tlq_config.h
makeflow/src/makeflow.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

This allows for makeflows, masters, and workers to retrieve their TLQ URL from their local TLQ log server and to advertise their URLs to each other.
Makeflow and workers are passed a --tlq=<port> flag. Makeflow passes this port to the master (along with the path to the debug log) via the batch queue interface. Makeflow, WQ master, and WQ workers each look up their TLQ URL from their local log server via TCP connection.
This functionality is turned on only when the makeflow (by extension the master) or a worker have been given the --tlq option.
Rework of #2357

Adds TLQ URL retrieval to Makeflow, WQ Master, and WQ Worker

---

makeflow/src/parser_jx.c

Fixes  "resources": { "mpi-processes" n }   being ignored.

mpi-processes was not parsed when declared in jx

---

deltadb/src/Makefile
ftp_lite/src/Makefile
parrot/src/Makefile

Objects from executables were not being deleted.  Only those explicitly defined in $(OBJECTS )were

Clean deltadb, parrot and ftp_lite *.o files from executables

---

dataswarm/clients/python3/dataswarm.py

Add the following operations to the dataswarm client: 
task-submit, task-remove, task-retrieve
file-submit, file-commit, file-delete, file-copy
service-submit, service-delete
project-create, project-delete
status
wait

dataswarm: client: add operations to client

---

work_queue/src/bindings/perl/Work_Queue/Task.pm
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

Adds work_queue_task_file_command to work_queue.h. (Function existed in .c file.)
Changed cmd so that %% is replaced with cache name at worker. Before the contents of the file were read/writen from stdin/stdout, which was not supported by all commands.
Implementation bug: I did not change the original implementation when dealing with errors. If transfer command fails, worker disconnects and transfer is tried in another worker. If command is incorrect, or the file is not accessible, this will disconnect all workers. Ideally, we would simply fail or retry the task somewhere else.

wq third put/get fix

---

doc/man/md/resource_monitor.md
resource_monitor/src/resource_monitor.c
work_queue/src/work_queue.c

In recent tests, it was useful to measure the resources used by a process, and to indicate whether certain resources limits were broken,  but without terminating the process. 
This pr adds the --measure-only to the resource monitor. If a limit is broken, this information is included in the final summary, but the process continues as normal.
wq already had the capability of turning off the monitor enforcement by not declaring  a taks limits. This pr updates wq to use the --measure-only option of the monitor.

Monitor no enf

---

dttools/src/buffer.c
dttools/src/buffer.h
dttools/src/mq.c
dttools/src/mq.h
dttools/src/mq_poll_test.c
dttools/src/mq_store_test.c
dttools/src/mq_wait_test.c
dttools/test/TR_mq_store.sh

This PR adds support for sending/receiving of file descriptors via MQ. These could be regular files, pipes, `stdin`/`stdout`, etc. In the context of DataSwarm, this is useful for sending/receiving files and directories (e.g. spawn `tar` and hook the stdio stream to MQ). The library is designed to select over all the different file descriptors and handle both the TCP connections and send/recv fds asynchronously. I tried out a number of configurations and checked that everything is being sent properly, no busy waiting, etc. I included tests for most of the cases I can think of and everything seems to be working, so I think this is ready to try out in DataSwarm.
This PR took a while to get right, since there are a number of tricky bits.
- Support unknown-length streams (`tar` will output ??? …

Stream file descriptors via MQ

---

dataswarm/manager/dataswarm_blob_rep.h
dataswarm/manager/dataswarm_manager.h
dataswarm/manager/dataswarm_rpc.c
dataswarm/worker/dataswarm_blob_table.c
dataswarm/worker/dataswarm_blob_table.h
dataswarm/worker/dataswarm_worker.c

Getting the blob is reduced to one state.
The tricky part is the worker function that sends the contents. It has to create the rpc response before sending the contents of the blob. However, on error we want it to behave as any other rpc. I added an *argument that indicates whether the dispatcher should send a response of its own.
The other minor issue is that once the transfer initiates, the rpc is set to 'success'. The manager is able to rectify to 'unable' if the transfer fails. So, for the worker 'success' means 'successfully started the transfer', and for the manager it means 'successfully got the whole blob'.

simplify blob-get

---

dataswarm/manager/Makefile
dataswarm/worker/Makefile

Otherwise the default make rules does not produce the binaries. We
probably want to revisit this, as these binaries will be facing the user
and their name is importat.

rename dataswarm_{manager,worker} binaries to ds_*

---

dataswarm/common/ds_message.h
dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_blob_table.h
dataswarm/worker/ds_process.c
dataswarm/worker/ds_process.h
dataswarm/worker/ds_task_table.c
dataswarm/worker/ds_task_table.h
dataswarm/worker/ds_worker.c
dataswarm/worker/ds_worker.h
dataswarm/worker/ds_worker_main.c

On worker startup, both the blob table and the task table are recovered from disk,
and then previously deleted tasks and blobs are addressed consistently.
Next step is to send a catalog of information back to the manager.

DS Recover Blob Table from Disk

---

doc/manuals/makeflow/index.md

As reported in the mailing list, warn about the expectation that all workflows will work in all batch systems without minor modifications. (Mostly due the underlying filesystem and implicit dependencies on directories.)

add warning about -T and makeflow

---

makeflow/src/makeflow.c

Fix for conda test. Binary coult not be accessed with the full path.

Do not assume absolute path of makeflow exe is accessible

---

dataswarm/common/ds_blob.c
dataswarm/common/ds_blob.h
dataswarm/common/ds_message.c
dataswarm/common/ds_message.h
dataswarm/manager/ds_blob_rep.h
dataswarm/manager/ds_manager.c
dataswarm/manager/ds_rpc.c
dataswarm/manager/ds_worker_rep.c
dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_blob_table.h
dataswarm/worker/ds_worker.c

Split ds_blob_table_delete into ds_blob_table_deleting and ds_blob_table_delete.   
*_deleting is called when the rpc blob-delete is received.
*_delete is called in a new function ds_blob_table_advance finds that there is something to do with a blob.
The final delete state is sent to the manager in an asynchronous update, as we do with tasks.

DS unify blob enums

---

dttools/src/mq.c

Adds a number of doc comments explaining how the internals of MQ are supposed to work. Also includes some compile time defines to put fds in blocking mode, which I *think* should be sufficient to switch to serial operation without further changes. This would of course cause the tests to deadlock, so we might try this out with DS.

Document MQ internals

---

dataswarm/common/ds_message.c
dataswarm/common/ds_message.h
dataswarm/common/ds_task.c
dataswarm/common/ds_task.h
dataswarm/manager/ds_manager.c
dataswarm/manager/ds_rpc.c
dataswarm/manager/ds_test.c
dataswarm/manager/ds_worker_rep.c
dataswarm/worker/ds_task_table.c

Also added task results as  undefined, success, permanent error, retry with fix (e.g. resource exhaustion), retry unchanged (worker gracefully disconnecting before task completed).

Tasks states, and task attempt states are monotonically increasing.

---

python_environments/python_package_cache

This is a new tool for our suite of Python packaging stuff, `python_package_cache`. It can take the place of `python_package_create`, but maintains a cache of previously built tarballs. The path to the generated/cached tarball is written to `stdout`. Parsl's WQ executor does this out of necessity, so I figured we should provide this as a tool. The matching and merging functionality of Landlord is also available, depending on how it's invoked:
- `python_package_cache spec.json`: Only reuse **exact matches** of the spec.
- `python_package_cache --approx spec.json`: Reuse the smallest **superset** of the spec. Optimizes for latency.
- `python_package_cache --merge 0.75 spec.json`: **Merge** the spec with a similar one in cache (subject to *alpha=0.75* cutoff from Landlord). Implies …

New Python packaging tool for caching tarballs

---

work_queue/src/bindings/perl/Work_Queue/Task.pm
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Files marked at WORK_QUEUE_FAILURE_ONLY will only be returned if the task does not succeed.  This is handy for tasks that generate large log files at runtime.  Don't bother bringing them back if not needed.

Work Queue Failure Only Flag

---

batch_job/src/batch_job_cluster.c

Put dot-slash in front of the batch job wrapper, solves a submission problem on LSF.

Batch Job LSF Fixup

---

python_environments/python_package_analyze
python_environments/python_package_cache
python_environments/python_package_create

The consensus in https://github.com/conda/conda-pack/issues/145 seems to be to just add the `--ignore-missing-files` flag, so this might be a semi-permanent workaround. This means our goto advice if a packed environment is **actually** failing with missing files will need to be "try building a fresh conda environment and running from there", unfortunately.

Fixes/improvements to Python packaging

---

dttools/src/jx_table.c
dttools/src/jx_table.h
work_queue/src/work_queue_status.c

WQ resources for tasks are now displayed when using 
`work_queue_status -R`

adds WQ tasks resources display

---

batch_job/src/work_queue_factory.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h

The WQ factory and the capacity computations did not include GPUs as a resource.  This PR fixes that.

WQ GPU Factory/Capacity Fixups

---

work_queue/src/work_queue.c

The check for actual resources consumption can be improved to avoid the problem of tasks being submitted in a loop while resources are fragmented? For example, a more comprehensive check that matches specific available workers to appropriate tasks. What do you think?

Check actual resources consumption in work_queue_hungry

---

makeflow/src/parser_jx.c
work_queue/src/Makefile
work_queue/src/work_queue_gpus.c
work_queue/src/work_queue_gpus.h
work_queue/src/work_queue_process.c
work_queue/src/work_queue_worker.c

The worker now keeps track of which specific GPUs each task is assigned to and then sets CUDA_VISIBLE_DEVICES to match that assignment.  That will  now allow us to run multiple concurrent GPU task such that each one stays in its lane.
There is still an oddity in how the manager assigns the total number of gpus to an execution request, but I'll bring that up in a separate issue.

WQ: Assign Tasks to Specific GPUs

---

work_queue/src/bindings/python3/work_queue.binding.py

Need this to add support for GPU specifications in Parsl WQ executor.
@btovar can you do a Conda release with this?

Add `specify_gpus` to WQ Python bindings

---

work_queue/src/work_queue.c

Hitting the manager host and port with a web browser will give a simple data API,
and then allow you to grab task/worker/resources data via JSON, in the same
format as work_queue_status.

WQ: Add simple API for fetching manager data via HTTP.

---

doc/man/m4/work_queue_worker.m4
doc/man/md/work_queue_worker.md
work_queue/src/work_queue_worker.c

They only added confusion when reporting resources available at worker.
The idea was to reserve disk and memory for the worker itself to use,
but the worker uses less than 2MB for both, which does not merit the
extra complications.

remove disk and memory minimum thresholds for worker.

---

work_queue/src/bindings/python3/work_queue.binding.py

`task.specify_buffer` calls method `_determine_file_flags(flags, cache)` but this method requires an additional argument `failure_only`. The fix is that I simply supply `None` to this argument as `specify_buffer` doesn't have `failure_only` argument. SHADHO runs with this fix too.

Fix task.specify_buffer

---

chirp/test/TR_chirp_acl.sh
chirp/test/TR_chirp_rmall.sh
chirp/test/chirp-common.sh
run_all_tests.sh

Moves all files automatically generated by a chirp test to a single temporary directory (e.g., acl, rendezvous transient, etc.). This directory is placed the cwd of the test if running as a regular user, or in /tmp if running as root. This allows access to all the needed files when the chirp_server processes drop privileges.
Previously the tests failed when running as root if part of the path of the needed files was inaccessible when dropping privileges.
(Fixes part of #2543. mq still fails, investigating that.)

Fix chirp tests when running as root

---

.github/workflows/nightly.yml

The idea is to generate binaries (e.g. parrot with cvmfs and bxgrid)
that we can test in the cctools-packaging-test.

adds a nightly ubuntu build

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

As recommended by compiler warning when testing for spack.

Turn anonymous enum to work_queue_category_mode_t

---

dttools/src/rmsummary.c

It gave notices for custom fields added by the user app (e.g., the resource_monitor adding executable_type, etc.), which is incorrect.

remove notice when reading rmsummary files from disk

---

doc/man/md/work_queue_status.md
doc/manuals/work_queue/index.md
dttools/test/test_runner_common.sh
work_queue/src/bindings/perl/Work_Queue.pm
work_queue/src/work_queue.c
work_queue/test/TR_work_queue_allocations.sh
work_queue/test/wq_alloc_test.py

In summary:
- default not specified gpus are 0.
- In fixed mode (the default) cores, memory and disk not specified get a value proportional to the resources specified, rounded, and taking the max if more than one of cores, memory, disk or **gpus** are specified.
- Not specifying anything gets you the whole worker.
- Specifying everything to 0 uses the whole worker.
Nothing is implemented, this is an update to the wq manual with the proposed changes.

Proposal for default resources

---

work_queue/src/bindings/perl/Work_Queue/Task.pm
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/test/wq_test.py

This like a perror but for work_queue_result_task_t. For debugging and user interaction it is more helpful to see for example a 'INPUT_MISS" rather than the integer 1.

wq: add API call to translate task result from integer to string

---

doc/manuals/work_queue/index.md
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_resources.h
work_queue/src/work_queue_worker.c
work_queue/test/wq_test.py

**Modifications:**
Line 3722 to 3726 in `work_queue.c` checks whether a worker has enough time for a task.
Line 22 in `work_queue_resources.h` adds time to the `work_queue_resources` structure.
Line 383 to 390 in `work_queue_worker.c`updates the manager on the time a worker has left.
**Diagnosis:**
When code is compiled and run with the example WQ program in the [docs](https://cctools.readthedocs.io/en/latest/work_queue/) (this program needs to add a call to `work_queue_task_specify_running_time` for the issue to appear), it seems that `work_queue_worker` is stuck in a loop starting at line 2962 in `work_queue_worker.c`. The main reason for this is that line 2979 in `work_queue_worker.c` returns the variable `result ` with a value of 0. A deeper dive into function …

WQ: Add Minimum Time as a Resource

---

doc/manuals/work_queue/index.md
work_queue/src/bindings/perl/Work_Queue/Task.pm
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/test/wq_test.py

Minor fixes to specify_running_time_{max,min}:
- adds perl bindings
- updates docs to seconds
- updates test to use specify_running_time_max

WQ run time fixes

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

Move end_time and wall_time to seconds, to match the new rmsummary.

Fix time units

---

work_queue/src/work_queue.c

Only min_time should be considered, as wall_time is a maximum time of
the task itself.

wall_time should not be considered when matching workers

---

doc/man/m4/condor_submit_workers.m4
doc/man/md/condor_submit_workers.md
work_queue/src/condor_submit_workers

Adds --class-ad to specify custom class ads when submitting workers to condor.
NDCMS use case:
```sh
condor_submit_workers ... --class-ad "+IsExpressJob" ...
```

Custom class ads for condor_submit_workers

---

work_queue/src/bindings/python3/work_queue.binding.py

This pr puts all the individual PythonTask staging directories inside a temporary directory per python process. This temporary directory is removed at the end of the process with atexit.

atexit remove staging directory of PythonTask's

---

batch_job/src/work_queue_factory.c

Also, error when max < 1.
Otherwise we get a surprising error in python when max is less than the default of 5.

wq factory: set min workers to max, when min > max

---

batch_job/src/work_queue_factory.c

This commit checks abort_flag each second the factory sleeps. This
allows a much faster response when using the factory with PythonTask.
The previous behaviour made the factory sleep for a whole period before
checking the abort_flag. Fast executing PythonTask would then have a 30s
overhead when using the 'with workers:' syntax.

wq factory: allow abort while sleep

---

work_queue/src/bindings/python3/work_queue.binding.py

Adds the error output to the exception when the factory process does not start correctly.  E.g.:
```
RuntimeError: Could not execute work_queue_factory. Exited with status: 1
unknown batch queue type: localx
```

Python factory print errors

---

dttools/src/list.c
work_queue/src/work_queue.c
work_queue/src/work_queue_status.c

As observed by @BarrySlyDelgado, work_queue_submit_task was noticeably slower than expected in the python bindings. This pr makes the submission more efficient by:
- Inserting a task into the queue as soon as its priority allows, rather than prioritize previously submitted tasks.
- Batch log stats requests together, rather than write stats on each submission.
- Keep max resources seen per queue in a field, rather than recompute it each time.

work queue: improve task submission time

---

parrot/test/TR_parrot_dir.sh

cctools builds via spack are failing due to test `TR_parrot_dir.sh`. This test is exercising a corner case of POSIX `open(name,O_DIRECTORY|O_CREAT,mode)` that seems to be unspecified and varies between Linux kernels.  Removing that part of the test case.

Parrot: Remove unspecific test case.

---

dttools/src/rmsummary.c
resource_monitor/src/resource_monitor.c

- peak cores computed over three-minute windows rather than one minute.
- fuzzy limit increased to 0.25 cores, rather than 0.1 cores.

Compute peak cores less aggressively

---

python_environments/src/python_package_run

Take advantage that ${UNPACK_TO} is created by mkdir, which is atomic most of the time.

python_package_run: lock on unpack dir rather than custom file

---

dttools/src/rmsummary.c
resource_monitor/src/resource_monitor.c

Reestablishes behaviour that was removed when switching to floating point resources.
It also fixes a bug where different time windows were used when computing peak_cores.

Fixes cores  limit

---

work_queue/src/work_queue.c

This pr cleans re-submissions from a task definition from a terminal state. Once resubmitted, the task gets a new taskid.
We already allowed re-submissions, but they only worked correctly when no resource management or max_retries were specified. This should make implementing retries in coffea a little bit easier.

work queue: cleaner resubmissions

---

work_queue/src/bindings/python3/work_queue.binding.py

Implemented this one directly in the python bindings. Otherwise freeing the memory used for the tasks became complicated as the mapping of python tasks to C struct needs to be updated too. (In fact, this pr also fixes the memory leak created by the cancellation by taskid.)
This is needed for canceling processing tasks in topcoffea when workflows are terminated early. The workflows should run normally the remaining accumulation tasks.

wq: cancel all tasks in a category, python bindings

---

work_queue/src/bindings/python3/work_queue.binding.py

On exit, sometimes the __del__ method is called when swig bindings are
no longer available. This commit catches such exceptions.

py wq: catch exceptions when cleaning up objects

---

dttools/src/category.c

We give priority to specify_* over category_max_resources. This fixes a
bug where specify_* would not define a limit, but later we wouldn't
check category_max_resources.

category: fix a bug where max allocation was ignored

---

doc/man/m4/work_queue_worker.m4
doc/man/md/work_queue_worker.md
work_queue/src/work_queue_worker.c

gpus=0 did not set gpus to 0, but allowed the detection of available
gpus.

wq worker: correctly handle --gpus=0

---

doc/manuals/work_queue/index.md

changed "congrads" to "congrats"

Fixed Typo in Work Queue Manuals

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

The minimum number of waiting tasks to consider the queue satisfied.
Default is 10.

wq: add tune parameter "hungry-minimum"

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

It is an int. No task is submitted to workers until wait-for-workers
number of workers connected is reached. After this, wait-for-workers is
reset to 0. Useful for testing, not for regular production.

add tune parameter: wait-for-workers

---

work_queue/src/work_queue.c

This changes allows for workers to connect when the queue is empty.  If the queue is empty, it will only return before the timeout if something interesting already happened during the wait (i.e. only workers connection/disconnection as there are no tasks.)
The target is to bootstrap workflows that submit tasks according to the resources available.

wq wait: do not return if queue is emtpy and nothing interesting has happened yet

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Changes the name of `asynchrony-multiplier` to `resource-submit-multiplier` tune parameter.  This factor (default to 1) is applied to cores, memory and gpus when deciding if a task should be sent to a worker. The idea is to allow for tasks to wait at workers.
This pr also fixes an old bug where a task was sent to a worker because of the apparent resources given `asynchrony-multiplier`, but the task would not be able to run because of the actual worker resources.
It also eliminates asynchrony-modifier, as it only had an effect for the old unlabeled tasks before work queue managed resources.
Lastly, it makes work_queue_hungry take into account the over-commitment.

Small fixes for over-commitment to workers

---

doc/man/m4/work_queue_worker.m4
doc/man/md/work_queue_worker.md
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

ignores the list of interfaces and directly tries to connect to the
manager address the catalog observes.
This is the original work queue behaviour from years ago, and it was
already present as a fallback from when a manager did not report a list
of interfaces.

wq: adds by_apparent_ip mode

---

work_queue/src/bindings/python3/work_queue.binding.py

The default recurse option using dill is false. Thus, previously, if a user used PythonTask for serialization, any sub functions would not be included in the. This would fix that.

Add recurse option to serialization

---

poncho/src/poncho_package_create

Moved env cache and base/full packages back to topeftenv.py. In this
way, poncho_package_create can just focus on creating environments. 
This means that the output argument is required again.
I still don't think the reading the spec from stdin works correctly.

Simplify poncho_package_create

---

work_queue/test/TR_work_queue_allocations.sh

The test succeeds running locally on cclmac02. Adding `set -x` as we are not getting any output when the test fails with the github action.

add debug switch to TR_work_queue_allocations.sh

---

work_queue/src/work_queue_worker.c

Otherwise, there was a race condition where a task could produce a file
between the removal of the workspace and the termination of the task.
This issue only happened for tasks that wrote files in the workspace
outside their sandbox. (Which breaks the wq task abstraction and
shouldn't really happen but for very special conditions.)

wq worker: cleanup workspace after complete disconnect from manager

---

dttools/src/Makefile
dttools/src/jx_canonicalize_test.c
dttools/src/jx_merge_test.c
dttools/test/TR_jx_canonicalize.sh
dttools/test/TR_jx_merge.sh

otherwise we have to reproduce the linking rules inside the TR_*.sh
files, and they may link to a different version of shared libraries than
the rest of the binaries.

move jx_{canonicalize,merge}_test to their own .c

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_internal.h
work_queue/src/work_queue_worker.c
work_queue/test/TR_work_queue_tag.sh
work_queue/test/wq_test_tag.py

For #2737.
Decided to modify `work_queue_wait_internal` directly, as that allows us to use the RETRIEVED state for tasks with the incorrect tag. Otherwise we would need to add another state, or maintain a list of done tasks.
Asking for the NULL (None) tasks means to wait for any task (e.g. q.wait_for_tag(None, time) == q.wait(time))

wq: work_queue_wait_for_tag

---

work_queue/src/bindings/python3/work_queue.binding.py

work in progress, but I believe it is close to done, as it works, and bigger chunks seem to be faster. Need to do an actual timed test with large data. 
For breaking up into tasks, associative operations work no matter how you break up the data, but operations like divison will change based on the size. The way I tried to fix this was by only breaking up the data in powers of 2, this way breaking up the tasks is the same as doing it as one big task. However, I am not sure if this is the best way, and there would be a gap between the requested chunk_size and the used one

WQ Abstractions: Tree Reduce

---

work_queue/src/bindings/python3/work_queue.binding.py

Fixed some minor idioms in work_queue.binding.py that were valid Python 3 but not valid Python 2.7, resulting in test regressions.

WQ: Fix backwards compatibility for Python 2.7

---

makeflow/example/starch-example.config
makeflow/example/starch-example.env
makeflow/src/starch
makeflow/test/TR_starch_extract_and_remove.sh

- Adds configuration example
- Adds --sfx-help to show relevant environment variables
- Adds SFX_EXEC env var to change which command to execute (if multiple commands in the package.) E.g:
```sh
starch -x date -x uname -c date example.sfx
./example.sfx
Mon Jan 10 11:12:02 EST 2022
SFX_EXEC=uname ./example.sfx
Linux
```
This also useful to run a shell with all the PATH and LD_LIBRARY_PATH variables set correctly to run a set of commands:
```sh
SFX_EXEC=/bin/sh ./example.sfx
sh$ which date
/home/myuser/example.sfx.27441.dir/bin/date
```
(wip: updating readthedocs)

Starch small fixes

---

work_queue/src/work_queue.c

Every three minutes we check for tasks that don't fit connected workers.
The warning includes the minimum size of worker needed to run these
tasks.
(Supersedes #2710: fixes merge history and renames some functions.)
(@Cpreciad could you check it with your examples?)

work_queue: print a warning for tasks that don't fit workers

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

For #2783. When an output cannot be transferred back because of low disk space, or incorrect permissions, the task is marked with the result `WORK_QUEUE_RESULT_OUTPUT_TRANSFER_ERROR`. The application can then decide what to do: retry after freeing space, stop submitting tasks, etc.
This approach follows more closely previous Work Queue behaviour. Terminating the application, or going into a holding pattern after a warning as discussed in #2783 meant adding a switch to the main wq loop. This pr puts the responsibility on what to do in the application.

wq: adds output transfer error as a task result

---

batch_job/src/batch_job_cluster.c

batch cluster: remove space between value and memory unit

---

deltadb/src/deltadb_stream.c
work_queue/src/work_queue.c

Updated compiler used in conda does not like that source and destination of strcpy are the same buffer. `deltadb_process_stream` modified so that the copy is not necessary, it must be imperceptibly faster too.

No strcpy to same buffer

---

batch_job/src/batch_job_cluster.c
dttools/src/macros.h
makeflow/src/parser.c

Time was parsed as usecs, rather than secs. Also fixed round up to integer resources from double specifications.

fix makeflow wall_time

---

dttools/src/category.c

This fixes a bug found in topEFT where max seen mode would not use the
whole worker. In max seen mode the max_seen values are loaded only for
the first allocation. In all the other modes, they are loaded in the
respective computations.

do not load max_seen resources if not on first allocation

---

chirp/src/chirp_client.c

The CCL-Chirp implementation getdir returns 0 on success, however the HTCondor-Chirp implementation of getdir returns the number of bytes in the directory listing.  This change accomodates both.

Chirp: Modified chirp_client_getdir to consider >=0 a success.

---

work_queue/src/work_queue_worker.c

I added a pipe connected to the stdin and stdout of the coprocess because 
1: the coprocess should be cut off from reading in from the stdin of the worker or outputting to the stdout of the worker
2: it might prove helpful to have a method for the worker to communicate with the coprocess
Also added a check that the coprocess is currently running and a max limit of 10 restarts to the coprocess so that the worker would not continuously restart it.

Pipes added to coprocess and limit to coprocess restarts

---

poncho/src/poncho_package_run

Not supported everywhere (e.g. shared filesystems)

poncho_package_run: remove sync call

---

dttools/src/macros.h
dttools/src/rmonitor_poll.c
resource_monitor/src/resource_monitor.c

As reported by @kmohrman, in some rare cases the cpu_time had a negative
value, which meant it was not included in the resource summary, but
cores where computed anyway as cpu_time/wall_time with an undefined
cpu_time value.

guard against incorrect values in cpu_time

---

work_queue/src/network_function.py
work_queue/src/work_queue_process.c
work_queue/src/work_queue_process.h
work_queue/src/work_queue_worker.c

Here is what @David-Simonetti-ND and I got working this week. The coprocess and worker now communicate via pipes on startup so that the port is no longer hardcoded and you don't have to pass the name of the function via the command line. We can now run multiple workers with the network function!

Use pipes with coprocess

---

batch_job/src/batch_job_cluster.c

The user command inside the wrapper may change the current directory,
which may cause the "stop" transaction of the job status to be written
to a different file when using relative path names.

batch_job_cluster: abs name for logfile

---

work_queue/src/network_function.py
work_queue/src/work_queue_worker.c

I changed the network function to send the size of the json followed by a newline followed by the actual json itself. There are also sanity checks to ensure that the received json matches the sent size.

Network function communication with json and envelope

---

poncho/src/poncho_package_create

Poncho package create now checks for the pip version when installing local pip packages. #2856

Checks for pip version in poncho_package_create

---

work_queue/src/Makefile
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/coprocess_example.py
work_queue/src/function_handler.py
work_queue/src/network_function.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_coprocess.c
work_queue/src/work_queue_coprocess.h
work_queue/src/work_queue_process.c
work_queue/src/work_queue_process.h
work_queue/src/work_queue_protocol.h
work_queue/src/work_queue_worker.c

E.g.
```
t = Task("my_sum")
t->specify_coprocess("my_coprocess")
```
will call the function "my_sum" in the coprocess with the "my_coprocess" name. Tasks are only sent to workers with matching coprocesses.
Run `work_queue/src/coprocess_example.py` as an example. (The file works both as the coprocess and the wq manager.)

move coprocess to its own .h.c

---

doc/manuals/makeflow/index.md

"see the Batch System Support section" now is a hyperlink to the section.

Update cross reference in Makeflow manual

---

work_queue/src/work_queue_process.c

I think this is an elegant solution for the dall bug. It allows for the coprocess output to be accessed in the exact same way as a regular task, but also allows wq debug output to still be output to the screen for the forked work_queue_worker process that communicates with the coprocess.

Fix for dall bug

---

work_queue/src/work_queue_process.c

I noticed I was sometimes getting extra characters at the end of the string returned by load_input_file, and the issue appears to be that the buf returned by load_input_file is sometimes (or never) properly terminated with a null character (in my case, fsize and bytes_read were always the exact same size, meaning that buf is entirely filled with no room for a null terminator).

Fixed buffer overflow in load_input_file

---

poncho/src/poncho_package_run

Needed because conda-unpack looks for a 'python' in PATH, but rh8 has
none.

activate env before conda-unpack

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/coprocess_example.py
work_queue/src/network_function.py
work_queue/src/work_queue_coprocess.c

Reworks the decorator to also wrap up the output of the user function into the response dict, and allows the user to specify the remote function arguments when creating the RemoteTask. Also switched from the multiprocess library to explicitly forking a process to run the function.

remote_execute decorator and switch to explicit fork()

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/coprocess_example.py
work_queue/src/network_function.py

When creating a RemoteTask, one can specify arguments by keyword as before, but now there is support for positional arguments and passing in a dictionary containing keyword arguments (pass in the dictionary as work_queue_argument_dict). The user can also mix and match these arguments, passing some arguments by keyword and some by position.

Option to specify RemoteTask arguments by keyword, position, dictionary, or position

---

work_queue/src/work_queue.c

A really small typo. This block of comment should be explaining the following `queue_lean_to_jx` function.

Typo fix in queue_to_lean_jx comment

---

work_queue/src/work_queue.c

recent change removed resources report from RETRIEVED state in the
transactions log. However, this was the only place were exhausted
resources were reported. This commit re-establishes that.

wq: report exhausted resource on task retrieval (transactions log)

---

work_queue/src/work_queue_worker.c

unlink file messages from the manager were silently ignored as the path to unlink was relative to the task, and not the cache path.

wq: use cache path to remove file at worker

---

work_queue/src/work_queue.c

As reported by a couple of users, the previous message that had the
manager 'speaking' in the first person was confusing.

rephrase rejected workers because of protocol mismatch

---

work_queue/src/work_queue.c

t.resources_measured was meant to always have a valid value, even when
no resource summary was available.

wq: always provide t.resources_measured

---

work_queue/src/work_queue.c

The message was printed on the right conditions, but the values where
always 0. The function needed the actual value, rather than the struct
pointer. (Surprised that the compiler did not pick this one up.)

wq: fix needed worker size message

---

doc/manuals/work_queue/index.md
work_queue/src/work_queue.c

Adds q.tune("force_proportional_resources", 1), which makes adjust
max_proportion so that an integer number of the given task category fit
the worker. In other words, it exchanges external for internal
fragmentation of resources. For automatic allocation modes such as
CATEGORY_ALLOCATION_MODE_MAX, this is beneficial, as tasks are much less
likely to fail for resource exhaustion.
For example, if a worker has 12GB, and the task asks for 3.5GB, then
force_proportional_resources will assign 4GB per task (three tasks
completely cover the worker, other than only 3*3.5GB=10.5GB, with 1.5GB
of external fragmentation). If the task asks
for 7GB, then it assigns 12GB to the task.
Advantages:
Eliminates avoidable resource exhaustion when using
ALLOCATION_MODE_MAX. For example, if the maximum task …

wq: equal resource proportions mode

---

dttools/src/category.c
work_queue/src/bindings/python3/Makefile
work_queue/src/bindings/python3/StatusDisplay.py
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue.i

- adds the `work_queue_status` API call, which works like the `work_queue_status` command, but can be called inside the code. (In fact, the status messages to the command are now constructed using this call.)
- adds the `application_info` method to python where applications can include statistics they want displayed.
- adds the StatusDisplay, which shows statistics as the manager runs. Currently only supports jupyter, but I plan to add text tables too. Activate by setting `WorkQueue` parameter like `status_display_interval=10` (update at least 10s apart).
Some examples: dynamic chunksize computation. coffea sends the stats shown in the application info box. 
mark when resources available are not enough for the tasks:
Example of display info implementation:
```python
class …
```

wq resources revamp

---

chirp/src/bindings/python3/Makefile
dataswarm/src/bindings/python3/Makefile
work_queue/src/bindings/python3/Makefile

Possible fix to conda azure builds sometimes messing up the final
modules
Traceback (most recent call last):
File "$SRC_DIR/chirp/test/../src/bindings/python3//chirp_python_example.py", line 6, in <module>
import Chirp
File "$SRC_DIR/chirp/src/bindings/python3/Chirp.py", line 1655
f the chirp jobs to be reaped.
^
IndentationError: unindent does not match any outer indentation level
Most likely than not, this won't fix it as the chances of the cat command doing something wrong are slim to none. However, this is the only step I can see where these errors are introduced. This errors occur only sometimes when running the conda-forge builds in azure for OSX.  The error goes away usually after a couple of retries.  I have tried building this commit in conda-forge, and has not failed yet.

bindigns: disable cat buffering

---

doc/manuals/poncho/index.md
poncho/src/poncho/package_analyze.py
poncho/src/poncho/package_create.py

This addresses #2949. the key "packages" is changed to "dependencies". pip packages are under "dependencies" as well within their own dict. The doc manual has been updated to reflect this change.

Updates Poncho and doc to reflect Conda's specification format

---

poncho/src/poncho/package_create.py

A typo in the an the IF branch when converting the PONCHO spec file caused an error in which empty environments would be created.

Fixed typo causing error in package_create

---

dataswarm/src/bindings/python3/dataswarm.binding.py
dataswarm/src/bindings/python3/dataswarm.i
dataswarm/src/examples/ds_example_blast.c
dataswarm/src/manager/dataswarm.h
dataswarm/src/manager/ds_file.c
dataswarm/src/manager/ds_file.h
dataswarm/src/manager/ds_manager_get.c
dataswarm/src/manager/ds_task.c
dataswarm/src/manager/ds_task.h
dataswarm/src/worker/ds_transfer.c
dataswarm/src/worker/ds_transfer.h
dataswarm/src/worker/ds_transfer_server.c
dataswarm/src/worker/ds_worker.c
dataswarm/test/ds_test.py

Add support for named output buffers, to permit retrieving multiple outputs without touching disk at the manager.

DS Output Buffers

---

.readthedocs.yaml
doc/Makefile
doc/cctools.doxygen.config
doc/manuals/index.md
doc/manuals/work_queue/index.md
mkdocs.yml

readthedocs now runs the doxygen config file. The generated docs are hosted in readthedocs.
As part of the doc generation, a theme is cloned from github (default theme is ugly.)

readthedocs + doxygen

---

dataswarm/src/manager/ds_manager.c

Tasks will now go to the back of the ready list if they have a priority of 0 (default priority) rather than inserting themselves before other tasks with the same priority.

Fixed task ordering issue

---

chirp/src/bindings/python2/.gitignore
chirp/src/bindings/python2/Makefile
chirp/src/bindings/python3/.gitignore
resource_monitor/src/bindings/python2/.gitignore
resource_monitor/src/bindings/python2/Makefile
resource_monitor/src/bindings/python3/.gitignore
taskvine/src/bindings/python3/.gitignore
taskvine/src/bindings/python3/Makefile
work_queue/src/bindings/python2/.gitignore
work_queue/src/bindings/python2/Makefile
work_queue/src/bindings/python3/.gitignore
work_queue/src/bindings/python3/Makefile

This was used on OSX when we depended on the local python installation. Now we make use of Python coming from Conda to get consistency.

Remove use of special symbolic link to Python.framework.

---

dttools/src/path_disk_size_info.c
taskvine/src/worker/vine_cache.c

Upon creating/unpacking a directory, measure the size properly for the cache-update message.

Vine: Measure Directory Sizes

---

taskvine/src/Makefile

@colinthomas-z80, I think this should fix the issues you saw yesterday with `make -j3`.

taskvine: build library before anything else

---

chirp/src/bindings/python2/Makefile
chirp/src/bindings/python3/Makefile
chirp/src/bindings/python3/chirp.binding.py
chirp/src/bindings/python3/chirp_jobs_python_example.py
chirp/src/bindings/python3/chirp_python_example.py
chirp/src/chirp.i
chirp/test/TR_chirp_job_python.sh
doc/cctools.doxygen
work_queue/src/bindings/python3/work_queue.binding.py

@fixes #3040 
Also, it moves `import Chirp`  to `import chirp`,  as `Chirp` implies a class.  This is only used with lobster, and they won't be using a newer cctools for a while.

Fix doc namespaces

---

taskvine/src/manager/vine_manager.c

The previous behavior, where we just simply appended new managers was confusing to tools and users.
I'd like to do the same to the debug log, but that would mean breaking compatibility with current makeflow and work_queue. However, since the debug log is not feed to other tools, the change is not as important.

vine: perf and transactions log truncate each open

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_blast.py
taskvine/src/examples/vine_example_watch.py

Instead of doing flags = VINE_CACHE | VINE_UNPACK, now we do  cache=True, unpack=True, etc.

taskvine: more pythonic file flags

---

doc/manuals/work_queue/index.md

- exit code is replaced by return status and add `-lcrypto` and `-lssl` to C linking instruction.

WQ: fix field in wq task and C linking instruction

---

taskvine/test/TR_vine_python.sh
taskvine/test/vine_test.py

Increase timeout for task completion, to deal with slow testing hosts.
Fix some accumulated errors in task failure reporting.

Fix Vine Python Test on OSX

---

dttools/src/category.c

A recent change was loading all the max observed resources, rather than just cores, memory, disk, and gpus. This was incorrectly setting limits in other measurements, such as start and end times.
As observed by tphung3

category: fix update to max seen values

---

doc/manuals/taskvine/index.md
doc/manuals/work_queue/index.md

Fixes #3078. Line of code was incorrectly indented.

fix C api for transactions log in manual

---

configure
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_service.cc
parrot/src/pfs_service.h
parrot/src/pfs_service_cvmfs.cc
parrot/src/pfs_service_local.cc
parrot/src/pfs_sys.cc
parrot/src/pfs_sys.h
parrot/src/pfs_sysdeps64.h
parrot/src/pfs_table.cc
parrot/src/pfs_table.h
parrot/src/pfs_types.h
parrot/src/syscall_64.tbl
parrot/test/TR_parrot_stat.sh

As observed in NDCMS+parrot in rh8,  utilities like ls and stat now use the call statx.
Local service redirects to statx.
cvmfs uses stat, and then copies relevant info to statx structures.
The rest of the services use a dummy entry, as with stat.

Adds statx to parrot

---

doc/manuals/install/index.md

Current install instructions have the prefix as $HOME/cctools and the base directory as $CONDA_PREFIX. This caused python to not recognize work_queue as a package. As far as I can tell both of these need to be the same for the same and $CONDA_PREFIX seems to be the best solution so I have made the change.

Fix Install Script on Work Queue manual for Github Install

---

work_queue/src/bindings/python3/work_queue.binding.py

Previously there was an issue of __del__ being called on a python task after os and sys had gone out of scope, causing the test case in the manual to error out at the end. By giving del two arguements (os and sys) with default arguments being the required libraries, Python will preserve references to the libraries, allowing __del__ to be called successfully.

Workqueue __del__ issue fixed on last instance of a python task

---

taskvine/src/bindings/python3/taskvine.binding.py

Taskvine had the same del issues that workqueue had so I applied the same fix in the vine bindings. As far as I can tell the python task temp dirs are created in the same way as work queue so everything should be cleaned up regardless at exit!

Fix __del__ behavior in taskvine

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.h
taskvine/src/manager/vine_txn_log.c
taskvine/src/worker/vine_worker.c

For #3102.
The "result ..." message was modified to include start and end times.
@BarrySlyDelgado `time_worker_start` and `time_worker_end` will appear in the dictionary `measured` of the plotting tool.

Add start, and end time to transactions log

---

taskvine/src/worker/vine_worker.c

This should fix the issue where CACHE_UPDATE appears to come from the "(null)" worker.
send CACHE_UPDATE after worker reports as ready, but not before it sends the resources it has.
This prevents the manager to schedule tasks in the worker before the list of files available is known.

send CACHE_UPDATE after worker reports as ready

---

poncho/src/poncho/package_serverize.py
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/worker/vine_coprocess.c
taskvine/src/worker/vine_coprocess.h
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c

Getting serverless to work on condor required changing the method of communication between coprocess and worker from using TCP to using pipes, as for whatever reason the task responsible for invoking the function call on the coprocess would not connect.

Vine: Serverless running on condor

---

deltadb/src/deltadb.c

Compiler used in conda-forge complained that strcpy src and dest may overlap. As far as I can tell, the strcpy is unnecessary as we can simply move the pointer of the start of the string (line is a pointer to whole_line).

deltadb: avoid strcpy line overlap

---

doc/man/m4/poncho_package_create.m4
doc/man/md/poncho_package_create.md
poncho/src/poncho/package_create.py
poncho/src/poncho_package_create

conda installation uses shell functions to wrap its commands. These functions are not available when using subprocesses inside python.
This commit makes it so that mamba, micromamba, $CONDA_EXE, and conda are prefered, in that order.
It also automatically installs micromamba without the need to use the --mamba switch. This can be prevented with --no-micromamba

poncho_package_create: fallback to $CONDA_EXE

---

chirp/src/chirp_reli.h
chirp/src/chirp_ticket.c
dttools/src/file_cache.c
dttools/src/hmac.h
dttools/src/md5.c
dttools/src/md5.h
dttools/test/TR_hmac_test.sh
makeflow/src/makeflow_mounts.c
parrot/src/parrot_md5.c
taskvine/src/manager/Makefile
taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_cached_name.h
taskvine/src/manager/vine_checksum.c
taskvine/src/manager/vine_checksum.h
taskvine/src/manager/vine_file.c
taskvine/src/worker/vine_worker.c
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Recursive checksumming functions are now in `vine_checksum.[ch]` since we are going to play around with that to introduce different checksum types.

Vine: Reorganized Use of MD5

---

taskvine/src/worker/vine_coprocess.c

Change from directly executing the coprocess command to having sh run the command as an argument. This allows the extra flexibly in the duty task to have poncho_package_run added to it.

Vine: Enable coprocess to start with poncho_package_run

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_xrootd.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c

adds vine_file_xrootd, FileXrootD.
Example is functional, but is missing the poncho recipe (i.e., assumes uproot and xrootd on execution site). The example uses PythonTask.

vine xrootd

---

taskvine/src/manager/vine_manager_put.c

In code, `info.st_mtime` refers to the last modified timestamp of the local file and `remote_info->mtime` refers to the last modified timestamp of the remote copy of the local file. The latter is always newer than the former as it is written to the local filesystem of the remote machine, thus the two debug messages are always printed. Removing the comparison condition removes the issue.

Vine: Remove always-true condition causing misleading debug messages

---

taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_put.c
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_cache.h
taskvine/src/worker/vine_worker.c

- Fixed incorrect warning about local files changing while in use.
- Fixed several cases of cache-update and remote-info fields set incorrectly. (Use zero for don't-know instead of assuming current time.)
- Fixed up some duplicate debug output.

Vine: Cleanup Debug Output

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_txn_log.c

It shouldn't affect `vine_plot_txn_log` as the records involved are not parsed by it.

adds commit times, attempt number to transactions log

---

dttools/test/test_runner_common.sh
taskvine/src/manager/vine_runtime_dir.c

When creating the logs files by date, the most recent one will be symlinked to "most-recent". E.g.:
```
ls /tmp/vine-run-info
total 11
drwxr-xr-x 4 btovar campus 2048 Feb 22 12:55 .
drwxr-xr-x 3 btovar campus 4096 Feb 22 12:52 ..
drwxr-xr-x 3 btovar campus 2048 Feb 22 12:54 2023-02-22T12:52:17
drwxr-xr-x 3 btovar campus 2048 Feb 22 12:57 2023-02-22T12:55:47
lrwxr-xr-x 1 btovar campus  119 Feb 22 12:55 most-recent -> /tmp/vine-run-info/2023-02-22T12:55:47
```
Thus, most recent debug log is in:
```
vine-run-info/most-recent/vine-logs/debug
```

vine symlink to most recent logs

---

taskvine/src/manager/Makefile
taskvine/src/tools/Makefile

Don't build and install this feature, it was never completed.
(But may be of interest in the future.)

Vine: Disable old taskvine JSON API proxy.

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager_get.c
taskvine/src/manager/vine_manager_put.c

Getting ahead of compiler warnings as we were using int where a size_t was expected.
Also, changed vine_file_length to vine_file_size, as length really only made sense for buffers of chars.

int file->length to size_t file->size

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/vine_runtime_dir.c
taskvine/src/manager/vine_runtime_dir.h

Adds a cache directory to the runtime dirs.
The motivation is to move directories such as `./vine-library-cache/` (#3170) to   m.cache_directory + `library-cache`

adds cache directory at vine_runtime_info_path/

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_get.c
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_txn_log.c
taskvine/src/manager/vine_txn_log.h
taskvine/src/tools/vine_plot_txn_log
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_sandbox.c
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker.h

Adds start time to the transactions log of transfers and cache updates.  
(In one example I ran with blast and 1000 concurrent tasks, the manager was so busy that by the time it read the cache_update, some short tasks had already finished, which messed up the plot.)

Add startime io updates

---

taskvine/src/manager/vine_txn_log.c
taskvine/src/manager/vine_txn_log.h
taskvine/src/worker/vine_worker.c

it makes easy to parse for the plots, as the origin is kept in usecs.
(The plotting tool was incorrectly dividing the wall_time by 1e6 anyway.)

use usecs instead of seconds in transfer transactions

---

taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_txn_log.c

The motivation is that such info was only available for tasks that were retrieved, but not for tasks lost in a disconnection.
Also, deduplicates resources measured info by only recording it for the retrieved state.

adds size input info to running state transaction

---

doc/manuals/taskvine/index.md
dttools/src/jx.c
dttools/src/rmonitor_poll.c
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/Makefile
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_fair.c
taskvine/src/manager/vine_fair.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/tools/vine_benchmark.c
taskvine/test/TR_vine_valgrind.sh

Changes `vine_enable_monitoring(m, dir, watchdog)` to  `vine_enable_monitoring(m, watchdog, series)`.  If series is 1, then time and debug information per task is written to  vine-logs/time-series. With this change, `vine_enable_monitoring_full` was made redundant and has been removed.
This pr also writes the resources measured for the manager to `vine-logs/workflow.json`, which eventually should comply with FAIR metadata requirements.
@tphung3 It also adds vine_tune(m, "monitor-interval", s); where s is an integer to set the interval of the rmonitor.

rework enable_monitoring API

---

taskvine/src/tools/vine_plot_txn_log

On converting start_time to seconds, the attribute used was wall_time. This cause the parser to detect an inconsistency and fallback to the time the transaction is recorded, which is not as precise.

Fix plot cache update bug

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_chirp.py
taskvine/src/examples/vine_example_xrootd.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c

E.g.:
```C
m.declare_chirp(chirp_server, filename, ticket_file)
```
If ticket_file is not given, then try the default auths.
I was able to run the blast example using a chirp server as the source instead of the http urls.

Adds vine_declare_chirp

---

taskvine/src/manager/vine_manager.c
taskvine/src/tools/vine_plot_txn_log
taskvine/test/vine_alloc_test.py

Proportional resources were allocating the whole disk. Since the resource multiplier is not used for disk, no tasks were overcommited to workers. This pr makes it so that the proportion takes into account the multiplier.

Fix proportional resources and resource multiplier

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_cached_name.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_mount.c
taskvine/src/manager/vine_task.c
taskvine/src/tools/vine_benchmark.c
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_worker.c
taskvine/test/TR_vine_valgrind.sh

Files are added using their cache name. The file_id was not needed anymore and was removed.

Add files to file_table when they are declared

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example.py
taskvine/src/examples/vine_example_blast.c
taskvine/src/examples/vine_example_blast.py
taskvine/src/examples/vine_example_chirp.py
taskvine/src/examples/vine_example_gutenberg.c
taskvine/src/examples/vine_example_gutenberg.py
taskvine/src/examples/vine_example_minitask.c
taskvine/src/examples/vine_example_mosaic.c
taskvine/src/examples/vine_example_mosaic.py
taskvine/src/examples/vine_example_peer_transfer.c
taskvine/src/examples/vine_example_poncho.c
taskvine/src/examples/vine_example_watch.c
taskvine/src/examples/vine_example_watch.py
taskvine/src/examples/vine_example_xrootd.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.c
taskvine/src/tools/vine_benchmark.c
taskvine/test/vine_test.py

`vine_mount_flags_t` and `vine_file_flags_t` had repeated flags related caching. This commit removes all caching related flags in `vine_mount_flags_t`. The "no flags" option in vine_mount_flags_t is the new `VINE_TRANSFER_ALWAYS`. Removing VINE_CACHE from vine_mount_flags_t showed that this mount flag was used in vine_task_add_{in,out}put in all the examples, which was incorrect.
file flags where renamed to `VINE_CACHE_NEVER`, `VINE_CACHE`, `VINE_CACHE_ALWAYS`, and `VINE_PEER_NOSHARE`. The main ideas are that `VINE_CACHE&VINE_CACHE_ALWAYS == VINE_CACHE`, and that peer transfer has to be disabled on a per file basis, as we assume that the users want peer transfers as they explicitly have to enable them.

Rename file flags

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c

- Added missing flags to declare chirp.
- Renamed `shared` to `peer_transfer` in python bindings (as that the name used in the function that computes the flags.)
- Added documentation to the flags in taskvine.h
- Apply file flags to the output of mini tasks, not to the mini tasks themselves.

File flags fixes

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_put.c

- Removes a regression where cache names where being computed for VINE_CACHE files.
- On a worker release, delete VINE_CACHE but no VINE_CACHE_ALWAYS files.
- Mark file as VINE_CACHE if VINE_CACHE_NEVER and send twice to a worker.
- Always record a file in the worker table, regardless of its cache flags.

Fixes for cache name and replicas

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_task.c

where name can be one of "allocated", "measured", or "requested"

adds s = vine_task_get_resources(t, name)

---

taskvine/src/tools/vine_plot_txn_log

For some reason I thought this pr was submitted and merged this week. I'm sorry about that. I realized it was not merged this morning. Since you are not using workers with multiple cores, there shouldn't be too much of a difference.
@BarrySlyDelgado 
For your comparison plots, I recommend using `--origin dispatched-first-task`, as this will eliminate the time waiting for workers.
@colinthomas-z80 
I added `--time-ticks-n` which adds n time ticks at regular intervals (default is 1). Also there is `--time-tick VALUE`, with VALUE in seconds from manager start, which may be specified multiple times. These two options may be used together.
Also there is `--legend` por the legend's position. Default is `upper left`. You can use `best` to reduce overlap, but it may increase the render time by …

Assign slots to executing tasks by default

---

makeflow/src/starch
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_chirp.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.c

An environment is a vine file that expands to a directory. The directory is expected to a have a `bin/run_in_env` wrapper.
Environments nest, applied in the order they are defined.
I modified starch to have the `bin/run_in_env`, and update the chirp example to show how it works for chirp. (It worked!)
Something nice about this approach is that we can design general mini task that have as an output a directory with the bin/run_in_env wrapper. (E.g. for apptainer, or other execution wrappers.)
@BarrySlyDelgado 
I think we should do something similar to poncho. The poncho environment should include bin/poncho_package_run, and a script bin/run_in_env that knows how to run poncho_package_run for that environment.

Adds execution environments to tasks

---

taskvine/src/manager/vine_file.c

Otherwise they get deleted when the task terminates. We didn't observe this before because `add_input_temp` did not declare the file at the manager.
With this change, the temp files stay at the worker until explicitly removed.  The only difference to other files is that temp files are not sent back to the manager.

mark temp files with VINE_CACHE

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/vine_manager.c
taskvine/test/vine_test.py

@BarrySlyDelgado 
For PythonTasks, it assumes that `poncho_package_run` is in the `bin` directory of the environment.

vine py: remove methods that added files to tasks without declaring them at the manager

---

taskvine/src/manager/vine_file.c

Per @colinthomas-z80, without this flag there were some scheduling issues.

forbid sharing minitasks, for now

---

taskvine/src/bindings/python3/taskvine.binding.py
work_queue/src/bindings/python3/work_queue.binding.py

E.g. in a notebook now you can do:
```python
m = vine.Manager(port=0, ssl=True)
factory = vine.Factory(m)
with factory:
...
```
and that creates local workers with ssl with the correct host port.
Also this fixes an incorrect openssl command line, and a sefgault with the incorrect staging dir.

vine py: SSL fixes

---

dttools/src/link.c
taskvine/src/manager/vine_manager.c

Remove extra debug info when workers suddenly disconnect.

ssl better logs

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/vine_file.c

As observed by @andrewhennessee, passing None as the second argument do `add_input` or `add_output` was incorrectly handled. None was turned into its string representation and interpreted as the remote name.
This pr makes it so that None is not turned into a string, and the underlying code can check for a null value. That str cast is still ugly

vine py: do not str None

---

dttools/src/category.c
dttools/src/debug.c
dttools/src/debug.h
dttools/src/debug_file.c
taskvine/src/manager/vine_manager.c
taskvine/test/TR_vine_valgrind.sh
work_queue/src/work_queue.c

Given valgrind report, fix long standing issue where reopening the log would print an error for closing fd -1.
Fixes a couple of mem leaks on vine cleanup related to monitoring.
Fixes mem leak in vine and wq where category was being overwritten. 
Related to @BarrySlyDelgado  report, vine_benchmark seems to be fine with respect to file descriptors. The blast example may be triggering something that vine_benchmark is not picking up.
Note: fd leaks is not treated by valgrind as an error. The output of the test needs to be inspected to see this report.

vine: Add resource monitor, track fds to test with valgrind

---

taskvine/src/manager/vine_file.c

They were dropped between declaring the file and actually creating the file.

fix mini task flags

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_txn_log.c

Fixes WAITING to WAITING message in log.  Newly tasks should be created with status UNKNOWN.   READY is for task newly submitted.

Fix double waiting log

---

taskvine/src/worker/vine_coprocess.c
taskvine/src/worker/vine_worker.c

The problem is that when no coprocess is ready to run a function, the message spams the log, e.g.:
2023/03/31 07:57:21.58 vine_worker[130168] vine: Found no valid coprocesses for state
2023/03/31 07:57:21.58 vine_worker[130168] vine: Found no valid coprocesses for state
2023/03/31 07:57:21.58 vine_worker[130168] vine: Found no valid coprocesses for state
2023/03/31 07:57:21.59 vine_worker[130168] vine: task 17 (pid 132843) exited normally with exit code 0
2023/03/31 07:57:21.59 vine_worker[130168] vine: Found coprocess with valid state with pid: 131887
2023/03/31 07:57:21.59 vine_worker[130168] vine: input: link /tmp/worker-196886-130168/cache/buffer-rnd-ufmcxlkyzmtwpss -> /tmp/worker-196886-130168/t.18/infile
2023/03/31 07:57:21.59 vine_worker[130168] vine: started process 132851: …

remove message when no coprocess is found with a given state

---

taskvine/src/manager/vine_manager.c
taskvine/src/tools/vine_plot_txn_log

Added some change_task_state calls when sending out Libraries to have the information about the Library task written to the txn log. The plot tool then uses that task information to plot the Libraries separately above all the regular tasks.

taskvine: Library Plotting

---

taskvine/src/manager/vine_manager.c

The break was a remnant a loop that used to live there.  
For #3252

vine: do not break out of mount loop when looking for transfers

---

configure

Recent changes to the conda build process cause the configure script to pickup the incorrect version of python. There are two version of python, the one we want to build against, and the one in the build environment. In previous versions of the build environment these were the same.
This pr picks up the version from conda environment variables when available. It also removes python2 and golang from the configure script, as their wq bindings are out of date and we won't update them.

Conda from vars

---

taskvine/test/TR_vine_python_task.sh
work_queue/test/TR_work_queue_python_task.sh

In conda-forge build the target python is no longer in the PATH, thus the local workers did not find the correct python version.

add python to path for local tests

---

poncho/src/poncho/package_serverize.py

The waitid system call does not exist on macOS, so changing from waitid to waitpid allows FunctionCall tasks to run on mac workers.

Change waitid to waitpid

---

doc/manuals/taskvine/index.md
doc/manuals/work_queue/index.md
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_pythontask.py
taskvine/src/examples/vine_example_xrootd.py
taskvine/test/TR_vine_python_task.sh
work_queue/src/bindings/python3/PythonTask_example.py
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/test/TR_work_queue_python_task.sh
work_queue/test/TR_work_queue_remotetask.sh

Needed because cloudpickle can serialize some of the objects that dask needs. In the internal use of PythonTask, dill and cloudpickle should be interchangable.
@David-Simonetti-ND I don't think this change affects coprocesses, as I don't think your code relies on particulars of dill.
@tphung3 Is dill used with the parsl integration? I think parsl does its own serialization.

dill to cloudpickle

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/examples/vine_example_dask_awk_array.py

For use, see the  cctools/taskvine/src/examples/vine_example_dask_awk_array.py example.

DaskVine: set resources, environment, and category per function through dask's compute call

---

poncho/src/poncho_package_run

Recently poncho_package_run started failing because `source ...../bin/activate` of conda wanted to consume `"$@"`, which contains the command line to execute.

poncho run: no args to activate

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

Adds init function to manager, and explicit staging directory.
The idea is to pass an initialization function at creation time, as:
```python
def my_init(m):
m.tune(.....)
m = vine.Manager(..., init_fn=my_init)
```
This is useful when the manager is created by a third-party (e.g. coffea) and we do not have direct access to the manager object.

py: Vine manager creation options

---

chirp/src/bindings/python3/ndcctools/chirp.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
work_queue/src/bindings/python3/ndcctools/work_queue.py

Better solution to #3097
Instead of using `__del__`, which is called in unpredictable ways, use `weakref.finalize`, which guaranteed to be called once per object before the globals are deleted.

__del__ to finalize

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

get as a synonym for dask_execute, accept single keys as compute targets.

Daskvine get function

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

(which was the whole point of using finalizers, sigh.)

manager: use finalizer on exit method to avoid double free

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/test/TR_vine_python_temp_files.sh
taskvine/test/vine_python_temp_files.py

Adds `t.enable_temp_output()` and `t.output_file` to support temp files in `PythonTask`. 
Needed to show that the dask graph can execute with all the outputs, but the last one remotely.
@dthain I'm not super happy that the `cloudpickle.load` breaks the abstraction in order to load the files, but I don't see a way around it.

Pythotask remote output

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/test/TR_vine_python_no_serialization.sh
taskvine/test/vine_python_no_serialization.py

The use case is functions that already serialized its output object (i.e. coffea, which gives a compressed output. Serializing it again is just a waste of potentially a lot of memory).

pythontask: add call to disable serialization of output

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/file.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/examples/vine_example_dask_awk_array.py
taskvine/src/examples/vine_example_dask_delayed.py
taskvine/src/examples/vine_example_dask_graph.py

Changed DaskVine to use files to represent results rather than keeping everything in the in memory dag. Otherwise we wouldn't be able to run things like topEFT.
This also allows the use of declare_temp() files by passing the `lazy_transfer=True` to `dask_execute`.

DaskVine with files and temp files

---

batch_job/src/vine_factory.c
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/vine_runtime_dir.c

Adds --parent-death to workers as a safeguard for the controlling process going away.
Makes factory use a different staging dir to the manager, as the manager may cleanup before the factory terminates.

Factory cleanup fixes

---

taskvine/src/examples/vine_example_blast.py
taskvine/src/examples/vine_example_chirp.py
taskvine/src/examples/vine_example_dask_awk_array.py
taskvine/src/examples/vine_example_dask_delayed.py
taskvine/src/examples/vine_example_dask_graph.py
taskvine/src/examples/vine_example_fixed_location.py
taskvine/src/examples/vine_example_gutenberg.py
taskvine/src/examples/vine_example_mosaic.py
taskvine/src/examples/vine_example_watch.py
taskvine/src/examples/vine_example_xrootd.py

Use `result` instead of `result_string`, and fix `set_name` of dask examples.

Vine: minor fixes for examples

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

map and pair will now include PythonTaskNoResult as an output in the list of results rather than causing an error.  I left tree_reduce alone because since the list is meant to be reduced to one element, I thought it made sense that one PythonTaskNoResult should cause an error for the whole thing.

Accounted for PythonTaskNoResult in Python abstractions

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

Using temp files does not currently work if the very last computation is a list. This is because the components of the list are not brought back from the workers.

vine dask: correctly recurse on lists

---

work_queue/src/Makefile

Script must have accidentally been removed at some point.

WQ: Install work_queue_graph_workers into bin.

---

poncho/src/poncho/package_create.py
poncho/src/poncho_package_create

This new feature allows poncho to package a specified conda directory directly, which may include editable packages on a shared file system.

poncho: add option to package directory directly

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
work_queue/src/bindings/python3/ndcctools/work_queue.py

Quirk of python where finalizers are called in the order they were defined on exit, regardless of the reference count. If there were active tasks, this meant that the finalizer of a task would free it, and then the manager would try to do the same from C.
Now tasks check if the manager finalizer is still alive, and whether the manager knows about the task.

vine, wq: fix double free where tasks were freed before the manager

---

doc/manuals/taskvine/index.md
dttools/src/histogram.c
dttools/src/itable.c
dttools/src/itable.h
dttools/test/test_runner_common.sh
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_mount.c
taskvine/src/manager/vine_mount.h
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/worker/vine_worker.c
taskvine/test/TR_vine_python.sh
taskvine/test/TR_vine_python_no_serialization.sh
taskvine/test/TR_vine_python_task.sh
taskvine/test/TR_vine_python_temp_files.sh
taskvine/test/TR_vine_ssl.sh
taskvine/test/TR_vine_tag.sh
taskvine/test/vine_test.py
work_queue/src/work_queue.c

Maintain all tasks and files in manager, even after completion.
Still needs to be refined so that both are deleted when needed.

Vine: Re-Create Lost Temporary Files

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/examples/vine_example_dask_graph.py

Now a PythonTask can execute full sexprs from dask. The previous mode, flattening the graph, can still be used by passing low_memory_mode=True to `get`.

vine dask: rework graph process not to destroy dask optimizations

---

doc/manuals/install/index.md

`packaging` is for poncho, `cloudpickle` is for DaskVine.

CCTools: add necessary package dependencies to development environment

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

`enable_monitoring_full` is no longer supported in C API so the same should happen to Python API.

Vine: remove enable_monitoring_full method in python API

---

.github/workflows/integration.yml
packaging/scripts/generate-images

centos8 does not reflect rhel8 as previous centos versions did. Instead we can use almalinux as a replacement for centos.
This pr replaces centos8 with almalinux8.  The version of mysql used to compile parrot does not compile anymore in almalinux9, though, which is something to consider for bxgrid when the campus upgrades to rhel9.
alma9 was added to the script that generates the images, but cctools does not compile against it yet.

Replace centos8 with almalinux8

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py

There was a recently introduced error where an exception on the python task would give an exit code of 0.

Pythontask correct exit code

---

taskvine/src/manager/vine_manager.c

We may attempt use a file at a peer for a transfer while subsequently unlinking/deleting it when the task ends.

Vine: Do not peer transfer nocache files

---

taskvine/src/examples/vine_example_blast.c
taskvine/src/examples/vine_example_blast.py

The latest URL is now
`https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.14.0+-x64-linux.tar.gz`, which breaks `vine_example_blast.{c,py}`. Pin down specific version of the executable solves the problem.

Pin down a version of blast executable

---

taskvine/src/manager/vine_manager_put.c

This printout is not especially useful and can make the debug log unnecessarily large

vine: remove transfer table from debug log

---

taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_cached_name.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager.c

This is for #3317. VINE_FILEs are given cache names based on their meta data when they are declared with a flag that is not CACHE_ALWAYS. Previously, they were just given a random cache name.

metadata cache names for vine_files that are not CACHE_ALWAYS

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
chirp/src/chirp_server.c
deltadb/src/catalog_server.c
dttools/src/catalog_query.c
dttools/src/catalog_query.h
dttools/src/catalog_update.c
makeflow/src/makeflow_catalog_reporter.c
resource_monitor/src/resource_monitor.c
taskvine/src/manager/vine_manager.c
work_queue/src/work_queue.c

Works, however it currently has the problem that update processes will accumulate as zombies.
Need to flesh out the `process` module so that we can easily reap only relevant processes of a given type.

Catalog: Perform TCP Updates in Background Process

---

poncho/src/poncho/package_create.py

`logging.basicConfig` has a global effect which might affect higher applications (e.g., this sort of hijacks the global logging config and stops them from setting their own configurations, happened with parsl+vine). This fix removes such behavior and only adds a handler (object telling messages where to go) to the locally created logger.

Poncho: Stop logger from having a global effect

---

taskvine/src/examples/vine_example_blast.py
taskvine/src/examples/vine_example_dask_awk_array.py
taskvine/src/examples/vine_example_dask_delayed.py
taskvine/src/examples/vine_example_dask_graph.py
taskvine/src/examples/vine_example_gutenberg.py
taskvine/src/examples/vine_example_pythontask.py

Now that peer transfers are enabled by default, add/fix the argument option to disable them if needed.

Vine: option for disabling peer transfers in examples

---

doc/manuals/taskvine/index.md

Documentation on Parsl repo is in progress but won't appear until Parsl friends make the next release. Otherwise this is RTM.

Vine: add documentation on how to use Parsl with TaskVine

---

dttools/src/Makefile

If a user does not provide a main function in their taskvine or work queue program, the linker may pick this up instead causing some confusing output.

remove env_replace utility from libdttools build

---

poncho/src/poncho/package_create.py
poncho/src/poncho_package_create

Poncho can now create a poncho tarball from an environment name for ease of use.

Poncho: add support to create a poncho tarball from a conda environment name

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py

Fix for #3393. When recursing on "x": "y" and setting the value of x, we would recurse on x rather than y. This probably came about because a similar function (get_ready) correctly uses x for its cases, and set_result was tailored from a copy-paste of get_ready.

dask: fix infinite recursion

---

doc/manuals/taskvine/index.md

The documentation shows the API of FunctionCall as `FunctionCall(lib_name,func_name, *args)` while the true API in python binding is `FunctionCall(func_name, lib_name, *args)`, partially causing issue https://github.com/cooperative-computing-lab/cctools/issues/3402. This PR fixes the docs and is RTM.

TaskVine: Fix serverless documentation

---

dttools/src/list.c

Simplify list_rotate to avoid use of malloc in the inner loop of wq/tv scheduling.

Simplify list_rotate

---

poncho/src/poncho/package_create.py

`set()` is not serializable, so `json.dumps` will fail in certain cases that `conda_spec['dependencies]`'s value is not changed. This is only a bandage fix however, and requires more thinking.

Poncho: Fix initial value so a variable is json-serializable

---

dttools/src/path_disk_size_info.c

`path_disk_size_info` used to open directories in advance before they are read. This behavior causes `too many open files` error with a big enough directory.
The change fixes this behavior by only opening directories to read when needed.
This PR is RTM if all is well.

dttools: fix too many open files

---

work_queue/src/bindings/python3/ndcctools/work_queue.py

The issue is that the old wq executor in coffea (currently used in topcoffea) explicitely calls the __del__ method. Since coffea is moving away from this type of executors, it is easier to fix this from the wq side.

adds __del__ dummy method to WorkQueue

---

taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c

Addresses #3434.  The are some other infelicities in the serverless code, but keeping the fix focused for now.

Vine:  Fix worker crash when using serverless.

---

doc/manuals/taskvine/examples/functional.py
doc/manuals/taskvine/examples/functions.py
doc/manuals/taskvine/examples/quickstart.py
doc/manuals/taskvine/examples/vine_example_apptainer_env.py

examples used deprecated import statements "import taskvine as vine" instead of "import ndcctools.taskvine as vine"

Fix imports in doc example

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_transfer.c

This PR fix #3445 by fsyncing and removing invalid files appropriately.
Also transfer timeout is bumped up to 300 seconds, which should serve fine for 5 GBs per transfer at ND.

Vine: fix #3445

---

taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_transfer.c

Mini tasks or any tasks that are run with `execute_and_wait` have the problem of executing regardless of the status of staged-in files. This PR fixes this and walks back on the `fsync` as it is not relevant. The previous situation where `fsync` apparently fixes the issue in #3348 is random and depends entirely on whether a worker transferring input files to a mini task on another worker fails or not, (e.g., sometimes workers are not evicted and sometimes they are.)
This PR is RTM.

Vine: Properly check if minitask has its input files staged in.

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_perf_log.c
taskvine/src/manager/vine_perf_log.h
taskvine/src/tools/vine_profile_dispatch

vine: mainloop improvements

---

.github/workflows/integration.yml
.gitignore
Makefile
doc/manuals/install/index.md
packaging/lint/README.md
packaging/lint/lint.sh
taskvine/Makefile
taskvine/src/Makefile
taskvine/src/bindings/Makefile
taskvine/src/bindings/python3/Makefile
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/examples/Makefile
taskvine/src/manager/Makefile
taskvine/src/tools/Makefile
taskvine/src/worker/Makefile

This PR made the following changes:
- Edit CI workflow so linting is performed first then regular build and test follows.
- Edit code to comply with flake8.
- Correct several `Makefile` to enable `flake8` linting tests.
- Add flake8 to dev environment so other contributors can run `make test`.
This PR partially addresses issue #3451 by using `flake8`.
Note: linting is currently supported for TaskVine's Python wrapper code.

Vine: Add flake8 to lint Python code of TaskVine

---

configure
packaging/lint/lint.sh
taskvine/src/manager/Makefile
taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_manager.c
taskvine/src/worker/Makefile
taskvine/src/worker/vine_worker.c

This PR made the following changes:
- When `--debug` flag is on with `./configure`, all C source files are compiled with optimal debugging optimization.
- Fix linting in manager and worker of TaskVine to report errors instead of keep going.
- reformat vine_manager.c and vine_worker.c
- add a default clause to a code segment in `vine_cached_name.c` to avoid compilation error.

Build: Fix debug and lint

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_schedule.h
taskvine/src/manager/vine_task.h
taskvine/test/TR_vine_python_serverless.sh
taskvine/test/vine_python_serverless.py

This PR made the following changes:
- Set default resources for library tasks so these tasks will have resources accounted for. The values are arbitrary and need further consideration.
- Remove max_proportion adjustment in `vine_manager_choose_resources_for_task`. This code assumes all tasks have the same resource box and thus tries to round resources. This is not true when library task uses few resources (e.g., 1 core) and function call tasks use arbitrary resources.
- Add check for library tasks when sending them to workers. This check is needed in case worker doesn't have available resources.
- Log library sending operation appropriately.
- Make `check_worker_against_task` available to be used in `vine_manager.c`.
- Fix resources for worker and tasks in serverless test script.
Warning: …

Vine: Partial fix of resources for serverless feature.

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_task.c
taskvine/src/worker/vine_worker.c

Fixes #3441.  A worker "feature" describes the whole worker, and doesn't have a clear way to remove once activated.  This PR no longer uses "features" to indicate that a serverless library is present.  Instead, the manager directly looks for the presence of a library task where l->provides_library matches t->needs_library.
Note that this PR does not (yet) fix the problem of controlling the number of tasks assigned to a library.  That's a separate problem.

Vine: Serverless: Match on library name, not feature.

---

poncho/src/poncho/library_network_code.py
poncho/src/poncho/package_serverize.py
poncho/src/poncho/wq_network_code.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/worker/vine_process.c

Currently Library Task is using stdin/stdout to communicate with worker processes to get data and return results. If a function call prints something out to stdout however, then the communication is corrupted. This fix changes Library Task to use proper pipes to talk with vine worker.
There's also some minor code refactoring and comment editing/adding.

Vine: Library Task communicates with Vine Worker using pipes instead of stdin/stdout.

---

doc/manuals/taskvine/index.md
doc/manuals/work_queue/index.md
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_schedule.h
work_queue/src/work_queue.c

Adds `m.tune("ramp-down-heuristic", 1)`.  When this is enabled and there are more workers than ready tasks, then tasks are allocated all the free resources of a worker.  When looking for workers by files or by time, ties are broken by worst fit.  This mode avoids unnecessary resource exhaustion when there are more workers than tasks. If the monitoring watchdog is not enabled, then this heuristic has no effect. By default it is disabled (set to 0).
It also adds `m.tune("hungry-minimum-factor", 2)`. A manager is hungry if the number of waiting tasks is less than then number of workers times this factor.  By default is set to 2 to avoid ramp-down mode to trigger when the workflow is not really terminating.
With this mode enabled I was able to run the processing+accumulation part of topEFT …

vine, wq: ramp down mode

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_summarize.c
taskvine/src/manager/vine_protocol.h
taskvine/src/manager/vine_resources.c
taskvine/src/manager/vine_resources.h
taskvine/src/worker/vine_gpus.c
taskvine/src/worker/vine_worker.c

`vine_resource` had vestigial fields `largest` and `smallest` that were a holdover from the WQ foreman and resulted in confusing debug output.

Vine: Cleanup resource accounting

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Avoid overhead of enforce_fixed_location unless there are relevant tasks in the queue

vine: track fixed location tasks

---

taskvine/src/bindings/python3/ndcctools/taskvine/file.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/taskvine.i

This seems to work:
```python
import ndcctools.taskvine as vine
import cloudpickle
m = vine.DaskVine(name="test", port=0)
b = m.declare_buffer(cloudpickle.dumps({"a": 0}))
print(type(b.contents()))
c=cloudpickle.loads(b.contents())
print(c)
s="hello pirate ♆"
b2=m.declare_buffer(bytes(s, "utf-8"))
print(bytes.decode(b2.contents(), "utf-8"))
```
```shell
<class 'bytes'>
{'a': 0}
hello pirate ♆
```

return file buffer contents as bytes object

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py

`t.get_metric` needs an argument, so it can't be a property.

vine: remove @property from get_metric definition

---

taskvine/src/manager/vine_manager.c

Fixes incorrect change of task state when resubmitting after exhaustion.

vine: correctly change the state on exhaust resubmit

---

.github/workflows/integration.yml
packaging/build-conda/build.sh
packaging/build-conda/configure.sh
packaging/build-conda/install.sh
packaging/build-conda/setup.sh
packaging/build-conda/test.sh
packaging/scripts/configure-from-image

Integration builds were not correctly picking up the installed conda environment, but running in the default conda environment.  This happened to work by accident b/c our tests were skipping over the cases where cloud pickle etc were not available.

Build: Run Correctly in Conda Environment

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/manager/vine_txn_log.c
taskvine/test/TR_vine_python_cancel.sh
taskvine/test/vine_python_cancel.py

The design of task cancellation is problematic because `task_cancel` is a distinct way of returning a completed task, which makes reference counting more complicated.  This change simplifies cancellation, so that cancelled tasks just get put into the RETRIEVED state and are then returned from `wait` like any other task.

Vine: Simplify Cancel

---

taskvine/test/TR_vine_allocations.sh
taskvine/test/TR_vine_python.sh
taskvine/test/TR_vine_python_serverless.sh
taskvine/test/TR_vine_python_ssl.sh
taskvine/test/TR_vine_python_tag.sh

Modify task vine-python tests to skip if cloudpickle/conda-pack are not present.  This is necessary to pass tests on macOS-11 base platform which has some ancient Python 2.
We need to move up from macOS-11 to a newer Mac platform, and bring in appropriate python dependencies.  But that will be another PR.

Build: Skip Python Tests on MacOS-11 (Python2)

---

taskvine/src/worker/vine_worker.c

When a task with no resources specified lands on a worker, it is assigned all resources of the worker (see `normalize_resources`). However, later on when the worker checks whether the task can fit the current resources, some resources have been taken away by other tasks, so the current task is too big for the worker and thus it is forsaken.
Example: an unspecified task arrives and is assigned 4 GBs of disk space. It depends on a poncho package of size 300 MBs. Once the poncho package is unpacked, the worker later finds out that its disk capacity is only 4 GBs - 300 MBs, so it forsakens the unspecified task as it thinks it doesn't have enough disk space while the unspecified task should run anyway.
Note that this problem doesn't happen with tasks that are clean, i.e., once their executions …

Vine: Make conservative disk estimates when the amount of disk is not given to worker

---

taskvine/src/worker/vine_sandbox.c

Issue #3504 
I have not yet recreated the issue to test if this solves the problem, for now it seems to achieve the intended goal.

Vine: measure whole directory in stageout 

---

taskvine/src/manager/vine_manager.c
taskvine/src/worker/vine_worker.c

For issue #3500.  The only thing missing from the comments is the symlink to sandboxes. This pr addresses the messages part.

Sync result msgs

---

taskvine/src/manager/vine_file_replica_table.c

vine: check transfer addr before using peer

---

taskvine/src/manager/vine_manager.c

vine: don't delete recovery tasks

---

taskvine/src/manager/vine_manager.c

If a task is given an invalid input file (e.g. bad url), the worker would correctly return the task to the manager
with "input missing" but the manager would then attempt to fetch the output files, and conclude "output missing".
This fix skips output fetching when input is missing.

Vine: Fix Input Missing Condition

---

doc/man/m4/poncho_package_run.m4
doc/man/md/poncho_package_run.md
poncho/src/poncho_package_run

Removes -k option from poncho_package_create, as it is already covered by -u DIR and -e DIR. With -k, a user would have to figure out the random name of the directory.

Poncho no k option

---

taskvine/src/manager/vine_manager.c

tasks_on_workers is accurate for what the manager knows. tasks_running depends on worker messages that may be stale.

vine:  changes tasks_running to tasks_on_workers for display tables

---

taskvine/src/worker/vine_worker.c

The formula to compute disk total in the codebase is disk.total = disk_available + disk.inuse (see @vine_resources_measure_locally). By introducing a 90% discount we inadvertently discount the disk inuse, leading to incorrect disk total estimate. This change only discounts the disk_available estimate as disk inuse must be reported as-is.
Note: The disk estimate is very unstable when a poncho tarball unpacks itself, leading to a couple of tasks with unspecified resources being forsaken in the beginning. Once the worker stabilizes then tasks with unspecified resources will be run as usual.

Vine: Fix disk accounting

---

doc/manuals/taskvine/index.md
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Submit recovery tasks for temporary files as soon as their worker is lost.
Use case: topEFT sorts tasks according to how large they are when constructing accumulation tasks. This means that it takes a long time to discover that a result that was expensive to compute was lost. With this change, recovery tasks are created as soon as the worker is gone. Since all tmp files are used as inputs at least once, and topEFT removes tmp files as soon as they are used, this change saves time at the workflow rampdown.
For #3496

vine: tune parameter immediate-recovery

---

taskvine/src/manager/vine_manager.c

if max depth > waiting tasks then tasks would be considered repeteadly for dispatch.

vine: do not consider more than ready tasks

---

taskvine/src/manager/vine_manager.c

Manual uses - for all options, but some used _ in the code.

vine: use - and not _ uniformly for tune options

---

.github/workflows/integration.yml
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/taskvine.h
taskvine/src/worker/vine_sandbox.c
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker.h
taskvine/test/vine_python.py

Attaching large directory trees to the sandbox is expensive by default b/c the worker does a recursive hard-link of the entire directories.  (This is to avoid the tasking being able to "tell" that the object is linked in.)
This PR adds a mount option allowing the object to be attached by a single symlink instead, if the user asks for it.
Considering whether `VINE_MOUNT_SYMLINK` should be used by default in `add_environment`, which would cover most of the `poncho` use cases.

Vine: Add symlink mount option.

---

taskvine/src/tools/vine_plot_txn_log

Change "WAITING" state to "READY", broken in #3494 

Vine: fix vine_plot_txn_log

---

doc/manuals/taskvine/index.md
poncho/src/poncho/library_network_code.py
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c

This PR introduces major fixes and improvements to the serverless facility of TaskVine as follows:
- A function invocation didn't interrupt the vine_worker sleep on the manager link, so each invocation must wait 5 seconds to return. This is because a function invocation isn't a child of the vine_worker. Now the library will send a SIGCHLD signal to the worker upon startup (send after configuration) and function execution completion. Note that the library needs the pid of the vine_worker as the vine_worker is the grandparent of the library instead of the parent. The parent of the library is the shell from exec.
- A function execution will implicitly assume that the necessary parameters are in a file called `infile` and it is supposed to dump results to `outfile`. These files are declared …

Vine: Improve Serverless

---

poncho/src/poncho/wq_network_code.py

WorkQueue: Fix Coprocess Change Path

---

taskvine/src/worker/Makefile
taskvine/src/worker/vine_worker.c

Terminate the buffer before convert it as a string.

TaskVine: Fix buffer null terminate

---

work_queue/test/TR_work_queue_remotetask.sh
work_queue/test/serverless_function.py

The serverless script in wq test is stale. This PR updates it.

WQ: Regenerate serverless script

---

taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_protocol.h
taskvine/src/worker/vine_worker.c

#3531 
This is one implementation where the worker signals the manager it has reached its configured timeout. With this information the manager makes the decision whether or not to release the worker shortly after. 

vine: conditional worker timeout

---

taskvine/src/tools/vine_plot_txn_log

Quick addition to sum the worker running time. It will be an interesting statistic when considering ramp-down performance. I may add a running time vs idle time as well. 

Vine: add cpu time to txn stats

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

Fix issue: #3573. task.submit_finalize(m) must be called when declaring a minitask, because that is equivalent to "submitting" the task for execution.

Vine: Finalize Task When Creating Mini-Task

---

dttools/src/file_link_recursive.c

symlink: do not append cwd path if arg is absolute

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

As observed Connor's workflow, retries were reset per task rather than accounted per dask id.

vine: correctly account for retries in dask vine

---

work_queue/src/work_queue_coprocess.c

Null check resource in case coprocess no longer exists
#3583 

null check resource

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Adds the `env_vars` parameter to `DaskVine.get` to set environment variables per task. Values of variables should be either strings, or functions that return strings and that take as arguments the current manager and current task.

daskvine: add argument to set env variables

---

poncho/src/poncho/library_network_code.py
taskvine/src/manager/vine_protocol.h
taskvine/src/worker/vine_process.c

Before, if a function call prints anything to stdout, then it is routed to the vine_worker process' stdout. This fixes that and makes the library task have the same stdin/out/err setup as the standard task.

TaskVine: Fix problem where function calls print to stdout of the vine_worker process

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c

The current implementation of scheduling function calls is buggy, as for a given task T1, it looks for a candidate worker W in the regular way as other tasks. It then checks W to see if W has the capacity to run T1. The problem is when the second check fails, the main loop in `send_one_task` rotates to the next task T2, T3, T4, etc., until W is available to run a function call again, instead of finding the next worker to run T1.
The fix moves the checking code inside `check_worker_against_task` in `vine_schedule.c`, effectively merging two checks into one. So all workers are checked for a task first before we loop through the task list.

TaskVine: Fix bug in function call scheduling

---

doc/manuals/taskvine/index.md
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_manager_put.h
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_cache.h
taskvine/src/worker/vine_worker.c

Related to #3563 
At the moment, upon a cache update, the manager will check if a temp file was created.
If that is the case, the manager will look for up to q->temp_replica_count workers to replicate the file to.
It uses the new message, `puturl_now,` to tell a worker to bring a remote file to the cache without the need to run a task

Vine: temp file replication

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py

This PR is a supplement of #3592.
The memory leak issue of FunctionCall tasks manifests on two sites: 
- Python maintains references to task objects, failing to timely delete them.
- The manager's declared input and output buffers were not properly disposed of immediately after output retrieval.
While #3592 resolved the first issue, this PR remedies the second.
Comparison of consumed memory before and after changes in this PR with an example executed on 100 tasks:

Vine: Memory Leak Supplement

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py

Fix for #3606. When outputs are not vine temp files, a name outside the task staging directory (but inside the manager staging directory) is set. This allows for the task to be garbaged collected without deleting its output.

dask+vine: set custom name to file outputs

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Since serialization may be expensive, with this commit we set a maximum number of tasks to submit to the manager per wait call. The rest of the tasks are added to a FIFO queue to wait their turn to be serialized. This has the effect of overlapping serialization with execution.

dask+vine: Do not immediately serialize waiting calls.

---

taskvine/src/manager/vine_manager.c

vine: remove file before table before freeing structure
We where using f->cache_name after the f structure had been freed.
It led to a segfault when a file was declared and removed immediately.

vine: file remove before delete

---

taskvine/src/manager/vine_mount.c

vine: when copying mounts, do not clone input file twice.

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_txn_log.c
taskvine/src/manager/vine_txn_log.h
taskvine/src/tools/vine_plot_txn_log

These entries appear as APPLICATION [custom message]

vine: write custom entries to debug and transactions logs

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

- Manager generates internal uuid and sends to the catalog.
- User can add properties with m.set_catalog_property. 
Intended use is recording connection to frameworks such as Dask, Parsl, etc. per #2642

Vine: Report UUID and Catalog Properties

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h

Truncate watched files at submit time, to avoid confusion when a workflow is restarted, and the user is doing a `tail -f log file`.
Arguably, we could also do an `unlink_recursive` on all output files, but I'm not so eager to take a destructive action that could be triggered accidentally.
Addressed #3051 

Vine: Truncate Watched Files on Submit

---

taskvine/src/manager/vine_manager.c

vine: free file resources if manager is gc'ed.

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c

Previously, the Work Queue and Vine factories special-cased HTCondor and required it to use /tmp for the scratch dir.  This was because (at Notre Dame), AFS was used for home directories, but HTCondor did not play well with AFS.
Today, HTCondor requires the use of the home directory for the user-log.  And also very few users of AFS remain.
So, this changes the factories to have the same default behavior for all batch systems -- use the current working directory for the scratch dir.  If that happens to be AFS, the factory gives an error.  If that happens to be not-home, (certain versions of) HTCondor gives an error.  The user can override with `--scratch-dir`
The more 'x' ticked, the faster your changes are …

Factory: Handling of Scratch Dir for HTCondor

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c

Adds the declare_file VINE_UNLINK_WHEN_DONE  (unlink_when_done=True in python) to unlink a file at the manager's disk when the file refcount goes to 0.
This pr only implements the mechanism, but it has not been integrated to other parts of the code (e.g., PythonTask).

Unlink when done (C and python bindings)

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/examples/vine_example_fixed_location.py
taskvine/src/examples/vine_example_mosaic.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/test/vine_python_temp_files.py

Rename remove_file to undeclare_file.
This better reflects the fact that we want the opposite of what declare_file does, and that remove_file does not actually remove the file from disk.

vine: remove_file to undeclare_file

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/vine_manager.c

The operation of vine_remove_file is now limited to just the file itself: it is removed from the file table, deleted from all workers.
But we don't iterate over all tasks.  (esp since there will often be a unique file per task). It is the caller's job to ensure that a file is only removed when all uses are complete.

Vine: Remove File Focused on Deleting Replicas

---

doc/manuals/taskvine/examples/run_command_in_apptainer.sh
doc/manuals/taskvine/examples/vine_example_apptainer_ctx.py
doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/examples/vine_example_chirp.py
taskvine/src/examples/vine_example_mosaic.py
taskvine/src/examples/vine_example_poncho.c
taskvine/src/examples/vine_example_poncho_in_python.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_task.c

`vine_task_add_environment` is confusingly similar to `vine_task_add_env_var`.  Change to:
- `vine_task_add_execution_context` for the general case
- `vine_task_add_poncho_package` for Poncho
- `vine_task_add_starch_package` for Starch.
- 

Vine: Rename Uses of Environment to Context and Package.

---

dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll.h
resource_monitor/src/bindings/python3/ndcctools/resource_monitor.py
resource_monitor/src/rmonitor_poll_example.c
taskvine/src/manager/vine_fair.c
taskvine/src/manager/vine_manager.c
work_queue/src/work_queue.c
work_queue/src/work_queue_coprocess.c

Measuring disk at the manager may take a long time, and it is information that we never really use. Further, it is noisy, as the manager's working directory may have files (such as previous logs) that are not related to the workflow.
@BarrySlyDelgado I think you were observing this a couple of months ago.
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to …

do not measure disk at the manager

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/worker/vine_sandbox.c
taskvine/src/worker/vine_worker.c

`vine_declare_empty_dir` was always a bit of an oddity because it mixed up the handling of input and output.  It was a carry over from WQ to handle a special case of long ago.  This PR removes the concept of an empty dir as input, and adds the mount flag `VINE_MOUNT_MKDIR` for output files.  This causes an empty directory to be made in the task sandbox as the "first step" of creating an output object.  It is equivalent to simply peforming `mkdir x` immediately before running the task.

Vine: Rework Empty Dir Handling

---

taskvine/src/manager/vine_manager_put.c

vine: disable file cache check warning (temporarily)

---

taskvine/src/manager/Makefile
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_factory.c
taskvine/src/manager/vine_manager_factory.h

Pulls out the (infrequently used) code the tracks the relationships between workers and the factories that they came from.  Cleaning things out to make the manager main loop more accessible.  Also keeps these related things clearly together in `vine_manager_factory`.

Vine: Factor Out Worker-From-Factory Code

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_protocol.h
taskvine/src/manager/vine_resources.c
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h
taskvine/src/worker/vine_worker.c

In preparation for making some improvements to the manager-worker protocol:
- Clean up handling of resource messages so that they are self-contained, rather than mixing asynchronous and info messages.
- Remove handling of info message that are totally unused by the worker.
- Remove the stats structure from `vine_worker_info` which was no longer filled with data but still being summed up.
The one item remaining is the `info tasks_running` coming from the worker, which is now saved as `w->dynamic_tasks_running`.  This seems useful for troubleshooting, but was never used for any stats or scheduling decisions.
This section is dedicated to …

Vine: Cleanup Worker Info and Stats

---

taskvine/src/tools/vine_plot_txn_log

PR [3617](https://github.com/cooperative-computing-lab/cctools/pull/3617) added the ability for the end user to add custom events to the transaction log. This PR enhances vine_plot_txn_log to show a labelled vertical bar whenever a custom event encountered in the log.

vine_plot_txn_log:  vine-3620 - added vertical line to transaction log graph

---

taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py

Previously TaskVine would generate wrapper and function file per task, even when the wrapper was the same for all the PythonTask, and the function was used by other tasks.
This pr makes it so that wrappers and functions are serialized once. Further, functions are not written to disc but kept as a declare_buffer.
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel …

vine: use a single file for wrappers, buffer for functions

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

vine: ensure factory scratch dir exists

---

deltadb/test/TR_catalog_server.sh
deltadb/test/TR_catalog_server_ssl.sh

This fixes an occasional bug in CI (on macos) in which TR_catalog_server_ssl fails b/c port 9097 is still in use from the prior test -- the killed server just hasn't exited quickly enough.
Wait for catalog server to exit after sending kill signal. This fixes an occasional bug in CI (on macos) in which TR_catalog_server_ssl fails b/c port 9097 is still in use from the prior test -- the killed server just hasn't exited quickly enough.

Test: Wait After Kill

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/manager/vine_manager.c

Don't use busy waiting flag to decide to break vine's wait loop.

vine: better prefer dispatch

---

taskvine/src/manager/vine_manager.c

vine: compare cache level TASK instead of WORKFLOW

---

dttools/src/Makefile
dttools/src/hash_table.c
dttools/src/hash_table.h
dttools/src/hash_table_offset_test.c
dttools/test/TR_hash_table_offset.sh
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_schedule.c

adds HASH_TABLE_ITERATE_RANDOM_START
like HASH_TABLE_ITERATE, but starting at a random key. Use as:
```C
int offset_bookkeep;
char *key;
some_type *value;
HASH_TABLE_ITERATE_RANDOM_START(table, offset_bookkeep, key, value) {
}
```

vine: Hash random start

---

taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager_get.c

vine: consider cached output buffers as replicas at workers

---

taskvine/src/manager/vine_file_replica_table.c

Begin with a check to make sure a replica is ready to transfer when we decide the file is available

vine: resolve uncertain temp availability issue 

---

makeflow/src/lexer.c
makeflow/test/TR_makeflow_020_syntax_dashes.sh
makeflow/test/syntax/dashes.makeflow

Per issue #3700 Makeflow was not accepting filenames with multiple dashes. The problem here is that the lexer is looking for a remote rename operator `->` as a terminator for a filename.  It correctly handled a single dash, but didn't look for more.  This fix consumes any number of dashes not followed by a `>`.

Makeflow: Fix handling of dashes in filenames.

---

dttools/src/set.c
dttools/src/set.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_get.c
taskvine/src/manager/vine_manager_put.c

To make the random selection efficient, a table that maps cachename->set of files was added.

vine: worker<->file association

---

taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c

If we restrict the check for replica availability only for replicas that are ready, then multiple recovery tasks for the same file are created.
This commit simply checks if there is a replica somewhere, even if it just in a pending state.
This means that #3692 is not fixed.

vine: fix recovery tasks multiple creation

---

configure
parrot/src/pfs_service_cvmfs.cc

Previous --debug only turned on optimizations that could be used with debug. Traditionally we always included debugging symbols.

configure: turn on max debug symbols with --debug

---

dttools/src/set.c
dttools/src/set.h

Adds call to generate a random array of the elements of a set. This to allow the modification of the set during iteration.

set: array of elements in random order

---

dttools/src/Makefile
dttools/src/hash_table.c
dttools/src/hash_table.h
dttools/src/hash_table_fromkey_test.c
dttools/test/TR_hash_table_fromkey.sh

Allows to start iteration from a given key in a hash table. (See example test).
It should be useful when want to restart iterations on a hash without checking every element. (E.g. schedule depth for file replicas.)
```C
int iter_control, iter_count_var;
HASH_TABLE_ITERATE_FROM_KEY( h, iter_control, iter_count_var, key_start, name, box ) {
```
This section is dedicated to changes that are ambitious or complex and require …

dttools: add hash iteration from a given key

---

taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_put.c

Adds pending replicas to the replica table. It also is able to choose different sources for the file, so that we can call this function somewhere in wait_internal to ensure the required number of replicas. (We need to discuss how to do that step efficiently.)
Commented out is the check for file_max_source_transfers, otherwise only one replica is created.
@colinthomas-z80 This one fixes the bug in #3714 for the current release. It conflicts with #3709 because it uses the functions that check for the number of replicas, but I think this should be minor conflicts.
This section is dedicated to changes that are ambitious or complex and require …

vine: record replicas in transit

---

taskvine/src/worker/vine_cache.c

This commit should be reverted once we track all the places that trigger a put url, url_now, or mini_task.

vine: temp fix, worker does not fail on repeated put_url

---

doc/manuals/taskvine/index.md
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c

Before it was with the exhausted tasks check. This made sense at the time because it was only used for exhausted resources. It is likely we soon we will use it more for transient failures, etc.

vine: move retry logic into a proper place

---

taskvine/src/tools/vine_submit_workers

This allows to submit workers inside a docker image that does not share a directory with the host. Per condor_submit documentation:
Spool all required input files, job event log, and proxy over the
connection to the condor_schedd. After submission, modify local
copies of the files without affecting your jobs. Any output files
for completed jobs need to be retrieved with condor_transfer_data.
This won't work immediately with the factory, as the condor log file needs to be manually transfered back with condor_transfer_data clusterid.jobid
Solves #3715 for coffea-casa.
Put …

vine: adds --spool to vine_submit_workers -T condor

---

dttools/src/s3_file_io.c

s3_file_io.c used an older code pattern of allocating HMAC_CTX on the stack,
and the current practice in SSL is to instead use HMAC_CTX_new/free.
Note that this module has a number of other code smells that I am not cleaning up at this moment.
Also, it was not compiled in CI due to the lack of lib curl.
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to …

S3: Fix use of HMAC_CTX

---

taskvine/src/worker/vine_process.c

Add environment variables to control thread quantity for MKL, VECLIB, BLAS, and NUMEXPR, in addition to the existing OpenMP.  Numpy and other systems may use any or all of these depending on how they were compiled.

Vine: Support more thread limits.

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_schedule.c

Fix segfault: handle possibility that check_worker_against_task may fail and invalidate the worker object if it attempts to send a library to the worker and fails.
Fixes #3471

Vine: Fix Library Failure Segfault

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_get.c
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_cache.h
taskvine/src/worker/vine_cache_file.c
taskvine/src/worker/vine_sandbox.c
taskvine/src/worker/vine_worker.c

Previously, when a library would exit (success or otherwise), two problems resulted:
1 - The function calls sent subsequent to that library would simply sit on the worker doing nothing.
2 - The manager would quickly re-dispatch a library to that same worker, resulting in a tight loop of failures.
This PR fixes these as follows:
1 - The worker now has extended logic for `task_can_fit_eventually` so that functions will be forsaken if there is no library process at all that could execute them.
2 - Forsaken tasks are now handled correctly by deleting their sandboxes once they are retrieved.
3 - The most recent failure of a library is recorded in the library prototype object and used to throttle re-dispatch of failed library tasks.
4 - Fetching of task stdout is factored out of get_result to …

Vine: Forsake functions when library exits.

---

taskvine/src/tools/vine_submit_workers

- Accept -Xarg -X arg --X arg --X=arg
- Options may be specified in any order. (Except for -Tbatch, which should appear before any batch option.)
- Added --dry-run to show submit files.
- Worker may receive both manager port address and name.
- Removed unused slurm job array
- Removed bashisms
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the …

vine: cleanup vine_submit_workers

---

taskvine/src/manager/vine_current_transfers.c
taskvine/test/vine_python.py

Avoid segfault with race condition where source worker disconnects before it can be blamed from a failed transfer.

vine: remove transfer pairs with sources

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h
taskvine/src/worker/vine_worker.c
taskvine/test/vine_python.py

Turn transfer missing result to forsaken.
Throttle worker and task accordingly.

transfer missing to forsaken

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
doc/man/m4/vine_factory.m4
doc/man/m4/vine_status.m4
doc/man/m4/vine_worker.m4
doc/man/md/vine_factory.md
doc/man/md/vine_status.md
doc/man/md/vine_worker.md
dttools/src/link.c
dttools/src/link.h
taskvine/src/tools/vine_status.c
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker_options.c
taskvine/src/worker/vine_worker_options.h
work_queue/src/work_queue_status.c
work_queue/src/work_queue_worker.c

Use correct domain name when setting SNI
Adds --tls-sni to change name presented on handshake.

vine: fixes to SNI handling (coffea-casa)

---

taskvine/src/manager/vine_schedule.c

The fixed location check routine was looking at file flags, rather than mount flags, causing some unpredictable task forsaking.
Also added a debug to make it more visible in the event we cannot find a worker with the file.

vine: fixed_location flag check

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c

When the dask executor finished the graph, now it will update the catalog info. Before, the info will not be updated if the manager was run inside a notebook (i.e., no further m.wait calls), which was confusing when running `vine_status`

dask vine: Report to catalog on end of processing graph

---

doc/man/m4/vine_worker.m4
doc/man/md/vine_worker.md
dttools/src/address.c
dttools/src/address.h
taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_protocol.h
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker_options.c
taskvine/src/worker/vine_worker_options.h

Adds explicit --transfer-address to vine worker. If given, manager does nothing to the address. worker urls are now `workerip://` and `worker://`.  If `worker://`, then on get, the worker does a name resolution.

vine: Worker contact address

---

dttools/src/category.c
dttools/src/category.h
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
work_queue/src/bindings/python3/ndcctools/work_queue.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

vine, wq: set a maximum number of task to run per category

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: lib tasks coffea casa minor fixes

---

taskvine/src/manager/Makefile
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_counters.c
taskvine/src/manager/vine_counters.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file_replica.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_mount.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_worker_info.c
taskvine/test/vine_python_task.py

Added vine_counters module to help with leak detection on primary objects.
Call vine_counters_print() to display total number of objects created/cloned/deleted.
Note that it's a bit tricky with Python because dangling references to objects in Python
will continue to reference the C objects as well.

Vine: Add counters for performance and leak detection.

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/manager/vine_manager.c

This do not fix the mismatch of clones for FunctionCalls.

vine: small task fixes related to mem leaks

---

dttools/src/random.c
taskvine/src/worker/vine_worker.c
work_queue/src/work_queue_worker.c

By using `srand` to compute worker-id, we didn't take advantage of `random_init`. 

Worker id after random init

---

dttools/src/cctools.c
dttools/src/cctools.h
taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/taskvine.i
work_queue/src/bindings/python3/ndcctools/work_queue.py
work_queue/src/work_queue.i

vine, wq: version strings

---

taskvine/src/manager/vine_manager.c

Previously whenever a function call is about to be dispatched, the manager writes `VINE_LIBRARY_SENT` to the transaction log which is incorrect. This is fixed so that the manager only writes it when a library is about to be dispatched.
Also finding the library in `commit_task_to_worker()` is redundant as `t->library_task` is set in vine_manager_check_worker_can_run_function_task()`, so it is removed.

TaskVine: Fix logging of library deployment

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: avoid running keys twice
Seldom on init, some keys would get schedule for execution twice. Changed from
list to dictionaries to eliminate repetitions.

Daskvine fix repeated keys

---

environment.yml
taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

`rich` dependency adds ~10MB to conda env. (A bare-bones with cctools and python is 579MB, with rich is 590MB).
Something like this is needed because of long running graphs the user has no indication of the progress. 

vine: dask add progress bar

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_schedule.h

If a worker had a library with all the slots full, the library would be sent again to the worker. 
Also, library tasks were cloned when submitted, but this is not needed as taskvine is the user of the task. For all other tasks we increase the ref count because is the responsibility of the user to delete them after wait.
These two conditions created a memleak just by checking whether tasks could be run.
I think this is the memleak observed in coffea.casa, but I have not tried yet.
The more 'x' …

vine: send library memleak

---

poncho/src/poncho/library_network_code.py
poncho/src/poncho/package_serverize.py
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_process.h
taskvine/src/worker/vine_worker.c

Second part of #3802.  The exit code of the function call is assigned to its process struct.
Note that no update in the protocol version is needed. The previous version used strtoul for the task id conversion, and discarded any extra characters.

vine: function call exit code

---

taskvine/src/manager/vine_counters.c
taskvine/src/manager/vine_counters.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_mount.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h

This PR changes all clones from various objects to addrefs as agreed in https://github.com/cooperative-computing-lab/cctools/issues/3797.

vine: change `clone` to `addref`

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.h

Splits VINE_TASK_TYPE_LIBRARY to VINE_TASK_TYPE_LIBRARY_TEMPLATE and VINE_TASK_TYPE_LIBRARY_INSTANCE. 

change LIBRARY to TEMPLATE and INSTANCE

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Return any completed task to the application without doing any work.

vine: Wait no wait

---

taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager_put.c

coffea casa touches token files, which modifies file times withouth modifying the contents.

vine: temporary change: do not fail task if input file changed

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_task.c

Remove library instances from retrieved list when waiting by tag.
Still need to fix when waiting by task id.

vine: release lib tasks

---

taskvine/src/manager/vine_blocklist.c
taskvine/src/manager/vine_blocklist.h
taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_txn_log.c
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h

Temporary fix for #3763. If worker can't transfer input file, it is released.
Without this change, coffea casa workflows get stuck, as there is always a worker that can't communicate with other workers.
Maybe we can add a counter so that the worker is released after 3 consecutive failed tasks, or something like that. 

vine: temporary, release worker that failed to xfer input file

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c

Makes the behavior of python tasks and function calls the same when dealing with input and output files. The caller should be in charge of undeclaring outputs. Function calls used to undeclare output when calling `t.output`, but this side effect made it hard to the caller to decide what to do with files.
This change also makes it easier to achieve #3828 and #3829.

vine: dask executor worker transfers segfault fix

---

.github/workflows/integration.yml

Github complains about actions v3 using NodeJS 16.  Updated to v4 using NodeJS 20.

Infra: Update GitHub actions to v4

---

poncho/src/poncho/package_serverize.py
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

While constructing and submitting a FunctionCall task, for example, `task = vine.FunctionCall('test-library', 'my_func', args.size)`, this PR checks one thing:
- `test-library` should exist in current libraries
It also comes with some renaming just for better readability 

vine: check if the library exists when submitting FunctionCall tasks

---

poncho/src/poncho/package_serverize.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

Fix for #3569, while calculating the hash for library functions, this pr does two things to avoid creating a new environment with minor modifications that do not affect the execution of functions:
- consider the module names in `import_modules`
- remove comments, blank lines and extraneous newlines 

vine: combine imports when calculating function hash

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_schedule.h

The scheduler should *not* modify the state of the system in check_worker_against_task. Instead, when scheduling a function call, look for compatibility and capacity for library tasks, and then dispatch them in commit_task_to_worker.
Fixes #3825

Vine: Keep Scheduler Stateless for Libraries/Functions

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_chirp.c
batch_job/src/batch_job_dryrun.c
batch_job/src/batch_job_internal.h
batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
dttools/src/copy_stream.c
makeflow/src/makeflow_module_archive.c

Fix for #3862
The current returning value of `copy_file_to_file` is `int64` if success. However, there are some places receiving the returned value with `int`, which might be overflowing and causing errors. 
In this PR I simply modified some variable types when using `copy_file_to_file` so that it consistently uses `int64` to avoid overflow.

vine: consistently use int64 in copy_file_to_file

---

taskvine/src/worker/vine_sandbox.c

Fix for #3864. 
Here the issue is that in the function `stage_output_file`, the parameter size is correctly passed to `vine_cache_add_file` to obtain the file size. However, this does not update the `f->size` field. In `vine_cache_add_file`, a new `f` object is created using `vine_hwache_file_create`, which is not the same as the `vine_file` object from `stage_output_file`. Therefore, despite the local `f` object using this size within `vine_cache_add_file`, it is discarded after the function ends, leaving the original `f->size` in `stage_output_file` unchanged. The correct approach would be to update the original `f->size` with `f->size = size` after the call to `vine_cache_add_file`.
Check these off to verify you have …

vine: assign size to t->size in stage_output_file

---

configure
dttools/src/auth_ticket.c

Modify `auth_ticket.c` to use openssl pkeyutl instead of (deprecated) rsautl.  Also used the opportunity to make this code more like idiomatic cctools code.  Fixes #3183 

Chirp: Use openssl pkeyutl instead of rsautl

---

batch_job/src/batch_job_vine.c

Report framework as "makeflow" through vine_set_property.  Addresses #2642

Batch Job: Use vine_set_framework to indicate when makeflow is using taskvine.

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_schedule.c

Before we only considered the size of active task data when calculating worker->disk.inuse. 
This additionally sums the cached files currently on the worker. This presents a more accurate picture of worker disk usage.
In combination with the default proportional resource allocation, provided the estimated allocation is large enough, we will not schedule a final task to fill up the disk and make the worker exit.
However if the proportional resource allocation is not large enough we may still overfill the worker and cause it to exit.  

vine: sum disk usage to avoid overfilling worker allocation

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c

The first solution for #3851 
This pr implements the file pruning feature in DaskVine executor. Once the DaskVine executor figures out that an output file is no longer needed in the future, it prunes it right away so that the stale files are not piling up on the workers and the workers have more storage for subsequent tasks. 
I tested the performance before and after the pruning feature is enabled on the following task graph (a compact version of the [skimmer](https://github.com/cmoore24-24/hgg/blob/main/notebooks/skims/skimmer/skimmer.py) application)
This is the per-worker disk usage(MB) over time(s) initially
And this is after the pruning is active
As the application proceeds, files that are no longer needed will be pruned right away, rather than remaining on the worker until the final …

vine: prune stale files in daskvine

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py

In PythonTask and FunctionCall, we do the garbage collection for input files in `__del__`, which undeclares the `self._input_file` to remove those files both in the cluster and the manager. The way FunctionCall declares input files is correct, but PythonTask uses local variables to declare input files, this prevents us from unsuccessfully undeclaring them in `__del__`.

vine: stage out pythontask input properly

---

taskvine/src/manager/vine_manager.c

The second solution for #3851 
While checking for available inputs, we return 0 as soon as an input file is missing and submit a relevant recovery task. For Connor's application, there are a large number of parallel tasks in the final stages, and most of them are lengthy. The final task can only run when all inputs are available. However, when considering the first several inputs' availability, some at the end may be missing and are not properly accounted for. Given that some tasks are extremely long, this increases the likelihood of losing other files during recovery. Recovering them one by one results in an endless loop.

vine: submit all potential recovery tasks for one task in one go

---

taskvine/src/manager/vine_manager.c

The third solution for #3851
Currently, with tuning `m.tune("transfer-temps-recovery", 1)`, the manager is able to replicate the lost temp files to reach the threshold, for better failure tolerance. 
The way to replicate temp files on worker removal is to invoke `recall_worker_lost_temp_files`, where every temp file is enqueued into the `temp_files_to_replicate`. Files in this queue will be considered to be replicated to reach the `temp-replica-count` threshold.  
However, there are two problems:
1. If the `temp-replica-count` is not tuned, the default replica count is `0`, a temp file will be recovered when a future task claims it as an input.
2. If the `temp-replica-count` is tuned, and all workers containing a temp file are lost at the same time, as no transfer sources are available, a …

vine: recover lost temporary files on worker removal

---

taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c

Fix #3890 
I previously misunderstood the meaning of `curr_file_replication_cnt`, which should be *the count of replicated files in the current round*, rather than *the total count of replicas for the current file*. 
The `curr_file_replication_cnt` can be `0` because the only worker holding it is busy replicating or the manager reaches the transfer limit. But that doesn't mean the file was lost.
It should be working now.

vine: fix useless recovery tasks submission

---

taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/test/TR_vine_python_future_module.sh
taskvine/test/vine_python_future_module.py

This adds module functions `wait` and `as_completed` to the vine futures. in regard to #3835

Vine: add wait and as_completed for futures

---

taskvine/src/bindings/python3/ndcctools/taskvine/file.py
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py

This changes the method in which results for TaskVine futures a retrieved. Previously, a retriever task would be spawned to read the TEMP file output of a future task and return the result. Instead, this PR directs the manager to fetch the file once a result is called.
This is to address #3892 in which exposes a weakness to the previous approach. For a DAG with N leaf nodes in which results are retrieved, 2N tasks will be spawned. Using the example @gpauloski provided, the latency should now be more comparable to the base example using PythonTasks.
```python
import time
import sys
import ndcctools.taskvine as vine
def noop():
pass
tasks = 50
if sys.argv[1] ==  'executor':
with vine.FuturesExecutor(manager_name='manager', opts={'min_workers': 1}, batch_type='local') as e:
start = …
```

Futures stream output

---

poncho/src/poncho/library_network_code.py

To fix #3892 
In the serverless mode, we use `cloudpickle` to serialize and deserialize arguments to/from a file. However, if some of the arguments are python packages or objects, the `cloudpickle` will serialize them by reference as the default approach, and unpickling them triggers the import of their dependencies at load time. ([difference between pickle and cloudpickle](https://github.com/cloudpipe/cloudpickle?tab=readme-ov-file#overriding-pickles-serialization-mechanism-for-importable-constructs) for reference)
For [example](https://github.com/cooperative-computing-lab/cctools/issues/3892#issuecomment-2272191427), the code snippets are dumping exactly the same `Data` object, except that one serializes by reference and the other serializes by value. The first one has a smaller file …

vine: deserialize argument infile before forking

---

doc/manuals/taskvine/index.md
poncho/src/poncho/package_serverize.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/examples/vine_example_function_call.py
taskvine/test/vine_python_future_funcall.py
taskvine/test/vine_python_serverless.py

This PR is in part to support #3892 to run on a serverless mode. It essentially does two things:
1. Rename the `import_modules` to `hoisting_modules` to expand it's definition, so as to accept not only python packages, but also classes and functions
2. Accept class and function declarations and hoist in the library code. For example:
``` Python
import uuid
import random
class test_class():
def __init__(self):
print("test")
def test_func():
return 100
libtask = engine.executor.create_library_from_functions(
"test-library", noop_task, hoisting_modules=[uuid, random, test_class, test_func], add_env=False
)
```
This will hoist the declarations of `test_class` and `test_func` so that function calls can invoke directly.
Check these …

vine: include functions and classes in hoisting_modules

---

doc/manuals/taskvine/index.md
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c
taskvine/test/TR_vine_python_serverless.sh
taskvine/test/vine_python_serverless.py

If the number of function slots is unspecified, it will now be set to the number of cores allocated to the LibraryTask.   (And, it was already the case that an unlabeled task uses all the cores on a worker.). This makes it easier for a user to get the expected result by just taking the defaults all the way through.

Vine: Function Slots Default to Number of Cores

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

For #3893. Do not catch import exception when creating a library and allow it to fail normally, which provides a clearer error message. 
- [] Manual Update     Update the manual to reflect user-visible changes.

TaskVine: dont catch import error when creating library

---

taskvine/src/worker/vine_worker.c

In a local setting (and perhaps remote) the total worker disk will grow smaller as files are generated and will quickly go below the library task allocation if it is has been given the whole disk.
Currently the resources given to a library task by the manager are fixed, where ideally we would adjust the allocation at runtime based on available remaining disk in the same way we schedule normal tasks. However the process of doing that is somewhat of a question. 

vine: remove disk check for library task

---

taskvine/src/manager/vine_schedule.c

The resource allocation problem I pointed out [yesterday](https://github.com/cooperative-computing-lab/cctools/pull/3909#issuecomment-2276165542) is a little bit different from Colin's observation, and PR #3909 doesn't really solve the problem for Greg's application. 
This is a temporary PR to quickly step over the resource check for normal function calls so that they are not hung due to the consistent `in_use + needed > total` statement.

vine: temporarily remove resource check for function calls

---

taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker_options.c

When other processes alongside the worker are consuming disk space on the machine, tasks which request the whole worker disk will be forsaken periodically because the worker is offering the entire available disk space, and the manager does not know about the unrelated disk consumption. 
This can be mitigated by either assigning a disk value to a task, or starting the worker with a finite disk value. If the user does none of these things the problem will persist. This will set a default worker disk value of half the available disk at the time the worker starts.

vine: default worker disk to half avaialble

---

taskvine/src/manager/vine_manager.c

We have observed in a few different scenarios where our proportional resource calculation and other default values are not effective in running some applications, sometimes even detrimental to their function. 
If a user specifies resources for a task we should give them exactly what they asked for. Some may find it confusing to see tasks are receiving more resources than were specified. This will also give the user the control to get their application running in the event our calculation is causing some issue. 

vine: do not override user resource specifications

---

doc/README.md
doc/manuals/jx-workflow/jx.md
doc/manuals/taskvine/code-examples
doc/manuals/taskvine/example-blast.md
doc/manuals/taskvine/example-functional.md
doc/manuals/taskvine/example-gradient-descent.md
doc/manuals/taskvine/example-gutenberg.md
doc/manuals/taskvine/example-mosaic.md
doc/manuals/taskvine/example-watch.md
doc/manuals/taskvine/index.md
doc/manuals/work_queue/index.md
doc/mkdocs.yml

The online version of the docs had big blank spaces where the example code should be!
- I fixed the instructions (and use of paths) in the examples so that our testing procedure now matches the deployment procedure.
- The settings for pymdown_extensions now fail if a file cannot be included, so we will actually see such problems in the future.
- A number of broken internal links and references are now fixed.

Doc: Fix Build Namespace and Broken Links

---

README.md
doc/manuals/install/index.md
doc/manuals/taskvine/index.md
doc/manuals/work_queue/index.md
packaging/build-conda/setup.sh

This PR updates the documentation to recommend the Miniforge distribution instead of Miniconda, since Miniforge defaults to the permissively licensed `conda-forge` channel (where `ndcctools` lives) rather than the default channel. This also removes the outdated note recommending Python 3.9, since this no longer applies.
I left the `-c conda-forge` flag in the conda usage examples to preserve compatibility with existing Miniconda installations.
~~The only remaining meaningful reference to Miniconda in the repo is the `packaging/build-conda/setup.sh` script, as I did not want to touch any CI infrastructure.~~ The script now uses Miniforge. 

Recommend Miniforge instead of Miniconda and remove Python 3.9 note in install documentation

---

taskvine/src/tools/vine_graph_log

The `vine_graph_log` tool uses a Python regular expression to extract the version of `gnuplot`. The regex string contains multiple regex escape sequences (e.g., `\s` and `\d`) that are not properly escaped. In Python <3.12, this raises a `DeprecationWarning`. In Python >=3.12, this raises a `SyntaxWarning`. In future versions of Python, this warning will become a `SyntaxError`.
When writing _complex_ regular expressions in Python, we should use raw strings. This prevents backslash characters from special treatment so they are properly passed to the regex engine.

Use raw string for Python regular expression

---

taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/test/vine_python_future_funcall.py
taskvine/test/vine_python_future_module.py
taskvine/test/vine_python_future_pythontask.py

Improves how task errors and timeouts are propagated in `Future`, `wait()`, and `as_completed()` when using the `FuturesExecutor` (see #3920). The commits are in chronological order, each addressing a single class/function, if you prefer to review it that way.
A couple notes:
- In addition to fixing how `TimeoutErrors` are raised in `as_completed`, I changed it to return a generator which will reduce latency on the consumer side compared to waiting to construct an iterator from a fully constructed list of futures.
- `FutureFunctionCall.output()`/`FuturePythonTask.output()` were inconsistent in when they raised vs returned task exceptions. I changed those methods to always return task exceptions, and then left the responsibility of raising exceptions to the `Future.result()`.
- …

Vine: Improve how errors are propagated with `FuturesExecutor`

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_task.c

For part of  #3920. Calling `future.done()` or `future.running()` on a future would fail as `cvine.vine_task_state(self._taskvine, task_id)` was removed. This adds bindings to check a task's state. NOTE: there is no cancelled state for a task so this still has to be fixed. 

Futures executor working done and running

---

doc/manuals/taskvine/index.md
taskvine/src/examples/vine_example_blast.py
taskvine/src/examples/vine_example_gutenberg.py
taskvine/src/examples/vine_example_watch.py

Solves #3937 by fixing discrepancies between the C and Python TaskVine examples. Also fixes stale reference to cache of "always" in docs.

Fix discrepancies between C and Python TaskVine examples (Solves #3937)

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Removes the `stats_disconnected_workers` field from `struct vine_manager` and all references. Resolves #3927.

[TaskVine] Remove references to stats_disconnected_workers (#3927)

---

doc/manuals/makeflow/index.md

The simple Makeflow example in the documentation does not work. It calls `curl` to download capitol.jpg using HTTP, which gives a 301 redirect to the HTTPS version. I updated the URL to specify HTTPS as has been done in other sections of the repository.

Update capitol.jpg URL in makeflow docs

---

poncho/src/poncho/package_create.py
poncho/src/poncho_package_create

This pr adds “pinned” to the poncho spec. The target use case is something like topcoffea, where we want to create an environment compatible with another environment. For example, we want numpy in the former, which means it should be the same version of numpy in the latter. The “pinned” spec allows specifying versions of packages that should be used in case they need to be installed as a dependency.
As an example: 
```json
{
"conda": {
"channels": ["conda-forge"],
"packages": [
"ndcctools",
]
},
"pinned": {
"conda": {
"python": "3.8.20=h4a871b0_2_cpython"
}
}
}
````
The above will try to install `ndcctools`, which depends on python. Python is pinned to version `3.8.20` and thus the version installed for `ndcctools` is `7.12.0`, the last version that exists with python 3.8 support. …

Poncho pinned

---

configure

Fix configure flags so that HAS_FUSE goes in ccflags not ldflags.

Chirp: Fix FUSE configure flags

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

While calling DaskVine get API, we have two arguments for the same purpose, `worker_transfers` and `lazy_transfers`, the later one is marked as deprecated.
The default value for both is `True`. If the users want to activate it, they may pass 
- worker_transfers=True
- lazy_transfers=True
- worker_transfers=True, lazy_transfers=True
This works well. However, if they want to deactivate it, they may pass
- worker_transfers=False
- lazy_transfers=False
- worker_transfers=False, lazy_transfers=False
Only the last works, because `worker_transfers or lazy_transfers` is always True if only one argument is explicitly passed by the users.
This PR changes the logic to - if one of the two arguments is False, then `self.worker_transfers` is False, otherwise True.
The following items must be completed …

vine: dask arg worker_transfers

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_cache.h
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker_options.c
taskvine/src/worker/vine_worker_options.h

This modifies vine_cache.c to wait on creating new transfer processes while a certain maximum number of transfers are in progress. 

vine: limit worker transfer processes

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

The cache directory of the TaskVine manager is incorrectly assigned to each workflow's staging directory. The property now correctly points to the global cache of TaskVine which is workflow-agnostic.

Vine: Fix cache directory property of manager in Python bindings

---

taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c

If peer transfers are disabled change temp file behavior so they are returned on creation like normal files. Taskvine will still manage naming and cleanup after the workflow completes.

vine: handling temp files when peer transfers disabled

---

chirp/src/chirp_fuse.c

Follows what we do in `chirp_reli_open` after the file has been created and needs to be opened again.

chirp_fuse: remove creation flags after mknod in chirp_fuse_create

---

taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.c

Assuming a declared file is created until it is specified as an output allows us to do two things:
- Fail a task if its input file is missing and no source for the input file has been given
- Use regular files as intermediate data without failing in the same way, since we specify the file as an input and revert it to the pending state

vine: assume file created on declaration until specified as output

---

chirp/src/chirp_fuse.c
doc/man/m4/chirp_fuse.m4
doc/man/md/chirp_fuse.md

Add `--single-server` option to `chirp_fuse` that connects the mount to a single fixed server, rather than the global namespace.  May be helpful for Angel's use-case at Argonne.

Chirp-FUSE: Single Server Mode

---

taskvine/src/manager/vine_manager.c

Increment the priority for tasks exhausting resources

---

chirp/src/chirp_client.c
chirp/src/chirp_server.c
chirp/src/chirp_tool.c
doc/man/m4/chirp_server.m4
doc/man/md/chirp_server.md

Chirp ticket time limit

---

taskvine/test/TR_vine_python_serverless.sh
taskvine/test/vine_python_serverless.py

This PR adds an IO test (input/output staging) for function calls.

Vine: Add IO test for function calls

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

`vine_hungry` is a potentially expensive operation if there are many workers connected or many waiting tasks. However, the hunger value only changes significantly when the number of connected workers changes, and this does not happen very often. This pr makes it so that we only call the hungry computation every 5s (by default), and in between these calls we simply keep track how many tasks have been added/removed to the ready queue since last time. 
This should make it safer to call `vine_hungry` inside a loop, like in #3991. 

add vine_hungry wrapper

---

taskvine/src/manager/vine_manager.c

Trying to debug #4000. almalinux* fails on CI but not locally. This pr makes a minimal hot fix change for comparison.

double reap quick fix

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/worker/vine_worker_options.c

Fix #3996
- Update the default values for a set of arguments regarding temp file replication:
- `q->worker_source_max_transfers` from 3 to 10
- `max_transfer_procs` from 5 to 10
- I keep `q->transfer_replica_per_cycle` as is (which is 10), as it limits the number of replications to request per temp file per iteration, and we are not likely to replicate each temp file more than 10 times.
- Improve the logic in the replication process, which helps the manager replicate more efficiently, add more comments
- Provide an API for Python to query the replica count for a file

vine: properly replicate temp files

---

doc/manuals/taskvine/example-cfd.md
doc/manuals/taskvine/index.md
taskvine/src/examples/vine_example_cfd.py

I propose adding a new example to the TaskVine documentation. This is a real-world example of a TaskVine application currently used by the Notre Dame Rocketry Team to perform CFD simulations at high throughput.

Write CFD example into documentation

---

batch_job/src/Makefile
batch_job/src/batch_queue.c
batch_job/src/batch_queue.h
batch_job/src/batch_queue_flux.c
doc/manuals/makeflow/index.md

This PR creates a batch_queue module for the [Flux Framework](https://flux-framework.org/).  `batch_queue_flux` is currently marked as experimental. The submit, wait, and remove functionality are implemented, but there is no support for staging out output files back to the submitter because it seems flux assumes a shared filesystem for this purpose. As a result, `vine_factory` works using this backend, but more complicated workflows in Makeflow will not work, as they assume output files will be staged back.
I also fixed some out of date documentation in `batch_queue.h`

Create batch_queue_flux as experimental module

---

taskvine/src/manager/vine_manager.c

Task sandboxes were not getting cleaned up under various failure conditions, resulting in a storage leak.
This ensures that "kill" gets sent for every call to reap_task_from_worker.
Also clarified comments to make clear what's going on.

Vine: Refactor Task Kill

---

batch_job/src/batch_queue_k8s.c
configure
dttools/src/bitmap.c
dttools/src/envtools.c
resource_monitor/src/Makefile
resource_monitor/src/rmonitor_helper.c

Fixes to compile in conda-forge linux_aarch64

Aarch 64 comp changes

---

configure

Put taskvine earlier in the package list, so that it gets tested first.  Will save us some time in active development.

Build: Test Taskvine First

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_schedule.c

vine: check worker transfer capacity earlier

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file_replica.c
taskvine/src/manager/vine_manager.c
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c
taskvine/test/TR_vine_python_serverless_failure.sh
taskvine/test/vine_python_serverless_failure.py

Add check for missing library into expire_tasks_waiting. Causes function call tasks that cannot possibly match a library to be returned to the called with error `MISSING_LIBRARY`.   Now, if the user submits a library that fails (and is removed), the corresponding function calls will also return and fail, so that we end up with a concrete failure instead of an endless application hang.

Vine: Function Calls Should Fail on Missing Library

---

doc/manuals/taskvine/index.md

Added a new documentation section, “Unknown Python Dependencies? SciUnit Helps,” which explains how to detect Python dependencies using SciUnit.

docs: add sciunit dependency management to manual

---

taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/examples/vine_example_dask_graph.py
taskvine/test/TR_vine_python_unlink_when_done.sh

update dask vine executor to new dask graphs

---

taskvine/src/bindings/python3/Makefile
taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/compat/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/compat/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/compat/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Adds: 
```python
from ndcctools.taskvine.compat import DaskVine
```
to execute old-style dask task graphs. All other taskvine classes should be imported normally (from `ndcctools.taskvine`).

vine: Compat DaskVine

---

taskvine/src/manager/vine_manager.c

- Apply `BYTES_TO_MEGABYTES` when converting bytes data into megabytes, instead of doing math.
- There is a bug in doing `w->resources->disk.total - w->inuse_cache`, where the left side is in MB while the right side is in Bytes

vine: apply BYTES_TO_MEGABYTES when calculate inuse_cache

---

taskvine/src/manager/vine_schedule.c

The hack in #3913 that skipped the resource check for function calls was indeed the right way to do it...
And as the check for function calls are skipped, `!t->needs_library` becomes always true, thus the second half part of `if (ti->provides_library && ti->function_slots_inuse == 0 && (!t->needs_library || strcmp(t->needs_library, ti->provides_library)))` can be completely removed.

vine: skip worker resource check for function calls

---

taskvine/src/manager/Makefile
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/manager/vine_task_groups.c
taskvine/src/manager/vine_task_groups.h
taskvine/src/worker/vine_sandbox.c
taskvine/src/worker/vine_sandbox.h
taskvine/src/worker/vine_worker.c

With task groups enabled, detect groups of sequential, temp-file dependent tasks, and send them in batches to a single worker, avoiding the overhead and complexity of maintaining fixed_location policy. 

vine: fixed_location task groups 

---

taskvine/src/manager/vine_manager.c

vine: typo

---

taskvine/src/bindings/python3/ndcctools/taskvine/file.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager_put.c
taskvine/test/vine_python.py

Add hooks to set file mode for non-file sources.
Fixes #3761

Vine: Set File Mode

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/test/vine_allocations.py

Part of #4006
Testing results using 32 4-core workers
- Before
- After 

vine: reserve a factor of disk when allocating resources

---

taskvine/src/manager/vine_manager.c

This line of log constitues most of the debug file when the replication threshold is large.
It's very easy to generate a 5 GB debug file when dealing with 9K tasks and each temp file is replicated for 6 times, wheras once removed it the debug file is less than 100 MB.

vine: remove a line from debug file

---

dttools/src/debug.c
dttools/src/debug.h
parrot/src/pfs_main.cc

On Linux, every single debug() event was resulting in the following system calls:
```
stat("/etc/localtime")
getpid()
getpid()
getpid()
write(fd,event)
```
With the sort of extensive debugging output emitted by taskvine, the cost of debug messages was becoming surprisingly high.  This PR reduces the cost to:
```
getpid()
write(fd,event)
```
Note that getpid() was previously cached and the system call optimized away, but this is no longer true:
https://sourceware.org/glibc/wiki/Release/2.25#pid_cache_removal
It turns out that it is surprisingly hard to catch all variations of fork() in order to invalidate such a cached value.
Maybe we don't need to write it to every debug line?
Check these off to verify you have completed all …

Debug: Remove Excess System Calls

---

dttools/src/priority_queue.c
dttools/src/priority_queue.h
dttools/src/priority_queue_test.c

Some clarities about the data structure:
- This data structure only holds references to the data—it doesn’t actually delete them when the structure is destroyed.
- When a function fails, it returns either -1 if it normally provides an index, or 0 otherwise.
- In `priority_queue_remove`, the data structure is adjusted via `sink` or `swim`, depending on whether the new priority is higher than the old one.
- Enqueue the data and the corresponding priority if called `priority_queue_update_priority` but didn't find the data.
- Change name `peak` to `peek`

dttools: priority queue data structure fix

---

taskvine/src/worker/vine_transfer_server.h

Vine: Worker transfer limit must be larger than manager limit.

---

taskvine/src/manager/vine_manager.c

In one call to link_poll handle any additional messages in the buffer.
This appears to remove some latency between messages coming in.

vine: link_poll handle whole buffer

---

taskvine/src/manager/vine_file_replica_table.c

It’s easy to accidentally add a file to a worker twice using `vine_file_replica_table_insert`. 
If the file already exists on the worker, we should avoid incrementing `w->inuse_cache`.
This causes inconsistence between the worker's actual cache inuse and the manager's record.

vine: check if file exists on worker when access file_replica_table

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

Update internal call to `shutdown_workers` to `workers_shutdown`. Resolves issue #4062 

vine: resolve shutdown_workers to workers_shutdown

---

taskvine/src/manager/vine_manager.c

@btovar observed a problem in which the manager crashes after processing an `idle-disconnect` message and disconnecting the worker.  The problem is that this invalidates the `vine_worker_info` object and the `link` object in the middle of `handle_worker`.  If the `idle-disconnect` is followed by any other asynchronous message (which is likely) then the manager ends up seeing messages from a worker that no longer exists.
The solution here is to eliminate the special case: `handle_idle_disconnect` now sends an `exit` message to a worker, but does not disconnect it immediately.   This allows the manager to process any following asynchronous messages, and the worker can perform whatever cleanup and communication it needs to do before disconnecting.  And then the disconnect will be handled in …

Vine: Fix Crash After Idle Disconnect

---

taskvine/src/bindings/python3/ndcctools/taskvine/compat/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/compat/dask_executor.py

vine: file pruning by depth

---

taskvine/src/manager/vine_manager.c

The `m.tune` parameter `immediate-recovery` was meant to immediately create recovery tasks when the only worker containing a temp file was lost. However, it was only activated for the input files of tasks currently running at the lost worker. This pr fixes that.
The use case is workflows such as dynamic map reduce where temporary files are undeclared as soon as they are not needed anymore, and any declared file will be eventually used in the future. Since tasks are created dynamically, the management of files cannot be left to taskvine proper. 

vine: make immediate recovery to recover immediately

---

taskvine/src/manager/vine_manager_put.c

vine: correctly assign to cache_level when file is reused

---

taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py

The warning is not really needed, and it spams each task output in topeft.

vine: remote warning when using legacy task graph

---

dttools/src/macros.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c

vine: round up sizes when converting bytes to other units

---

poncho/src/poncho/library_network_code.py
taskvine/src/bindings/python3/ndcctools/taskvine/compat/dask_executor.py
taskvine/src/manager/vine_manager.c

Add an init_command to daskvine tasks, common in other workflow systems eg. parsl. I am using it for filetrace.
Also do a "make format" to fix the general linting issue

DaskVine: add dask init_command

---

taskvine/src/worker/vine_transfer_server.c

I found this problamatic while investigating #4076 
In the worker's transfer server process, the time when increasing the `child_count` is before we even check if the `lnk` is valid or if the fork was successful. This leads to inaccurate counting, especially when the connection is `NULL` (timeout) or the fork fails. The result is that the worker could block indefinitely in the `waitpid` call, waiting for a child process that doesn't exist. 
The solution is to only increment the `child_count` after successfully forking a child process, and handle fork failures separately to ensure the count remains accurate, preventing unnecessary blocking.

vine: count child_count properly in the transfer server process

---

dttools/src/copy_stream.c
taskvine/src/worker/vine_cache.c

I met a consistent segfault error when running a worker locally which performs frequent temp file staging in/out.
It turned out that there was a bug in the `copy_file_to_buffer` function when handling error cases. The function would free the buffer on read failures but not set it to `NULL`, creating a dangling pointer. Specifically, when `full_read` failed, the function would free `*buffer` without nullifying it, then return `-1`. 
``` C
int64_t total = full_read(fd, *buffer, *len);
if (total == -1) {
printf("copy_file_to_buffer: total == -1\n");
free(*buffer);
}
```
The calling code's condition `if (copy_file_to_buffer(...))` was problematic because in C, any non-zero value (including -1) evaluates to true. This meant that with a return value of `-1`, the code would incorrectly enter a …

vine: dangling pointer, crashes worker

---

taskvine/src/manager/vine_manager.c

@JinZhou5042 @Ian2327 could you test this pr and confirm it fixes the sefgaults observed?

vine: hotfix, use consistent results in handle_failure/fetch_output

---

taskvine/src/manager/vine_manager.c

vine: reference library_task in function tasks

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h

When retrieving tasks results, we want to do one worker at a time. The previous mechanism would maintain two data structures: one hash table with workers that have results, and a list of tasks with results ready to be retrieved. Looking at workers one at a time in the table, tasks would be retrieved and deleted from the list. Keeping the hash table was inefficient, and as @JinZhou5042 observed, the implementation lead to O(n^2) iterations.
This pr uses only the list of tasks to be retrieved and removes the hash table. Now we look at one task in the list, see which worker has it, and get all the tasks from that worker. Note that the first task we looked at may not be actually retrieved if there are more tasks to be retrieved in that worker, and the retrieval limit has been reached.
I like …

vine: Fix waiting retrieval

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_sandbox.c

Now mini tasks are allowed to fork if their sandbox cannot be staged. In this way the output file of the mini task can generate the corresponding cache-invalid message.

Mini task fail on input missing

---

doc/manuals/taskvine/index.md

1. Fixed data type for `m` to match the actual return type of `vine_create` accross the snippets
2. The variable `q` was changed to `m` with a data type of `struct vine_manager *` a couple years ago but some functions in the snippets still used `q`
3. Added the missing link-time dependencies for compiling C Taskvine scripts

vine doc: Fix data types, var names mismatches and link time dependendencies

---

taskvine/src/worker/vine_cache.c

When the worker sends an invalid cache message to the manager, it now also removes the file from its cache as if the manager had sent an unlink message. This cleans up the state of the replicas at the worker so that further puturl request succeed.
This fixes a bug where puturls are ignored because of previous failures to transfer, which caused tasks to be forsaken forever.

vine: worker unlinks file if invalid cache

---

deltadb/src/catalog_server.c
deltadb/src/deltadb_query_main.c

Catalog history queries made with `deltadb_query --catalog` didn't work for two reasons:
1 - The query tool was not constructing the proper url -- fixed.
2 - The catalog was timing out streaming queries to quickly -- added a streaming timeout parameter for that case.

Catalog: Fix Streaming Queries

---

dttools/src/link.c
dttools/src/list.c

#4074 describes a (rare) problem where `listen` can fail after a `bind`.  Our current range-listening code cannot handle this well, because one cannot attempt to rebind after one has succeeded.  This PR simplifies and reworks the link listening code to do range-listening by calling `link_serve_address` repeatedly, so that we can recover from a failed `listen.

Link: Fix failed listen after bind

---

taskvine/src/manager/vine_manager.c

Removing this line can greatly reduce the size of the debug log for some workflows

vine: remove a printing message from the debug log

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_cache.h
taskvine/src/worker/vine_worker.c

Fix removal sequence to avoid some rare memory errors:
- Rename vine_cache_wait -> vine_cache_check_files for clarity.  (It doesn't block!)
- vine_cache_check_file should *not* remove the object, because some callers expect it to be valid.
- vine_cache_check_files *should* remove because it has no further use for the object.
Fixes #4205

Vine: Fix cache removal error in worker.

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

This removes `prune_files` as an argument for the dask_executor and adds a description for the `prune_depth` option, which is actually used. 

Remove prune_files option 

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c

Modify vine_fetch_file to set errno according to various cases:
- `ENOENT` - file has not yet been created, no context expected.
- `EAGAIN` - file has been created, but no replica currently available, try again
- `EIO` - some other unexpected failure mode, data no longer available
Fixes #3750

Vine: Specific error cases for vine_fetch_file
