parrot/src/pfs_main.cc

Somehow the code for parrot envlist option is moved outside the switch statement, and `optarg` is lost meaning outside `switch`.

Correct the code for Parrot envlist option

---

parrot/src/parrot_package_create.c

Currently fullcopy of a file to new_path is implemented by `copy_file_to_file`. However,  if the new_path exists, `copy_file_to_file` will fail. 
Solution: Before each `copy_file_to_file`, remove new_path if if exists.

Before fullcopy of a file to new_path, remove new_path if it exists.

---

parrot/src/parrot_package_create.c

Allow the filesystem created by `parrot_package_run` to use /tmp from the host machine.

Add `/tmp /tmp` into common-mountlist

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/test/TR_parrot_execve.sh

The loader must be given a real executable to load, not an interpreted one.
Fixes #660.

Use the interpreter as the logical_exe.

---

parrot/src/parrot_package_create.c

Directly mounting the /tmp dir of the host machine to each package
results in all packages share the same /tmp dir.

Create a tmp dir under each package if it does not exist

---

apps/parrot_cms/cmsjob.sh
apps/parrot_cms/parrot.cmsjob.sh

If parrot is not needed, the user can run ./cmsjob.sh directly.

Move the CMS env variables into cmsjob.sh

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

This was a fun one to debug, had to dig into glibc to figure out that rtld_fini
was being changed from NULL pointer to a garbage one.
Fixes #677.

Don't reset registers after execve.

---

parrot/src/pfs_main.cc
parrot/src/pfs_table.cc
parrot/src/pfs_table.h

mmap_proc now takes a buffer to put output in, instead of a filename.  We can
now use mmap_proc to print mappings for a tracee that segfaults.
Additionally, I've improved the output of mmap_proc to be easier to read and
included some missing mappings (the executable file).

Make it easier to print tracee mappings.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

5ec25682acecbec17469239bf40d2619d4390c81 introduced a problem where
the arguments were not restored on a failed execve.
I've also added a comment to clarify why we don't restore the registers.

Restore arguments if execve failed.

---

parrot/src/pfs_service_cvmfs.cc

As reported by Brian Bockelman. EXDEV is only valid for errors regarding
hard links.

Change cvmfs symlink error to ENOENT.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

Jakob Blomer reported a failure by /bin/rm to remove a directory containing a
file. The issue was caused by a failed F_DUPFD on the directory fd. Because of
this, /bin/rm does not iterate over the directory and instead tries to directly
execute rmdir.
The reason for the failed F_DUPFD was an unnecessary check to see if the target
fd was a "special file descriptor" (e.g. the Parrot channel). The target fd would
be the third argument of:
fcntl(fd, F_DUPFD, start);
The "start" fd can be any valid fd as the kernel does not close start fd, it
just uses it as a starting point in the table. [Contrast this with dup2, where
the target fd *is closed* and we *do* need the check.]
Fixes #688.

Allow the "target" fd to be special for fcntl dup.

---

configure

As of the upcoming cvmfs 2.1.20, cvmfs requires libuuid.  This patch adds the linker flag to the parrot build if it is configured with cvmfs support.

Link against uuid if libcvmfs is used

---

dttools/src/pattern.c
dttools/src/pattern.h
dttools/test/TR_pattern.sh
parrot/src/pfs_table.cc

This allows for more natural string indexing. Using Lua's 1 based indexing was
a regular source of bugs.

Use 0 based offsets.

---

parrot/src/pfs_channel.c

The linked list for entries is circular. If we delete next, and next == prev,
then we cannot merge e with prev.
Found with valgrind.

Handle prev == next.

---

doc/man/parrot_run.m4
parrot/src/pfs_main.cc

In order to support valgrind, we have to turn it off prior to tracing the root
tracee. To do this, we use exec. Shipping around another executable to exec is
a bit ridiculous so I'm using the shell instead. The shell requires some signal
handling logic so I'm not enabling this behavior by default. I don't trust it
works everywhere.
Fixes #512.

Add valgrind support.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

Addresses bug in lhcb test for #689. I believe the lhcb test is now working
properly.

getdents64 places d_type before d_name.

---

allpairs/src/allpairs_master.c
allpairs/src/allpairs_multicore.c

add --symmetric option to allparis_multicore and allpairs_master
this option allows allpairs compute only half of a symmetric matrix
Add --index option into allpairs_multicore
this option allows the user to specify the indexes of a matrix
This branch tries to fix #731

optimization of Allpairs in the symmetric case

---

makeflow/src/makeflow.c

Fixed my dumb copy-paste mistake:
- Use file argument instead of optarg.
- Replace input w/output as needed.

Fix Bug in Makeflow Wrapper

---

work_queue/src/work_queue_test.c

dd doesn't allow upper-case metric prefixes on macos.

Fix WQ Tests on OSX

---

work_queue/src/work_queue_test.c

Avoid using metric prefixes to dd, for portability.

Fix WQ Tests on OS X and Linux, Again

---

parrot/src/parrot_package_run
parrot/src/pfs_main.cc

Background:
When `parrot_package_run` is used to repeat one command within a package, the env variables from <package>/env_list need to be imported.
Problem:
Some environment variables use backslash + newline to construct a long command, and some environment variables include escape sequences (e.g., PS1="\u@\h \w\$ "). the `read` command, without the `-r` option, uses backslash as an escape character, causing the line `PS1="\u@\h \w\$ "` to be `PS1="u@h w$ "`. The `-r` option of `read` disables this behavior, but introduces a new problem - the long commands constructed through backslash + newline will be split into multiple lines.
Solution:
First merge the long commands constructed through backslash + newline in the env_list into one single line, then use `read -r` to read the file.

Improved Environment for Parrot Packaging

---

work_queue/src/work_queue.c

Use a single itable to keep tasks' state. This simplifies the code, and also ensures that a task is in a single state. q->ready_list simply lists the task order.

Wq single structure

---

makeflow/src/makeflow.c
makeflow/test/TR_makeflow_040_recursive.sh
makeflow/test/TR_makeflow_remote_naming.sh
makeflow/test/TR_makeflow_src_example.sh

Make tests more portable (and more likely to succeed) by removing dependencies on curl/convert and other external programs.
(Still adding tests, don't merge yet.)

Make Tests More Portable

---

dttools/src/Makefile
dttools/src/elfheader.c
dttools/src/elfheader.h
dttools/src/memfdexe.c
dttools/src/memfdexe.h
parrot/src/pfs_channel.c
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_process.cc
parrot/src/pfs_process.h
parrot/src/pfs_sys.cc
parrot/src/pfs_sys.h

This commit addreses two different bugs:
o Executing the loader as a wrapper unconditionally changes argv[0]. So prior
to this commit, Parrot would change the runtime loader by executing:
execve("/path/to/loader.so", [argv[0], "/path/to/exe", argv[1], argv[2], ...], [...]);
Unfortunately, the loader will replace argv[0] with "/path/to/exe".
Applications sensitive to that change will fail. This is issue #678.
o If the loader referred to by the executable (PT_INTERP) is in a non-local
file system, like cvmfs, then the kernel will not be able execute the program.
execve will fail with ENOENT. This is issue #781.
This commit solves these problems by editing the PT_INTERP program header of
executable to refer to a local copy of the loader.

Edit the executable to change loader.

---

Makefile
packaging/rpm/README
packaging/rpm/ndcctools_template.spec
packaging/rpm/rpm_creator.sh

Add `make rpm` into Makefile
Put RPM stuff into cctools/packaging/rpm
The full feature of ndcctools depends on 9 packages: fuse, python, globus, swig, libuuid, readline, zlib, perl, and cvmfs.
To create RPMs for ndcctools with all package support mentioned above, there are two options.
Option 1: Use `./configure.afs` inside the `%build` section and create RPMs on a machine which supports the access of /afs/crc.nd.edu/group/ccl/software/cctools-dependencies.
This option is currently supported by the `make rpm` rule of cctools.
Option 2: Specify each package dependency as a `BuildRequires` attribute, and create RPMs on a machine with all these dependencies installed or you have root access to install these dependencies.
This option is currently not supported by the `make rpm` rule of …

Add `make rpm` into Makefile 

---

makeflow/src/starch

This now works with python2 (2.6, 2.7) and python3 (3.X) unmodified.
Support for python2.4 is dropped due to lack of BytesIO and changes in
exception handling syntax.
Addresses #801

starch: support both python2 and python3

---

makeflow/src/starch

To support python2.4 avoid octal literals, avoid binding exception
variables, and utilize logging for reporting.
Further cleansup #803 and helps with #801

starch: support python2.4 through python3.x

---

chirp/src/chirp_fs_local_scheduler.c

Assuming the admin didn't mount other file systems under the Chirp root, this
guarantees that job files can be linked (job file binding 'LINK') into the
Chirp file system.

Create job sandbox under the root directory.

---

chirp/src/chirp_acl.c

This fixes an issue where one tries to give a ticket put rights:
ticket_modify ticket /path p
but this fails because the subject has write permission but not put.

Give WRITE ACL implicit PUT.

---

chirp/src/chirp_fs_local_scheduler.c
chirp/src/chirp_job.c
chirp/test/TR_chirp_job.sh
doc/chirp.html

This binding was added to allow for job sandboxes to be on another file system
while maintaining cheap startup/cleanup (as COPY is naturally expensive). With
commit 8c6065e moving job sandboxes to the Chirp root, this is unnecessary to
support.
It's also worth adding that SYMLINK violated the conceptual design of jobs by
allowing output files to be written to during job execution, rather than at job
completion. It's also possible for applications to readlink the symlink to
obtain the real path of the file under the Chirp root. In principle, we don't
want to allow this.

Remove Chirp job file SYMLINK binding.

---

dttools/src/rmonitor_poll_internal.h
work_queue/src/work_queue.c

Based on #814 (only adds one more commit).
When using work_queue_enable_monitoring, the first summary of the resources report corresponds to the master. Resources are polled every 5 minutes. The summary also includes the master command line and the master project name (if given).
This follows the new convention on the resources archive, in which the first summary of a file is taken as the parent of all the summaries in that file.

Wq master monitor resources.

---

apps/makeflow_blasr/makeflow_blasr
apps/makeflow_blast/makeflow_blast
apps/makeflow_bwa/makeflow_bwa
apps/makeflow_gatk/makeflow_gatk
apps/wq_replica_exchange/protomol_functions.py
apps/wq_replica_exchange/wq_replica_exchange
deltadb/src/python-old/catalog_history_count
deltadb/src/python-old/catalog_history_filter
deltadb/src/python-old/catalog_history_plot
deltadb/src/python-old/catalog_history_read_and_print
deltadb/src/python-old/catalog_history_select
deltadb/src/python-old/catalog_history_stream
dttools/src/Makefile
dttools/src/cctools_python
galaxy/cctools.py
galaxy/makeflow_gatk_wrapper.py
makeflow/src/makeflow_linker_python_driver
makeflow/src/makeflow_monitor
makeflow/src/starch
prune/src/prune.in
resource_monitor/src/resource_monitor_visualizer.py
run_all_tests.sh
umbrella/src/umbrella.py
weaver/src/examples/arguments.py
weaver/src/tests.py
weaver/src/weaver.in
work_queue/src/python/work_queue_detailed_example_1.py
work_queue/src/python/work_queue_detailed_example_2.py
work_queue/src/python/work_queue_example.py
work_queue/src/work_queue_graph_log

Proposal to resolve #801.
You can check its use with starch.
Note that I did not want to use hard coded values from configure, as that may break for the binary releases.
cctool_python reads the second line of a python script, which
should be of the form:
which lists, in order of preference, the acceptable versions to run the
script. For example:
means: only run on python 2.4.
means: 2.7 and 2.6 are both ok, but prefer 2.7.
means: any version 3 is ok.

Python exec

---

parrot/src/pfs_table.cc

Fixes #823.
UNIX makes no guarantees [1] about the form of paths returned by getcwd,
only that it is an absolute path. However some applications [2] assume that
the path returned by getcwd has no redundant trailing slashes.
Haiyan found this problem in a CMS application (made of Perl scripts) which
would fail when a getcwd path had redundant terminating slashes. The Perl
code is here [2]. The failing function is verifypath.
The fix for this problem is to simply strip trailing slashes in
pfs_table::getcwd. PR incoming.
[1] http://pubs.opengroup.org/onlinepubs/009695399/functions/getcwd.html
[2] /cvmfs/cms.cern.ch/slc5_amd64_gcc434/cms/cmssw/CMSSW_4_2_8/bin/slc5_amd64_gcc434/SkelParser.pm

Remove trailing slashes from paths ret. by getcwd.

---

doc/confuga.html

@batrick, does this look correct? This is in case the default port is already taken.
With this modifications, I am getting the following error:
2015/06/29 09:09:27.42 makeflow[2714] batch: exited abnormally: ERRORED (Invalid cross-device link)

add explicit port to master node

---

doc/umbrella.html
umbrella/example/cms_complex/README
umbrella/example/cms_complex/cms_complex.sh
umbrella/example/cms_complex/cms_complex.umbrella
umbrella/example/cms_opendata/README
umbrella/example/cms_opendata/cms_opendata.sh
umbrella/example/cms_opendata/cms_opendata.umbrella
umbrella/example/cms_simple/README
umbrella/example/cms_simple/cms_simple.sh
umbrella/example/cms_simple/cms_simple.umbrella
umbrella/example/povray/README
umbrella/src/README
umbrella/src/umbrella.py
umbrella/src/working_principle

1) Add mount_env into the umbrella spec syntax
mount_env allows the user's analysis code to ignore the data location, and
also makes the relocation of the dependency easier without changing the
analysis code and just change the spec file.
2) Add a new umbrella example for cern_opendata
This example comes from the cern opendata website.
3) Check HTTP_PROXY for Umbrella+Docker+Parrot app
4) Use the right version of cctools
If the sandbox mode is parrot, use the cctools version which matches
the host machine.
If the sandbox mode is docker or chroot, and parrot is needed inside
the sandbox to deliver cvmfs, use the cctools version which matches
the specification os requirement.
5)    Create mountpoint for each level of a path, Add fake mounts into parrot mount file
If a mountitem '/a/b/c' is …

Several Umbrella Features

---

chirp/src/chirp_server.c

Jobs should be associated with the effective subject (e.g. unix:batrick) rather
than the current subject (e.g. ticket:abcdef). This solves permission errors
where the user cannot manipulate jobs created by an old ticket.
Fixes #832.

Chirp jobs should check the effective subject.

---

chirp/src/chirp.i
chirp/src/chirp_swig_wrap.c
chirp/src/chirp_swig_wrap.h
chirp/src/perl/Chirp/Client.pm
chirp/src/perl/chirp_jobs_perl_example.pl
chirp/src/perl/chirp_perl_example.pl
chirp/src/perl/my_script.sh
chirp/src/python/chirp.binding.py
chirp/src/python/chirp_jobs_python_example.py
chirp/src/python/my_script.sh

Python and Perl bindings for the chirp job interface.
Examples:
chirp/src/python/chirp_jobs_python_example.py
and
chirp/src/perl/chirp_jobs_perl_example.pl
Bindings are written so that a user should not need to write json directly, but instead use hashes.

Job chirp bindings

---

parrot/src/pfs_service_cvmfs.cc

The `max_open_files` option for cvmfs was originally meant to increase the maximum number of open files.  In the context of non-privileged users, that doesn't make much sense though because users are typically anyway at their limit. The current default has in many cases the opposite effect of restricting the user from the normal 1024 limit. The lhcb test case from the [LHC test applications](https://github.com/jblomer/parrot-test), for instance, does not work with a limit as small as 500. This patch removes the default limit.

remove restriction of maximum number of file descriptors for cvmfs

---

weaver/src/weaver/script.py

The help doc was changed but not the arg parser?

Parse -O as output_directory.

---

dttools/src/cctools_python

Sets PYTHONPATH in cctools_python.
I am not too happy about setting PYTHONPATH implicitly for the user, as it may break local setups. That said, we cannot guarantee cctools_python to work correctly without this fix.
Let's give these solutions a try, but with our eyes open for something less icky.
(ref #847)

set python path according to script

---

configure

The busy merging recently somehow changed the `potential_packages` string in the `configure`.
So currently compiling our master branch does not compile umbrella and prune.
This readds umbrella and prune into `potential_packages`.

Add umbrella and prune into `potential_packages`

---

chirp/src/chirp_sqlite.h
chirp/src/confuga_fs.h
chirp/src/confuga_job.c
chirp/src/confuga_node.c
chirp/src/confuga_replica.c

This simplifies the code by utilizing nested transactions. This allows internal functions to be used normally as they can now be called from within a transaction.

Improve Confuga internal API to use SQLite savepoints

---

work_queue/src/work_queue_worker.c

Without this fix, if the worker connects to a second master it never gets tasks.
(Will merge as soon as autobuild completes.)

Worker fixes

---

umbrella/example/cms_opendata_git/README
umbrella/example/cms_opendata_git/cms_opendata_git.sh
umbrella/example/cms_opendata_git/cms_opendata_git.umbrella
umbrella/example/git_protocol/README
umbrella/example/git_protocol/git_protocol.sh
umbrella/example/git_protocol/git_protocol.umbrella
umbrella/src/umbrella.py

Umbrella git support + two new examples:
1) umbrella/example/cms_opendata_git: git is used inside the user's application.
2) umbrella/example/git_protocol: git is not used inside the user's application, but used by umbrella to deliver some dependencies from git repos.
Other tiny changes:
1) Check the existence of attributes before using them.
2) Set the default action for software dependencies to be unpack.

Umbrella git support

---

work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

As requested by @annawoodard, stats_hierarchy now does not report tasks waiting at a foreman as running.
The regular stats (without hierarchy) follows the previous behavior (anything dispatched from the master is considered as running).

report running and waiting from hierarchy

---

work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

@annawoodard found that our API doc does not list the possible values of task states and task results. This is because we use define CONSTANT, and we have to manually update all of the documentation.
This pr changes these defines to an enum, so that the documentation is updated automatically.

use enums instead of defines for better doc

---

work_queue/src/pbs_submit_workers
work_queue/src/sge_submit_workers
work_queue/src/slurm_submit_workers
work_queue/src/torque_submit_workers

While preparing for XSEDE tutorial @nhazekam found a problem with the submission workers. @nhazekam found that in  if [ $cores=0 ], the variable is assigned, rather than compared. @nhazekam also found the solution:  if [ $cores=0 ].
This pr implements the solution that @nhazekam found.
Credit to @nhazekam.

fix arg cores comparison

---

chirp/src/chirp_server.c

We were reporting EACCES for all ACL check failures in putfile and putstream,
which masks possible ENOENT errors. This bug has existed since before we moved
to svn.

Use errno set by ACL module.

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

Removes any 'if(result)' or 'if(result > x)'. Now say 'if(result == SUCCESS)' or alike.
Also, remove return -1, 0, 1 for messages. Now say, e.g.: return MSG_NOT_PROCESSED.
These changes eliminated already two bugs:
1) Sometimes task with app failures were treated like worker failures.
2) Some invalid messages were ignored without an error message.
The use of enumerations also allows better compiler messages in the most recent versions of gcc and clang.
This is motivated from the need to find the bug #872.

Cleanup return codes

---

parrot/src/pfs_service_cvmfs.cc

Without this fix, access to the alien cache is sequential, rather than simultaneous.

set lock_directory option for cvmfs

---

parrot/src/irods_reli.cc

Based on #878.
Check if the user password file is created, and if not, advice the user to use iinit.
Fixes #725.

Irods don't ask for passwd with parrot

---

chirp/src/python/chirp.binding.py

bug fix: mkdir chirp python binding was missing the mode argument

---

chirp/src/chirp_server.c

The link RPC, as with the normal UNIX link syscall, allows for symbolic links
to be hard linked. For example:
$ ln -s foo bar
$ ln bar baz
$ ls -la bar baz
lrwxrwxrwx 2 batrick users 3 Aug 11 10:45 bar -> foo
lrwxrwxrwx 2 batrick users 3 Aug 11 10:45 baz -> foo
Currently the Chirp server would perform ACL checks on the resolved target, in
this case foo instead of bar. If this symbolic link points somewhere the
current subject lacks rights, then the RPC will fail with permission denied.
The fix is to use chirp_acl_check_link instead of chirp_acl_check on the
target.
Fixes #887.

Do not resolve link target for ACL check.

---

work_queue/src/work_queue.c
work_queue/src/work_queue_process.c
work_queue/src/work_queue_worker.c

We used link_read to read an env var=value pair. The master send
strlen(var=value) "var=value\n". On the worker side, the \0 would appear
after the '\n', outside the computed length.
Also in this commit, overwrite custom value of CORES, MEMORY and DISK
with the value from specify_*.
Fix for #891

bugfix: incorrect string len causing memory corruption.

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_internal.h
work_queue/src/work_queue_protocol.h
work_queue/src/work_queue_worker.c

1) Cache files are never updated automatically, even when changed locally.
2) Non-cache files receive names per task, even when locally they are the same file.
3) Added wq_invalidate_file to manually remove cached files. It also cancels any running task using the file.
invalidate_file does not work for buffers or commands. I am not sure how to that yet.

Safe file send and cache

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

Pulled out this commit from #889. 
Needed for cache fixes.
Resubmit if result is FORSAKEN. Note that in this commit no condition at the worker produces that result.

re-enqueue a task if result is RESULT_FORSAKEN

---

allpairs/src/allpairs_multicore.c
chirp/src/chirp_server.c
dttools/src/Makefile
dttools/src/catalog_update.c
dttools/src/host_disk_info.c
dttools/src/host_disk_info.h
dttools/src/host_memory_info.c
dttools/src/host_memory_info.h
dttools/src/path_disk_size_info.c
dttools/src/path_disk_size_info.h
makeflow/src/makeflow_analyze.c
makeflow/src/makeflow_gc.c
makeflow/src/makeflow_viz.c
makeflow/src/parser.c
sand/src/sand_filter_kernel.c
sand/src/sand_filter_master.c
work_queue/src/work_queue.c
work_queue/src/work_queue_process.c
work_queue/src/work_queue_process.h
work_queue/src/work_queue_resources.c
work_queue/src/work_queue_worker.c

Rename functions related to worker resource measuring, to make clear they are about the host.
On the worker side:
- Size of files in the cache is subtracted from the size of the box needed by a wq process.
- If a task exhaust it limits, that task result is RESOURCE_EXHAUSTION. Other running tasks are stopped, with result FORSAKEN.

Police task usage

---

resource_monitor/src/rmonitor_helper.c

If an application called exit, the exit wrapper would be called twice.
This was not a problem for most applications, but it was confusing
signals from Matlab. Now the wrapper is called only once.

rmonitor: do exit wrapper only once.

---

doc/man/resource_monitor.m4
dttools/src/rmonitor.c
dttools/src/rmonitor.h
dttools/src/rmsummary.c
dttools/src/rmsummary.h
makeflow/src/makeflow.c
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c
resource_monitor/src/rmonitor_helper_comm.c
resource_monitor/src/rmonitor_helper_comm.h
resource_monitor/src/rmonitor_types.h
work_queue/src/work_queue.c

Include input and output files on task summary.
Classify inputs and outputs according to the mode used in open.
Simplify command line options.
Fix bug where a signal handler was executed twice.

Rmonitor file list

---

work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_pool.c

As requested by @klannon, @awoodward, and @matz-e.
Applications such as Lobster submit tasks according to the number of workers available. This creates a chicken-and-egg problem when using work_queue_pool, as the pool does not grow if there are no tasks available. Setting a minimum number of workers in the pool is not a good solution, as many workers may go underutilized with long tails.
This request gives the master the API work_queue_specify_num_tasks_left. work_queue_pool can then compute the number of tasks as: left + running + waiting. Lobster can then inform the catalog how many tasks are left to be created, and the pool can create the workers accordingly.

wq tasks left

---

parrot/src/pfs_channel.c
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/pfs_process.cc

Special file descriptors (currently the channel and the Parrot directory) are
allocated from the top of our file descriptor pool. After setting up all
special file descriptors, the root tracee will lower its RLIMIT_NOFILE so that
special file descriptors are outside of its allocation/visibility.
Fixes #927.

Make special file descriptors invisible to tracee.

---

work_queue/src/work_queue_status.c

Fix bug for -T and -W in wq_status. project_name was always considered set.

add missing * for checking wq_status project_name

---

dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c
resource_monitor/src/rmonitor_helper_comm.h

1) Keep last related error.
2) Capture write with ld preload.
3) Quit on no space and no file descriptors.

Turn some errors into resource exhaustion signals

---

doc/man/work_queue_pool.m4
dttools/src/json_aux.c
dttools/src/json_aux.h
work_queue/src/batch_job.c
work_queue/src/batch_job.h
work_queue/src/work_queue_pool.c

As requested by @klannon, @matz-e, and @awoodard.
The configuration file is re-read if changed (at every cycle, that is
every 30 s). If an error is detected, the previous values are used.
The file should be proper json, as:
{
"master-name": "my_master.*",
"max-workers": 100,
"min-workers": 0
}
Call as:
work_queue_pool -Cmy_conf_file
Valid fields are:
master-name:
foremen-name:
min-workers:
max-workers:
task-per-worker:
timeout:
worker-extra-options:
cores:
memory:
disk:

WQ pool config file

---

work_queue/src/batch_job_condor.c
work_queue/src/work_queue.c
work_queue/src/work_queue_pool.c

As request by @klannon, @matz-e, and @annawoodard.
Calls like:
q.blacklist("babadook.net")
q.blacklist("hello.com")
are converted in work queue pool with condor in the submit file to:
requirements = ((machine != "babadook.net") && (machine != "hello.com"))
This means that once the worker idles out, the pool request no to get that machine again.
@dthain, @nhazekam

Blacklist pool

---

umbrella/example/openmalaria/openmalaria.umbrella
umbrella/example/povray/README
umbrella/example/povray/povray_S.umbrella
umbrella/src/umbrella.py

This branch allows the user to specified urls of data from curateND in Umbrella specs.
urls from curateND does not include the file names, instead use a random name for each file. For example, 
The download url from curateND for a file named `scenario.xml.tar.gz` is                            `https://curate.nd.edu/downloads/hd76rx93c3q`.
Umbrella specs should keep record of both the compressed file name (if compressed) `scenario.xml.tar.gz` and uncompressed file name `scenario.xml` to ease the resource existence checking.

Support curateND URLs in Umbrella

---

work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_protocol.h
work_queue/src/work_queue_worker.c

Fix for #966.
Adds:
work_queue_task_specify_running_time(t, useconds)
Also, standardizes  end_time (absolute from epoch) to useconds, so that all times required have the same units.

Max task time

---

work_queue/src/work_queue_worker.c

Fix overflow.  The altered conditional always results to true, I think this may be due to the subtraction of two `uint64_t`s?
Without this, tasks with a specified end time terminate immediately.

Fix maximum_end_time handling.

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

As requested by @klannon to replace grep-fu with the debug output.
Adds as to the queue stats:
total_workers_lost                 (e.g., evicted)
total_workers_fast_aborted
total_workers_idled_out

adds stats for workers lost, fast aborted, or idled out

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/pfs_table.cc

Commit 50200922bb94e4a11743561ac84ae5f1ba90b08b introduced an error where
events for other tracees would be handled after setting trace_this_pid. The
intent of trace_this_pid is to setup a barrier preventing handling of other
events until the current two stage operation completes (clone or open).
Now Parrot immediately waits again for a tracee that sets up such a barrier.
I've corrected the variable name to make this intent more clear.
Fixes #986.

Immediately wait for tracee on wait barrier.

---

doc/parrot.html
parrot/src/pfs_main.cc
parrot/src/pfs_resolve.c
parrot/src/pfs_resolve.h
parrot/src/pfs_sys.cc
parrot/src/pfs_table.cc
parrot/src/pfs_table.h
parrot/test/TR_parrot_permissions.sh

This feature just sets up some mounts behind the scenes to prevent access to paths not explicitly listed in the whitelist file it's given. I've tested it with user-defined mounts (via mountfile and via command line option) and everything seems to work as expected. The executable being run has to be in one of the allowed paths, and will most probably require some libraries. A minimal whitelist like the following is enough to run simple programs, e.g. dash.
/bin
/lib
/lib64
/usr/bin
/usr/lib
/usr/lib64

Add permissions to parrot mountlist.

---

apps/parrot_atlas/parrot.atlas.sh
parrot/src/pfs_service_cvmfs.cc
parrot/test/TR_parrot_cvmfs_access.sh
parrot/test/TR_parrot_cvmfs_alien_cache.sh

Original convention for web servers providing cvmfs repositories was to use 
http://<HOSTNAME>/opt/<VIRTUAL ORGANIZATION>
like http://cvmfs-stratum-one.cern.ch/opt/atlas.  These URLs are still active on WLCG web servers but considered deprecated.  The URI scheme changed to
http://<HOST NAME>/cvmfs/<FULLY QUALIFIED REPOSITORY NAME>
like http://cvmfs-stratum-one.cern.ch/cvmfs/atlas.cern.ch

change default cvmfs uri from /opt/$VO to /cvmfs/$FQRN

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_resources.c
work_queue/src/work_queue_resources.h
work_queue/src/work_queue_worker.c

This fixes the problem of update messages spam. The master asks for
updates once every so often, rather than the workers sending multiple
messages asynchronously.
The only change for keepalive semantics is that a message is requested
according to last_update_msg_time, rather than last_msg_received_time.
Also, in this way we have a single time interval, the keepalive one, that master has control of. Before we had one for stats and resources at the worker.

Piggyback on keepalive to send stats/resources update.

---

work_queue/src/work_queue_worker.c

This reverts a change in which the first connection to the master used a short timeout. The idea was to make the worker more responsive. This, however, causes workers to repeatedly disconnect if the master does not immediately (i.e., 15 sec) confirms the connection.

Use long timeout when first contacting master.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

These should block `getgroups`/`setgroups` with `EPERM` when using `--fake-setuid`. If blocking `getgroups` is unnecessary, then a21e7a9701076aa2c94a7852e0c2e3eeab98cb7d just needs to be reverted.

Supplementary groups

---

dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll_internal.h
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_types.h

Accumulate the maps we just found per file. First, we merge together all the maps segment that overlap. With this, we do not overcount private segments, but do consider that segments are shared as little as possible.
After this merging, we determine upper bounds, such as: 
virtual >= referenced >= private >= referenced - private >= shared.
If swap size is zero, then virtual and private have the exact values, and we have worst case counts for referenced and shared.
When we accumulate resident for the result, we do it from private + shared, rather than the resident reported originally as this would overcount shared.
There could be a way to use Pss (proportional resident) to improve these bounds.
This should mitigate some obvious overcounting, as reported by @annawoodard.

Take into account shared memory when computing resident memory for the resource monitor

---

dttools/src/rmonitor.c
dttools/src/rmonitor.h
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/makeflow_wrapper_monitor.h
resource_monitor/src/resource_monitor.c
work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Adds work_queue_enable_monitoring_full which also generates debug monitor output and time series. Should be used judiciously, as these files are in the order of gigabytes for long running tasks.
Also, enable_monitoring asks now for a directory, rather than a filename. This is to be consistent with makeflow.

Monitor add debug, series files  to wq

---

work_queue/src/work_queue_status.c

Crash only occurs when catalog has invalid expressions with null type.

Fix segfault in work_queue_status

---

makeflow/test/TR_makeflow_023_export_wq.sh
makeflow/test/TR_makeflow_030_gc_on_demand.sh
makeflow/test/TR_makeflow_040_recursive.sh
makeflow/test/TR_makeflow_remote_naming.sh
makeflow/test/dirs/testcase.subdir.01.makeflow
makeflow/test/dirs/testcase.subdir.02.makeflow
makeflow/test/dirs/testcase.subdir.03.makeflow
makeflow/test/dirs/testcase.subdir.04.makeflow
makeflow/test/dirs/testcase.subdir.05.makeflow
makeflow/test/dirs/testcase.subdir.06.makeflow
makeflow/test/dirs/testcase.subdir.07.makeflow
makeflow/test/dirs/testcase.subdir.08.makeflow
makeflow/test/dirs/testcase.subdir.09.makeflow
makeflow/test/dirs/testcase.subdir.10.makeflow
makeflow/test/dirs/testcase.subdir.11.makeflow
makeflow/test/syntax/Makeflow
makeflow/test/syntax/collect.makeflow
makeflow/test/syntax/export.external.makeflow
makeflow/test/syntax/export.makeflow
makeflow/test/syntax/line_continuation.makeflow
makeflow/test/syntax/meta.makeflow
makeflow/test/syntax/meta2.makeflow
makeflow/test/syntax/options.makeflow
makeflow/test/syntax/recursive.makeflow
makeflow/test/syntax/remote_name.makeflow
makeflow/test/syntax/test.makeflow
makeflow/test/syntax/typo.makeflow
makeflow/test/syntax/variable_issues.makeflow
makeflow/test/syntax/variable_scope.makeflow

Fixes failure in Makeflow GC on-demand test and adds INTPUTS and OUTPUTS line to test makeflows so as to eliminate the notice lines printed during testing.

Updated makeflow tests to use INPUTS/OUTPUTS

---

makeflow/src/makeflow.c
makeflow/src/makeflow_log.c
makeflow/src/makeflow_log.h

We still reset the node state, we just don't report that we are retrying the node if we are cleaning.
Address #1003. @btovar

Log recovery silently resets nodes if cleaning

---

doc/man/resource_monitor.m4
dttools/src/rmonitor_poll.c
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c

Adds: --follow-chdir (disable by default) and --measure-dir=<dir> (can be specified multiple times).
Cleans debug output and memory measurements on error.
Does not print opened files to summary if inotify is not active.
Fixes #1017.

Monitor cleanup/manually add dirs.

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_resources.c

Use inuse field to count committed resources at the master.
Worker does not communicate inuse to the master anymore, only total, min and max.

Committed the right way

---

dttools/src/rmonitor_poll.c
resource_monitor/src/resource_monitor.c

Before, we would report the previous correct value per resource. Now they are reported by sets.

Skip process if an error is found

---

work_queue/src/work_queue_pool.c

Use "workers needed", "workers requested", and "workers submitted", rather than "raw needed",
"in queue", etc.
As requested by @matz-e.

Use same field names in debug and standard output.

---

doc/man/resource_monitor.m4
dttools/src/rmonitor_types.h
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c

Decouple monitor and task exit status.
Monitor exit status:
RM_SUCCESS    0: no monitor errors, task exit status is 0
RM_TASK_ERROR 1: no monitor errors, task exit status is non-zero.
RM_OVERFLOW   2: no monitor errors, task terminated given of resources limits.
RM_MONITOR_ERROR 3: task could not be executed (missing executable, no
writing permissions for summaries, etc.)
This should make easier the retries at makeflow when implementing the complete resources loop.

Monitor errors

---

work_queue/src/work_queue.c

As reported by @matz-e. Somehow this code was pulled into a binary void.

update committed resources in stats

---

doc/umbrella.html
umbrella/example/cms_complex/README
umbrella/example/cms_complex/cms_complex.umbrella
umbrella/example/cms_opendata/README
umbrella/example/cms_opendata/cms_opendata.umbrella
umbrella/example/cms_opendata/cms_opendata_S.umbrella
umbrella/example/cms_opendata_git/README
umbrella/example/cms_opendata_git/cms_opendata_git.umbrella
umbrella/example/cms_simple/README
umbrella/example/cms_simple/cms_simple.umbrella
umbrella/example/git_protocol/README
umbrella/example/git_protocol/git_protocol.umbrella
umbrella/example/openmalaria/README
umbrella/example/openmalaria/meta.json
umbrella/example/openmalaria/openmalaria.umbrella
umbrella/example/openmalaria/openmalaria_S.umbrella
umbrella/example/povray/README
umbrella/example/povray/povray.umbrella
umbrella/example/povray/povray_S.umbrella
umbrella/src/umbrella.py

Currently, some output files are generated inside the sandbox and lost tracked after the job is done. As reported in #1032 .
This branch adds a new section `output` into umbrella specification files, which allows the composer of an umbrella spec file to specify the output files and directories. The users of umbrella can reap or even redirect these outputs to somewhere else using the `--output` option of umbrella.

Add output support for umbrella

---

work_queue/src/perl/Work_Queue.pm
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Adds categories to work queue, with the API: work_queue_task_specify_category(t, "mycategory");
Tasks without an explicit category belong to "default".
Fast abort is computed per category with: work_queue_acitvate_fast_abort_category(q, "mycat", mult);
If fast abort for a category is not explicitly specified, the value from "default" (work_queue_acitvate_fast_abort) is used.
If a category has -1 as multiplier, use the default. If 0, deactivate for that category.
To do:
Compute first allocations per category to implement the whole resources loop.
Update with categories coming from makeflow.
Update with the batch options commit (dangling wq_fast_abort_option).

WQ categories

---

makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/makeflow_wrapper_monitor.h
sand/src/sand_align_master.c
sand/src/sand_filter_master.c
work_queue/src/batch_job.c
work_queue/src/batch_job.h
work_queue/src/batch_job_chirp.c
work_queue/src/batch_job_condor.c
work_queue/src/batch_job_hadoop.c
work_queue/src/batch_job_internal.h
work_queue/src/batch_job_local.c
work_queue/src/batch_job_work_queue.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h

This branch is looking at having the batch-queue express whether it supports a qiven feature as opposed to Makeflow having to switch on the queue type to see if it supports. The goal is that if new types are added or behavior changes it would be addressed in the batch_job*.c instead of adding more options to Makeflow. @btovar Still working on this and testing, but let me know your thoughts.

Batch Job Feature API

---

chirp/src/chirp_fs_local_scheduler.c

This prevents loading a single storage node with pulls due to the common
ordering of input files for jobs in a workflow. (e.g. all jobs specify the same
large database as the first input file.)

Order pull transfers randomly.

---

dttools/src/jx.c

Solves a segmentation fault I found in Chirp during catalog updates.

Fix insert/append of array items.

---

umbrella/example/cms_complex/README
umbrella/example/cms_complex/cms_complex.umbrella
umbrella/example/cms_opendata/README
umbrella/example/cms_opendata/cms_opendata_S.umbrella
umbrella/example/cms_opendata_git/README
umbrella/example/cms_simple/README
umbrella/example/cms_simple/cms_simple.umbrella
umbrella/example/git_protocol/README
umbrella/example/openmalaria/README
umbrella/example/povray/README
umbrella/example/povray/povray_S.umbrella
umbrella/src/umbrella.py

1. Add destructive mode into Umbrella, which directly modify the rootfs to run the task.
2. Tune the ec2 execution engine of Umbrella    
(2.1) Send umbrella job to ec2 instance, run umbrella destructive mode on the ec2 instance.    
(2.2) Add --ec2_instance_type option to umbrella

Umbrella destructive mode + ec2 execution engine

---

dttools/src/disk_alloc.c

Fixes the way disk_alloc_delete finds and resolves the correct name of the mountpoint that is passed to losetup. This is necessary to de-allocate loop devices with a mountpoint pathname greater than 62 characters long.

Disk alloc fix

---

batch_job/src/batch_job_work_queue.c
dttools/src/rmonitor_poll.c
dttools/src/rmsummary.c
dttools/src/rmsummary.h
makeflow/src/dag_node.c
makeflow/src/dag_visitors.c
makeflow/src/makeflow.c
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmon_tools.c
resource_monitor/src/rmon_tools.h
resource_monitor/src/rmonitor_poll_example.c
work_queue/src/work_queue.c

Rename make_rmsummary to rmsummary_create.
Rename resident_memory to memory, workdir_footprint to disk, and workdir_num_files to total_files.
Add rmsummary_delete.

rmsummary follows naming conventions

---

umbrella/example/povray/README
umbrella/example/povray/povray_S_s3.umbrella
umbrella/src/umbrella.py

1) Upload the dependencies of one umbrella spec to the Amazon s3; and create a
new umbrella spec with data dependencies from s3; Upload this new umbrella spec
to s3
2) Support dependencies from s3 during runtime

umbrella communicates with s3

---

parrot/src/pfs_main.cc

Some environment variables would overwrite the CLI switches.
This was privately reported by Rodney Walker. The alien cache was being
initialized to "" after the command switches causing the switch to do nothing.
Only the PARROT_CVMFS_ALIEN_CACHE environment variable worked.
Introduced by 1b64779f7a0cbd6c2db6d70254de0c6beaa9970a.
Fixes #1092.

Fix env loading in Parrot.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_table.cc
parrot/test/TR_parrot_mmap.sh

````
commit c7de11342b86a7e67f734aee11fac3ae478ffac4
Author: Patrick Donnelly <pdonnel3@nd.edu>
Date:   Fri Jan 15 12:28:31 2016 -0500
Add more test code for mmap splits.
commit 949871994c000af2a556082b2e24d11b8745cdd8
Author: Patrick Donnelly <pdonnel3@nd.edu>
Date:   Fri Jan 15 12:27:30 2016 -0500
Correct bug in after split size/file offset.
Also add debug message for split.
commit 3d3649d6338a3f4498ad9414a202d6d208bedf38
Author: Patrick Donnelly <pdonnel3@nd.edu>
Date:   Fri Jan 15 12:25:37 2016 -0500
Use a memfd for proc maps.
This does away with the dependency on /dev/shm.
commit 5d85f5a9b636a36c30bef92afa8f7741b6cd9ef0
Author: Patrick Donnelly <pdonnel3@nd.edu>
Date:   Fri Jan 15 12:22:41 2016 -0500
Only munmap if kernel succeeds.
Our code was being more lenient with inputs and …
```

More bug fixes for memory mappings

---

umbrella/example/povray/README
umbrella/example/povray/povray_S_osf.umbrella
umbrella/src/umbrella.py

For deps from s3 or osf, first try to download it as a normal url using vanilla
python. If failed, try to use python packages (boto3 or requests) and the user
authentication to download deps.

Modify the Umbrella mechanisms for osf or s3 resources

---

dttools/src/category.c
dttools/src/category.h
dttools/src/rmsummary.c
work_queue/src/perl/Work_Queue.pm
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

As requested by @matz-e. In python:
s = q.stats_category("my_category")
print s.tasks_waiting
Note that only stats relevant to tasks are included (bytes transfered, the different tasks counters etc.)
(EDIT: reorganized code to remove memory leaks.)

Stats per category

---

dttools/src/random.h
parrot/src/pfs_service_bxgrid.cc
parrot/src/pfs_service_lfc.cc
parrot/src/pfs_table.cc

Use of signed random number when selecting replicas led crashes 50% of the time.
(This didn't come up until recently, b/c bxgrid was using an old parrot binary.)

Critical Fix to Parrot-Bxgrid support

---

dttools/src/Makefile

Add jx.h into the public library list, which is required by work_queue.h

---

dttools/src/debug.c
dttools/src/debug.h

When stderr is redirected, D_{FATAL, NOTICE, WARN} are not printed to the terminal. The number one commit makes it so by printing such messages to /dev/tty if stderr is not a tty. The second commit simply adds notice as a function, similar to fatal and warn.
(@dthain: Adding these now so that students from the cloud computing class have friendlier messages.)

Errors to terminal

---

doc/chirp.html

The world has changed somewhat since we originally did the code for these environment variables.  It seems that libhdfs is now a separate package, and the library usually appears in /usr/lib64/libhdfs.so.  So, I have changed the docs to reflect the more common situation.
If the user doesn't set `LIBHDFS_PATH`, our code will search for it in `HADOOP_HOME`, which I think is no longer a common configuration.
I suggest that we simplify that setup to be `dlopen` on either `$LIBHDFS_PATH` (if set) otherwise `libhdfs.so` and skip searching through `HADOOP_HOME`.
(But we still need to search `JAVA_HOME` for `libjvm.so`)
@batrick What do you think?

Update Chirp HDFS Docs (and maybe code)

---

resource_monitor/src/resource_monitor.c

Processes were being terminated because the monitor considered EAGAIN a resource message.

resource_monitor messages: consider only resources errors

---

umbrella/example/cms_complex/cms_complex.umbrella
umbrella/example/cms_complex/cms_complex_S.umbrella
umbrella/example/cms_complex/cms_complex_S_osf.umbrella
umbrella/example/cms_complex/cms_complex_S_s3.umbrella
umbrella/example/openmalaria/openmalaria.umbrella
umbrella/example/openmalaria/openmalaria_S.umbrella
umbrella/example/povray/povray.umbrella
umbrella/example/povray/povray_S.umbrella
umbrella/example/povray/povray_S_local+osf.umbrella
umbrella/example/povray/povray_S_local.umbrella
umbrella/example/povray/povray_S_osf.umbrella
umbrella/example/povray/povray_S_s3.umbrella
umbrella/example/povray/povray_base_local.umbrella
umbrella/src/umbrella.py

1) Use python boto3 to communicate with EC2 instead of CLI
2) moving ec2 ami info into umbrella spec
Originally, Umbrella used a dict to maintain the mapping between the os
name and the EC2 AMI info. This solution requires update the dict every time a
new mapping entry is added.

moving ec2 ami info into umbrella spec

---

batch_job/src/batch_job_work_queue.c
dttools/src/category.c
dttools/src/category.h
dttools/src/rmsummary.c
dttools/src/rmsummary.h
makeflow/src/Makefile
makeflow/src/dag.c
makeflow/src/dag.h
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/dag_resources.c
makeflow/src/dag_resources.h
makeflow/src/dag_variable.c
makeflow/src/dag_visitors.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/parser.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h

When a rule fails because of resources, it is then tried with the maximum allocation per category.
First allocation is computed automatically as jobs complete.
It works in all batch systems (not only wq).
(@dthain, @nhazekam, @charleszheng44)

DVDT resources mini-loop with makeflow

---

dttools/src/debug.c
resource_monitor/src/rmonitor_helper_comm.c

A couple of fixes as reported by lobster:
- Do not print debug message regarding /dev/tty more than once.
- Do not open/close the monitor socket every time there is a message. This worked when they were only very few messages to send (in most cases, only one). However, now that we track send/recv, write/read, the overhead was too big. Now we keep the socket open for the duration of the process.

Less msgs to monitor

---

work_queue/src/work_queue.c

As reported by @matz-e:
I currently am processing stuff with one category, with the following passed to WQ:
2016-02-04 05:24:18 [DEBUG] lobster.core: Category merge: {'cores': 1, 'memory': 900}
2016-02-04 05:24:18 [DEBUG] lobster.core: Category processing: {'wall_time': 1800000000, 'cores': 1, 'memory': 1500}
…
queue.specify_max_category_resources(category, constraints)
logger.debug('Category {0}: {1}'.format(category,constraints))
Yet I have a task that’s running for 3 hours right now? I also don’t see these constraints passed along:
2016/02/05 01:36:29.79 work_queue_python[1696366] wq: tx to dev4.crc.nd.edu (129.74.85.17:57466): task 8592
2016/02/05 01:36:29.79 work_queue_python[1696366] wq: tx to dev4.crc.nd.edu (129.74.85.17:57466): cmd 192
./cctools-monitor …

use category as fall-back to user labeling

---

parrot/src/pfs_dir.cc
parrot/src/pfs_main.cc
parrot/src/pfs_service.cc

I *think* this should resolve #1107. This adds entries under / for all services compiled into Parrot

Show all compiled-in services under /

---

batch_job/src/batch_job.c

@btovar @batrick Please take a look to see if this addresses the issue in #1148 . The issue was that the default batch_job feature set was overriding the features defined in the batch_job_chirp.

Update to fix chirp local jobs

---

resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c

Do not compute histograms allocations with brute force unless -b is given.

No brute force

---

dttools/src/rmsummary.c
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c

@charleszheng44: This branch uses symbolic variables for gnulot, defined in the files:
CATEGORY_RESOURCE_vars.gnuplot

histograms misc fixes

---

doc/umbrella.html
umbrella/example/povray/README
umbrella/src/umbrella.py

Allow uppercase checksum in umbrella specs
Check the return code of intermediate os construction
Avoid re-creating the new os image with dependencies installed

Fix Umbrella checksum case sensitive

---

work_queue/src/work_queue.c

If end time was specified, then autolabeling of other resources was not performed. This pr fixes that.

Do not consider end time as a labeling resource

---

dttools/src/rmsummary.c
dttools/src/rmsummary.h

As requested by @matz-e. Make resources exceeded per task API available.

include limits exceeded in work queue measurement task report

---

doc/workqueue.html

Use `$HOME/cctools` in the Work Queue manual, since that's where beginners are going to install.  (And nobody told them to set `$CCTOOLS`.)

Clarify WQ Build Instructions

---

dttools/src/stringtools.c

This is to address #1164. Per the discussion in the issue, the new default behavior is to append `/bin/sh -c []`. This also fixes a potential segfault in `string_wrap_command`

Fix for #1164: quote and escape Makeflow wrapper commands by default

---

doc/parrot.html
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_sys.cc
parrot/src/pfs_sys.h
parrot/src/pfs_table.cc
parrot/src/pfs_table.h
parrot/src/syscall_parrot.tbl

This pull request adds handling of the `BTRFS_IOC_CLONE` ioctl to trigger an in-Parrot copy via `copyfile_slow`. With a recent version of coreutils, this functionality is available through `cp --reflink`. This feature masks the *real* BTRFS_IOC_CLONE, which might not be an issue. Also, I wasn't sure about the desired semantics for a clone operation. At the moment, this does not seek to the beginnings of files before copying.

Add in-Parrot file copy via BTRFS_IOC_CLONE

---

doc/makeflow.html

I updated the section about wrappers to match the current rules on command substitution. Forgot to put this in the original PR

Update Makeflow docs with wrapper substitution rules

---

work_queue/src/work_queue_worker.c

Fixes a problem reported by Matt Vander Werf, in which the worker disconnects it the idle-timeout is reached during a "put ..." message from the worker.

reset idle timer on incoming file transfers

---

chirp/src/chirp_fs_hdfs.c

Fixes #1132
@batrick please double check

Chirp-HDFS rmdir should not be recursive

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/test/TR_parrot_thread_fd.sh

Otherwise, the kernel may make a modification to the fd table while Parrot is completing the clone of a process. Thus, the kernel and Parrot fd tables get out of sync.
Fixes #1179.

Add wait barriers to serialize fd table changes.

---

dttools/src/category.c
dttools/src/category.h
dttools/src/category_internal.h
resource_monitor/src/Makefile
resource_monitor/src/resource_monitor_cluster.c
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c
resource_monitor/src/rmon_tools.h

Include time overhead for reading all summaries, and computing the first allocations.
Include waste for 0.95 allocation.

Computation overheads and waste table

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

As requested by @matz-e.  task->result only returns a single error code, rather than an "or" of codes.
The only codes that are ever or-ed are missing stdout and missing output. This pr makes it so that if both are present, only missing output is returned.
Also, care was taken so that the older codes (missing input, output, stdout) may still be compared with & and ==, while newer codes can be compared with ==. With this, a simple switch case can be done on task->result, rather than multiple ifs with & in the condition.

Linearish wq codes

---

batch_job/src/work_queue_factory.c

As reported by @annawoodard, the factory would segfault if no masters were found in the catalog.
This became evident given the recent cclweb00's catalog hiccup.

fix segfault when no masters appear in the list

---

doc/makeflow.html

add a missing list item label for `job_id`

Tiny update of Makeflow user manual

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

We should not let new threads/processes escape Parrot through this flag to clone.
I don't think this is related to the recently reported Parrot crash for Rodney et al.

Catch and abort on CLONE_UNTRACED.

---

doc/man/parrot_run.m4
doc/parrot.html
parrot/src/Makefile
parrot/src/chroot_package_run
parrot/src/parrot_client.c
parrot/src/parrot_client.h
parrot/src/parrot_package_run
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/syscall_parrot.tbl

Test if Parrot is running using parrot_version.
Environment variables are not the right mechanism for testing if Parrot is
already running. In #1203, the PARROT_ENABLED environment variable would be
sent along with jobs to remote systems which would prevent Parrot from running.
Instead, just try a Parrot system call to see if we're already running Parrot.
Fixes #1203.

Parrot Self Detection

---

doc/makeflow.html

The first rule in `example.makeflow` requires `/usr/bin/convert`, which should be explicitly put into the rule.

Fix missing executable name in example.makeflow

---

dttools/src/jx.c
dttools/src/jx.h
makeflow/src/dag_visitors.c
makeflow/src/dag_visitors.h
makeflow/src/makeflow_analyze.c
makeflow/src/makeflow_viz.c

For #1178 
I added a new option `makeflow_analyze -J` that reads the DAG from the given makeflow and prints a JSON representation. The output for the example included with Makeflow is [attached](https://github.com/cooperative-computing-lab/cctools/files/178743/example.json.txt). The JSON DAG object has a few main keys:
- `categories` associates variables, resource limits, etc. with category names
- `environment` is a set of environment variables to be sent with a makeflow when run
- `rules` is a list (in no particular order) of the rules that make up the makeflow
Each rule is an object that stores
- `command`
- lists of input and output filenames
- the category for that rule
I also attached [another example](https://github.com/cooperative-computing-lab/cctools/files/178744/example2.json.tx …

First draft of JSON export for Makeflow

---

batch_job/src/Makefile
batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_dryrun.c
doc/man/makeflow.m4
makeflow/src/makeflow.c

This is a first draft for #946. I added a new batch system, `dryrun`. If Makeflow is invoked as `makeflow -T dryrun`, it performs all validation, dependency checking, but instead of actually running jobs, it prints the command it would have used. Since issuing commands to the batch system is one of the last things Makeflow does, this will get wrappers or any other transformations that might be added.
In addition, this batch system's log is actually a flattened shell script that should generate the same results as running the makefile, albeit sequentially. Since it doesn't depend on Makeflow, the shell script from e.g. `makeflow -T dryrun -L archive.sh` can serve as an archival representation as in the issue. I'd like to try this out on a larger, more complex sample makefile, since I've …

Add dryrun mode + flat shell script output to Makeflow

---

parrot/src/pfs_main.cc

Oleg Nesterov noticed a bug [1] in this code where SIGCONT could wake multiple
newly cloned threads from their initial SIGSTOP. This would cause the threads
to continue executing without stopping at system calls. That is, they would
only stop at other ptrace events like PTRACE_EVENT_CLONE or PTRACE_EVENT_EXIT.
The only way to trace system calls on a new thread is to use PTRACE_SYSCALL
after receiving its stop signal.
Possible fix for #1207.
[1] https://lkml.org/lkml/2016/3/21/644

Do not use kill to wake thread from initial stop.

---

resource_monitor/src/resource_monitor.c

Fix for #1220.
On urgent messages, such as from exiting processes, timeout.sec was set to 0, but not timeout.usec. This commit fixes that.

Also set timeout.usec = 0 on urgent messages.

---

makeflow/src/makeflow.c
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c

Third time... SIGCONT was ignored by sigtimedwait in RH5 unless there is an explicit handler. Now all tests run in acceptable time.

Set dummy handler for SIGCONT.

---

doc/man/starch.m4
makeflow/src/starch
makeflow/test/TR_starch_date.sh
makeflow/test/TR_starch_date_config.sh
makeflow/test/TR_starch_extract_and_remove.sh

Currently, `starch` assumes that the whole command is provided by its `-c` option.
This would fail if the provided `-c` option is incomplete or the user wants to
add more parameters to the command during runtime.
The change here allows the user to provide more parameters during runtime.

Add positional parameters to starch run.sh

---

dttools/src/jx_pretty_print.c

The JX code prints objects with pretty indentation, but leaves arrays compact. I added some array indentation code similar to the existing code for objects

Pretty print JX_ARRAY

---

makeflow/src/starch

Problem: When multiple commands based on the same SFX executable, let us say `convert`, are running concurrently, they all try to uncompress the tarfile inside the SFX at the same time. 
Solution: using locking to guarantee only one process, `P1`, uncompress the SFX, other processes will wait until `P1` finishes.

ensure only one job untar a starch SFX

---

work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_internal.h

As requested by @klannon, let the user choose the name of the resource summary files.

Specify monitor directory per task

---

allpairs/src/allpairs_multicore.c
dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll.h

I *think* the units are correct. `allpairs_multicore` appears to use bytes for calculating blocksize, while the environment variable seems to be in megabytes.

Check CORES and MEMORY when starting allpairs_multicore

---

makeflow/src/lexer.c

If a command line started with " " and also contained : (such as
http://...), the line was read as a file specification. This commit
treats space as tab, to signify the start of rule.
Also @nhazekam

Fix space and : parsing error.

---

dttools/src/jx_count_obj_test.c
dttools/src/jx_parse.c
dttools/src/jx_parse.h

This is in reference to #1231
Since JX expressions allows lookups, the parser has to scan beyond the end of the object/array, and then unscan (if there's no lookup). Since the library JX supports parsing TCP streams directly, seeking back isn't really an option, so to unscan, the parser stores the extra character and uses it on the next scan. Unfortunately for @btovar's use case, `jx_parse_stream` automatically creates and destroys the parser, throwing out the unscanned character and getting the stream out of sync on subsequent calls, hence the garbled test output.
I added a new function, `jx_parser_yield`, that parses a single value and leaves the parser intact for subsequent calls. If someone needs to do streaming JX parsing, I think it's not unreasonable that they dig around in the …

Add jx_parser_yield to support streaming JSON parsing

---

dttools/src/jx_pretty_print.h
dttools/src/rmonitor.c
dttools/src/rmsummary.c
dttools/src/rmsummary.h
makeflow/src/makeflow.c
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmon_tools.c
resource_monitor/src/rmonitor_poll_example.c
work_queue/src/work_queue.c

The spaces and newlines accumulated fast when accounting the size of
files.

Do not pprint summaries at scale.

---

work_queue/src/work_queue.c
work_queue/src/work_queue_status.c

Fixes two bugs:
- We were asking keepalive checks from status workers.
- The master was not sending arrays to work_queue_status, which either timedout or segfaulted.
Fixes #1253

Wq status fixes

---

parrot/src/pfs_table.cc

The pattern would fail to match if "self" was not followed by a "/".
Fixes #1255.

Resolve /proc/self to tracee proc dir.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/test/TR_parrot_procexe.sh

This is necessary for the Linux loader which relies on /proc/self/exe being the
canonical path to the executable.
Note that this commit doesn't stricly make /proc/self/exe the canonical path.
We only resolve the final component as that should catch all instances of this
bug. [If there is a link in the middle of the path, it will be resolved
normally in any case.]
Fixes #930.

Do readlink on final exe path component.

---

dttools/src/jx_count_obj_test.c
dttools/src/jx_parse.c

Do not delete parser on error for yield, let caller see errors. If yield calls delete, the outside call has no way of knowing delete should not be called again.

jx yield fix

---

parrot/src/pfs_dispatch.cc

Use 64-bit stat struct for fstatat64.

---

doc/man/work_queue_status.m4
dttools/src/category.c
dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_table.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_status.c

Adds -A to work_queue_status, so that the number of workers that can run tasks, per category, are reported. E.g.:
work_queue_status -A localhost 9001
````
CATEGORY          WAITING  FIT-WORKERS    MAX-CORES   MAX-MEMORY     MAX-DISK
my_category             1            0            4          ???          ???
default                 0            0          ???          ???          ???
manual-label            1            0            5          ???          ???
````
@klannon, is this what you were thinking about?
Also available with the API, the value of FIT-WORKERS is stats.workers_able, as whole and per category.

Report unmatched tasks

---

resource_monitor/src/resource_monitor.c

Before, the number of cores reported was the average used wall/cpu
times. Now, we look at previous values of times, and report the maximum.

Record peak number of cores.

---

dttools/src/.gitignore

These binaries keep showing up in my `git status`

Add jx_count_obj_test and libforce_halt_enospc.so to .gitignore

---

chirp/src/chirp_global.c

chirp query, manually free expr only when query creation fails

---

work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

On resource exhaustion, we just retrieve the summary for the task (retrieving all output files does not make sense, as the task was killed by the monitor.)
Also, we add to the stats the retries and time spent given resource exhaustion.

Monitor fetch

---

dttools/src/category.c
dttools/src/category.h
makeflow/src/dag_node.c
makeflow/src/makeflow.c
work_queue/src/work_queue.c

When tasks were first ran and exhausted resources, they were always retried regardless if they exhausted their maximum limit or a worker limit. Now they are only retried for worker limits.

do not retry tasks that already went over maximum

---

dttools/src/buffer.c
dttools/src/jx_print.c
work_queue/src/work_queue.c
work_queue/src/work_queue_status.c

wq_status would wait for jx_parse to receive an EOF from the master's jx_print_link. However, once the master sent a status message, it would not send anything else. This commit makes it so that the status worker is removed immediately after the status message is sent (wq_status is used in a one-shot manner anyway).
Along the way, a valgrind warning about an initialized buffer was silenced.

Wq long wait status fix

---

dttools/src/rmsummary.c

When merging two resource summaries, limits and peak times were ignored.

merge max resources correctly

---

chirp/src/chirp_fs_local.c
chirp/src/chirp_fs_local.h
chirp/src/chirp_fs_local_scheduler.c
chirp/test/TR_chirp_symlinks.sh
configure
dttools/src/Makefile
dttools/src/catch.h
dttools/src/compat-at.c
dttools/src/compat-at.h
dttools/src/create_dir.c
dttools/src/create_dir.h
dttools/src/mkdir_recursive.c
dttools/src/mkdir_recursive.h
dttools/src/sha1.c
dttools/src/sha1.h
dttools/src/unlink_recursive.c
dttools/src/unlink_recursive.h
dttools/test/TR_umr.sh

This is solution 1b of issue #380.
Each operation involving a path is decomposed into components which are traversed. All symlinks are handled by Chirp without the kernel's help.
Fixes #380.

Handle symbolic links within Chirp root.

---

work_queue/src/work_queue.c

Sending the command line with link_putlstring did not printed in the debug log anymore.

print cmd in debug log

---

doc/man/work_queue_worker.m4
work_queue/src/work_queue_worker.c

Add memory-threshold, that works as disk-threshold.
Check also against resource.total, rather than only resource.inuse.
Also, give some breathing room to the resource monitor. For example, for disk, the worker reports to the master:  disk.total - disk_threshold as the disk size. Then we check in the worker with disk.inuse > disk.manual - disk_threshold/2. Same for memory.

Worker broken promises

---

work_queue/src/work_queue_worker.c

This is needed for when the worker is launched without the --memory option, but a task has explicit memory requirements. If the free available memory of the system is consumed by some other process the task never got to run in the worker, and it was never returned to the master.

if task cannot run in the worker anymore, forsake it

---

resource_monitor/src/resource_monitor.c

Find peak cores by time windows, rather than sample count.

Rmonitor less noisy cores

---

chirp/src/confuga.c
chirp/src/confuga_fs.h
chirp/src/confuga_job.c
chirp/src/confuga_replica.c

If the daemon is not busy, then go ahead and sleep.
Further work might also monitor changes to the SQLite database using inotify or
similar to make the daemon more responsive.
Fixes #1264.

Count operations to decide when to sleep.

---

dttools/src/Makefile
dttools/src/http_query.c

change the `Request-URI` field of http requests:
When there is no proxy to be used, the `Request-URI` field should be `abs_path`.

Http request format fix

---

dttools/src/http_query.c

Use actual_host only after sscanf succeeds

Http request construction fix

---

chirp/src/chirp_global.c
chirp/src/chirp_server.c
chirp/src/chirp_status.c
chirp/src/confuga_fs.h
chirp/src/confuga_node.c
doc/catalog.html
doc/chirp.html
doc/confuga.html
doc/index.html
doc/makeflow.html
doc/workqueue.html
dttools/src/catalog_query.c
dttools/src/catalog_query.h
dttools/src/catalog_server.c
dttools/src/catalog_update.c
makeflow/src/makeflow.c
sand/src/sand_align_master.c
sand/src/sand_filter_master.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_catalog.c
work_queue/src/work_queue_status.c
work_queue/src/work_queue_worker.c

Here's a first draft of backup catalog server support for #1187. For sending updates or creating queries, everything now takes a string of hosts to try. The default is `catalog.cse.nd.edu;backup-catalog.cse.nd.edu`. Multiple servers are specified in a semicolon delimited list, and each host can optionally have a port specified. For updates, the various places that directly sent datagrams now use a common function that sends to all hosts. Queries are attempted in order, unless a query to a host previously failed, in which that host is tried after other options. I tried to split this PR up into individual commits because changing the catalog interface touches a lot of areas (Makeflow, Work Queue, Chirp, Confuga, etc. ). Also, some catalog stuff is exposed in Work Queue's library interface, …

Backup catalog server

---

parrot/src/pfs_process.cc
parrot/src/pfs_table.cc

This resolves a problem with /proc/pid/fd/n giving "fd" instead of the real
path to the bootstrapped file.

Give attached fd its real name.

---

parrot/src/pfs_table.cc

The issue is that an extra directory separator / would cause a pattern match to
fail in open_object.

Fix bug where /proc/pid/fd/ was not intercepted.

---

parrot/src/pfs_table.cc
parrot/src/pfs_table.h

So the result would be that reading /proc/pid/fd/X would always read from the
current process' table.

Fix bug where pid was ignored for some paths.

---

work_queue/src/condor_submit_workers

Fix request of disk, and simplify --autosize option handling.
Always set the size of the worker to size of TARGET, as TARGET may be larger.
Also, request by default a minimum of 1 core, 1 GB of RAM and 1 GB of disk.

Condor submit fix

---

parrot/src/pfs_service.cc
parrot/src/pfs_service.h
parrot/src/pfs_service_ftp.cc
parrot/src/pfs_service_grow.cc
parrot/src/pfs_service_http.cc
parrot/src/pfs_service_local.cc

All services report files as seekable. The local service no longer opens
unseekable files since the introduction of native file descriptors.
This resolves an issue privately reported by Benjamin Wynne. In his case, an
attached fd during the bootstrap phase was wrongly marked as unseekable. The
fix for that is obviated by this commit which simply removes all the unused
seekable logic.

Remove unused is_seekable logic.

---

work_queue/src/work_queue.c

For #1312
Need to make a copy in case of a string constant

Avoid free()ing constant string

---

doc/catalog.html
doc/index.html
dttools/src/catalog_query.c
dttools/src/catalog_query.h
work_queue/src/work_queue.h

Forgot to clean up the documentation on this, thanks @dthain

Update docs to reflect catalog host delimiter

---

batch_job/src/batch_job_condor.c
batch_job/src/work_queue_factory.c

Compute disk size in kB correctly for condor.
Use same default values as condor_submit_workers
worker has the same size as TARGET.

Wq factory autosize fix

---

dttools/src/catalog_server.c

For #1303
I added a bit of code so that query prosesses' command lines to show the remote address. As to the query timeout, there's already a `--timeout` option implemented. I tested it with a local server instance and `nc` to simulate a slow client. It does indeed end query processes after a fixed amount of time (60 s by default). Is this option set too high for the production catalog server?

Change command name on catalog_server query processes

---

dttools/src/category.c
dttools/src/category.h
makeflow/src/makeflow.c
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c
work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue.i

Part 2 of #1269.
update first allocation using max worker/max seen per category.
First commit is: 
Compute allocation every n tasks. 			d3b2be5

Wq alloc by max seen

---

chirp/src/chirp_fs_local.c
chirp/src/confuga_namespace.c

Fixes bug where an extra '/' (e.g. 'foo//bar') would cause resolve to restart
path resolution at root after descending into foo.

Consume multiple / after component.

---

chirp/src/confuga.c

This makes the server more responsive during sporadic activity.

Use exponential delay for Confuga sleep.

---

resource_monitor/src/resource_monitor.c

Series is written to disk by complete lines. This allows an external process to tail the series and implement custom triggers.

Monitor time series fixes

---

dttools/src/disk_alloc.c

Bug fix: adds option to mkfs which makes the process of instantiating a loop device more explicit

Fixes mount issue in disk_alloc

---

dttools/src/disk_alloc.c

This prevents the terminal from becoming swamped with lengthy, obscure output.
@dthain @btovar, could you take a look please?

Modifies disk_alloc_create to redirect lengthy output to /dev/null

---

work_queue/src/work_queue.c
work_queue/src/work_queue_process.c

Fixes a bug as reported by @nhazekam

bug fix: export correctly CORES, MEMORY, and DISK when task execs

---

work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

As reported by @yannakopoulos. Two issues:
Noise from new workers was causing resource totals in the log to be negative.
Signed numbers were being printed as signed.

Fix signedness when printing resources to the wq log.

---

makeflow/src/parser.c

Setting to default overwrote the different variable which resulted in every task using the default category values. No values were set in the actual categories. Now every variable is tied to the most recent defined category and not the default, unless that was the most recent.

Makeflow Variable are set to most recent Category, not default

---

configure
dttools/test/TR_b64.sh
dttools/test/TR_buffer.sh
dttools/test/TR_chunk_test.sh
dttools/test/TR_data_struct_set.sh
dttools/test/TR_hmac_test.sh
dttools/test/TR_path_basename.sh
dttools/test/TR_path_collapse.sh
dttools/test/TR_path_dirname.sh
dttools/test/TR_path_extension.sh
dttools/test/TR_path_remove_trailing_slashes.sh
dttools/test/TR_pattern.sh
dttools/test/TR_stringtools.sh
dttools/test/TR_umr.sh
parrot/test/TR_parrot_bind.sh
parrot/test/TR_parrot_cloexec.sh
parrot/test/TR_parrot_clone.sh
parrot/test/TR_parrot_clone_untraced.sh
parrot/test/TR_parrot_dir.sh
parrot/test/TR_parrot_execve.sh
parrot/test/TR_parrot_fake_setuid.sh
parrot/test/TR_parrot_mmap.sh
parrot/test/TR_parrot_msg_fd.sh
parrot/test/TR_parrot_personality.sh
parrot/test/TR_parrot_thread_fd.sh
resource_monitor/src/piggybacker.c

This is for #1286.
I added a new option to the `configure` script to compile with these options. N.B. that GCC>=4.8 is required. If configured as
./configure --sanitize
all programs will exit with non-zero status and print details in the case of leaks. The numerous changed files are due to test scripts that compile their own code. Extra linker flags are required for those tests, so I passed them through an environment variable. I'm not sure if this is the most correct way to do it, though

Add option to compile with -fsanitize=address and -fsanitize=undefined

---

batch_job/src/batch_job_condor.c
dttools/src/stringtools.c
dttools/src/stringtools.h
dttools/test/TR_stringtools.sh

Added function that escapes quotes which is required in a condor submit file. Needed as quotes are used in wrapping of commands with wrappers and resource monitor.

Added function to escape Condor, called in batch_job_condor

---

batch_job/src/work_queue_factory.c
doc/man/work_queue_factory.m4

Default is 5, same as the default for min workers. Less than 1, disables limit.

Adds --workers-per-cycle, to limit new workers spawned in wq_factory

---

batch_job/src/batch_job.c
makeflow/src/makeflow.c

This waits to free until after we have made a duplicate of the new value. This prevents an issue if the old value passed back in. e.g. as in Makeflow
previous = batch_queue_get_option (q, "batch-options");
if(new-options)
batch_queue_set_option(q, "batch-options", new-options);
run task
if(previous)
batch_queue_set_option(q, "batch-options", previous);
Set option duplicates the passed value, and removes the previous value. When removing the previous value, it also frees that value as batch_job created it in the first place. The issue occurs when you pass back in the original value that you retrieved and it has already been freed. This happens regardless of whether you set new options or not. 
This pull request still frees the internal copy when a new value is set. It also returns a copy …

Batch job option fix

---

dttools/src/Makefile
dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_match.c
dttools/src/jx_match.h
dttools/test/TR_jx_match.sh

I wrote up some access functions for unwrapping JX structs. The common case I had in mind (and encountered a lot with JX functions and Makeflow import) is reading a value of a specific type into a local variable. There are specialized functions for lookups in objects, so these do something similar for `struct jx`s in general. In addition to the extra opportunities for the compiler to check things, these functions are more readable in code than digging around in struct fields and enum variants.
The `jx_match_*` functions follow a common interface. Each type has a specialized match function. If the struct is the requested type, a pointer to the raw field inside the `struct jx` is returned, or `NULL` otherwise. This can be used to directly modify the `struct jx`, or more commonly, can be …

JX match functions

---

work_queue/src/condor_submit_workers

Turns out that 1GB of memory per core eliminated many machines at ND pool.
Note that the original 1024MB has never been included in an official release.

Change default memory from 1024 to 512 MB in condor_submit_workers

---

work_queue/src/work_queue_worker.c

worker informs the master of terminating signal with: info vacating %d
Also, when new tasks start to run, the worker sends a message to the master. Before, such message would be sent when the master asked for a keepalive, but this made the task_running stat to be off by about 3 minutes (the keepalive interval). The master still asks for keepalives, this change only resets the timeout.

Worker message enhacements

---

batch_job/src/batch_job.c
batch_job/src/batch_job_condor.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/makeflow_wrapper_monitor.h

Fix that uses the basename of Resource Monitor files remotely on condor. 
If resource monitor is enabled with Condor, we write the monitor command to use a file in the cwd, not in a directory. This way the monitor output if sent back by Condor. As Condor does the actual transport of the files, there isn't code in batch_job_condor to intercept and rename the files. To put them in the correct location a move function is used to rename the files in the expected directory prior to checking if the output exist.
@btovar Give this a look, though it is not an ideal solution. 
Continuation fix for Issue #1364

Resource Monitor file directories in Condor

---

chirp/src/.gitignore
chirp/src/Makefile
chirp/src/confuga.c
chirp/src/confuga.h
chirp/src/confuga_adm.c
chirp/src/confuga_fs.h
chirp/src/confuga_job.c
chirp/src/confuga_node.c
chirp/src/confuga_replica.c
doc/confuga.html
doc/man/confuga.m4
doc/man/confuga_adm.m4

This commit adds a new CLI tool (with accompanying C API) for adding and removing SN in Confuga.
$ confuga_adm confuga://... sn-add [-p <password file>] [-r <root>] <"uuid"|"address"> <uuid|address>
and
$ confuga_adm confuga://... sn-rm <"uuid"|"address"> <uuid|address>
The root directory of the storage node set via the "-r" switch is the location
the HN will use to store SN state. The default root directory is "/.confuga".
The password file passed via "-p" is expected to hold the same contents as a
file on the storage node located at '/password' under the storage node's root
directory set via the '-r' switch. Usually the user doesn't want to explicitly
set this up so the HN will automatically create this password file if the '-p'
option is not used.
Examples:
$ confuga_adm …

Improve Confuga SN management/membership

---

dttools/src/jx.c
dttools/src/jx.h
makeflow/example/example.json
makeflow/example/example.jx
makeflow/src/Makefile
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/dag_visitors.c
makeflow/src/makeflow.c
makeflow/src/parser.h
makeflow/src/parser_jx.c
makeflow/src/parser_jx.h

Here's a first pass at a parser for the Makeflow JSON format (#1178). I added the `--json` flag to Makeflow to switch to the JSON format. I made some adjustments to the output format as well. If I dump JSON from `example.makeflow`, I get
{
"default_category":"default",
"categories":
{
"default":
{
"environment":
{
"CONVERT":"/usr/bin/convert",
"CURL":"/usr/bin/curl",
"URL":"http://ccl.cse.nd.edu/images/capitol.jpg",
"MAKEFLOW_INPUTS":"",
"MAKEFLOW_OUTPUTS":"capitol.montage.gif"
}
}
},
"rules":
[
{
"command":"/usr/bin/convert -delay 10 -loop 0 capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg capitol.270.jpg capitol.180.jpg capitol.90.jpg capitol.montage.gif",
"allocation":"first",
"outputs":
[
"capitol.montage.gif"
],
"inputs":
[
"capitol.jpg",
"capitol.90.jpg", …

Makeflow JSON import

---

batch_job/src/batch_job.c
batch_job/src/batch_job_work_queue.c
makeflow/src/makeflow.c
work_queue/src/work_queue.c

Checks that the batch job system supports absolute path filenames/remote-names. Exits with message and rule number of first encountered problem.
Also exits if specify file fails. I can make this a fatal error w/message, but did not as WQ already prints error message.
@btovar take a look.

Makeflow prevent absolute paths in WQ

---

dttools/src/stringtools.c

Small change to use xxstrdup instead of strdup.

Move strdup to xxstrdup for failure msg

---

makeflow/src/dag_visitors.c
makeflow/src/dag_visitors.h
makeflow/src/makeflow_viz.c
makeflow/test/TR_makeflow_viz.sh

Adds more options for better control of DOT options when creating Makeflow graph. This was used for SC 16 paper.

Enhance DAGtoDOT options

---

makeflow/src/parser.c

Found by using $CATEGORY in makeflows for vectorbase.

$CATEGORY should give the current category, not the previous.

---

batch_job/src/work_queue_factory.c
chirp/src/chirp_status.c
dttools/src/jx_table.c
dttools/src/jx_table.h
work_queue/src/work_queue_status.c

When declaring tables, negative widths indicate minimum sizes that may
expand if columns available.
Fixes #1384

Honor COLUMNS env var when printing work_queue_status

---

makeflow/src/dag_file.c
makeflow/src/dag_file.h
makeflow/src/dag_node.c
makeflow/src/dag_variable.c
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/src/makeflow_log.c
makeflow/src/parser.c

Update variable names and add file size information to dag_file.
Mechanism for setting estimated size: 
FILE=something
FILESIZE=estimatedsize
also required a small fix to prevent segfault when setting the same variable several times in the same rule/node context.
Also, cleans up makeflow logging to be slightly more consistent.

Fix dag file sizes

---

batch_job/src/batch_job_work_queue.c
batch_job/src/work_queue_factory.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_graph_log
work_queue/src/work_queue_worker.c

Added fill_deprecated_stats_{queue,task} so that old application can run without change.
The new stats for the queue, are:
```C
/* Stats for the current state of workers: */
int workers_connected;    /**< Number of workers currently connected to the master. */
int workers_init;         /**< Number of workers connected, but that have not send their available resources report yet.*/
int workers_idle;         /**< Number of workers that are not running a task. */
int workers_busy;         /**< Number of workers that are running at least one task. */
int workers_able;         /**< Number of workers on which the largest task can run. */
/* Cumulative stats for workers: */
int workers_joined;       /**< Total number of worker connections that were established to the master. */
int …
```

wq stats cleanup

---

work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py

Under some conditions, the logic in the bindings would always cache files.
Discovered by  @WenzhaoLi and @annawoodard.

fix logic for cache flag in bindings

---

doc/man/chroot_package_run.m4
doc/man/parrot_package_create.m4
doc/man/parrot_package_run.m4
doc/parrot.html
parrot/src/parrot_package_create.c

Add `--add` and `--new-env` option to `parrot_package_create` to allow the user to add new dependencies into an existing package.

expand parrot packaging tool

---

parrot/src/pfs_service_cvmfs.cc

It turns out that for libcvmfs >= 2 redirection of cvmfs logging takes place just before attaching a repository.  This means that `LogCvmfs` calls during the global libcvmfs initialization are issued unfiltered.  This PR places the redirection call just before the `cvmfs_init` calls.

Fix redirection of cvmfs logging

---

work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Some projects, such as lobster, sometimes use several sequential masters to finish a single workflow. The current pr adds the API specify_min_taskid so that taskids can be made consistent across the different masters. wq guarantees that the taskid of future submitted tasks is at least the minimum desired (it could be larger).  Most users will never need this function.
@dthain, @matz-e, @annawoodard

set the minimum desired taskid

---

dttools/src/rmonitor_poll.c

Fixed the issue in rmonitor_get_command_line which didn't have an "fclose" before terminating.

Fix for rmonitor opening too many files

---

chirp/src/chirp_reli.c
chirp/src/chirp_reli.h
chirp/src/perl/Chirp/Client.pm
chirp/src/python/chirp.binding.py

As reported by @matz-e. 
Chirp clients keep the connection open once the python object was destroyed.

Close chirp binding

---

doc/makeflow.html

The dependency tracking of makeflow has been removed from `makeflow` into `makeflow_analyze`.
This PR updates the Makeflow user manual to reflect this change.

Fix doc for makeflow linking deps

---

doc/umbrella.html
umbrella/src/umbrella.py

this boolean field can be used to mark whether a dependency should be uploaded into s3/osf or not.

Add `upload` field into umbrella spec

---

batch_job/src/work_queue_factory.c
work_queue/src/work_queue.c

Mix fixes foremen. Specially:
Use  resource.largest rather than resource.total when comparing workers and tasks.
Consider workers_connected from foremen  in wq_factory.

Foreman round 4

---

work_queue/src/work_queue_status.c

Helps enormously when master names are long and would be severly truncated
by default.  Setting the COLUMNS environment variable helps, too, but has
to be reset if the terminal changes in size.

Automatically determine terminal width.

---

work_queue/src/work_queue_worker.c

With the recent change of using largest instead of total, some tasks were not being dispatched. This is because 'largest' was not being discounted the avail_threshold values.

use avail_thresholds in largest resources reported

---

umbrella/src/umbrella.py

This PR allows the `inputs` and `output` options of Umbrella to have an extra trailing comma.
This feature makes it easier to integrate umbrella into makeflow, which always puts an extra trailing comma at the end of the `input_files` and `output_files` strings for each dag_node.

Allow an extra traing comma in umbrella i/o opts

---

dttools/src/stringtools.c

Currently, `string_combine` does not allow its arguments to be `NULL`.
The PR fixes this.

Enhance string_combine

---

parrot/src/pfs_main.cc
parrot/src/pfs_service_cvmfs.cc

@jblomer added a new interface for option handling and initialization for libcvmfs rev. 23, so this PR updates our Parrot connector. I *think* this works for any libcvmfs version. I also made some changes on our end. I'd like to pass configuration to libcvmfs as directly as possible, so I marked some of the Parrot specific or legacy parts as deprecated. New users can use any desired options from the [libcvmfs docs](http://cvmfs.readthedocs.io/en/latest/cpt-configure.html). Aside from Parrot-internal options like repo switching, `--cvmfs-option` and `--cvmfs-option-file` should be preferred for configuring CVMFS in Parrot, since they use the same syntax as the FUSE module and libcvmfs.
Also, is there a reason Parrot explicitly disallows direct connections and requires a proxy?

Use new libcvmfs interface if available

---

doc/man/parrot_run.m4
doc/manual.h
parrot/src/Makefile
parrot/src/parrot_helper.c
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/pfs_time.cc
parrot/src/pfs_time.h
parrot/src/pfs_types.h
parrot/test/TR_parrot_time_stop.sh

Added a new mode to Parrot that allows one to control the time, so as to support experiments in reproducibility:
`parrot_run --time-stop` forces the current time to midnight, January 1st, 2001 UTC.
`parrot_run --time-warp` does the same thing, but advances the clock by .01s upon every request for the current time.

Parrot Timewarp Mode

---

umbrella/src/umbrella.py

This PR backups the parrot binary for redhat5, redhat6, centos6 into crc afs, and allows umbrella to download the parrot binary from crc afs url.

Update the url of parrot binary for umbrella

---

dttools/src/auth_ticket.c

Fixes #1477.
The problem was that chirp_auth_ticket always returned success. Now it returns failure by default, unless a success is explicitly stated.

Give error code when no more tickets are available.

---

parrot/src/pfs_service_local.cc

The implementation of `lutimens` in Parrot's `local` service was missing the `AT_SYMLINK_NOFOLLOW` flag, making it equivalent to `utimens`. All the feature tests were already there, so this is just a one-liner.
@btovar I can confirm that this fixes the issue described in #1476

Add missing AT_SYMLINK_NOFOLLOW to local lutimens

---

umbrella/src/umbrella.py

This makes the order of parrot error info (written into stderr) and umbrella
log info (written into stdout) correctly.

Disable stdout buffering of umbrella

---

batch_job/src/batch_job_cluster.c
batch_job/src/work_queue_factory.c

Fixes two problems that were preventing correct operation at Arizona:
* -N batch name cannot be more than 15 characters
* scratch directory of factory needs to be on a shared filesystem.

Factory Fixes

---

work_queue/src/work_queue.c
work_queue/src/work_queue_resources.c

Two fixes for #1495:
1) When a task was forsaken, we did not update the accounting for that worker at the master.
2) Memory available at the worker is reported as the total memory, rather than the free memory at the time of measurement.

Fix forsaken stop

---

allpairs/src/allpairs_master.c

Clean up allpairs output:  do not emit command strings as they are submitted, since they are typically cryptic invocations of allpairs_multicore.

All Pairs Output

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

WAITING_RESBUMISSION state was not used anymore. Tasks marked with such state were never rescheduled.

remove waiting_resubmission state

---

dttools/src/Makefile
dttools/src/category.c
dttools/src/category_test.c
dttools/src/histogram.c
dttools/src/histogram_test.c
dttools/test/TR_category.sh
resource_monitor/src/resource_monitor_histograms.c

As found by @klannon, first allocations were being rounded down as we were using the bottom edge of the histogram buckets. This pr changes allocations to use top edges, and adds a test for the category code.

Fix histogram edge

---

work_queue/src/work_queue_worker.c

This is a small commit, but a potentially big change.
I propose that the time has come to make WQ multi-core by default.
Currently, a WQ worker only advertises one core, unless someone explicitly overrides this.
As machines are getting bigger and fatter, it is more naturally the case that we are either
(a) running multiple single core tasks on a machine or (b) matching multicore tasks to multicore machines.
This patch causes WQ to advertise all the cores available, unless overriden by the factory,
the batch system or the user.
Also, we explicitly printf the resources at startup, since this is a significant operational concern
and debugging challenge for the naive user.
Thoughts?
Concerns?

Work Queue Display Resources

---

doc/makeflow.html
makeflow/example/example.categories.makeflow
makeflow/example/makeflow_umbrella/README
makeflow/example/makeflow_umbrella/example_in_makefile.makeflow
makeflow/example/makeflow_umbrella/umbrella_specs/convert_S_category1.umbrella
makeflow/example/makeflow_umbrella/umbrella_specs/convert_S_category2.umbrella
makeflow/src/dag_node.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_umbrella.c
makeflow/src/parser.c
makeflow/test/syntax/directives.makeflow
makeflow/test/syntax/directives_bad_value.makeflow
makeflow/test/syntax/directives_unsupported.makeflow

This PR adds the support to allow the user to specify an Umbrella specification for a group of rule(s) in the Makefile by putting the following directives before the rule(s) you want to apply the Umbrella spec to:
```
.UMBRELLA CATEGORY 1
.UMBRELLA SPEC convert_S.umbrella
```
In this case, the specified Umbrella spec will be applied to all the following rules until a new `.UMBRELLA CATEGORY...` directive is declared. All the rules before the first `.RESOURCE CATEGORY ...` directive will use the Umbrella spec specified by the `--umbrella-spec` option. If the `--umbrella-spec` option is not specified, these rules will run without being wrapped by Umbrella.
An example makefile with umbrella specs can be found at `cctools/makeflow/example/makeflow_umbrella/example_in_makefile.makeflow`:
``` …
```

Support specifying umbrella specs in makefile

---

batch_job/src/work_queue_factory.c
doc/man/work_queue_factory.m4

First pass at adding wrapping functionality to the factory.  This allows you to prefix the worker with an environmental construction tool, for example:
Run a bunch of workers inside an Umbrella environment:
```
work_queue_factory --wrapper "umbrella run myenv.spec" --wrapper-input "myenv.spec" . . .
```
Run workers inside a singularity container:
```
work_queue_factory --wrapper "/usr/bin/singularity run my.img" --wrapper-input "my.img" . . .
```
The code is not quite as elegant as I hoped; if we use the existing `string_wrap_command()`, it carefully escapes all of the dollar-dollar escapes that we want Condor to substitute.  Arg.  So, this one only allows the wrapper to be a prefix on the current command.  Needs more thought.
@btovar @klannon should come in handy for deploying Lobster in …

Add Wrappers to Factory

---

apps/makeflow_blast/README
apps/makeflow_bwa/Makeflow
apps/makeflow_bwa/README

Updates bwa from fastq to query.
Also moves examples to using named makeflow file instead of Makeflow.

Update makeflow_blast/bwa README

---

dttools/src/random.c
dttools/src/stringtools.c

This is for #1506 
A CSPRNG might be nice, but I agree it's not really necessary for our use. We wouldn't want to use a `string_cookie` for any sort of key material or anything beyond the simple handshake. It looks like Mersenne Twister was added fairly recently and hasn't made it all the way through the codebase, so thanks for the issue @bbockelm

Use Mersenne Twister in string_cookie

---

umbrella/src/umbrella.py

Currently, depending on `cctools_python` makes it difficult to share `umbrella`. 
The PR aims to separate `umbrella` from `cctools_python`, and check the python version info itself.

Separate umbrella from cctools_python

---

umbrella/src/umbrella.py

Messing up /var in parrot mountlist may break jobs sent to work_queue_worker running on condor, whose workspace is often under /var.

Avoid messing up /var in umbrella parrot mountlist

---

makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_umbrella.c
makeflow/src/makeflow_wrapper_umbrella.h

Every rule in a makefile may have its own umbrella spec file.
To avoid `w->wrapper->input_files` accumulating umbrella spec files for different rules, first clean it up and then recreate it.

Reset the input files of makeflow umbrella wrapper for each rule

---

makeflow/src/makeflow_wrapper_umbrella.c

Problems:
Currently, makeflow always first check whether a umbrella logfile already exists before starting or recovering a makeflow. This makes it impossible for the users to retry their makeflows.
Failure cases:
A makeflow run may fail if some jobs failed on some bad workers, and the user may want to retrying the makeflow to rerun these failed jobs. Checking the existence of umbrella_logfile would cause makeflow retries fail.
Solutions:
Therefore, in this PR, we stop check the existence of umbrella_logfile here.

Stop checking the existence of umbrella logfile

---

dttools/src/catalog_server.c

This eliminates problems with servers sending invalid JSON, which then confuses consumers of the JSON query.

Catalog: Accept only constant JSON.

---

doc/jx.html
dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/test/jx.expected
dttools/test/jx.input
makeflow/example/example.jx
makeflow/src/makeflow.c
makeflow/src/parser_jx.c

Makeflow's JX representation was written to allow JX variables to be introduced at the file level and at the rule level, using special `"variables"` keys under the root object and rule objects. Unfortunately, this made evaluating the Makeflow complicated. Previously, Makeflow's parser built the contexts itself and `jx_eval`ed each rule object individually. Aside from being ugly, this precludes using a function or operator to build the list of rules, as you need to evaluate that down to an array. @nhazekam have been thinking about how to do this for some time and were coming up with quoting + multiple eval passes, some sort of partial or lazy evaluation, eval hooks, etc.
I realized that Makeflow has no business building and manipulating variable contexts, which should be part of the JX …

Let bindings

---

makeflow/src/makeflow_wrapper_umbrella.c

Currently, using the `--umbrella-spec` option of makeflow and the `LOCAL` tag in a makefile together would cause the following error:
```
makeflow[175943] error: Remote renaming is not supported with -Tlocal or LOCAL execution. Rule 1.
```
Problem:
the umbrella log file is added into the target files of a dag node with a remote name even if the rule is marked as `LOCAL`.
Solution:
If the job is marked as `LOCAL`, adding the umbrella log file into the target file without the rename name.

Allow --umbrella-spec option and LOCAL tag used together

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_table.cc

This addresses #1548
I've been testing on `xstream-ln02.stanford.edu`. I can confirm that the program mentioned in the original bug report works as expected with these changes.

Handle bind()/connect() on abstract AF_UNIX sockets

---

makeflow/example/example.mount
makeflow/example/example.mount.makeflow
makeflow/src/dag_file.h
makeflow/src/makeflow_mounts.c

Use `wget` to download the http and https resources specified in the makeflow mount files.

Use wget to download http(s) resources in the makeflow mount files

---

resource_monitor/src/rmonitor_helper.c

Fixes #1553 by falling back to syscalls to avoid jemalloc deadlocks.
The problem is created by us calling dsym, which in turns calls malloc, which calls a jemalloc wrapper that sets a mutex and also makes us call dsym again, which in turns calls malloc, and hilarity ensues.
This commit detects when the results of dsym has not been set, assumes we are in some initialization code, and falls back to syscalls. Note that this will create problems in the future, as we are bypassing the wrappers below the resource monitor (in particular, the glibc function wrappers.) However, this issue has been observed only with jemalloc.

Avoid resource_monitor and jemalloc deadlocks

---

chirp/src/chirp_client.c
doc/index.html
doc/network.html
dttools/src/Makefile
dttools/src/address.c
dttools/src/address.h
dttools/src/catalog_query.c
dttools/src/datagram.c
dttools/src/domain_name.c
dttools/src/link.c
dttools/src/link.h
dttools/src/stringtools.c
dttools/src/stringtools.h

Second pass at IPV6 support.
Expanded address handling in `datagram` and `link` to handle both `AF_INET` and `AF_INET6`.
By default, `domain_name` will return the OS preference for address modes.
This can be overridden by setting `CCTOOLS_IP_MODE` to `IPV4` or `IPV6` or `AUTO`, which may be helpful for testing/debugging in networking environments.
Issue #1201

IPV6 Support

---

parrot/test/TR_parrot_bind.sh

This addresses #1571 
If the current working directory doesn't support sockets (which appears to be the case on some versions of AFS), the test fails. This patch switches to absolute pathnames that are extremely unlikely to be on weird filesystems

Don't test socket bind in the working directory

---

resource_monitor/src/python/rmonitor_allocations_example.py
resource_monitor/test/TR_python_allocations.py

It was hard to get consistent samples across runs, so we do not check for a particular value anymore.

python allocation fix tests

---

doc/umbrella.html
umbrella/src/umbrella.py

This is useful for the case when an executable is downloaded as a plain file instead of a tarball. 
By default, the python `urllib` library turns off the execute mode of a file, which can not be found by searching the `$PATH` env. 
Using the new `mode` attr allows the user to set the file mode of a plain file.

Add `mode` attr into umbrella specs

---

makeflow/src/makeflow_analyze.c

makeflow_analyze -b DIR would only succeed if DIR already existed.
(Found this bug while fixing a bug related to incorrect assignment of categories, which fix is still to come.)

create output directory when using bundler

---

configure
configure.afs

Fixes #1593.
Git code was moved to configure.afs.
To ./configure, I added --build-label and --build-date. These are set from configure.afs (or manually, if a user so desires.)

Git out configure

---

dttools/src/stringtools.c
dttools/src/stringtools.h
parrot/src/pfs_table.cc

This addresses #1559
Since the namespace symlinks have some unusual behaviour, Parrot shouldn't try to follow them by itself. Also, this pull request changes the handling of `/proc/self` and `/dev/fd`. Previously, these paths short circuited name resolution, so for example, mount lists simply wouldn't be applied to any path with those prefixes. This moves the substitution as late as possible, after name resolution and symlink following.

Don't follow namespace symlinks

---

parrot/src/pfs_channel.c
parrot/src/pfs_table.cc

This is a minimal fix for #1584. Currently Parrot incorrectly handles channels during a rename. If there's an existing mapped entry under the new name, then a rename will result in multiple entries with the same name, only one of which is current. This patch makes any files being renamed over anonymous, that way they won't be returned from the cache. Once the last existing mapping is removed, they can be cleaned up as usual.

Make existing channel anonymous on rename

---

makeflow/src/dag_visitors.c
makeflow/src/lexer.c
makeflow/src/parser.c

When switching to .MAKEFLOW directives, all the related variables were being assigned at the node level, rather than the dag. This meant that all nodes were assigned to the first category that was defined.
Since we do not use directives inside a node anyway, I simply deleted that from the code.
Also, we were assigning two times the values to a variable when it was both a directive and a special variable. The result was not an error, but it was inefficient.

fix mis-assignment of categories

---

doc/man/chroot_package_run.m4
doc/man/parrot_package_run.m4
parrot/src/chroot_package_run
parrot/src/parrot_package_run

Currently, `parrot_package_run` does not work well on packages created by tools
other than `parrot_package_create` due to lacking of `common_mountlist` and
`env_list` files inside the packages.
This commit fixes this.

Enhance parrot_packaging_run

---

dttools/src/address.c
dttools/src/address.h
dttools/src/domain_name.c

This is for #1601. With no address specified, the default behaviour is IPv4 only, which can be overridden with an environment variable. @dthain this fixes the issue I was having on the CRC machines

Check CCTOOLS_IP_MODE when handling addresses

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/pfs_process.cc
parrot/src/pfs_process.h

Fixed PID was used to help bring a HEP application closer to being deterministic.
These features could be dangerous options if there are any incidental PID conflicts (ie. important processes could get killed). Use at your own risk.

Add parrot feature: fixed PID and warped PID

---

dttools/src/category.c

Newer versions of GCC (6.3.1 on my laptop) issue a warning about "misleading indentation" here. I had to switch to tabs to compile with `--strict`

Fix indentation to compile on newer GCC

---

work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.h

Adds the binding to specify 'by_ip' or 'by_hostname'.

add preferred connection to bindings

---

parrot/src/pfs_table.cc

Old versions of `find` read links in an odd way. In the case of `/proc/self/exe`, `find` first opens `/proc/self`, then reads the link `exe`. Parrot's symlink following has been short circuiting on any resolved path with prefix `/proc/self/` (note the trailing slash), so opening `/proc/self` falls through to Parrot.
I wrote a more careful regex, and adjusted the footwork for dealing with symlinks and `/proc`, which I think is *more correct*. Testing on RHEL5-7, the failing test from #1610 passes with these changes.

Match /proc/self more carefully

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/test/TR_parrot_argv0.sh

It looks like some previous fixes lined up to cause an issue for the specific case of `exec()`ing a symlink to an interpreted script. `decode_execve` was overwriting the passed-in path with the value of the symlink. This should leave `argv[0]` as passed in while still setting `/proc/self/exe` to the canonical path to the executable.
This seems to resolve the issue in #1612

Pass the right argv[0]

---

doc/man/resource_monitor.m4
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor.c
work_queue/src/perl/Work_Queue.pm
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue.i

When <file> exists, the resource_monitor takes a snapshot of the
resources and removes <file>. The snapshot is written to
PREFIX.snapshot.NN, where PREFIX is the prefix used for the summary
file. The snapshots are also included in the final summary file, under
the key "snapshots".
Example:
myscript.sh
init()
echo "after_init" > signal.file
analysis()
echo "after_analysys" > signal.file
$ resource_monitor --snapshot-file=signal.file -Omysummary -- ./myscript.sh
$ ls
mysummary.snapshot.01
mysummary.snapshot.02
mysummary.summary
(as requested by @klannon, and @matz-e)

Adds --snapshot-file=<file> to resource_monitor

---

doc/man/work_queue_worker.m4
work_queue/src/work_queue_worker.c

First part to fix #1615. 
Allows several  master hosts to be specified per worker.

add x.x.x.x:pppp;y.y.y.:qqqq master specification

---

work_queue/src/work_queue_worker.c

Do not interpret more than one pair of ':'

---

configure
dttools/src/Makefile
dttools/src/interfaces_address.c
dttools/src/interfaces_address.h
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Second part to fix #1615.
The master informs the catalog about multiple interfaces with a json field that looks like:
"network_interfaces":[{"family":"AF_INET","host":"129.74.153.171","interface":"eth0"},{"family":"AF_INET","host":"172.17.42.1","interface":"docker0"},{"family":"AF_INET6","host":"fe80::b6b5:2fff:fecf:a0d4%eth0","interface":"eth0"},{"family":"AF_INET6","host":"fe80::c025:bff:feaa:31f2%docker0","interface":"docker0"}]
Only works on linux, as it needs getifaddrs, which is not POSIX.  If the master runs on a non-linux machine, the field is not included.

Inform catalog about multiple interfaces

---

dttools/src/Makefile
dttools/src/stats.c
dttools/src/stats.h
dttools/src/xxmalloc.c
dttools/src/xxmalloc.h
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/pfs_service_grow.cc
parrot/src/pfs_service_local.cc
parrot/src/pfs_table.cc

This is a first draft of local mode for GROW-FS. The idea is to index a directory on the local system, and let Parrot handle metadata without touching the filesystem. To access the directory `/home/john` with this, first generate the index.
$ make_growfs /home/john
$ touch /home/john/foo
Note that we added a file after generating the index. Next, run your program under Parrot. `/grow/` should still work as before, except for the path `/grow/local`. Parrot will search the local filesystem rather than connect to a web server. Now you can look at metadata under `/home/john` without touching the disk.
$ ls /grow/local/home/john
$ cat /grow/local/john/foo          # ENOENT: the file is not in the index
Any reads are passed down to the local filesystem.
I haven't done extensive testing, but it …

Add local mode to GROW-FS

---

umbrella/src/umbrella.py

Currently, Umbrella does not check the OS type of the host machine, and fails on Mac.
This PR checks the OS type and terminates Umbrella if the host machine is not Linux.

Add os check in Umbrella

---

doc/man/parrot_run.m4
doc/parrot.html
parrot/src/pfs_main.cc

Add an option to Parrot to disable a compiled-in service at runtime. This addresses #1629, so that it's possible to tell Parrot not to intercept `/cvmfs` and instead let things fall through to the FUSE module. @hmeng-19 let me know if this works for you

Add --disable-service to parrot

---

doc/umbrella.html
umbrella/example/cms_complex/README
umbrella/example/cms_opendata/README
umbrella/example/cms_opendata_git/README
umbrella/example/cms_simple/README
umbrella/example/git_protocol/README
umbrella/src/umbrella.py

Change parrot version used in umbrella, the parrot used in umbrella moves to the commit id [14fb31b](https://github.com/cooperative-computing-lab/cctools/commit/14fb31b22c2b263e4b0764754b7aefd22b7d90ea).
Allow `--use_local_cvmfs` to use cvmfs on the host machine in umbrella
Add `--parrot_log` option to allow generate parrot debugging log
Remove outputs from cleanup list if job succeeds

Allow users to use cvmfs on the host machine in umbrella

---

parrot/test/TR_parrot_cvmfs_access.sh
parrot/test/TR_parrot_cvmfs_alien_cache.sh

Simply change the proxy used for parrot tests.

update proxy of failing parrot tests

---

umbrella/src/umbrella.py

This PR aims to allow umbrella to treat "Scientific Linux" as "redhat".
It should fix the problem Petra encountered on a Scientific Linux machine:
https://groups.google.com/forum/#!topic/cctools-nd/Qw0ya4w9_b4

Treat scientific linux as redhat in umbrella

---

resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper_comm.c

Using a combination of  singularity and the resource_monitor,  some tasks are getting stuck waiting on a recv forever. This is even after select indicates that the corresponding fd is ready for reading. 
The current pr puts a maximum recv wait time, and ignores malformed messages.

Lobster fixes halt on recv

---

umbrella/src/umbrella.py

This option allows the users to specify a SITECONF for their cms applications instead of using the default one provided by umbrella.
The option should be a tar.gz local file path (e.g., /tmp/1.tar.gz) or url path (e.g., http://.../1.tar.gz) pointing to the site configuration files for cms applications, the SITECONF dir should be organized following the suggestions at https://twiki.cern.ch/twiki/bin/view/CMSPublic/SiteConfInGitlab
This PR aims to fix #1645 .

Add --cms_siteconf opt into umbrella

---

makeflow/src/makeflow.c

For debugging errors in makeflow scripts, associating a problematic rule with its line number might not be straightforward in some cases (like long makeflow scripts with comments). This PR adds the line number to the error message.
before:
```2017/05/26 14:24:41.09 makeflow[45593] error: Absolute paths are not supported on selected batch system. Rule 244.```
after:
```2017/05/26 14:26:03.26 makeflow[46565] error: Absolute paths are not supported on selected batch system. Rule 244 (line 740).```

Add line numbers in makeflow error messages

---

dttools/src/histogram.c

We declared variable `b` as `unit_64`, which is an unsigned number, thus `b = abs(b)` is not necessary any more.

remove redundant code

---

resource_monitor/src/resource_monitor.c

possible fix to rarely occurring garbage values in the rmonitor host field.
As reported by @t172

better hostname result check for rmonitor

---

dttools/src/histogram.c

Further fix for #1666. Compilers are magical things.

add missing abs after ceil

---

doc/makeflow.html
makeflow/src/makeflow.c

When using Makeflow with `--shared-fs`, also check if the file is remotely renamed. If so, pass it to the batch system anyway. This could lead to poor performance if used on large files.
resolves #1680

DON'T do remote renaming on shared fs

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_amazon.c
batch_job/src/batch_job_blue_waters.c
batch_job/src/batch_job_chirp.c
batch_job/src/batch_job_cluster.c
batch_job/src/batch_job_condor.c
batch_job/src/batch_job_dryrun.c
batch_job/src/batch_job_internal.h
batch_job/src/batch_job_local.c
batch_job/src/batch_job_mesos.c
batch_job/src/batch_job_work_queue.c
makeflow/src/dag.c
makeflow/src/dag.h
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/src/makeflow_gc.h

This PR changes Makeflow's default behavior for failed tasks. Assuming there isn't an input file or an existing file not managed by Makeflow with a conflicting name, any outputs produced by a failed rule are copied to a `makeflow.failed.n` directory, where `n` is the node ID, and print a message for the user. Running `makeflow -c` will remove failed directories. This should make debugging failures much easier, as logs and such can be brought back as long as they're specified as outputs. I tested locally, on Condor, and with Work Queue.
resolves #1451

Save outputs of failed Makeflow rules

---

batch_job/src/batch_job_internal.h
makeflow/src/dag.c
makeflow/src/makeflow_gc.c

Makeflow's new default of saving failed outputs gives up if it can't move the files, and doesn't try to handle unusual paths. This included absolute paths, so the rename would fail since the parent directory structure would not exist. This PR tries to create any parent directories before the rename. In the case of absolute paths, this will result in a slightly weird directory hierarchy (e.g. `makeflow.failed.3/home/john/workflow/output.log`), but the failed outputs should be there.
resolves #1451 (again)

Support for absolute paths when moving failed Makeflow outputs

---

doc/makeflow.html
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/src/makeflow_gc.h

When debugging my JX BWA-GATK workflow, I was annoyed that there were failed output directories lying around for rules I had fixed. This PR cleans up failed outputs if a rule succeeds after retrying. This is how I would expect things to work when tweaking command lines, and turning on automatic retries implies that there will be intermittent failures we don't care about, so I think this is the right thing to do.

Failed cleanup

---

work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Noted at the tutorial today: People trying to transfer directories containing broken symlinks (such as those created by editors as lock files) would result in mysterious failures in WQ.
Also, some code hygeine commits.

Fix Bug in Symlink Handling

---

batch_job/src/batch_job_local.c
dttools/src/process.c
dttools/src/process.h

Makeflow local execution should use `process_waitpid` instead of `waitpid` directly so as to interact cleanly with multiple points of fork and wait.

Makeflow Local Waitpid

---

parrot/src/Makefile

Not made by default. Use: parrot_cvmfs_static_run
Still needs to be run on the same kernel version and glibc it was
compiled with.

compile statically parrot_run and cvmfs (parrot_cvmfs_static_run)

---

batch_job/src/batch_job_condor.c
makeflow/src/makeflow.c

Move check early in Makeflow to allow for a clearer error.

Enable AFS check for both Docker and Condor.

---

configure

As reported by CJ Grady, perl check would fail in stampede 2.

catch perl conf error before it happens

---

chirp/src/chirp_global.c
chirp/src/chirp_status.c
makeflow/src/makeflow_status.c
work_queue/src/work_queue_status.c

Recent changes to JX syntax broke a few places internal to the code that parsed hard-coded JX expressions from C code. I hadn't noticed them until something cropped up in #1712. The immediate fix was just to update the query strings. After that, I searched around the codebase and replaced the hard-coded strings with expressions to build up JX structures in memory. This is safer for wonky inputs, and lets the compiler do more to check the code. As far as I know, these are all the hard-coded JX expressions in CCTools.

Replace inline JX strings with type-checked expressions

---

resource_monitor/src/resource_monitor.c

Solution for  #1685. We do not round up the value of peak cores unless more than %10 of the extra core is used.

smooth peak cores computations

---

work_queue/src/work_queue.c

When there were no events, wq would wait for one more second since we were using stoptime <= time(0). Also, since time(0) rounds down, some poll times (stoptime - time(0)) were 0, causing busy waits (only for that last second).
As reported by @nhazekam

Fix wq busywait

---

work_queue/src/work_queue.c

Before, 0 would wait at least a second. This pr re-establish that.
Also, wait at least 5 seconds for invalid timeouts.

fix 0, negative timeouts

---

parrot/src/pfs_service_cvmfs.cc

Turns out Parrot was detecting the error in #1737, but wasn't saying anything unless debug logging was on. This PR should give an error message when CVMFS fails in init.

Fix reporting for CVMFS init errors

---

dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll_internal.h
dttools/src/rmonitor_types.h
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor.c

Fixes #1678 
In the resource summary now it will appear:
...
"machine_cpus":
[
4,
"cores"
],
"machine_load":
[
0.07,
"procs"
],
...
The load is computed in 60s windows. The value in the summary is the peak load.

adds s->machine_load and s->machine_cpus to resource_monitor

---

doc/man/resource_monitor.m4
resource_monitor/src/Makefile
resource_monitor/src/file_watch_example.json
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_file_watch.c
resource_monitor/src/rmonitor_file_watch.h
resource_monitor/src/rmonitor_helper.c
resource_monitor/src/rmonitor_helper_comm.c
resource_monitor/src/rmonitor_helper_comm.h
resource_monitor/src/rmonitor_snapshot.c
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

adds --snapshot-events=file to resource_monitor
file looks like:
```json
{
"one.log":
{
"events":
[
{
"label":"start",
"pattern":"# START",
"count":1
}
]
},
"two.log":
{
"events":[
{
"label":"anyline",
"pattern":"^.*$",
"on-truncate":true
}
]
},
"three.log":
{
"delete-if-found":true,
"events":[
{
"label":"manualsnapshot",
"on-creation":true
}
]
}
}
```
The monitor watches for changes in the files, and matches the regular
expressions. If there is a match, a snapshot is generated.
Still working on it... @klannon, is this what you had in mind for #1714?

resource_monitor snapshots when watching (log) files

---

makeflow/src/makeflow.c
makeflow/src/makeflow_log.c
makeflow/src/makeflow_log.h

The log must be flushed (not necessarily sync'd) after each event, and it must definitely be flushed and sync'd when makeflow exits.  This fixes a bug observed by Kyle that a completed makeflow may be missing log entries at the end.

Makeflow: Fix bug in log consistency

---

resource_monitor/src/resource_monitor.c

I didn't rebase #1761 off the current master, and there were some changes in Resource Monitor in the meantime I didn't notice. This should get the red off Autobuild.

Unbreak everything

---

doc/man/makeflow.m4
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c

Sends local environment variables where the makeflow is running to the
remote execution sites.
Fix for #1796

adds --send-environment

---

parrot/src/pfs_service_cvmfs.cc

Enables multi-repository functionality without the need to set `PARROT_ALLOW_SWITCHING_CVMFS_REPOSITORIES`

Enable cvmfs repository switching by default on new libcvmfs

---

parrot/src/pfs_service_cvmfs.cc

This adds the new public signing keys to parrot's default configuration for *.cern.ch repositories.  It also ensures that all valid public keys are probed for *.cern.ch repositories.

Update cvmfs cern.ch default config to latest keys

---

deltadb/src/deltadb_query.c

This fixes crashes in queries across > 9 month queries.

Fix memory leak in deltadb_query.

---

parrot/src/pfs_service_cvmfs.cc

cvmfs 2.4 does not use the function, and the compiler complains.

make cvmfs_parrot_logger not static

---

parrot/src/pfs_service_cvmfs.cc

Fix for #1820.
The check for proxy was done twice, once conditionally on libcvmfs revision, and another unconditionally. I simply removed the unconditional one.

for LIBCVMFS_REVISION < 23, continue if proxy has not been defined.

---

makeflow/src/makeflow_hook.c
makeflow/src/makeflow_hook.h

Simple helper functions for consistently adding inputs and outputs to batch_task from a hook.

Add hook add file helper functions

---

makeflow/src/starch
work_queue/src/work_queue_worker.c

As we found out using singularity, sometimes _CONDOR_SCRATCH_DIR points to a directory that is not accessible outside the container. This causes trouble with the work_queue_worker.
This pr makes it so that the work_queue_worker and starch only use a temp directory if that directory is accessible.

condor scratch may not be accessible inside a container

---

makeflow/src/makeflow.c

Use go to to redirect failures. Allows for clean exit and finalization of code. Maybe not strictly necessary, but allows for clean up under failed initialization circumstances. This also lets us clean
up the batch_queue.

Update failure condition in makeflow

---

makeflow/src/dag_node.c
makeflow/src/parser.c
makeflow/src/parser.h
makeflow/src/parser_jx.c

@btovar The previous category resource specifications removed local node level resource specification support. This should add it back.
@trshaffer You are add due to changes in the `parser_jx.c` 
TODO: Add tests for resource resolution
TODO: Test more thoroughly with categories.

First pass at fixing node level resources

---

makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/makeflow.c
makeflow/src/makeflow_hook.c
makeflow/src/makeflow_hook.h
makeflow/src/makeflow_wrapper.c
makeflow/src/makeflow_wrapper.h
makeflow/src/makeflow_wrapper_enforcement.c
makeflow/src/makeflow_wrapper_enforcement.h
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/makeflow_wrapper_monitor.h
makeflow/src/makeflow_wrapper_umbrella.c
makeflow/src/makeflow_wrapper_umbrella.h

This code change migrates Makeflow to creating a task when a node is submitted and then passing that task to node_complete. This currently stores the task with the associated node, but would prefer that it is retrieved from batch_job_wait. Once batch_job is updated to handle batch_task this will be changed.

Mf task migration

---

chirp/src/Makefile
configure
resource_monitor/src/Makefile

Example:
LD=musl-gcc LD_FLAGS=-lm CC=musl-gcc ./configure --static --with-{readline,perl,python}-path=no

Build chirp (but chirp_fuse) statically.

---

makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/src/makeflow_gc.h
makeflow/src/makeflow_hook.c
makeflow/src/makeflow_hook.h
makeflow/src/makeflow_log.c
makeflow/src/makeflow_module_storage_allocation.c

Migrates the storage allocation code out of Makeflow main into a module. This also removes several unnecessary hooks.
A change of note is that this continues moving all exits success or failure to using gotos and properly cleaning up. As a result some logging events needed to check for null to avoid segfaults. Let me know if this is an unacceptable change.

Hook storage allocation

---

makeflow/src/makeflow_hook.c

Found bug where if the remote name is NULL these functions seg fault. They have been updated to work correctly. This will only have affected wrappers, but hopefully has not affected anyone yet.

Remove seg fault possibility

---

makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/src/makeflow_gc.h
makeflow/src/makeflow_log.c
makeflow/src/makeflow_module_fail_dir.c
makeflow/src/makeflow_module_storage_allocation.c

Realized this functionality was removed but the variables are still there. They are now removed.

Remove redundant var in makeflow_clean

---

dttools/src/catalog_query.c
dttools/src/catalog_query.h
work_queue/src/work_queue.c

Catalog updates are now automatically compressed if they exceed a size threshhold (1200 bytes).
WQ in particular will attempt to send a "full" update if it can be compressed within this limit.
If not, it sends a "lean" update.
Fixes #1744

Automatic size/compression of catalog updates.

---

parrot/src/pfs_table.cc

Fixes #1847
This is basically the same issue as #1559. Rather than adding more special cases as we find them, this PR tries to detect any occurrences of magic symlinks. These symlinks have similar-looking targets, so when in `/proc` Parrot won't follow this kind of symlink. I don't think this will cause issues in not following normal symlinks that happen to have this form. Since they're always relative, there would have to be entries under `/proc` with unusual filenames (containing `:`, `[`, and `]`). Everything under `/proc` is managed by the kernel, so I think this should be a more reliable approach.

Detect magic symlinks under /proc and don't try to follow them

---

resource_monitor/src/Makefile

This was making the static-libgcc to be excluded from the compilation line, and libraries not being included as needed. The result was that a task in lobster was seg-faulting mysteriously.

use LDFLAGS not CCFLAGS (!) when linking monitoring library

---

makeflow/src/makeflow_module_singularity.c

Addresses issue of singularity using redirect from underlying command.
e.g.
bwa aln ref.fa query.fq > query.sai
and
singularity ... bwa aln ref.fa query.fq > query.sai
SAI in the second case is corrupted by singularity standard output.
This may be applicable to Docker...

Sing shell quote

---

makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/makeflow_module_shared_fs.c

Move the shared-fs support out of makeflow's main and into a module. This is still being tested, but should have the same behavior as the previously released functionality.

Hook shared fs

---

dttools/src/rmonitor.c
dttools/src/rmonitor.h
makeflow/src/makeflow.c
makeflow/src/makeflow_module_resource_monitor.c
work_queue/src/work_queue.c

Add handling to specify resource monitor and also enable measuring a directory. 
When measuring the directory in a Makeflow task we use $PWD always. This allows
the directory to reflect wherever it is executed and not some assumed name.

Update resource monitor module

---

parrot/src/pfs_main.cc
parrot/src/pfs_table.cc

When started with the `--no-flock` option, Parrot simply returns success on all calls to `flock(2)`. This could be dangerous, but it's probably fine. Since Parrot's `flock()` support is broken, this is necessary to work around #1875

Add flag to disable flock

---

makeflow/src/makeflow_module_sandbox.c

I ran into an issue with directories specified as inputs/outputs. The generated wrapper scripts skip directories, leading to loads of failures. This PR does `cp -r` so both files and directories get copied into the sandbox.

Do recursive copies in Makeflow's sandbox mode

---

dttools/src/stringtools.c
dttools/src/stringtools.h

I needed to use `strcmp()` to sort a list of strings. There are some pointer gymnastics required to work with list_sort, so I pulled this from `qsort(3)`.

Add string comparison function for list_sort

---

makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/parser_jx.c
makeflow/src/parser_make.c

In my other PR, I had to awkwardly make changes throughout both Makeflow parsers. Some places (setting the command/submakeflow and adding the node to the DAG) were repeated between the two, and in fact differed in behavior. This PR abstracts that logic into functions on `struct dag_node` that both parsers can call into. Rebasing onto this will also clean my other PR up significantly.

Add functions to set up struct dag_node

---

configure.afs

Use host's python and perl for the binary distributions.

use perl and python from host, not afs

---

batch_job/src/work_queue_factory.c

Before, the factory would wait until all workers of previous cycles to
connect before submitting new workers. If a worker had a problem, this
would halt future submissions.
Now the factory would have workers_per_cycle waiting at any time. (Until
the target number of workers is reached.)

factory to have N workers to wait connection at any time.

---

dttools/src/jx2json.c

I had just used an empty context as the default when `eval()`ing each piece, but context changes should be visible to other args, not just the final document. So for example, this PR lets you fill in variables in a context file by defining them earlier on the command line.

Fix jx2json eval so that context changes are visible to subsequent args

---

dttools/src/copy_tree.c

This error would always produce a logic error where only one entry in the directory is being copied over due to breaking from the while loop when something other than 0 returning from copy_direntry. This function will not necessarily always return 0 when it successfully runs but it will return -1 on error. The change in the conditional statement may not be necessary but was added for clarity on when the while loop will terminate.

copy_dir_real fix in copy_tree.c

---

makeflow/test/dirs/testcase.subdir.01.makeflow
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

This is a quick fix for #1892. Instead of using scanf, we use pattern_match.
This should be the final solution, as it breaks the syntax of the protocol (i.e., tokens separated by a space). It does preserve, however, backwards compatibility.

Fix space in dir recursive get for wq

---

dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/test/jx.expected
dttools/test/jx.input

Overload the + operator to allow for string concatenation between unequal types.

JX String Concatenation

---

dttools/src/jx2json.c
dttools/src/jx_eval.c
dttools/src/jx_eval.h
makeflow/src/dag_visitors.c
makeflow/src/parser.c

Under the existing JX code, there is no obvious translation of our example "convert" workflow into a JX form, because one must always have a separate file in order to define values for substitution.  This PR allows a JX document to have a "define" section which is merged into the context for evaluation, allowing you to have a self-contained document.
Also, the context is evaluated against itself, which allows various definitions to build upon each other, or to use non-atomic values such as list comprehensions..
I'm not entirely sure about the appropriate name of this section.
Maybe "let" or "define" or "constants" or ...
For example:
```
{
"define": {
"CONVERT":"/usr/bin/convert",
"CURL":"/usr/bin/curl",
"URL":"http://ccl.cse.nd.edu/images/capitol.jpg",
"RANGE":range(0,360,90)
},
"rules": …
```

JX Embedded Context

---

dttools/src/jx2json.c

Allows for `jx2json -np < file.jx` to pretty-print JX without evaluating it to JSON.
Handy for reformatting workflows.

Add No Eval Option to jx2json

---

dttools/src/.gitignore
dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_parse.c
dttools/src/jx_print.c
dttools/test/jx.expected
dttools/test/jx.input

Resolves #1922
This replaces the existing JX error messages (hard to read) with simpler function-looking messages. Errors are reported as normal strings.
See the new [expected test](https://github.com/trshaffer/cctools/blob/c1687324df43e34471b529e215138a711aecc6a1/dttools/test/jx.expected#L181) for how things look now.

JX eval errors

---

work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

Before we would try to keep the worker around when a task filled the
disk alloted to the worker. However, this only works for inputs that are
not cached (e.g., not makeflow). CJ found that the master would keep sending tasks to a
worker, and those tasks eventually would fill the worker's disk. The
tasks were terminated, but the cached was not cleared, thus disk usage
at the worker kept increasing, and the tasks kept failing.
Since there is no easy way to tell at the worker which files are cached,
this commit makes it so that the worker disconnects.

Worker always clean on disk exhaustion

---

makeflow/src/makeflow.c
makeflow/src/makeflow_module_archive.c

Added flags to change the s3 hostname, s3 access key, and s3 secret key. This will make it useful for when a user wants to use an s3 like library like Minio over regular s3 use.

Flag Additions for S3 Archive

---

batch_job/src/work_queue_factory.c

I ran into this situation the other day: I started a work queue, and a work queue factory to handle workers. After letting the computation run for a while, I realized that I had underestimated the amount of time my tasks would take, and also underspecified the worker limits of the factory. I started another factory.
However, multiple factories don't play well together. I got to a point where all the tasks were distributed to workers but, because the factory doesn't check whether the number of connected workers meets the task needs, each factory was constantly spinning up new workers to meet a need that didn't exist. 
This patch fixes that by doing a sanity check to see whether there are workers connected from other sources, and considering that number when it computes …

Work queue: Consider workers connected from other sources

---

batch_job/src/work_queue_factory.c

remove old safeguard, as new workers needed cannot be negative

---

batch_job/src/batch_job_cluster.c

Specifies cores with -c in SLURM and only submits as a single task. The previous version assumed 1 task=1 core and would specify a job as multiple tasks.

Specify cores with -c 

---

batch_job/src/work_queue_factory.c

Fixes bug introduced in #1958.
Existing workers need to be applied *before* the max workers per cycle constraint, otherwise `new_workers_needed` can be reduced to 0 when the number of workers from other sources is greater than `workers_per_cycle`.
Sorry about that, @btovar. This seems to be working as expected now.

Fix existing new workers calculations

---

configure
dttools/src/debug.c
dttools/src/debug.h
parrot/src/Makefile
parrot/src/pfs_main.cc
parrot/src/pfs_service_ext.cc
parrot/src/pfs_table.cc

This PR adds ext2fs as an optional dependency so that Parrot can mount ext[234] disk images. This could be expanded to support read/write access, but for the moment I kept things RO. Users specify the path to an image file which Parrot loads and exposes as a directory tree under `/ext_%d`. I might adjust how images are specified on the command line and the paths they get to improve ergonomics. I've done enough testing to make sure basic functionality works (look around directories, read files, exec programs, follow symlinks).
See also #1947

Parrot support for mounting ext images

---

.travis.yml
chirp/test/TR_chirp_perl.sh
dttools/test/test_runner_common.sh
run_all_tests.sh
travis.sh
travis_build.sh
work_queue/test/TR_work_queue_foreman.sh
work_queue/test/work_queue_common.sh

This PR will enable Travis on the main repo. I've been testing on my fork, and things seem to be working well. This configuration tests on Travis' default Linux and Mac environments, and in Docker environments we currently use for Autobuild. A couple of points might require discussion:
- The behavior of `run_all_tests.sh` changes so that failed tests result in non-zero exit status. This will likely break the current Autobuild setup. I'm of the opinion that any failed tests should be considered an overall failure, but we might need to drop this commit and keep the current setup with different levels of failure for compatibility with Autobuild.
- I removed the test for WQ Foreman. From a quick glance at the Autobuild display, this test fails about a third of the time, and is ignored in …

Enable Travis CI

---

doc/man/resource_monitor.m4
dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll.h
resource_monitor/src/resource_monitor.c

Allows to track arbitrary pids owned by the user executing the monitor.
It tries to figure out children processes from /proc/pid/.../children  where available.
Less precise measurements, as fork and exit events cannot be captured.

adds --pid=<pid> to the resource_monitor

---

parrot/src/pfs_main.cc
parrot/src/pfs_service_cvmfs.cc

As reported by @khurtado. 
Also, cleaned it up so that we don't pass the proxy value to cvmfs via an environment variable.

use HTTP_PROXY when -p is not specified

---

.travis.yml
travis_build.sh

This PR creates an OSX release tarball on Travis. I went with the default environment (OSX 10.13). Also installs SWIG through Homebrew to address a mailing list issue.

Build OSX release

---

doc/man/resource_monitor.m4
doc/resource_monitor.html
dttools/src/rmonitor.c
dttools/src/rmonitor_poll.c
resource_monitor/src/resource_monitor.c
work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_test_main.c

Measure but don't kill tasks that exhaust resources.
(To help with debugging in shadho.)

give the option to just measure, but not kill tasks in workqueue

---

batch_job/src/batch_job_cluster.c
makeflow/example/example.categories.makeflow
makeflow/src/makeflow.c

Support SGE resources.
Only specifies Memory and Cores.
Assumes parallel environment `-pe smp` on SGE (single machine).
The default type of memory is `-l h_vmem=$$M`. 
Updated example to run in SGE with specified resources. Previously was failing with original resource specification.
Addresses #1978

Update SGE resource parsing

---

work_queue/src/work_queue_graph_log

It gave wrong results when the application time was larger than the step
resolution.

Don't force same height for bars in graph.

---

work_queue/src/work_queue.c

Removes doubled jx_insert_integer for workers_able attribute

---

configure

./configure included some anaconda  compilation flags that caused an error when compiling bindings for 3.6.
This error did not occur with pythons not compiled with anaconda.
Compilation against python 3.7 still does not work, but it seems related to the C code generated by swig.

WorkQueue with python 3.6 from anaconda

---

doc/makeflow.html
doc/man/makeflow.m4
makeflow/src/makeflow.c
makeflow/src/makeflow_mpi_starter.c
work_queue/src/work_queue_worker.c

@dthain @btovar 
Probably not necessary, but before the mpi boilerplate code I added a link in a comment to the tutorials where I learned how to use MPI. Ben said it wasn't necessary, especially because it's not an exact copy paste, but it's pretty similar in the variable naming. At the very least, whoever comes after me and needs to maintain it will have a link to a good tutorial on MPI.
Also included are some of the other changes that haven't been merged in yet, namely updating the commandline reference for task sandboxing in `-T mpi` mode and updated wording in the manpages/webpages.

Mpi tutorial reference

---

dttools/src/jx.c
dttools/src/jx_parse.c
dttools/test/jx.expected

Fixes #2007 
This reverts the hotfix in #2006 and makes the changes in the parser. For the specific case of a unary minus preceding a numeric constant, we carry out the evaluation at parse time. JSON doesn't allow a preceding plus, but we could allow that if someone wants it.

Unary minus in JX

---

work_queue/src/work_queue_worker.c

wq worker: use all cores available by default

---

dttools/src/Makefile
dttools/src/jx_canonicalize.c
dttools/src/jx_canonicalize.h
dttools/test/TR_jx_canonicalize.sh

Picking up from #1942, this PR introduces a `jx_canonicalize` function for rendering a JX object as a string in canonical form. This is intended for both generating a hash of some JX or for producing a stable representation. I allowed a conservative subset of JX:
- Only plain JSON types
- Object keys must be strings
- Object keys must be unique
This is to ensure that it's straightforward to decide how things should canonicalize without saying anything about future language changes. This canonical form is not great for general printing because of the aforementioned restrictions, lack of support for whitespace padding, and weird formatting of floats. It should, however, produce a stable JSON representation suitable for hashing or use as a dictionary key or what have you. For hashing uses …

Add function to canonicalize JX

---

umbrella/src/umbrella.py

Additional checks in Umbrella to prevent deleting an entry that doesn't exist or iterating over None.
Both are encountered when using Makeflow.
The first is a result of only specifying parrot in parrot mode.
The second is a result of no executable, which can occur if it is assumed to exist in the environment. In the example makeflow this could be `/usr/bin/convert`.
These are small safety changes to allow Makeflow to work and should not break any existing Umbrella usage.

Add additional checks to umbrella

---

deltadb/src/Makefile
deltadb/src/deltadb_query.c
deltadb/src/deltadb_stream.c
deltadb/src/deltadb_stream.h
deltadb/src/deltadb_upgrade_log.c
dttools/src/catalog_server.c
dttools/src/jx_database.c

In an effort to reduce the size of catalog logs, this PR introduces a new event type "M" (merge) which captures multiple changes in a single merge event.  (In short, each UDP update now corresponds to a single log event.)

Catalog/DeltaDB Merge Event

---

work_queue/src/work_queue.c

This fixes a segfault triggered when task was cloned after completion and then deleted. There was a double free in the rmsummary structures.

correctly clone task resources

---

work_queue/src/work_queue.c

Fix issue where an active task structure is resubmitted, e.g.,  two q.submit(task) with the same task, as protection for naive task cloning.

do not allow resumission of active task structures

---

work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/work_queue.c
work_queue/src/work_queue.h

This is a bug fix. For some reason the count argument was added to specify_feature, but never really implemented.

bug fix: features don't take counts

---

dttools/src/jx.c

I ran into a bug when trying to override JX variables on the command line in Makeflow. Turns out `jx_merge()` was reversing the order of the list of pairs in an object, which led to old values mysteriously reappearing. This PR replaces that logic, doing a wholesale copy of each object then splicing the pieces together.

Fix jx_merge()

---

chirp/src/python/chirp.binding.py
work_queue/src/python/work_queue.binding.py

This change is necessary for swig4 usage.
swig pre version 4 defined _object as a fallback in case object was not
defined. Since we require at least python2.7 which does define object,
we can drop the use of _object.
Fix for #2054

use object instead of _object

---

parrot/src/pfs_table.cc

Fixes a compilation error with the newer glibc 2.26.

re-add sys/sysmacros.h for glibc 2.26

---

batch_job/src/work_queue_factory.c

A debug statement was iterating master_list twice. Some masters were not
being served workers as a result.

do not iterate twice masters_list

---

work_queue/src/work_queue_process.c

Some docker images do not set PATH at all, and execlp("sh", ...) fails.
Fixes #2067

Use execl instead of execlp when launching tasks in workers

---

doc/workqueue.html

Update the Work Queue User's manual to explain that users need to specify all resource requirements for a task in order to allow for multiple tasks to run on a single worker.

Work Queue User Manual Update

---

batch_job/src/batch_job_cluster.c
doc/man/makeflow.m4
makeflow/src/makeflow.c

This PR adds a flag to switch to pre f892d75f behavior. This is helpful for figuring out which job/command is running. This is not the default, as we shouldn't assume that the batch system will handle it.

Add flag to use previous logic for job names

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

Adds q->stats->master_load
When close to 1, the master is at full load dealing with the transfer of tasks, and cannot accept connections of new workers.
When close to 0, the master is mostly waiting for something to happen.
It can be seen as a measure of capacity taken from the behavior of the master, independent of any time measures.

add measure of master load

---

README
deltadb/src/deltadb_query.c

Advance the display_next counter by display_every on every output.
This prevents the display time drifting out of phase when time updates are irregular.

DeltaDB Time Intervals

---

makeflow/src/dag_node.c
makeflow/src/makeflow_module_fail_dir.c

This PR has Makeflow write out a file called `INFO.json` in the `makeflow.failed.%d` directories that get created on rule failure. This consists of the fields from `dag_node_to_jx()`, plus the exit code/signal. An example of the info for the usual `example.makeflow` (where I modified one of the rules to fail):
{
"exit_code":1,
"command":"/usr/bin/convert -swirl 90 capitol.jpg capitol.90.jpg; exit 1",
"inputs":
[
{
"size":51274,
"dag_name":"capitol.jpg"
}
],
"outputs":
[  
{
"size":1073741824,
"dag_name":"capitol.90.jpg"
}
],
"environment":
{
"CORES":"1",
"OMP_NUM_THREADS":"1"
},
"category":"default",
"resources":
{
}
}

Write out info on Makeflow failures

---

work_queue/src/bindings/perl/Work_Queue.pm
work_queue/src/bindings/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Supersedes #2048 without the need to modify work_queues communication protocol. It also adds perl and python bindings.

adds work_queue_specify_draining_by_hostname

---

packaging/conda/build.sh
packaging/conda/meta.yaml

I've added support for tests in the meta.yaml, and changed the build script to exclude weaver when installing with Python 3 as the python version.

Updated conda build recipe

---

work_queue/src/bindings/python/Makefile
work_queue/src/bindings/python/work_queue.binding.py
work_queue/src/bindings/python/work_queue_async.py
work_queue/src/bindings/python/work_queue_async_example.py
work_queue/src/bindings/python3/Makefile

It should work as drop-in replacement for the classic work_queue
module.
HIGHLY EXPERIMENTAL CODE, IT MAY NOT WORK AT ALL
BEHAVIOUR DIFFERENCE: queue transfers/receives tasks even when wait() is not called.
INTERFACE DIFFERENCE: q.wait(0) returns immediately if no task to return is ready. Also, the new method q.receive() is the same as q.wait(0)
It mainly captures submit and wait calls. Tasks submitted get added to a
queue for later real submission. Returned tasks are put into a queue to
be retrieved at the client's convenience. Any other call is made with a
lock (that is, no two work queue calls can be made at the same time.)

Python work_queue library that allows for asynchronous wait

---

dttools/src/jx_print.c
dttools/test/jx.expected

Fix bug in JX output: doubles were emitted with only six digits of precision (the default of printf %g) now they use up to 16 digits.

Fix Bug in JX Double Output

---

dttools/src/jx.c
dttools/src/jx_database.c
dttools/src/jx_parse.c
dttools/test/TR_jx_merge.sh

This is a fix for #2094 
Putting aside any changes to JX objects for the moment, I simply reverted to the original `jx_merge()` implementation and added a workaround for the motivating problem. I tested against the minimal case in the linked issue and didn't observe any corruption.

Hotfix for Catalog Server

---

configure

A recent change made swig 2.0.4 a requirement for all bindings, when this is a requirement only for python3. This pr allows bindings for perl and python2 when only an older version of swig is available.
This issue was found when Brian Lin was trying to create an rpm of cctools for OSG.

allow python and perl bindings (and no python3) for old versions of swig

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_resolve.c
parrot/src/pfs_resolve.h
parrot/src/pfs_table.cc

The current path resolution code in Parrot seems to more or less ignore the `LOCAL` access control. This PR adds a new resolve outcome, `PFS_RESOLVE_LOCAL`, that causes subsequent opens to skip service lookup, forcing use of the local filesystem. Aside from that, this return code behaves almost the same as `PFS_RESOLVE_UNCHANGED`.
Fixes #2121

Fix LOCAL in Parrot mountlist

---

batch_job/src/batch_job_k8s.c
batch_job/src/batch_job_local.c
batch_job/src/batch_job_mpi.c
dttools/src/shell.c

Fixes a bug in which if PATH does not include /bin, batch_job_local cannot execute the job.
This may occur when a workflow sets the PATH variable in JX.

Batch local /bin/sh

---

doc/jx-quick.html
doc/jx-tutorial.html
doc/jx.html
dttools/src/.gitignore
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/test/jx.expected
dttools/test/jx.input

Rework of #2117 to use a function rather than a weird language construct. It's somewhat unusual compared to existing functions in that it reaches into the parent context.
If everyone approves of the syntax, I'll update the docs and examples.
Closes #2117
Resolves #2107

Template function

---

chirp/test/TR_chirp_perl.sh

Changed paths in chirp/test/TR_chirp_perl.sh from `src/perl/` to `src/bindings/perl` as referenced in issue #2134.

Perl Chirp test path update (Fix #2134)

---

chirp/src/bindings/python3/Makefile
configure.tools.sh

From a [thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/cctools-nd/lwt9A_EZJK4) on the mailing list, there are compilation errors on Python 3.7 using conda. I grabbed the fix in 3fd3826554c0c4dbc3a1a2425175c541ff07baab and put it on the Chirp bindings, and things seem to work.

Fix compilation for Chirp SWIG bindings for Python 3.7

---

batch_job/src/batch_job_condor.c

This allows to easily modify the condor submit file the factory uses.
E.g., as needed by mfrayer at Wisconsin:
work_queue_factory -T condor --batch-options="universe=docker\ndocker_image=debian" ...etc...

expand newlines, etc. in batch-options for condor/wq-factory

---

doc/makeflow.html

Corrected Typo in makeflow manual #2142: In /cctools/doc/makeflow.html on line 282, "produceds" should be "produces"

Fix typo in makeflow manual on line 282

---

work_queue/src/work_queue.c

Fixes for #2179 
When freeing the struct used for capacity, we we were not freeing the pointer to its resources.

Correctly free the struct used for capacity

---

configure

It is not needed for swig, and causes issues if libperl is not compiled
with '-fPIC', as with conda-forge.

Do not link against libperl

---

chirp/src/bindings/perl/Makefile
configure
work_queue/src/bindings/perl/Makefile

This eliminates the need of setting PERL5LIB.

Install perl modules where conda wants them.

---

configure
configure.tools.sh

Instead of requiring c++, parrot is disabled.

do not require c++ in configure

---

batch_job/src/work_queue_factory.c
doc/man/m4/work_queue_factory.m4
doc/man/md/work_queue_factory.md

Forces the factory to run as a work queue master when -Twq is specified.
It can only be used with -Twq.
If only one of -Twq or --run-factory-as-master is given, the factory
terminates, and the user is adviced to use -Tlocal instead.
Fix for #2190

wq factory: add --run-factory-as-master

---

dttools/src/Makefile
packaging/scripts/configure-from-image
packaging/scripts/generate-images

This pr modifies `packaging/scripts/configure-from-image` such that the `work_queue_worker` binary is compiled statically. This eases the deployment of workers across machines with the same architecture.
If this works as intended, we can follow a similar approach for compiling cctools with conda, such that workers do not depend on the conda environment's shared libraries.

Compile work_queue_worker statically with travis

---

batch_job/src/batch_job_condor.c

A set of parentheses was sometimes missing when both condor requirements and blacklisted hosts were used.

Fix condor requirments in batch job

---

makeflow/src/makeflow_analyze.c
makeflow/src/makeflow_viz.c

The problem was that the result of jx_parse_cmd_args was not being
reassigned to jx_args. Eventually this would lead to a double free.

Fix segfault in makeflow_{viz,analyze} with --jx-args

---

configure
umbrella/src/Makefile

The pr #2211 brought attention to the fact that the umbrella documentation was not optional.  This pr makes it so that if the documentation for umbrella cannot be build, then the installation does not fail.
In the very near future we should do something in the spirit of #2211, and detect the pydoc corresponding to the correct python environment. I would like to this using python itself, rather than what we currently do, which is manipulating names for a command line which will eventually break.

make umbrella and its documentation really optional

---

dttools/src/rmonitor.c

Changes the behavior of the function that searches for the monitor. Now, when an explicit path is given and the monitor is not found, it immediately returns. The previous fallback behavior leads to a confusion on which monitor executable is being used.

do not look for monitor executable with explicit search options

---

packaging/scripts/configure-from-image

This matches how we compile things for conda. In conda we disabled it because in OSX libperl is needed for produce the bindings, but the libperl provided cannot be linked against. Recent changes to the osx travis images also have this issue.

Disable perl bindings in OSX

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

Related to #2229.
When the resource monitor failed to execute, the task was marked with return status 0. This should be really considered as an internal work queue error.

Correct work queue status of task when monitor summary not available

---

makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/makeflow.c

Fix for #2185. Ensure that the files created while parsing are always deleted.

Always remove temporary jx args files

---

work_queue/src/bindings/python/work_queue_futures.py

correctly name concurrent.futures.CancelledError

---

configure
configure.tools.sh
packaging/scripts/generate-images

Fixes some of the issues with the configure script, such as:
- Automatic detection of some packages outside the given --with-*-path options.
- ldflags and ccflags were permanently  modified while testing for a package, even when the detection eventually failed.
- Results of package detection were in different places, which was confusing for debugging.
- Some packages used  PKG_avail=no, and others PKG=0 to indicate failure on detection. Now all packages use PKG_avail. Executables are now PKG_exe.
-  --with-python-path  did not automatically detect with version is found, and it was fixed for version 2. (For legacy,  --with-python2-path is now added.)
- Bindings did not report when swig was not available, nor when the swig version was to old for them.
- Incorrectly checking whether the …

Cleaner configure script

---

chirp/src/chirp_alloc.c
chirp/src/chirp_benchmark.c
chirp/src/chirp_fs_local.c
chirp/src/chirp_put.c
chirp/src/chirp_recursive.c
chirp/src/chirp_tool.c
chirp/src/confuga.c
chirp/src/confuga_namespace.c
configure
dttools/src/address.h
dttools/src/auth_kerberos.c
dttools/src/auth_unix.c
dttools/src/file_cache.c
dttools/src/full_io.c
dttools/src/host_disk_info.c
dttools/src/host_memory_info.c
dttools/src/link.c
dttools/src/load_average.c
dttools/src/md5.c
dttools/src/rmonitor_poll_internal.h
dttools/src/rmonitor_types.h
dttools/src/uptime.c
resource_monitor/src/rminimonitor_helper.c
resource_monitor/src/rmonitor_helper.c

Removes compile options and #ifdef's for cygwin, sunos, aix, and bsd's that are not darwin.

Remove unused os checks

---

dttools/src/host_disk_info.c
dttools/src/host_disk_info.h
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Related to issue #2229.
I opted for simply warn rather than terminating the worker as command absolute paths would work when workspace is on a noexec filesystem.
@annawoodard, thanks again for debugging this issue for us!

Warn when worker workspace on noexec filesystem

---

doc/manuals/makeflow/index.md
makeflow/example/example.makeflow
makeflow/src/lexer.c
makeflow/src/lexer.h
makeflow/test/TR_makeflow_025_quoting.sh
makeflow/test/TR_makeflow_025_quoting_open.sh
makeflow/test/syntax/quotes.01.makeflow
makeflow/test/syntax/quotes.02.makeflow
makeflow/test/syntax/quotes.03.makeflow

With a recent change, using "a": "b" would fail with a syntax error.
This pr also adds two tests to check " and ' syntax, and makes the example in the manual the same as example.makeflow with respect to the use of quotes.

Accept " when specifying file requirements

---

dttools/src/host_disk_info.c
dttools/src/host_disk_info.h
work_queue/src/work_queue_worker.c

Create a test script to check whether we can execute files from the worker's scratch directory.
The previous method of checking filesystem flags was removed, as it was not portable.

Portably check worker exec

---

resource_monitor/src/rmonitor.i

The swig version 4.0 changed the way it generates access methods.  Before we were are able to read the fields present in the rmsummary structure. In 4.0 we have to manually name each field.

manually set fields, as introspection of swig changed.

---

resource_monitor/src/bindings/python3/resource_monitor.bindings.py

Adds a specific exception for a monitoring internal error, and renames functions that started with __, as to follow standard python coding guidelines.

Monitor py style

---

configure

conda adds some python flags that clash with swig. These flags are not needed for linking anyway, as the python libraries from conda in OSX are compiled statically.

fix linking for conda on darwin

---

parrot/src/Makefile
parrot/test/TR_parrot_cvmfs_access.sh
parrot/test/TR_parrot_cvmfs_alien_cache.sh

Ensures that  the correct libraries, such as for cvmfs, are linked when building parrot.

Fix parrot linking

---

apps/wq_bwa/wq_bwa

There was an error where two of the splits were not being created/submitted as tasks. A simple fix is proposed here.

wq_bwa: fixed off by two error when submitting tasks

---

batch_job/src/batch_job_condor.c

As of HTCondor version 8.9.3, the default userlog format puts the year
into the job log, looking like this
005 (312.000.000) 2020-03-28 23:01:04
the old format looked like
005 (312.000.000) 03/28 23:01:04
Currently, makeflow hangs forever, not seeing completed jobs when HTCondor
uses the new format.
This patch allows cctools to parse both the old and the new format. Note that
the code used to assume the year was 2008, this been updated to 2020, in the
case where we don't know.
Note that you can configure HTCondor to emit the old format by setting
DEFAULT_USERLOG_FORMAT_OPTIONS = legacy

Support new HTCondor job log format containing year

---

batch_job/src/batch_job_condor.c

Folow up to #2268.
Computes current year in case HTCondor log does not provide (old log format). Before we simply used a fixed value.

HTCondor year fallback for old log format

---

work_queue/src/work_queue_json.c

Found with gcc 7.3.0.
As far as I can tell, the logic of the function prevents the uninitialized values from being used.

Pedantic warnings wq json

---

deltadb/src/deltadb_reduction.c
resource_monitor/src/resource_monitor.c

Found with gcc version 7.3.0.
Initial value is provided by the switch statement, but the compiler is missing that.

fix uninitialized value in deltadb_reduction_value

---

dttools/src/jx.c

Warning found with gcc 7.3.0.
The uninitialized value never comes into play, as initialization is covered by the switch statement. Adding an initial value to make the compiles happy.

guard uninitialized struct in jx_copy (pedantic compiler fix)

---

parrot/src/pfs_main.cc
parrot/src/pfs_table.cc

Warnings found with 7.3.0.
The uninitialized value never came into play. Adding an initial value to make the compiler happy.
The other commit eliminates the use of sprintf.

Pedantic warnings parrot

---

makeflow/src/makeflow_linker.c
makeflow/src/makeflow_summary.c
makeflow/src/parser_make.c
work_queue/src/work_queue_json.c

Warnings found with 7.3.0.
The uninitialized values never came into play. Adding initial values to make the compiler happy.

Pedantic warnings makeflow

---

chirp/src/chirp_fs_local.c
chirp/src/confuga_job.c
chirp/src/confuga_namespace.c
chirp/src/confuga_replica.c
chirp/src/json.c

Warnings found with gcc 7.3.0.
I simply silenced the strict aliasing one, as I am not sure what those are lines are doing, and we should be replacing json.h and json.c with jx anyway.

Pedantic warnings confuga

---

chirp/src/bindings/python3/chirp.binding.py
resource_monitor/src/bindings/python3/resource_monitor.bindings.py
work_queue/src/bindings/python3/work_queue.binding.py

conda-forge CI failed for python3.8/osx with a SyntaxWarning (using 'is' instead of ==).
This pr comes from using a python linter to pickup other such warnings.

Python bindings style changes 

---

doc/man/.gitignore
dttools/src/load_average.c
makeflow/test/TR_makeflow_alloc_output.sh
resource_monitor/src/.gitignore
work_queue/src/.gitignore

Currently, we count *logical* cores when examining the host system. On systems that make use of hyper-threading (especially extreme cases like Xeon Phi), this can lead to accidental over-subscription issues.
This PR changes `load_average_get_cpus()` to return the number of *physical* cores on the machine. For Macs, this is a simple change. For Linux, it requires some digging into `/sys`. I've tested a number of CPU configurations:
- Single-socket, no HT (cclws20)
- Single socket, HT (cclws19)
- Multi-socket, no HT (crcfe02)
- Multi-socket, HT (earth)
From what I could find online, the Xeon Phi registers as a normal CPU with HT, but I don't think I have access to any real machines to test on.
Resolves #2262

Return the number of physical CPUs from load_average_get_cpus()

---

work_queue/src/work_queue_json.c
work_queue/src/work_queue_json.h
work_queue/src/work_queue_json_example.c

Adds the "environment" : { "key": "value", .... } object to the task description. Each key-value pair is fed to work_queue_task_environment_variable.
Simplifies cache and watch flags to simple boolean values (cache = true|false, watch = true|false).
Catches segfault when no task is ready after wait timeout.

wq_json environment variables

---

parrot/src/pfs_main.cc

Manually kill first child process if attachment fails.

---

work_queue/src/work_queue.c
work_queue/src/work_queue_protocol.h
work_queue/src/work_queue_worker.c

(Note: This hasn't been tested at all, I'm making a PR so I don't lose the code here.)
Address the performance problem of sending large directories via WQ.
The existing implementation of recursive put stinks b/c it sends every file
as a distinct transaction, forcing the worker to check for and create all
parent directories for every file.
This implementation provides a proper streaming put protocol, to go with
the streaming get protocol already in use.  Directories are sent via a stream
of data:
```
dir d
file x size mode
(data)
file y size mode
(data)
file z size mode
...
end
```
In this scheme, all file names must be simple names without paths.
Should minimize the metadata interactions that the worker has with the underlying filesystem.

WQ Recursive Put

---

work_queue/src/work_queue.c

Rationale: Although 10 seconds ought to be plenty for an epsilon-sized file,
consider what happens when streaming a large directory.  A large set of files
gets pushed over to the worker, which stuffs everything in the buffer/cache.
Suddenly, when the buffer cache is full, transfers stutter as data is pushed
to disk.  The transfer time of a single item may be affected as much by what
came before, than by its own size.
An even better solution would take into account the time to transfer everything
prior to this item.  But until we have that more sophisticated approach, this
change will make things a little more stable.

WQ: Increase the minimum file transfer time to 60 seconds.

---

work_queue/src/work_queue_graph_log

The print statements in the usage function of work_queue_graph_log was using the syntax from python2. I was able to fix it to be able to work with python3.

fix an error in the work_queue_graph_log help message (python2-3)

---

work_queue/src/work_queue_graph_log

Popen and check_output return a bytes object that needs to be converted to a string for regex matching.

fix type error (bytes) when reading gnuplot version

---

python_environments/python_package_run

- Adds debug log messages to measure the time each step takes (untaring, unpacking, command line, etc.). Activate with -d or --debug  options.
- Adds --help-env-creation which shows a recipe on how to create an environment that this script can consume. (Mainly ensure that conda and conda-pack are included.)
- Accept -- as a separator between options and command line to be executed.
- Accept a directory as a possible conda environment (as an alternative to a tar file).
This is the script used when testing pr #2290

python_package_run  time measurements

---

batch_job/src/batch_job_work_queue.c
work_queue/src/bindings/perl/Work_Queue/Task.pm
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_json.c
work_queue/src/work_queue_process.c
work_queue/src/work_queue_worker.c

I changed it to specify_enviro**n**ment_variable.  
I left the original  specify_enviroment_variable, but in the deprecated section.
The perl and python bindings had the correct spelling, so this is mostly for our internal code that uses C.

fix specify_enviroment_variable typo in wq api

---

work_queue/src/work_queue.h

Newer compilers warn about this missing declaration:
warning: ‘struct work_queue’ declared inside parameter list will not be
visible outside of this definition or declaration.

Forward declare struct work_queue.

---

work_queue/src/work_queue.c

The task information was not used anywhere. (Sometimes the task was even
NULL, and that case was never checked.)

Remove task struct from file creation and naming

---

resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c
resource_monitor/src/rmonitor_helper_comm.c

For long-running subprocesses (i.e., running for more than .25s), the
resource_monitor measures the resources one last time before the process
exits. This is not done for short-running subprocesses, as the measurement
overhead becomes noticeable (e.g., madgraph in HEP, that internally uses
make, gcc, and a series of very small python and shell scripts).
However, this distinction is only relevant for subprocesses, and not for
the very first process created by the application to be measured. A
measurement before exit is always done for this first process, as this
guarantees a measurement of any of the short-running subprocesses via
getrusage.
The previous code that labeled a process as the first process had a race
condition in which several processes may identify themselves as the root …

rmonitor: Remove race condition when detecting root process
