work_queue/src/work_queue.c
work_queue/src/work_queue_internal.h

make_cache_name called one time per file/directory

---

doc/workqueue.html
work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py

Wq blacklist bindings

---

doc/makeflow.html

Wrapper Documentation Update

---

parrot/src/pfs_channel.c

Otherwise, fallback to other channel locations.

Test if channel can be used for executable code.

---

parrot/src/irods_reli.cc

Remove stale connection from hash table.

---

configure
doc/install.html

See issue #691 
This pull request supersedes #699 
It is in it's own branch now.

Better instructions for Mac OS X Command line tools.

---

configure

Fixes #710 in just one place, [batrick's way](https://github.com/cooperative-computing-lab/cctools/issues/710#issuecomment-93493743).

on reconfigure, make clean (fixes #710)

---

parrot/src/pfs_channel.c

Use a memfd for the Parrot channel.

---

chirp/src/chirp_filesystem.c
dttools/src/link.c
dttools/src/link.h

Various cleanup of the link library.

Link cleanup

---

dttools/src/Makefile
dttools/src/cwd_disk_info.c
dttools/src/cwd_disk_info.h
work_queue/src/work_queue_worker.c

Workers disconnect when their workspace uses more disk than the specified --disk option.

Disk broken promise

---

parrot/src/irods_reli.cc

Retry iRODS cmd on intermittent errors.

---

Makefile

Add README into cctools/doc/

---

makeflow/test/makeflow_dirs_test_common.sh
run_all_tests.sh
work_queue/test/work_queue_common.sh

The test framework was not detecting failures in the tests!
Now it does. And we have a few latent failures. (To be addressed in later pulls.)

Test Framework Should Detect Failures

---

makeflow/test/TR_makeflow_021_export.sh
makeflow/test/TR_makeflow_linker_001.sh
makeflow/test/linker/001/001.mf
makeflow/test/linker/001/a.py
makeflow/test/linker/001/b.py
makeflow/test/linker/001/c.sh
work_queue/src/work_queue_process.c

Workign through failed tests revealed after test framework was fixed.

Test Repairs

---

parrot/src/pfs_main.cc
parrot/src/pfs_service_cvmfs.cc
parrot/test/TR_parrot_cvmfs_access.sh
parrot/test/TR_parrot_cvmfs_alien_cache.sh

Parrot cvmfs tests

---

work_queue/src/condor_submit_workers
work_queue/src/ec2_submit_workers
work_queue/src/pbs_submit_workers
work_queue/src/sge_submit_workers
work_queue/src/slurm_submit_workers
work_queue/src/torque_submit_workers
work_queue/src/work_queue_submit_common

Some additions to the submission scripts.
In particular, the -E flag, to directly pass arguments to a worker.

Worker flags

---

parrot/src/pfs_main.cc

fd's and cvmfs use temporary directories that are valid for a single
parrot instance. This commit creates a directory per instance that is
deleted when parrot exits. This cleans up the fd's and cvmfs
directories.

One temp directory per parrot instance.

---

apps/wq_maker/wq_maker

Update modification that allow Maker to function correctly using WQ. @dthain

Modified WQ_MAKER to support execution using MAKER-P_2.28 Atmosphere images

---

.gitattributes
chirp/src/chirp_server.c
configure
configure.tools.sh
dttools/src/assert.h
dttools/src/catalog_server.c
dttools/src/catalog_update.c
dttools/src/cctools.c
dttools/src/cctools.h
dttools/src/http_query.c
ftsh/src/ftsh.c
parrot/src/pfs_main.cc
parrot/src/pfs_service_cvmfs.cc
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Simplify and enhance release/version info.
* Make release configuration simpler.
* Include commit identifier via git commands or via `git archive`.
* Include Git branch name or release qualifier.
* Indicate if the working tree was "dirty".
* Use date of latest commit for "release date".
Example:
`./chirp/src/chirp_server version 4.6.0 [version-commit:16c8d21b] (released 2015-05-11 21:15:28 -0400)`

Version + branch/commit

---

doc/man/parrot_run.m4
parrot/src/pfs_main.cc
parrot/test/TR_parrot_cvmfs_access.sh
parrot/test/TR_parrot_cvmfs_alien_cache.sh

Do not run cvmfs tests if cvmfs is not configured.

Fix Parrot Tests

---

packaging/macports/Portfile
packaging/macports/readme.txt

This should satisfy issue #722.

Include Portfile for installing cctools with MacPorts

---

makeflow/test/example.cfg
makeflow/test/example.osx.cfg

Fix starch tests, replace hostname with uname.

Fix Starch Tests

---

weaver/src/Makefile

Use sed with percent delimiters.

Version String in Weaver

---

dttools/src/elfheader.c
parrot/src/pfs_dispatch.cc
parrot/test/TR_parrot_execve.sh

Fix static executable handling broken by #786

---

parrot/test/TR_parrot_execve.sh

Test execve of static executables.

---

doc/man/makeflow_viz.m4
dttools/src/itable.h
dttools/src/set.h
makeflow/src/dag_node.h
makeflow/src/dag_visitors.c
makeflow/src/dag_visitors.h
makeflow/src/makeflow_viz.c

Makeflow viz

---

umbrella/example/povray/README
umbrella/src/umbrella.py

Replace the usage of CWD with PWD
Adjust umbrella log

Replace the usage of CWD with PWD

---

resource_monitor/src/resource_monitor.c

Fix inotify bug. Read all messages at the end of execution.

Rmonitor fix

---

doc/man/parrot_run.m4
dttools/src/debug.c
dttools/src/debug.h
dttools/src/debug_file.c
dttools/src/stringtools.c
dttools/src/stringtools.h
parrot/src/.gitignore
parrot/src/Makefile
parrot/src/parrot_client.c
parrot/src/parrot_client.h
parrot/src/parrot_debug.c
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_main.cc
parrot/src/syscall_parrot.tbl

Add new parrot_debug syscall.

---

resource_monitor/src/.gitignore
umbrella/src/.gitignore

A couple of .gitignore additions to cleanup git status.

.gitignore: rmonitor_poll_example and umbrella_helper.html

---

apps/makeflow_blast/makeflow_blast
apps/makeflow_bwa/makeflow_bwa
apps/makeflow_gatk/makeflow_gatk
galaxy/makeflow_bwa_wrapper.py
galaxy/makeflow_bwa_wrapper.xml
galaxy/makeflow_gatk_wrapper.py
galaxy/makeflow_gatk_wrapper.xml

These were updates that modify bio-apps to a standard form. Removed hardcoded variable passing to passing the extra arguments through. @btovar

App update to standard setup

---

chirp/src/Makefile
chirp/src/chirp_acl.c
chirp/src/chirp_filesystem.c
chirp/src/chirp_fs_local_scheduler.c
chirp/src/chirp_job.c
chirp/src/chirp_server.c
chirp/src/chirp_sqlite.c
chirp/src/chirp_sqlite.h
chirp/src/chirp_ticket.c
chirp/src/confuga_job.c
chirp/src/confuga_namespace.c
chirp/src/confuga_replica.c

Pulled from my transfer-stats branch.

Misc. Chirp fixes

---

weaver/src/weaver/script.py

Follows the CCTools updated help document.

Parse -l as -o.

---

parrot/src/pfs_service_cvmfs.cc

This patch adds support for libcvmfs revision >= 18, which includes support for reading large files in several chunks on request of the corresponding byte range.  It complements a [pull request for the cvmfs code](https://github.com/cvmfs/cvmfs/pull/1003). Files that are available in multiple chunks will have a libcvmfs file descriptor with bit 30 set.  Since now read requests are channeled through `cvmfs_read`, libcvmfs can handle such file descriptors in a special way and defer the download of chunks from `cvmfs_open()` to `cvmfs_read()`.
I tested this change against the [LHC test applications](https://github.com/jblomer/parrot-test).  An example for a chunked file can be found in /cvmfs/cernvm-prod.cern.ch/cvm3/var/lib/rpm/Packages.
The changes to parrot should be backwards compatible …

Add support for chunked files available in libcvmfs revision >= 18

---

doc/man/work_queue_worker.m4
work_queue/src/work_queue_worker.c

Worker quits after --wall-time=seconds have passed.

---

doc/man/work_queue_status.m4
work_queue/src/work_queue_status.c

Solves #818.
Example:
$ work_queue_status -M 'lobster.*'
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS
lobster_lhe_v14_23 earth.crc.nd.edu       9000     425     122        3     145

-M <name> shows statistics for masters matching that name.

---

work_queue/src/work_queue.c

Clone task's env_list, cached_name, and resources measured.

---

work_queue/src/batch_job_work_queue.c
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_process.c
work_queue/src/work_queue_worker.c

Request by @khurtado, for better reporting to the CMS dashboard.

work_queue_worker export resources

---

work_queue/src/slurm_submit_workers
work_queue/src/torque_submit_workers

Small compatibility changes for XSEDE15. @btovar please checkout.

Modify slurm and torque submits for compatibility

---

umbrella/example/git_protocol/git_protocol.umbrella
umbrella/src/umbrella.py

Illustrate usage of umbrella id attr inside a umbrella specification file;	
add doc for git and root protocol support;

Illustrate usage of umbrella id attr

---

configure
parrot/src/irods_reli.cc

Compilation works (almost) out of the box! (some symlinks here and there og *.hpp need some afixin').

fixes for compilation with iRODS 4.1 from official packages

---

chirp/src/perl/Chirp/Client.pm
chirp/src/python/chirp.binding.py

chmod chirp perl/python bindings

---

dttools/src/debug_file.c

Before we used fstat to test the size of the log and then perform a rotation if
it exceeded the maximum. However, this does not handle the situation where the
log was rotated by another process. This would cause the log to be rotated
multiple times with each process working with its own log, all but one
anonymous files.
This commit performs a (racey) stat on the file path for rotation checks and
for testing whether the inode of the file has changed. If the inode has
changed, we reopen the log as it was rotated by a peer process.

Handle log rotations for multiprocess debugging.

---

work_queue/src/batch_job_cluster.c

add #$ -S /bin/bash to sge.wrapper file

To add a SGE compatibility code line

---

doc/makeflow.html
doc/man/makeflow.m4

Makeflow Docker Docs

---

work_queue/src/work_queue.c
work_queue/src/work_queue_pool.c

use system mask for group permissions

---

work_queue/src/work_queue.c

Use enums for task_state arguments, and print a string describing the state.

Task state better debug

---

work_queue/src/work_queue.c

remove > comparison for message status

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_table.cc

Fixes /proc/self/exe returning cache path.

---

parrot/src/pfs_service_cvmfs.cc

Fixes #921.
This example now works:
parrot_run -dall -odebonlyparrot --cvmfs-repo-switching -M/etc/localtime=/cvmfs/cernvm-prod.cern.ch/cvm3/usr/share/zoneinfo/posix/GMT /cvmfs/cernvm-prod.cern.ch/cvm3/usr/bin/unzip /cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar
@jblomer, could you confirm this commit does the trick?

change cvmfs_active_filesystem as fds need it

---

configure

@hmeng-19, can you give this one a go?
Fix proposal for #925

check for python and python_dev separately

---

allpairs/src/allpairs_master.c
doc/man/allpairs_master.m4
doc/man/makeflow.m4
doc/man/wavefront_master.m4
makeflow/src/makeflow.c
wavefront/src/wavefront_master.c
work_queue/src/batch_job_work_queue.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

Due to difference in internal/external Stampede IPs we want to allow for using the hostname that can be resolved correctly from either location. @btovar Please take a look, particularly in Makeflow where I pass as I'm not positive this is the cleanest way to pass this.

First pass at using hostname

---

parrot/src/pfs_main.cc

We perform wait4 until there are no tracees left to wait for.  Previously, we
would wait for a process, handle the event, then repeat.  This caused problems
with Java where threads would get stuck in a race condition with
sched_yield/futex.
The reason I discovered this solution is due to strace(1). I've long wondered
why it chooses to wait for all tracees before processing events (you can see
this if you strace strace).  After again seeing the sched_yield infinite loop
again in #927, I recalled this peculiarity and decided to give the strace
approach a try.  It apparently fixes the problem. I couldn't find any
documentation on why strace does this.
Fixes #43.
Fixes #505.

Wait for all tracees before processing events.

---

dttools/src/path.c
dttools/src/path.h
dttools/src/rmonitor.c

Looks for resource_monitor in PATH.
Adds path_which, that acts like the which command.

Find resource_monitor in PATH.

---

work_queue/src/work_queue_pool.c

Ensure we read config file from symlink

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

read persona without options

---

work_queue/src/work_queue_pool.c

avoid wq pool segfault when catalog is not available

---

doc/man/resource_monitor.m4
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.h

update to resources api doc

---

work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Retry a task a maximum number of times

---

work_queue/src/work_queue_pool.c

Based on experiences of @annawoodard.

Better path handling for wq pool conf file.

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h

Blacklist slow workers with a timeout.
Per #975.

blacklist slow workers with a timeout

---

work_queue/src/work_queue.c

wq monitoring_file, use umask as given by the user

---

resource_monitor/src/resource_monitor.c

Adds a field to display the monitor version used, as:
monitor_version:          6.0.0.e51ad7ff

add monitor version to summary

---

work_queue/src/work_queue_worker.c

print local address/port in worker's log

---

work_queue/src/work_queue.c
work_queue/src/work_queue_internal.h
work_queue/src/work_queue_worker.c

Worker exit vs release

---

parrot/test/TR_parrot_search.sh
parrot/test/TR_parrot_search_chirp.sh
parrot/test/fixtures/.__acl
parrot/test/fixtures/a/.__acl
parrot/test/fixtures/a/b/.__acl
parrot/test/fixtures/a/b/c/.__acl

create search fixtures manually

---

work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.h

explain difference between cmd_time and total_cmd_time

---

work_queue/src/work_queue.c

As requested by @matz-e to save earth.

compress series and debug monitoring logs in work queue

---

work_queue/src/work_queue.c
work_queue/src/work_queue_protocol.h

Refactor inuse/committed stats.
Increment protocol counter, as workers do not send inuse/committed information anymore.

Wq report committed

---

chirp/src/Makefile
chirp/src/confuga_file.c
chirp/src/confuga_fs.h
chirp/src/confuga_job.c
chirp/src/confuga_namespace.c
chirp/src/confuga_replica.c

Refactors some common file handling into a module.

Add Confuga file module.

---

dttools/src/random.c

The code copying to the array was completely wrong.

Fix assertion failure.

---

chirp/src/chirp_client.c
dttools/src/auth.c
dttools/src/auth_address.c
dttools/src/auth_globus.c
dttools/src/auth_hostname.c
dttools/src/auth_kerberos.c
dttools/src/auth_ticket.c
dttools/src/auth_unix.c
dttools/src/md5.h
dttools/src/shell.c
dttools/src/shell.h
work_queue/src/work_queue.c

I've used these changes for all of my experiments with Confuga for the CCPE paper. So the changes have received quite a bit of testing.

Catch transient authentication failures

---

chirp/tools/workflows/bench-tests
chirp/tools/workflows/confuga-blast
chirp/tools/workflows/confuga-load
chirp/tools/workflows/pull-tests
chirp/tools/workflows/pull-tests-narrow
chirp/tools/workflows/pull-tests-narrow.py
chirp/tools/workflows/pull-tests.py
chirp/tools/workflows/scheduler-tests
chirp/tools/workflows/test-common.bash

Updated workflows from Confuga CCPE branch.

Confuga workflow update

---

dttools/src/auth_ticket.c

This was causing a significant slowdown as openssl would stat files in AFS that
it could not access.
@dthain: this is what caused the ~5 second turnaround time for push transfers in some of the Confuga experiments.

Prevent openssl from opening files in $HOME.

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_process.cc
parrot/src/pfs_process.h
parrot/test/TR_parrot_fake_setuid.sh

Implement getgroups/setgroups for --fake-setuid

---

umbrella/example/povray/README
umbrella/example/povray/povray_S_local+osf.umbrella
umbrella/example/povray/povray_S_local.umbrella
umbrella/example/povray/povray_S_osf.umbrella
umbrella/src/umbrella.py

umbrella communicates with OSF
1) Upload the dependencies of one umbrella spec to OSF, and create
a new umbrella spec with data dependencies from OSF; Upload this
new umbrella spec to OSF
2) Support dependencies from OSF during runtime

umbrella communicates with OSF

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_amazon.c
batch_job/src/batch_job_chirp.c
batch_job/src/batch_job_cluster.c
batch_job/src/batch_job_condor.c
batch_job/src/batch_job_internal.h
batch_job/src/batch_job_local.c
batch_job/src/batch_job_work_queue.c
batch_job/src/work_queue_factory.c
doc/man/work_queue_factory.m4
makeflow/src/makeflow.c
wavefront/src/wavefront.c
work_queue/src/condor_submit_workers
work_queue/src/work_queue.c
work_queue/src/work_queue_internal.h

 Wq factory autosize

---

dttools/src/macros.h
dttools/src/rmonitor_poll.c
dttools/src/rmonitor_poll.h
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_poll_example.c
work_queue/src/work_queue.c

consider rusage for max.
Fix memory leaks.

Rmonitor two minor enhacements

---

work_queue/src/work_queue.c

If no output directory is given for enable_monitoring,  t->resources_measured is still filled, but the summary file is discarded.

Monitor in wq without keeping summaries.

---

dttools/src/path.c
resource_monitor/src/resource_monitor.c

Add exec to open

---

parrot/src/pfs_mmap.h
parrot/src/pfs_sys.cc
parrot/src/pfs_sys.h
parrot/src/pfs_table.cc
parrot/src/pfs_table.h
parrot/test/TR_parrot_mmap.sh

Fix segfault in Parrot's mmap splitting

---

batch_job/src/work_queue_factory.c
doc/man/work_queue_factory.m4

Made it so that when there are no masters in the work queue pool after a given amount of time work_queue will timeout.

Work Queue Pool Timeout

---

dttools/src/disk_alloc.c
dttools/src/disk_alloc.h
dttools/src/disk_alloc_test.c
dttools/src/disk_allocator.c
work_queue/src/work_queue_process.c

Adds filesystem argument to disk_alloc_create so the fs is no longer hard coded into the function

disk_alloc_create filesystem argument

---

umbrella/example/povray/README
umbrella/example/povray/povray_base_local.umbrella
umbrella/src/umbrella.py

umbrella build <source.umbrella> <dest.umbrella>
Build behavoir calculates the metadata info of each dependency:
id, checksum, size, uncompressed_size.

Add umbrella build behavior

---

parrot/src/pfs_dir.cc
parrot/src/pfs_service_local.cc
parrot/test/TR_parrot_dir.sh

This is a partial fix for #1104 expedited for Rodney Walker's work. @trshaffer is working on the complete fix.

Open local directories without O_DIRECTORY

---

doc/umbrella.html
umbrella/example/cms_complex/README
umbrella/example/cms_complex/cms_complex_S.umbrella
umbrella/example/cms_complex/cms_complex_S_osf.umbrella
umbrella/example/cms_complex/cms_complex_S_s3.umbrella
umbrella/example/povray/README
umbrella/example/povray/povray_S_local+osf.umbrella
umbrella/example/povray/povray_S_osf.umbrella
umbrella/src/umbrella.py

Add s3 umbrella spec for cms_complex app
Put osf auth info into umbrella options  
Ignore resources from cvmfs when umbrella uploads to OSF/s3

  Add s3 umbrella spec for cms_complex app

---

makeflow/src/makeflow_gc.c

Update for #1116 @btovar Take a look and make sure this resolves the issue.

Do not clean inputs

---

makeflow/example/example.makeflow

@nhazekam: I changed the makeflow example by adding categories and required inputs. See #1116 before merging.

better comment mf example, added categories

---

doc/man/disk_allocator.m4
dttools/src/disk_allocator.c

disk_alloc help messages

---

umbrella/src/umbrella.py

Reformat the help docs for umbrella behaviors
Print the stdout and stderr of Umbrella user cmd to the terminal

Umbrella output + help docs

---

umbrella/src/umbrella.py

Update the Umbrella uploading mechanisms to OSF/s3: If the dependency already has an url from osf/s3, do not re-upload it.

Umbrella avoids duplicate uploading/downloading

---

dttools/src/rmonitor_types.h
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmon_tools.c
resource_monitor/src/rmon_tools.h
resource_monitor/src/rmonitor_helper.c
resource_monitor/src/rmonitor_helper_comm.c
resource_monitor/src/rmonitor_helper_comm.h
work_queue/src/perl/Work_Queue/Task.pm
work_queue/src/python/work_queue.binding.py

Example:
./resource_monitor -Omon --sh "curl www.google.com > /dev/null"
...
"bytes_received":    [20259,"B"],
"bytes_sent":    [169,"B"],
...

add network support to the resource_monitor

---

resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_helper.c

Improve exiting processes waiting times.
Change command line to seconds.
Reduce bw noisy measurements.

Rm small fixes

---

chirp/src/chirp_fs_hdfs.c

libhdfs crashes if you call unlink(x) and x does not exist.
"rmall" needs to go through do_unlink to check for errors first.

Fix Chirp HDFS Crash on rmall

---

makeflow/src/lexer.c
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/src/parser.c

@nhazekam: I've noticed some memory leaks in pr #1133. This pr cleans some. Please fix the rest of the memory leaks after this pr is merged.

fix parser/lexer memory leaks

---

README

Fix PATH setting in cctools README

Fix PATH setting in cctools README

---

batch_job/src/batch_job_condor.c
batch_job/src/work_queue_factory.c
batch_job/src/work_queue_factory.conf.example
doc/man/work_queue_factory.m4
dttools/src/Makefile

@charleszheng44: I made some changes, please review.
Supersedes #1123.

Charleszheng44 wq factory condor

---

batch_job/src/work_queue_factory.c
chirp/src/python/chirp.binding.py
doc/man/work_queue_factory.m4
dttools/src/category.c
dttools/src/category.h
dttools/src/jx_print.c
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/Makefile
resource_monitor/src/resource_monitor_cluster.c
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c
resource_monitor/src/rmon_tools.h
work_queue/src/work_queue.c

Small bug fixes to the resource_monitor_histograms tool.

Histograms for loop paper

---

makeflow/example/example.makeflow

Add resources to makeflow example

---

doc/umbrella.html
umbrella/example/povray/README
umbrella/src/umbrella.py

Update umbrella.html
Umbrella build ignores remote deps, only cares about local deps
Change the args layout of umbrella build

Umbrella track behavior

---

makeflow/example/example.categories.makeflow
makeflow/example/example.makeflow

Makeflow example simple

---

batch_job/src/batch_job_work_queue.c
makeflow/src/dag_resources.h
makeflow/src/makeflow.c
work_queue/src/work_queue.c

Send stats per category from work queue to the catalog.
Also, pass resources per category from makeflow to work queue (and then to the catalog).

Wq categories to catalog

---

chirp/src/chirp_client.c

Commit a303060 missed the chirp client code.

Prevent openssl from opening ~/.rand.

---

dttools/src/jx.c

Check for NULL item/pair equality.

---

resource_monitor/src/resource_monitor_histograms.c

Charleszheng44 add min count var gnuplot

---

dttools/src/category.c
dttools/src/category.h
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c

Do not assume independence between resource peaks and wall time.

Treat peak and wall time as dependent variables 

---

dttools/src/category.c
dttools/src/category_internal.h
resource_monitor/src/resource_monitor_histograms.c

Generate a table with allocations and expected wasted resources.

Allocation wasted resources

---

doc/makeflow.html

Docs for MAKEFLOW Keyword

---

resource_monitor/src/Makefile
resource_monitor/src/resource_monitor_cluster.c
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c

Minor rm errors

---

run_all_tests.sh

@trshaffer, does this solve your issue?

add monitor to PATH for tests

---

doc/makeflow.html

Saw a paragraph repeated while reading Makeflow docs

Remove repeated paragraph from Makeflow documentation

---

resource_monitor/src/rmonitor_helper_comm.c

Per an issue that @nkremerh found.

prepend library to LD_PRELOAD

---

resource_monitor/src/resource_monitor_histograms.c

Print number of retries to the stats.

write number of tasks retried

---

makeflow/src/makeflow.c

Fixes #1209 
@dthain @btovar please review.

Fixes Makeflow consistency check error reporting

---

makeflow/src/dag_visitors.c
makeflow/src/makeflow.c

This is still an unholy bit of code, and we should find a more general solution.

Fix broken cast in dag_visitors

---

doc/parrot.html

Remove reference to ancient known bugs page.

Update Parrot Manual

---

dttools/src/Makefile
dttools/src/jx_count_obj_test.c
dttools/test/TR_jx_count.sh

test example to count jx objects

---

dttools/src/category.c
dttools/src/category.h
dttools/src/rmonitor_types.h
resource_monitor/src/resource_monitor.c
work_queue/src/work_queue.c

Several small fixes from lobster.

Lobster fixes

---

dttools/src/category.c
work_queue/src/work_queue.c

use AUTO_MAX on any resource exhaustion

---

resource_monitor/src/Makefile
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/rmon_tools.c
resource_monitor/src/rmon_tools.h

Adds stats considering precise resource usage knowledge.

Seer perfect info

---

dttools/src/jx_parse.c

read doubles with e,E notation

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_amazon.c
batch_job/src/batch_job_chirp.c
batch_job/src/batch_job_cluster.c
batch_job/src/batch_job_condor.c
batch_job/src/batch_job_dryrun.c
batch_job/src/batch_job_internal.h
batch_job/src/batch_job_local.c
batch_job/src/batch_job_work_queue.c
dttools/src/category.c
dttools/src/category.h
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/dag_visitors.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/parser.c
work_queue/src/work_queue.c
work_queue/src/work_queue_internal.h

Use the logic of work queue for retrying tasks in makeflow.
@nkremerh: This should solve your issue. Please test comprehensively, even without resources.

Makeflow send resources

---

dttools/src/rmsummary.c
work_queue/src/work_queue.c

Wq long command

---

work_queue/src/work_queue_process.c

unset problematic environment variables

---

chirp/src/confuga_job.c
chirp/src/confuga_replica.c

Instead of attempting to create transfer jobs for each scheduled job (SCHEDULED
-> REPLICATED), the scheduler now looks at all scheduled jobs when creating new
transfer jobs.

Simplify and optimize TJ scheduling.

---

dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor.c

Print rmsummary to buffer.
Simplify exit_type logic.

rmsummary monitor misc fixes

---

chirp/src/confuga_job.c

Check for jobs scheduled on lost storage nodes.

---

work_queue/src/work_queue_worker.c
work_queue/test/work_queue_common.sh

Mainly, do not disconnect after a forsake, as we already check for disconnection conditions somewhere else, and marked the task appropriately.

Forsake if total changed fixes

---

allpairs/test/TR_allpairs_bitwise.sh
allpairs/test/TR_allpairs_composite.sh
dttools/src/path_disk_size_info.c
dttools/test/test_runner_common.sh
sand/src/sand_filter_master.c
work_queue/src/work_queue_worker.c

Tests should not timeout any longer.
Also, fix for #1301

Allpairs test fix

---

dttools/src/catalog_query.c
dttools/src/catalog_query.h

For #1313
Since the previous PR was refactoring anyway, this should be a very small change

Switch to comma-delimited catalog host list

---

batch_job/src/batch_job_work_queue.c
dttools/src/category.c
dttools/src/category.h
dttools/src/macros.h
dttools/src/rmsummary.h
makeflow/src/dag_node.c
makeflow/src/dag_visitors.c
makeflow/src/makeflow.c
makeflow/src/parser.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_resources.c
work_queue/src/work_queue_resources.h
work_queue/src/work_queue_status.c

First part of #1269.
Account tasks by the boxes the workers create for them.

Wq by boxes

---

work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_test_main.c

Part 3 of #1269.
First commit is:
Add tasks transactions log. 			1523bfa

Wq transactions log

---

chirp/src/confuga_replica.c

Otherwise the transaction will fail due to foreign key constraints.
Also, improve debug output.

Delete TransferJob referencing deleted File.

---

dttools/src/random.c
work_queue/src/work_queue_test_main.c
work_queue/src/work_queue_worker.c

These are a set of fixes that allow the `work_queue_worker` to run successfully on the Raspberry Pi.
Thanks to @adingler for reporting these issues.

Raspberry Pi Fixes

---

work_queue/src/work_queue_process.c
work_queue/src/work_queue_process.h
work_queue/src/work_queue_worker.c

Worker tempdir

---

chirp/src/chirp_filesystem.h
chirp/src/chirp_fs_chirp.c
chirp/src/chirp_fs_confuga.c
chirp/src/chirp_fs_hdfs.c
chirp/src/chirp_fs_local.c
chirp/src/chirp_server.c
chirp/src/chirp_sqlite.c
chirp/src/chirp_sqlite.h
chirp/src/confuga.c
chirp/src/confuga.h
configure
dttools/src/Makefile
dttools/src/buffer.c
dttools/src/dpopen.c
dttools/src/uuid.c
dttools/src/uuid.h
parrot/src/parrot_cp.c
parrot/src/parrot_mount.c
parrot/src/pfs_service_xrootd.cc
work_queue/src/work_queue_example.c
work_queue/src/work_queue_priority_test.c

This is a prereq for #1324, #1325, and #1326.

Create UUID for Chirp server to send to Catalog.

---

sand/src/Makefile
sand/test/TR_sanity.sh

Sometimes sand_align_master was still running after the test script finished.

cleanup sand test

---

makeflow/src/dag_node.c
makeflow/src/parser.c

Solve issue #1165, set OMP_NUM_THREADS = 1 and export it as an environment variable.

resolve #1165

---

doc/man/makeflow.m4
dttools/src/rmsummary.c
dttools/src/rmsummary.h
makeflow/src/dag.c
makeflow/src/dag.h
makeflow/src/dag_resources.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c

 Allocation makeflow fixes

---

batch_job/src/batch_job_work_queue.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_worker.c

@dthain, as discussed. Let me know if this looks ok before I add the time stats measurements.

Changes to wq wait loop to autoregulate capacity

---

batch_job/src/batch_job.c
batch_job/src/batch_job_condor.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/makeflow_wrapper_monitor.h

Reverts cooperative-computing-lab/cctools#1373.
Sorry, merged by mistake.

Revert "Resource Monitor file directories in Condor"

---

dttools/src/catalog_query.c

Fix JX test in catalog_query_read

---

batch_job/src/work_queue_factory.c

This helps with two issues:
- A master may have reach its capacity, and new workers do not have a
chance to connect to it anyway.
- A worker job may be idle (e.g., condor) or in the queue (e.g., sge),
and submitting new workers is counterproductive. In particular,
consider a master that does not have many tasks to run anymore. As old
workers time-out, the condor idle jobs start to run and connect to the
master. They are never given tasks, and in turn time out, which is a
waste of resources.

Do not submit new workers until old workers connect.

---

dttools/src/set.c
dttools/src/set.h

Enhancement to sets to allow for duplicating and inserting sets and lists.

Add ability to add lists and sets to sets, also set duplicate

---

batch_job/src/batch_job.h
batch_job/src/batch_job_work_queue.c
dttools/src/Makefile
dttools/src/libforce_halt_enospc.c
makeflow/src/makeflow.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_process.c
work_queue/src/work_queue_protocol.h
work_queue/src/work_queue_worker.c

Adds Makeflow & Work Queue recognizing loop device being full

---

batch_job/src/batch_job.h
batch_job/src/batch_job_work_queue.c
makeflow/src/makeflow.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_process.c
work_queue/src/work_queue_worker.c

@nkremerh please review (and test).

disk loop allocation cleanup

---

Makefile
batch_job/src/Makefile
configure
dttools/src/Makefile
resource_monitor/src/Makefile
wavefront/src/Makefile
work_queue/src/Makefile
work_queue/src/perl/Makefile

Remove all *.o when doing make clean.
configure --with-*-path no    sets    config_*_path=no      correctly

Configure make fixes

---

parrot/src/pfs_table.cc

Add Parrot Debug on Failure

---

batch_job/src/batch_job.c
batch_job/src/batch_job_condor.c
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_monitor.c
makeflow/src/makeflow_wrapper_monitor.h

@btovar This is attempt 2 take a look and let me know what you think. #1364

Flatten resource monitor output in Condor

---

doc/index.html
doc/man/catalog_update.m4
dttools/src/catalog_update.c

Now custom fields will override standard fields.

catalog_update: fix bug in duplicate fields

---

work_queue/src/work_queue.c

remove leaked static variables

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

Only check cone flags on a real clone, not on fork.

Fix Parrot Clone Bug

---

dttools/src/Makefile
dttools/src/histogram.c
dttools/src/histogram.h
dttools/src/histogram_test.c
dttools/test/TR_histogram.sh

Factor out the histogram code from category.c into its own data structure.
I still need to change category.c and resource_monitor_histograms.c

Histogram data structure

---

batch_job/src/work_queue_factory.c
doc/man/work_queue_factory.m4

adds -B (batch-options) to work_queue_factory

---

umbrella/src/Makefile

check the existence of `pydoc` before using it

Fix umbrella Makefile

---

umbrella/example/makeflow/README
umbrella/example/makeflow/example.makeflow
umbrella/example/makeflow/makeflow_S.umbrella

This PR creates an Umbrella spec for an easy makeflow, the image conversion one.

Add umbrella spec for an easy makeflow

---

work_queue/src/work_queue.c

wq: accumulate to category only when resources summaries are meaningful

---

umbrella/src/umbrella.py

As #1320 pointed out, it is expected that an umbrella user may want to obtain extra outputs which are not specified in the `output` section of an Umbrella spec.
This PR extends the format of the `--output` option of umbrella to accept two styles of settings: 
the 1st one is `<container_path>=<local_path>`;
the 2nd one is `<container_path>=<local_path>:<file_type>` (file_type can be `f` for files or `d` for dirs).
(Of course, the users have freedom to mix these two styles if they like.)
When the first style is used, we treat it as we currently do;
When the second style is used, we will not check the output section of the umbrella spec, because the user already tells us the file type.

Allow the umbrella users to specify output types

---

work_queue/src/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Fix cache names in wq

---

dttools/src/category.c

Mean time computation was incorrect.

First allocation fixes.

---

doc/man/resource_monitor_histograms.m4
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/resource_monitor_tools.c
resource_monitor/src/resource_monitor_tools.h

Cleanup histogram visualization

Histograms fixes for release

---

batch_job/src/work_queue_factory.c

flush stdout of wq_factory

---

work_queue/src/work_queue.c
work_queue/src/work_queue_graph_log

As reported by @matz-e. Some fields (e.g., time_status_msgs) where not copied to the results structure.

do a memcpy rather than copy fields one by one

---

work_queue/src/work_queue.c
work_queue/src/work_queue_graph_log

Adds stack graph to show time master utilization.
Cleans up capacity computation. (Nate, please check it is still correct. I do not think we wanted to weight the difference, but the total.)

Wq graph fixes

---

doc/makeflow.html
doc/man/makeflow.m4
dttools/src/path.c
dttools/src/path.h
makeflow/example/makeflow_umbrella/README
makeflow/example/makeflow_umbrella/convert_S.umbrella
makeflow/example/makeflow_umbrella/example.makeflow
makeflow/src/Makefile
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_umbrella.c
makeflow/src/makeflow_wrapper_umbrella.h
umbrella/example/makeflow/convert_S.umbrella

Add `--umbrella-spec` and `--umbrella-binary` option into makeflow
Add `dag_node->umbrella_spec` to track the umbrella spec needed for each rule
Add `makeflow_wrapper_umbrella` model

Run each makeflow rule as an Umbrella job

---

resource_monitor/src/Makefile

Fixes linker command line ordering for the resource_monitor

fix for ubuntu compilation

---

batch_job/src/batch_job.c
batch_job/src/batch_job_work_queue.c
makeflow/src/makeflow.c

Clean wq transactions log with makeflow.

---

dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/resource_monitor_tools.c

Compute histograms with fractions of cores for dvdt journal paper.

add resolution to cores in histograms

---

doc/makeflow.html
doc/man/makeflow.m4
makeflow/example/makeflow_umbrella/README
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_umbrella.c
makeflow/src/makeflow_wrapper_umbrella.h

Add umbrella logfiles into makeflow log file
Add umbrella-log-prefix opt
Fix umbrella wrapper

Handle umbrella logfiles elegantly in makeflow

---

batch_job/src/Makefile
batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_blue_waters.c
doc/man/makeflow.m4
doc/man/work_queue_factory.m4
makeflow/src/makeflow.c

Incorporates Blue Waters into current version. @btovar @dthain

Added Blue Waters support

---

dttools/src/Makefile
dttools/src/category.c
dttools/src/category.h
dttools/src/histogram.c
dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/Makefile
resource_monitor/src/resource_monitor_histograms.c
resource_monitor/src/resource_monitor_tools.c
work_queue/src/work_queue_graph_log

Misc additions for dvdt paper: cores_avg, add max to webpage report, etc.

Histograms json structure

---

batch_job/src/work_queue_factory.c

Treating it as a double did not make much sense anyway.

tasks per worker in factory as an integer

---

batch_job/src/work_queue_factory.c
dttools/src/jx_parse.c
work_queue/src/work_queue.c

Fix blacklisted workers

---

resource_monitor/src/resource_monitor.c

When the monitor detects the file .cctools_resource_monitor_debug, it
starts to write debug information to .cctools_resource_monitor_debug.log
Removing .cctools_resource_monitor_debug stops the debug output.
The monitor checks for .cctools_resource_monitor_debug every 30 s.
Use case:
In lobster, some ill-behaved tasks are sometimes manually detected, and
the resource_monitor debug output would be useful to fix them. However,
the monitor debug output would be too big if active for all tasks.

Activate monitor debug file during runtime.

---

doc/makeflow.html
doc/man/makeflow.m4
makeflow/src/Makefile
makeflow/src/dag.h
makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper.h
makeflow/src/makeflow_wrapper_docker.c
makeflow/src/makeflow_wrapper_docker.h
makeflow/src/makeflow_wrapper_singularity.c
makeflow/src/makeflow_wrapper_singularity.h

Added the ability to wrap tasks in singularity.

Singularity Support in Makeflow

---

batch_job/src/work_queue_factory.c
dttools/src/rmsummary.c
dttools/src/rmsummary.h
work_queue/src/work_queue.c

@nkremerh: please take a look. I removed the alpha computations from the factory, as they will be done from the master (and we did not get the correct info anyway).

Total task info to catalog

---

chirp/src/chirp_server.c

Chirp Server: Close socket after fork.

---

umbrella/src/umbrella.py

Use `-m` and `-l` instead of env variables to set options of parrot

Use parrot_namespace to allow parrot-in-parrot

---

umbrella/src/umbrella.py

This PR adds the support for relative mountpoint in umbrella data section. These mounpoints will be relative to the CWD.
This makes it possible to put the data dependencies specified in Umbrella data sections and the dynamic data deps created by makeflow (i.e., intermediate data) into the same directory.
Reason:
The intermediate data involved in a makeflow are difficult to specified in a static umbrella spec, and sometimes the application logic requires these intermediate data and the input deps exist under the same dir.

Support relative mountpoint in umbrella data section

---

makeflow/src/makeflow_status.c

Make headers consistent with work_queue_status and fit in 80 cols.

Makeflow Status Headers

---

makeflow/example/example.categories.makeflow
makeflow/src/parser.c
makeflow/test/syntax/directives.makeflow
makeflow/test/syntax/directives_bad_value.makeflow
makeflow/test/syntax/directives_unsupported.makeflow

@charleszheng44:
Use:
.MAKEFLOW CATEGORY default
.MAKEFLOW MODE MIN_WASTE

re-establish MODE (accidentally removed by UMBRELLA)

---

makeflow/src/makeflow_wrapper_umbrella.c

Reverts cooperative-computing-lab/cctools#1544

Revert "Allow --umbrella-spec option and LOCAL tag used together"

---

makeflow/src/makeflow.c
makeflow/src/makeflow_wrapper_umbrella.c
makeflow/src/makeflow_wrapper_umbrella.h

This fixes the problem pointed out at #1544 again.

Allow --umbrella-spec option and LOCAL tag used together (New)

---

dttools/src/rmonitor_poll.c
resource_monitor/src/resource_monitor.c

cores avg was not being updated in the monitoring polling library.

update cores_avg in monitor

---

doc/man/work_queue_status.m4
work_queue/src/work_queue_status.c

Implements #1568 
@dthain Please let me know how this first pass looks.

Adds capacity to Work Queue Status

---

work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py

add blacklist with timeouts to python and perl

---

batch_job/src/work_queue_factory.c
work_queue/src/work_queue_worker.c

Addresses #1504 
Adds -H and -p options for master host and master port respectively
Removes project/foreman name regex from function arguments

Allow specification of master host and master port in Work Queue Factory

---

doc/index.html

Add viewport meta tag to fix display on tablets/handhelds.

Fix Doc Index Display

---

parrot/src/pfs_main.cc

As a follow-up from #1591, I added a nicer warning message if `ptrace` appears to be disabled. This should give users some pointers rather than just looking like Parrot is broken

Add helpful warning if ptrace attach fails with EPERM

---

work_queue/src/work_queue.c

As reported by Sunimal Rathnayake, sand_filter_master was not making any progress with certain inputs.
The cause was a loop created by a combination of constitutive calls of work_queue_hungry, without a call to work_queue_wait.  In the ramp-up, work_queue_hungry always returned 100, and without calling work_queue_wait, the queue never exited the ramp-up stage.
This commit makes it so that the queue exits the ramp-up stage after 100 tasks are already waiting, and avoids infinite loops when using work_queue_hungry.

ramp-up of work_queue_hungry depends on ready tasks

---

parrot/src/parrot_package_create.c

Currently, `parrot_package_create` does not keep the file size info when the copy degree of a file is metadata-level copy, because using `truncate` system call on an empty file on AFS results in the `st_blocks` field becomes non-zero, which makes it difficult to determine whether a file is really empty or not. 
This PR is an attempt to keep the file size information. This may cause some applications involving AFS file accesses to break.

Parrot Packaging: Detect File Size

---

dttools/src/catalog_query.c
dttools/src/path_disk_size_info.c
work_queue/src/work_queue_worker.c

@charleszheng44: I think this should fix your issues.

Fix segfault hostnames

---

umbrella/src/umbrella.py

Umbrella uses `subprocess.Popen` to run shell commands. Currently, Umbrella directly runs the commands without checking the existence of these shell executables.
This PR first checks the existence of executables before running a command.

Check the existence of executables in Umbrella

---

umbrella/src/umbrella.py

This option allows the user to specify a parrot_run from the local
filesystem, which is useful when cctools does not provide binaries
for the OS of the host machine.

Add --parrot_path option to umbrella

---

batch_job/src/Makefile
batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_mesos.c
batch_job/src/mesos_task.c
batch_job/src/mesos_task.h
batch_job/src/work_queue_factory.c
doc/makeflow.html
doc/man/makeflow.m4
doc/man/work_queue_factory.m4
dttools/src/text_list.c
dttools/src/text_list.h
makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/mf-mesos-executor
makeflow/src/mf_mesos_executor
makeflow/src/mf_mesos_scheduler
makeflow/src/mf_mesos_setting
resource_monitor/src/resource_monitor_histograms.c

This PR is for mesos mode, which rebased the latest master branch.

Makeflow Mesos Support

---

apps/wq_maker/wq_maker

Update to print stats and properly set resources. This requires Error.pm and Error/Simple.pm, both of which are included with MAKER. However, the user needs to add it PERL5LIB path.

Maker stats

---

batch_job/src/batch_job_mesos.c

1. Change `getline` to `fgets`
2. Change "`debug(D_BATCH, ...); return 1;` to `fatal(...);`"
fix issue #1649

Change getline->fgets for portability.

---

dttools/src/text_array.c
makeflow/src/makeflow.c
makeflow/src/makeflow_log.c
makeflow/src/makeflow_log.h
makeflow/src/makeflow_wrapper.h
makeflow/src/makeflow_wrapper_enforcement.c

Doing some general code cleanup to facilitate the next developments in Makeflow...
(Don't merge, more is coming.)

Makeflow Cleanup

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_process.cc
parrot/test/TR_parrot_noop_setuid.sh

This addresses #1657 
I also refactored some of the id change code, which was duplicated and all over the place

Parrot Setuid No-Ops

---

work_queue/src/work_queue_graph_log

check gnuplot version in work_queue_graph_log

---

dttools/src/rmsummary.c
dttools/src/rmsummary.h
resource_monitor/src/resource_monitor_histograms.c

Histogram fix for paper

---

makeflow/src/Makefile
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/makeflow.c
makeflow/src/makeflow_local_resources.c
makeflow/src/makeflow_local_resources.h

Extends #1697. It should work now.

Makeflow Local Resources Take #2

---

makeflow/src/lexer.c
makeflow/test/TR_makeflow_020_syntax_command_comment.sh
makeflow/test/syntax/command_comment.makeflow

correctly advance lexer on quoted comment sign

---

work_queue/src/work_queue.c

indicate in transactions log why worker was removed

---

work_queue/src/work_queue_status.c

Fixes expression to fit new JX syntax

---

batch_job/src/batch_job_amazon.c
batch_job/src/work_queue_factory.c
doc/makeflow.html
makeflow/src/makeflow.c

Add support for remote file renaming to -T amazon.

Makeflow Amazon Remote Renaming

---

batch_job/src/work_queue_factory.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_graph_log

@btovar Code was overhauled after a lengthy rebase, please take a look.

Adds Work Queue capacity calculation

---

doc/makeflow.html

Updated the monitoring example code to show how to run the monitoring tools simultaneously with the file. I also added a few links and fixed some typos.

Fixed Makeflow doc

---

doc/makeflow.html
doc/man/makeflow.m4
makeflow/src/makeflow.c
makeflow/test/TR_makeflow_030_gc_ref_count.sh

Addressed #1670  reintroduces garbage collection options to the help message.

Updated makeflow options to include GC

---

dttools/src/catalog_server.c

Partially addresses #1732. @nhazekam you will need to test with your half of the solution.

Catalog Server Accepts Compressed Updates

---

doc/catalog.html
dttools/src/catalog_query.c

Compresses data for catalog updates using zlib.

Catalog Client Sends Compressed Updates

---

work_queue/src/perl/Makefile
work_queue/src/python/Makefile

Fix for #1745 
@pivie, @nhazekam  can you corroborate it works for you?

add -lz to swig bingings

---

doc/install.html

fix install page version

---

work_queue/src/work_queue.c
work_queue/src/work_queue_status.c

fix work_queue_status -R with direct query.

---

dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/test/jx.expected
dttools/test/jx.input

Adding the join function to JX which operates like the join function in Python where a list of strings can be combined into a single string with a delimiter if it is specified.

adding join function

---

makeflow/src/makeflow_monitor

reset "finished" on new STARTED

---

batch_job/src/work_queue_factory.c

add --catalog to wq_factory

---

batch_job/src/work_queue_factory.c

Addresses #1729.
@btovar @dthain Thoughts?

Adds environment variable passing option for batch_job_submit

---

dttools/src/Makefile

Remove jx2json from SOURCES

---

doc/prune.html
prune/examples/census/compare_surnames.py
prune/examples/census/compare_word
prune/examples/census/count_sum
prune/examples/census/dups
prune/examples/census/match_people.py
prune/examples/census/matches
prune/examples/hep/hep.py
prune/examples/hep/hep.wq.py
prune/examples/merge_sort/merge_sort.py
prune/src/prune/client.py
prune/src/prune/db_sqlite.py
prune/src/prune/glob.py
prune/src/prune/master_local.py
prune/src/prune/master_wq.py
prune/src/prune/timer.py
prune/src/prune/utils.py
prune/src/prune/worker.py
prune/src/prune/worker_local.py
prune/src/prune/worker_wq.py

Allow specification (in workflow) of base directory for prune files
Parameterize CVMFS proxy
Update examples and manual to include new features

Prune updates

---

batch_job/src/work_queue_factory.c

factory reports to catalog

---

makeflow/src/dag_variable.c
makeflow/test/TR_makeflow_020_category_variable_scope.sh
makeflow/test/syntax/category_variable_scope.makeflow

don't look for variables after node is defined ( #1771 )

Fix for #1771

---

dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/src/jx_test.c
dttools/test/jx.expected
dttools/test/jx.input

Added the ceil and floor math functions for use in the jx examples. updated join loop and related test that was failing parse. Added checking to print parse errors in jx_test.

Addition of ceil and floor. Fix join and jx_test.

---

dttools/src/jx.c
dttools/src/jx.h
makeflow/src/parser_jx.c

From the email discussion started by @btovar

Change jx_iterate_keys to return a const char *

---

dttools/src/jx2json.c

Fix pretty printing in jx2json

---

work_queue/src/work_queue_status.c

output correct JSON with -l -T, -l -W

---

dttools/src/debug_file.c

Quick commit to address #1671.

Set default size to 0

---

work_queue/src/work_queue.c

Adds debug message displaying where master is running

---

dttools/src/Makefile
dttools/src/string_set.c
dttools/src/string_set.h
makeflow/src/dag.c
makeflow/src/dag.h
makeflow/src/dag_node.c
makeflow/src/dag_visitors.c
makeflow/src/parser.c
makeflow/src/parser_jx.c

@btovar please take a look. I still need to do a bit of testing, but I figure it can still be removed. Addressed #1773

Fix var sets

---

parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc

Parrot sendmmsg/recvmmsg

---

parrot/src/pfs_service_cvmfs.cc

switch cvmfs repos, unless LIBCVMFS_VERSION == 1

---

batch_job/src/Makefile
batch_job/src/batch_file.c
batch_job/src/batch_file.h
batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_task.c
batch_job/src/batch_task.h

Initial setup of batch_task to be used with wrapper and hooks in Makeflow. Common interface with batch_job. Does not interface with submit yet.

Batch task

---

dttools/src/debug.h
makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/makeflow_hook.c
makeflow/src/makeflow_hook.h
makeflow/src/makeflow_hook_example.c

Initial commit to show the structure and organization of MAKEFLOW HOOKS.

Hook header

---

parrot/src/pfs_process.cc

Fix misplaced statement in getgroups

---

makeflow/src/makeflow.c
makeflow/src/makeflow_hook.c
makeflow/src/makeflow_hook.h

Updates the register functionality to allow flexibility about adding hooks and duplicate hooks.

Hook register

---

makeflow/src/dag_file.c
makeflow/src/dag_file.h
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/parser_jx.c
makeflow/test/json/env.json
makeflow/test/json/files.json
makeflow/test/json/local.json
makeflow/test/json/simple.json

Functions that return a Node/Task as a JX object.
Will be used later for wrappers and in Batch Job.

Added functions to convert data struct to jx

---

batch_job/src/Makefile
batch_job/src/batch_task.c
batch_job/src/batch_task.h
batch_job/src/batch_wrapper.c
batch_job/src/batch_wrapper.h
dttools/src/stringtools.c
dttools/src/stringtools.h

This is a library function for generating wrapper scripts. The same functionality is repeated in a few places in Makeflow, so this gives a common implementation to simplify the transition to modules.

Builder for wrapper scripts

---

batch_job/src/work_queue_factory.c

Not super portable right now. This pull request is more for demonstrating an idea, to be discussed at HEP meetings.

modified work_queue_factory to integrate runos into the factory. 

---

parrot/src/pfs_main.cc
parrot/src/pfs_service_cvmfs.cc

do not set HTTP_PROXY if using -p, instead set PARROT_HTTP_PROXY

---

makeflow/example/example.makeflow
makeflow/src/Makefile
makeflow/src/dag_file.h
makeflow/src/dag_node.c
makeflow/src/makeflow.c
makeflow/src/makeflow_hook.c
makeflow/src/makeflow_module_fail_dir.c
makeflow/src/makeflow_module_sandbox.c

Added sandbox option to Makeflow.

Hook sandbox

---

parrot/src/pfs_service_cvmfs.cc

Do not merge before checking with @btovar
Fixes #1836

Initial fix for #1836

---

dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/test/jx.expected
dttools/test/jx.input

I need a few shell-related functions in JX for describing workflows

JX additions

---

parrot/src/pfs_table.cc

For #1855 
This doesn't fix the issue in general, so we would still see buggy behavior with symlinks that have `/proc/self` as an intermediate path component. This PR just adjusts existing path resolution that handles `/dev/fd` as a special case. I think this resolution order is more correct than what's there now.

Rewrite /proc/self and /dev/fd before following symlinks

---

work_queue/src/condor_submit_workers

do not rewrite --cores,--memory,--disk given manually

---

dttools/src/jx_parse.c
dttools/src/jx_parse.h
makeflow/src/dag.c
makeflow/src/makeflow.c
makeflow/src/parser.c

Fixes to get @cjgrady's workflow running. WIP is at trshaffer/workflowDemo@dea4964d1

Fix Makeflow JX handling

---

configure
configure.afs
resource_monitor/src/Makefile

Fix for python3 with anaconda

---

doc/man/resource_monitor.m4
doc/man/work_queue_worker.m4
resource_monitor/src/resource_monitor.c
work_queue/src/work_queue_worker.c

We got CJ in trouble because of confusing descriptions in the work_queue_worker.

better work_queue_worker show_help

---

batch_job/src/batch_job.h

Very minor note about jobid gap.

Add note to api about submit/wait valid jobids gap

---

makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/makeflow_module_vc3_builder.c

Added VC3 Builder Module to makeflow.

Add VC3 Builder Module

---

batch_job/src/batch_job_cluster.c

This is to work around a buggy qsub wrapper in place at the CRC.
cc @dthain

Use a counter for job names submitted via cluster

---

batch_job/src/batch_job_amazon.c
batch_job/src/batch_job_lambda.c
dttools/src/Makefile
dttools/src/semaphore.c
dttools/src/semaphore.h

Added a semaphore to control download concurrency in batch_job_lambda.
With this PR, I can run the bwa workflow through lambda easily.

Lambda D/L Concurrency Control

---

batch_job/src/work_queue_factory.c
work_queue/src/work_queue.c
work_queue/src/work_queue.h

This is a cleanup and revision of the capacity model to reflect changes made between revisions of the corresponding paper on master-worker capacity.

Cleanup of Master-Worker Capacity

---

makeflow/src/dag_visitors.c

Simple case: [ "output.txt" ]
Complex case: [ "dag_name": "output.10", "task_name":"output.txt"]

Fix bug in output of file object in json file format:

---

doc/index.html
doc/jx-quick.html
doc/jx-tutorial.html
doc/jx.html
doc/makeflow.html

Added more up-front example and discussion to Makeflow manual.
Added workflow-oriented tutorial on JX.
Added quick reference card on JX.
Still needs some cleanup to reconcile end of makeflow manual with JX reference page.

Updated JX Documentation

---

doc/catalog.html
dttools/src/catalog_query.c
dttools/src/catalog_server.c

Combines update compression and TCP transport.
Merged code has not been tested yet.
Supersedes #1739

Catalog Updates via TCP

---

makeflow/src/parser_jx.c

standard error messages

---

batch_job/src/batch_job.h
batch_job/src/batch_job_cluster.c
makeflow/src/makeflow.c

Enforce constraint that batch jobs may not have the jobid zero.

Batch Job Zero

---

doc/jx-tutorial.html

resources and categories

---

dttools/src/jx_parse.c
dttools/src/jx_parse.h

Elaborated many parsing errors to show what was expected and what was actually observed.
Only first parsing error is displayed, to avoid later confusion.

Improved JX Parsing Errors

---

batch_job/src/batch_file.c
batch_job/src/batch_file.h
batch_job/src/batch_task.c
configure
configure.afs
dttools/src/Makefile
dttools/src/path.c
dttools/src/path.h
dttools/src/s3_file_io.c
dttools/src/s3_file_io.h
makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/makeflow_module_archive.c

This branch implements functionality to upload, download, and check for files in an aws s3 bucket using the c library curl. The local archive code has been updated to accommodate for directories when they are included in the input and output files of a task too. Hashing directories and checking to see if something is a directory has been implemented into the file batch_file.c. Most of the code that has been implemented has been into the file makeflow_module_archive.c. Flag options have been added to the command line so the user can run the s3 archive code or choose which s3 bucket they would want to upload/download their files from.

Makeflow S3 archive and Directory Hashing

---

doc/makeflow.html

Added short description of how to use the S3 archive in the Makeflow manual.

S3 Archive Documentation Added

---

makeflow/src/makeflow_module_archive.c

Trying to merge new code into master with the deletion of these lines of code.

New attempt at merging new flags for S3 archive

---

configure

To compile cctools on stampede:
CC=gcc CXX=g++ LDFLAGS='-fstack-protector' ./configure --without-static-libgcc

Add LDFLAGS for correct compilation

---

batch_job/src/batch_job_cluster.c
doc/makeflow.html
doc/man/makeflow.m4
makeflow/example/example.categories.makeflow
makeflow/src/makeflow.c
makeflow/src/parser.c

Should address #1857. Untested by virtue of not having access to a Torque cluster. @btovar please take a look.

Add resource parsing to Torque

---

parrot/src/pfs_service_local.cc

If we get `ENXIO` with `O_WRONLY`, we're either opening a device file with no corresponding device or a fifo with no readers (due to Parrot making opens `O_NONBLOCK`). Linux allows pipe opens to succeed with `O_NONBLOCK|O_RDWR`, so we can retry failed opens in the case of `O_NONBLOCK|O_WRONLY`. Switching to `O_RDWR` prevents this hack from being tried more than once.
Resolves #1964

Catch ENXIO opening a fifo with no readers

---

allpairs/test/TR_allpairs_bitwise.sh
allpairs/test/TR_allpairs_composite.sh
chirp/test/TR_chirp_tickets.sh
dttools/src/histogram.c
dttools/src/json.c
parrot/src/pfs_resolve.c
parrot/test/TR_parrot_mmap.sh
parrot/test/parrot-test.sh
resource_monitor/src/resource_monitor.c
sand/test/TR_sanity.sh
work_queue/src/work_queue_worker.c

These are some assorted bugs that came up while I was getting the tests green. Some are compiler complaints, and there's a fix for #1963

Random Bugfixes

---

work_queue/src/work_queue.c

avoid double free on MSG_FAILURE

---

makeflow/src/parser_make.c

Corrected typo in make parser for UMBRELLA.

Fixed typo in makeflow parser

---

batch_job/src/Makefile
batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_mpi.c
configure
doc/install.html
doc/makeflow.html
doc/man/makeflow.m4
doc/man/makeflow_mpi_starter.m4
doc/workqueue.html
makeflow/src/Makefile
makeflow/src/makeflow.c
makeflow/src/makeflow_mpi_starter.c
makeflow/src/makeflow_mpi_submitter.c
work_queue/src/work_queue_worker.c

Enable with e.g., ./configure --with-mpicc-path=$(which mpicc)
See doc/makeflow.html for running instructions.
Supersedes #1952

MPI worker and batch mode

---

dttools/src/catalog_query.c

do not busy wait when no catalog can be contacted

---

configure
dttools/src/getopt.h

Find getopt.h in MaxOSX.sdk when appropiate

---

umbrella/src/umbrella.py

Fixes to run umbrella in py2/py3.

Umbrella fixes for py3

---

batch_job/src/batch_job_amazon_batch.c

When we make a job for batch, we have a registry command to register a job, and we have one registry per-job. So I added a cleanup command for when we pull the job. Technically there's no additional money cost for having a million jobs, but it's polite to clean up your resources used anyway.
Also, I added a specification in the registry to keep containers in privilaged mode so they can then mount an EFS on startup, enabling jobs to have as much disk-space as necessary.

added a deregister command to clean up job registry and Added privilaged Mode

---

doc/makeflow.html
doc/man/makeflow.m4
makeflow/src/makeflow.c

Updated the mpi documentation after my meeting with Prof @dthain for Makeflow. Also added the makeflow option --mpi-task-working-dir instead of using --working-dir

Mpi documentation

---

work_queue/src/perl/Work_Queue.pm
work_queue/src/python/work_queue.binding.py

Make work_queue_invalidate_cached_file available in python and perl

invalidate cached files bindings

---

configure
makeflow/src/condor_submit_makeflow
work_queue/src/python/work_queue.binding.py

Small additions to the python api and fixes post Madison's tutorial.

Small fixes

---

.gitignore
allpairs/test/.gitignore
chirp/test/.gitignore
deltadb/src/.gitignore
doc/man/catalog_server.m4
dttools/src/catalog_server.c
makeflow/src/.gitignore
makeflow/test/.gitignore
parrot/test/.gitignore
sand/test/.gitignore

Also updated `.gitignore`s to de-clutter my `git status`
For #2030

Doc updates for catalog_server

---

batch_job/src/work_queue_factory.c
doc/man/work_queue_factory.m4

Addresses #2030 
Adds missing options to documentation
Modifies wording to fit columns

Documentation Update for Work Queue Factory

---

doc/man/work_queue_status.m4
work_queue/src/work_queue_status.c

fix the work_queue_status --help message and man page

fix work_queue_status manual

---

work_queue/src/python3/Makefile

python3 compilation fixes

---

doc/man/makeflow.m4
makeflow/src/makeflow.c

Update the options to reflect which options are parsed and limit their length. Also update the corresponding man page.

Makeflow usage

---

doc/man/makeflow_viz.m4
makeflow/src/makeflow.c

Makeflow viz doc fixes

---

doc/man/resource_monitor.m4
doc/resource_monitor.html

remove doc saying resource_monitor works with Darwin

---

work_queue/src/perl/Work_Queue.pm

set allowed port range when creating the queue.
specify transactions, debug, and stats log when creating the queue.

Small additions to the perl api to match python.

---

work_queue/src/condor_submit_workers
work_queue/src/pbs_submit_workers
work_queue/src/slurm_submit_workers
work_queue/src/torque_submit_workers
work_queue/src/work_queue_submit_common

Adds --docker-universe to condor_submit_workers

---

work_queue/src/work_queue.c

update task result when result so far is unknown

---

makeflow/src/makeflow_ec2_setup

Thanks to Prof. Thain and Ben's suggestions, I have updated the makeflow_ec2_setup in cctools to a python2/3 script that is able to handle and parse json responses from the AWS. This is an updated and more sustainable version of the script and will be compatible for different users under different enviornments. -Yifan Yu

makeflow ec2 setup updated

---

work_queue/src/work_queue.i

fix off_t in work_queue.i

---

dttools/src/rmonitor_poll.c
resource_monitor/src/resource_monitor.c

Fix cpu time measurements in the monitor

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_mpi.c
configure
doc/makeflow.html
doc/workqueue.html
makeflow/src/makeflow.c
work_queue/src/work_queue_worker.c

Working on consolidating all MPI code into batch_job_mpi.  (WIP)

Makeflow-MPI Cleanup

---

packaging/conda/README
packaging/conda/build.sh
packaging/conda/meta.yaml

Conda recipe

---

doc/index.html
doc/makeflow.html
doc/man/condor_submit_makeflow.m4
doc/manual.h
makeflow/src/condor_submit_makeflow

- Added additional error checking and output to condor_submit_makeflow
- Added documentation for condor_submit_makeflow
- Updated copyright boilerplate date.

Cleaned up condor_submit_makeflow

---

dttools/src/Makefile
dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_binary.c
dttools/src/jx_binary.h
dttools/src/jx_binary_test.c

An experiment: `jx_binary_read` / `jx_binary_write` encode JX to stdio streams in a binary representation.  Does it pay to do so?

 JX Binary Representation

---

batch_job/src/work_queue_factory.c
dttools/src/copy_tree.h

Copy wrapper inputs to factory scratch directory

---

doc/man/catalog_update.m4
doc/man/resource_monitor.m4
dttools/src/catalog_query.c
dttools/src/catalog_server.c
resource_monitor/src/resource_monitor.c

adds 'uuid' to identify records in catalog updates

---

batch_job/src/work_queue_factory.c

use correct binary from --worker-binary

---

configure
dttools/test/TR_b64.sh
dttools/test/TR_buffer.sh
dttools/test/TR_chunk_test.sh
dttools/test/TR_data_struct_set.sh
dttools/test/TR_hmac_test.sh
dttools/test/TR_jx_canonicalize.sh
dttools/test/TR_jx_match.sh
dttools/test/TR_jx_merge.sh
dttools/test/TR_list_compat.sh
dttools/test/TR_list_core.sh
dttools/test/TR_path_basename.sh
dttools/test/TR_path_collapse.sh
dttools/test/TR_path_dirname.sh
dttools/test/TR_path_extension.sh
dttools/test/TR_path_remove_trailing_slashes.sh
dttools/test/TR_pattern.sh
dttools/test/TR_stringtools.sh
dttools/test/TR_umr.sh
dttools/test/test_runner_common.sh
parrot/src/Makefile
resource_monitor/src/Makefile

Remove all hardcoded mentions of gcc to ${CC}.

gcc to ${CC}

---

chirp/test/TR_chirp_job_python.sh
chirp/test/TR_chirp_python.sh
configure
configure.tools.sh
packaging/scripts/configure-from-image
resource_monitor/test/TR_python_allocations.py

Some configure fixes needed for conda-build.

Configure fixes

---

doc/man/Makefile

make clean  was cleaning the generated .md man pages.

Do not clean md files.

---

work_queue/src/bindings/perl/work_queue_example.pl
work_queue/src/bindings/python3/work_queue_example.py
work_queue/src/work_queue_example.c

Changes how we call work_queue_create, etc. so that they are easier to modify in a tutorial.

Examples easier to modify

---

work_queue/src/work_queue.c

Fix for #2188. The line reads:
```
time master-pid TASK taskid {RETRIEVED|DONE} {SUCCESS|SIGNAL|END_TIME|FORSAKEN|MAX_RETRIES|MAX_WALLTIME|UNKNOWN|RESOURCE_EXHAUSTION} {exit-code} {limits-exceeded} {resources-measured}
```

add exit code to wq transactions log

---

packaging/conda/build.sh
packaging/conda/meta.yaml

This pr contains the conda recipe used for conda-forge. It can also be used for the cclnd channel.

Conda recipe updates

---

work_queue/src/work_queue.c

Don't count status connections as workers

---

work_queue/src/bindings/perl/Work_Queue.pm
work_queue/src/bindings/python/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

- Added the "long-timeout" option to work_queue_tune.
- Updated the C, Perl, and Python docs to reflect all available options.

Updated Timeout Control

---

batch_job/src/batch_job.h
doc/cctools.doxygen

- Cleaned up API doc mainpage to focus on API users, not implementors.

API Doc Mainpage

---

doc/manuals/index.md

add API index link to docs

---

doc/manuals/jx/jx-quick.md
doc/manuals/jx/jx.md
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h

Add len() to JX

---

batch_job/src/batch_job_cluster.c

use getcwd instead of PWD in cluster module

---

dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_binary.c
dttools/src/jx_eval.c
dttools/src/jx_export.c
dttools/src/jx_function.c
dttools/src/jx_print.c

do not copy context on eval

---

makeflow/src/makeflow_monitor

rewrite makeflow_monitor to cleanup race condition

---

makeflow/src/dag_node.c
makeflow/src/makeflow.c
makeflow/src/parser_jx.c

Makeflow memory leaks fixes

---

run_all_tests.sh
work_queue/test/TR_work_queue_python.sh
work_queue/test/wq_test.py

Tests that the bindings can be loaded correctly, and that simple tasks can be executed, including recursive inputs and outputs.
It also checks for expected failures modes, such as missing input and outputs.

test for wq python bindings

---

makeflow/src/makeflow.c

The use case is amazon batch jobs where we could not create new
submissions because some hard limit.
Solves #2161

wait for makeflow jobs even when remote submission fails.

---

INTRO.md
WorkQueue_Jupyter_Tutorial.ipynb

Includes full Jupyter Tutorial for WorkQueue and TJ's Parsl tutorial as well.  Zoe is still working on the Coffea portion.
Instructions for installation are included in INTRO.md

WorkQueue Jupyter Tutorial

---

batch_job/src/work_queue_factory.c

Fix for #2255.
The fix consists on clearly separating the two cases: only masters, and masters+foremen.
Before, we  processed the masters, and then added the foremen, but this lost information that the foremen computation needed not to over-count tasks.

Do not over-count running tasks when using foremen and wq factory.

---

chirp/src/json.c

See https://github.com/cooperative-computing-lab/cctools/pull/2273#issuecomment-609940570

update comment, not updating json.c with jx.c

---

packaging/scripts/configure-from-image

Increases debug output when using CI.

Print config.mk on error

---

work_queue/src/bindings/python3/work_queue.binding.py

@trshaffer From your code I renamed it to work_queue.Factory, made a distinction between command line only and config file options, and made some variables and functions class attributes.
Let me know if it still works as you intended.

Python interface for wq factory

---

batch_job/src/work_queue_factory.c
work_queue/src/bindings/python3/work_queue.binding.py

These changes are intended to make the test for work queue in coffea simpler, with something like:
```
workers = wq.Factory(batch_type='local', master_host_port='localhost:9123'):
with workers:
...etc...
```
This eliminates the script that launch and wait for a worker in coffea. Also, it eliminates the use of the catalog making the connection directly to the master just launched.

work queue factory allow host:port when using configuration file

---

work_queue/src/work_queue.c

delete uncachable input files of forsaken tasks

---

work_queue/src/work_queue_graph_log

Small changes for  wq graph log  and python3.

wq graph log and python3

---

dttools/src/jx_function.c

Some little fixups to make JX fetch() more user friendly.

JX Fetch Fixups

---

chirp/src/Makefile

Clean missing objects from chirp programs.

---

.travis.yml
configure
packaging/scripts/generate-images
work_queue/test/TR_work_queue_valgrind.sh

Major issues were that the dash shell does not expand {}, and that the swig version was old.

Adds ubuntu image to travis testing

---

dataswarm/Makefile
dataswarm/apps/dataswarm_test
dataswarm/clients/python3/dataswarm.py
dataswarm/manager/Makefile
dataswarm/manager/dataswarm_manager.c
dataswarm/worker/Makefile
dataswarm/worker/dataswarm_worker.c

Added initial structure for dataswarm.
Everything builds, but nothing works yet!
This will give us a place to start working in parallel.

Data Swarm Setup

---

dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/test/jx.expected
dttools/test/jx.input

Copies the same enforced lazy eval of the query within select and adds it to project.
Addresses #2313

Modifies project to perform lazy eval like select

---

dataswarm/manager/Makefile
dataswarm/manager/dataswarm_client.c
dataswarm/manager/dataswarm_client.h
dataswarm/manager/dataswarm_manager.c
dataswarm/manager/dataswarm_worker.c
dataswarm/manager/dataswarm_worker.h
dataswarm/worker/Makefile
dataswarm/worker/dataswarm_worker.c

Building up basic structure for manager-worker communication.

Dataswarm Communication

---

dataswarm/manager/Makefile
dataswarm/manager/dataswarm_manager.c
dataswarm/manager/dataswarm_manager.h
dataswarm/manager/dataswarm_message.c
dataswarm/manager/dataswarm_message.h
dataswarm/worker/Makefile
dataswarm/worker/dataswarm_message.c
dataswarm/worker/dataswarm_message.h
dataswarm/worker/dataswarm_worker.c
dttools/src/debug.c
dttools/src/debug.h

Manager advertises itself to catalog, worker uses it to connect.

Dataswarm Catalog Support

---

dataswarm/worker/Makefile
dataswarm/worker/dataswarm_blob.c
dataswarm/worker/dataswarm_blob.h
dataswarm/worker/dataswarm_worker.c

First crack at blob storage implementation.
Not hooked up to main loop yet.

Dataswarm Worker

---

doc/manuals/jx/jx-quick.md
doc/manuals/jx/jx.md
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/test/jx.expected
dttools/test/jx.input

Useful for expanding querying functionality to include `LIKE`-style functionality from SQL.

Adds JX like regex matching function

---

apps/wq_bwa_json/wq_bwa_json.py
work_queue/src/clients/python3/work_queue_server.py
work_queue/src/work_queue_json.c
work_queue/src/work_queue_server.c

Address issue #2320 and the port detection aspect of issue #2321 
Does a simple read of stdout before connecting to get the port the server is listening on and connects there.

first pass at fixing worker port selection issue

---

apps/aws/cctools-AMI.py
apps/makeflow_blasr/makeflow_blasr
apps/makeflow_blast/makeflow_blast
apps/makeflow_bwa/makeflow_bwa
apps/makeflow_gatk/makeflow_gatk
apps/wq_bwa_json/wq_bwa_json.py
apps/wq_replica_exchange/protomol_functions.py
apps/wq_replica_exchange/wq_replica_exchange
apps/wq_visualization/dev/NewLogFormatVisualize.py
apps/wq_visualization/dev/OldLogFormatVisualize.py
apps/wq_visualization/example/work_queue_example.py
apps/wq_visualization/log_converter.py
apps/wq_visualization/visualizer.py

- python 2->3 changes recommended by 2to3 (mostly print and except)
- /usr/bin/env python -> /usr/bin/env python3

Update Apps to Python3

---

configure

Adds missing include to swig+perl .o wrapper file

add include path to swig+perl

---

dttools/src/category.c
dttools/src/category.h
dttools/test/TR_category.sh
work_queue/src/bindings/perl/Work_Queue.pm
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

Define minimum resources for a category

---

dataswarm/manager/dataswarm_test.c
dataswarm/worker/dataswarm_blob.c
dataswarm/worker/dataswarm_blob.h
dataswarm/worker/dataswarm_mount.c
dataswarm/worker/dataswarm_mount.h
dataswarm/worker/dataswarm_task.c
dataswarm/worker/dataswarm_worker.c
dataswarm/worker/dataswarm_worker_main.c

The test script is now running (mostly) correctly and is able to create, put, commit, and delete blobs, as well as run a task within a simple namespace.

DS Worker Fixups

---

dataswarm/manager/dataswarm_test.c
dataswarm/worker/dataswarm_blob.c
dataswarm/worker/dataswarm_worker.c

free(deleting_name) came before delete_fir(deleting_name).

DS worker blobs fix blob_delete

---

dataswarm/manager/dataswarm_manager.c
dataswarm/manager/dataswarm_message.c
dataswarm/manager/dataswarm_message.h
dataswarm/manager/dataswarm_worker_rep.c
dataswarm/manager/dataswarm_worker_rep.h
dataswarm/worker/Makefile
dataswarm/worker/dataswarm_blob.c
dataswarm/worker/dataswarm_blob.h
dataswarm/worker/dataswarm_mount.c
dataswarm/worker/dataswarm_task.c
dataswarm/worker/dataswarm_worker.c
dataswarm/worker/dataswarm_worker_main.c
dttools/src/jx.c
dttools/src/jx.h

Reconciling differences between tasks and blobs...

DS Worker: Tasks and Blobs

---

mkdocs.yml

fix undefined references in readthedocs nav bar

---

dataswarm/manager/dataswarm_message.c
dataswarm/manager/dataswarm_message.h
dataswarm/worker/dataswarm_blob.c
dataswarm/worker/dataswarm_task_table.c
dataswarm/worker/dataswarm_task_table.h
dataswarm/worker/dataswarm_worker.c
dataswarm/worker/dataswarm_worker.h

- Fix up message construction.
- Status updates on a timer.
- Fix blob delete.
- Adjust namespace for errors.

DS Worker Buildout

---

batch_job/src/batch_job_mpi.c
doc/man/m4/makeflow.m4
doc/man/m4/makeflow_mpi_starter.m4
doc/man/md/makeflow.md
doc/man/md/makeflow_mpi_starter.md
doc/manuals/install/from-source.md

change mpicc-path to mpi-path everywhere

---

dataswarm/manager/Makefile
dataswarm/manager/dataswarm_manager.c
dataswarm/manager/dataswarm_manager.h
dataswarm/manager/dataswarm_message.c
dataswarm/manager/dataswarm_rpc.c
dataswarm/manager/dataswarm_rpc.h
dataswarm/manager/dataswarm_test.c
dataswarm/manager/dataswarm_worker_rep.c
dataswarm/manager/dataswarm_worker_rep.h
dataswarm/worker/dataswarm_blob.c

Cleaned up the operations to perform RPCs against the worker and moved them into dataswarm_rpc.  Now calls wait for the matching results to come back, and dispatch asynchronous updates to dataswarm_worker_rep_async_update.

DS Manager Buildout

---

dataswarm/clients/python3/dataswarm.py

Same operations as previously merged. Just one extra commit to fix some naming errors in the first pass.

DataSwarm: Manager: Client operations

---

dataswarm/manager/dataswarm_manager.c

There are a few warnings still, but it compiles.

DataSwarm: Manager: fix compilation errors

---

dataswarm/manager/dataswarm_blob_rep.h
dataswarm/manager/dataswarm_manager.c
dataswarm/manager/dataswarm_manager.h
dataswarm/manager/dataswarm_message.h
dataswarm/manager/dataswarm_rpc.c
dataswarm/manager/dataswarm_rpc.h
dataswarm/manager/dataswarm_task_rep.h
dataswarm/manager/dataswarm_test.c
dataswarm/manager/dataswarm_worker_rep.c
dataswarm/manager/dataswarm_worker_rep.h
dataswarm/worker/dataswarm_blob.c
dttools/src/jx.c
dttools/src/jx.h

Got the sequence  create->commit->delete for blobs working.
If this looks like a good idea, I can start working on put and copy, also tasks.

blob async rpcs

---

dataswarm/manager/dataswarm_message.h
dataswarm/manager/dataswarm_rpc.c
dataswarm/manager/dataswarm_task_rep.h
dataswarm/manager/dataswarm_test.c
dataswarm/manager/dataswarm_worker_rep.c
dataswarm/manager/dataswarm_worker_rep.h
dataswarm/worker/dataswarm_task_table.c
dataswarm/worker/dataswarm_worker.c

Updates the task_rep states according to the messages from the worker.

DS task async updates

---

dataswarm/common/ds_mount.c
dataswarm/common/ds_task.c
dataswarm/common/ds_task.h
dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_task_table.c
dataswarm/worker/ds_task_table.h
dataswarm/worker/ds_worker_main.c

Task metadata is now recorded in the "meta" file in each task directory, and recovered at startup.

DS Task Persistence Take 2

---

dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_worker.c
dataswarm/worker/ds_worker.h

- Generate all paths in ds_worker for consistency.

DS Worker Paths

---

dttools/src/mq.c
dttools/src/mq.h

calls link_address_local to enquire about the address and port the queue
is listening.

adds mq_address_local

---

dataswarm/manager/Makefile
dataswarm/manager/ds_client_ops.c
dataswarm/manager/ds_file.c
dataswarm/manager/ds_file.h
dataswarm/manager/ds_validate.c
dataswarm/manager/ds_validate.h

Fixup some compile issues in the manager.

DS Manager Fixup

---

dataswarm/manager/ds_rpc.c
dataswarm/manager/ds_rpc.h
dataswarm/manager/ds_test.c
dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_blob_table.h
dataswarm/worker/ds_task_table.c
dataswarm/worker/ds_task_table.h
dataswarm/worker/ds_worker.c

Manager can now send task-list and blob-list to get back a dictionary of objects.
A little concerned about how this will work with 1000s of objects...

DS Worker List Tasks and Blobs

---

batch_job/src/batch_job.h
batch_job/src/batch_job_cluster.c

For issue #2418. Tested on stampede2.

Cluster hearbeats

---

dataswarm/common/ds_message.c
dataswarm/common/ds_message.h
dataswarm/manager/.gitignore
dataswarm/manager/ds_client_rep.c
dataswarm/manager/ds_client_rep.h
dataswarm/manager/ds_manager.c
dataswarm/manager/ds_manager.h
dataswarm/manager/ds_rpc.c
dataswarm/manager/ds_test.c
dataswarm/manager/ds_worker_rep.c
dataswarm/manager/ds_worker_rep.h
dataswarm/worker/.gitignore
dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_blob_table.h
dataswarm/worker/ds_task_table.c
dataswarm/worker/ds_worker.c
dataswarm/worker/ds_worker.h
dttools/src/mq.c
dttools/src/mq.h

Compiles, probably doesn't work right....

First pass at wiring MQ into DS

---

dataswarm/common/Makefile
dataswarm/manager/Makefile
dataswarm/manager/ds_client_ops.h
dataswarm/manager/ds_manager.c
dataswarm/manager/ds_rpc.c
dataswarm/manager/ds_rpc.h
dataswarm/manager/ds_worker_rep.c
dataswarm/manager/ds_worker_rep.h
dataswarm/worker/Makefile
dataswarm/worker/ds_blob_table.c
dataswarm/worker/ds_blob_table.h
dataswarm/worker/ds_task_table.c
dataswarm/worker/ds_task_table.h
dataswarm/worker/ds_worker.c
dataswarm/worker/ds_worker.h
dataswarm/worker/ds_worker_main.c

Simplify handling of common objects.

DS Common Library

---

dataswarm/clients/python3/dataswarm.py
dataswarm/manager/ds_validate.c

Client successfully handshakes and submits a task. (from python using mq msg header)

DS py client draft

---

dttools/src/jx_parse.c
makeflow/src/dag_node.c
makeflow/src/dag_node.h
makeflow/src/makeflow.c
makeflow/src/makeflow_gc.c
makeflow/test/TR_makeflow_040_sub_workflow_jx.sh
makeflow/test/TR_makeflow_050_sub_workflow_jx_for.sh

Makeflow jx sub args

---

doc/manuals/jx/jx-tutorial.md
doc/manuals/work_queue/index.md
makeflow/src/makeflow.c
work_queue/src/work_queue.c

- adds nestes workflows example
- improves statistics log in wq manual
- adds transactions log to wq manual

Small doc additions (wq and jx)

---

makeflow/src/dag_variable.c
makeflow/src/dag_variable.h
makeflow/src/parser.c

Makeflow category multiple definition warning

---

doc/manuals/jx/jx-tutorial.md
makeflow/src/makeflow.c

Makeflow: add makeflow executable as an input for nested workflows

---

.travis.yml
packaging/travis/travis.sh

Add docker login info to travis

---

dataswarm/manager/ds_client_ops.c
dataswarm/manager/ds_client_ops.h
dataswarm/manager/ds_file.c
dataswarm/manager/ds_file.h
dataswarm/manager/ds_manager.c
dataswarm/manager/ds_validate.c

Every client call is of the form   ds_client_TARGET_OP(manager, params), where TARGET is task, file, etc, and OP is submit, delete, etc.

DS: standard client calls

---

work_queue/src/work_queue_status.c

Work Queue Tasks in JSON

---

dttools/src/jx.c

JX: Convert Recursive to Iterative Copy

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_cluster.c
doc/manuals/makeflow/index.md

As of now, untested b/c we do not have an LSF facility.

Makeflow: First pass at LSF support.

---

work_queue/src/work_queue.c

(it's generating a lot of noise in the debug logs.)

WQ Silence Extra Capacity Output in Log

---

configure
tlq/Makefile
tlq/client/tlq_client
tlq/log_define
tlq/ltrace_wrapper
tlq/server/log-types
tlq/server/parsers/ltrace_parser
tlq/server/parsers/makeflow_and_work_queue_master_parser
tlq/server/parsers/makeflow_parser
tlq/server/parsers/work_queue_master_parser
tlq/server/parsers/work_queue_worker_parser
tlq/server/tlq_server

This brings the files required for TLQ's functionality into CCTools.
The CCL TLQ repository contains added documentation, example applications, and example datasets. These additional files are kept in the TLQ repo.

Adds core TLQ files to main repository

---

dttools/src/rmsummary.c
work_queue/src/work_queue.c

Fix gpu rmsummary

---

work_queue/src/work_queue.c
work_queue/src/work_queue_status.c

Tables now fit in 80 columns wide.

show resources when using wq_status with -T and -W

---

batch_job/src/batch_job_condor.c
batch_job/src/work_queue_factory.c

Pass through GPU resources requested through the batch_job interface.
Allows the work_queue_factory to select gpus correctly.

Batch Job HTCondor GPU

---

resource_monitor/src/bindings/python3/resource_monitor.bindings.py
resource_monitor/src/resource_monitor.c

This while we figure out how to correctly measure them.

resource monitor: set gpus as the measured value if given as limit

---

makeflow/src/sge_submit_makeflow

sge_submit_workers was not getting the -p argument.

set correct parameters for sge_submit_workers

---

batch_job/src/batch_job_cluster.c
batch_job/src/batch_task.c
batch_job/src/work_queue_factory.c
doc/manuals/resource_monitor/index.md
dttools/src/category.c
dttools/src/category.h
dttools/src/category_test.c
dttools/src/rmonitor.c
dttools/src/rmonitor_poll.c
dttools/src/rmsummary.c
dttools/src/rmsummary.h
makeflow/src/dag_node.c
makeflow/src/dag_visitors.c
makeflow/src/makeflow.c
makeflow/src/makeflow_local_resources.c
makeflow/src/parser.c
resource_monitor/src/bindings/python3/example_simple_limit.py
resource_monitor/src/bindings/python3/resource_monitor.bindings.py
resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor.i
resource_monitor/src/rmonitor_poll_example.c
work_queue/src/work_queue.c
work_queue/src/work_queue_worker.c

Prepares for fractional cores.
Moves resource bookkeeping to double from int, which simplified some of the logic.

Resources cleanup I

---

doc/manuals/work_queue/index.md
mkdocs.yml

- Master -> Manager
- Clarify basic Conda install
- Clean up resources explanation.

Misc updates to WQ docs:

---

.github/workflows/nightly.yml

Create an ubuntu nightly binary build to test with cctools-packaging-test.

Nightly build

---

work_queue/src/work_queue.h

documents WORK_QUEUE_PREEXIST as internal use only

---

dttools/src/jx_eval.c
makeflow/src/dag_variable.c
makeflow/src/makeflow.c
makeflow/src/parser.c
makeflow/test/TR_makeflow_valgrind.sh
work_queue/test/TR_work_queue_valgrind.sh

Fixes makeflow leaks found by valgrind

---

work_queue/src/bindings/python3/work_queue.binding.py

Resolves #2570 
I also adjusted the interface so it can be used directly rather than via context manager to make things easier in Jupyter notebooks. I tried to note in the docs that this is not the recommended way of doing things outside of Binder.

Update WQ Factory Python docs

---

.github/workflows/integration.yml
packaging/scripts/configure-from-image
packaging/scripts/generate-images
run_all_tests.sh

fix python2 for centos7 binaries

---

doc/manuals/work_queue/index.md
work_queue/src/work_queue.c
work_queue/src/work_queue.h

WQ: new fast abort

---

doc/man/m4/work_queue_worker.m4
doc/man/md/work_queue_worker.md
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue_worker.c

adds --parent-death to work_queue_worker

---

work_queue/src/bindings/python3/work_queue.binding.py

ensure that strings are fed to python specify_file

---

CREDITS

I realized I never added myself to the credits.

Adds NK-H to credits

---

doc/man/m4/chirp.m4
doc/man/m4/jx_repl.m4
doc/manuals/jx/jx-repl.md
dttools/src/Makefile
dttools/src/jx_eval.c
dttools/src/jx_function.c
dttools/src/jx_function.h
dttools/src/jx_repl.c
dttools/src/jx_sub.c
dttools/src/jx_sub.h

Not yet ready for merge -- still a working prototype.  I'm open to any ideas/changes to make this a more useful tool.  The code is also a little messy, so any tips on how to improve it are also welcome.

jx_repl tool for JX language exploration

---

work_queue/src/work_queue.c

Accumulate requested resources, and not allocated.

bug fix wq hungry

---

batch_job/src/work_queue_factory.c
doc/man/m4/work_queue_factory.m4
doc/man/md/work_queue_factory.md

Make it really easy to run remote workers via python_package_run:
```
work_queue_factory --python-package pack.tar.gz  . . .
```

Factory Package Option

---

dttools/src/category.c
dttools/src/category.h
dttools/src/histogram.c
dttools/src/histogram.h
dttools/src/rmonitor.c
dttools/src/rmsummary.c
parrot/src/pfs_dispatch.cc
parrot/src/pfs_dispatch64.cc
parrot/src/pfs_mmap.h
parrot/src/pfs_table.cc
work_queue/src/work_queue.h

Small fixes found when testing for 7.3.

Misc fixes for 7.3

---

deltadb/src/deltadb_query.c
deltadb/src/deltadb_query_main.c
deltadb/src/deltadb_reduction.c
deltadb/src/deltadb_reduction.h
doc/man/m4/deltadb_query.m4
doc/man/md/deltadb_query.md

Allows for observing the number of instances of a given value, such as querying the unique names in a given time range.

DeltaDB: Add UNIQUE reduction type

---

python_environments/src/python_package_run

This to better track env expansion issue with topcoffea.

better log messages for python_package_run

---

configure

python-config is meant for embedded interpreters.

eliminate use of python-config

---

dttools/src/rmsummary.c
makeflow/src/makeflow_local_resources.c
work_queue/src/condor_submit_workers

* Changed condor_submit_workers to prevent users from specifying localhost as the servername
* Fixed bug with makeflow_local_resources_print

Minor bugfixes

---

poncho/src/poncho_package_run

This brings to poncho_package_run:
- https://github.com/cooperative-computing-lab/cctools/pull/2644
- https://github.com/cooperative-computing-lab/cctools/pull/2633
and renames all instances of python_ with poncho_

Match poncho_package_run with python_package_run

---

work_queue/src/work_queue.c

correctly report resources allocated/requested in wq status

---

batch_job/src/work_queue_factory.c

new_workers_needed is computed as: submitted - connected, which
already considers the workers_waiting_to_connect.
By subtracting  workers_waiting_to_connect, we were accounting for those
workers twice. E.g., say
250 needed
249 submitted
248 connected
-> new needed: 250 - 249 = 1
-> waiting to connect: 249 - 248 = 1
but by subtracting waiting to connect from new needed, we incorrectly
determine that 0 new workers are needed, when we really want 1 to reach
250 submitted.
Instead, this pull request makes it so that workers to connect are
accounted in the max worker_per_cycle. Now new needed + waiting to
connect cannot be larger than workers_per_cycle.

wq factory: correctly handle workers_waiting_to_connect

---

batch_job/src/batch_job_cluster.c
doc/man/m4/makeflow.m4
doc/man/md/makeflow.md
makeflow/src/makeflow.c

Supersedes #2702, fixes #2701.

Add keep-wrapper-stdout option

---

makeflow/src/makeflow_monitor
makeflow/test/TR_makeflow_monitor.sh

Fix for #2734 
Also other fixes for newer python versions.

makeflow_monitor fixes

---

doc/manuals/poncho/index.md

Updates PONCHO documentation to reflect PONCHO's current usage.

Updated PONCHO documantation

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h

wq wait retrieve many

---

work_queue/src/bindings/python3/work_queue.binding.py

Conflicts:
work_queue/src/bindings/python3/work_queue.binding.py

WQ: Abstractions with Chunk Size - Map

---

deltadb/src/deltadb_query_main.c
doc/man/m4/deltadb_query.m4
doc/man/md/deltadb_query.md

Rename reductions TEMP -> TIME_ and update docs for clarity.

DeltaDB: Update Docs

---

doc/man/m4/catalog_query.m4
doc/man/md/catalog_query.md
dttools/src/catalog_query_tool.c

Added --output option to catalog_query to display data in more convenient forms.

Catalog: Add tabular output option.

---

work_queue/src/work_queue.c

An error on close may report an error on a previous write (e.g. on AFS).
We observed this with AFS volumes close to their quota, where output
files seemed to be transferred correctly to the manager, but failed to
update in the shared file system.
For #2784.  Preserves current behavior as if the `write` calls failed (see #2783).

wq: check close for errors at manager

---

dttools/src/jx.c
dttools/src/jx.h
dttools/src/jx_eval.c
dttools/src/jx_parse.c
dttools/src/jx_pretty_print.c
dttools/src/jx_print.c
dttools/src/jx_sub.c
dttools/test/jx.expected
dttools/test/jx.input

**Demo:**
```
$ ./jx_repl 
Welcome to the JX Language Explorer.
Type 'help' for help
in_0  : ["A", "B", "C", "D", "E", "F"]
out_0 : 
[
"A",
"B",
"C",
"D",
"E",
"F"
]
--------------------
in_1  : {k: 0 for k in out_0}
out_1 : 
{
"A":0,
"B":0,
"C":0,
"D":0,
"E":0,
"F":0
}
--------------------
in_2  : {k: out_1[k] + 1 for k in keys(out_1)}
out_2 : 
{
"F":1,
"E":1,
"D":1,
"C":1,
"B":1,
"A":1
}
--------------------
```
**Error checking:**
```
in_3  : {k: abc for k in range(3)}
error on line 1, abc: undefined symbol
--------------------
in_4  : {abc: 1 for k in range(3)}
error on line 1, abc: undefined symbol
--------------------
```
**Dict-Comprehension within a pair list:**
```
in_5  : {k: 0 for k in out_0, "G": 0, "H": 0}
out_5 : 
{
"A":0,
"B":0,
"C":0,
"D":0,
"E":0,
"F":0,
"G":0,
"H":0
} …
```

JX: Dictionary Comprehensions

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/test/TR_work_queue_python_task.py
work_queue/test/wq_python_task.py

Also fixes #2792 by serializing arg list as is, rather than expanding and creating a new list.

Adds kwargs to PythonTask

---

work_queue/test/TR_work_queue_allocations.sh
work_queue/test/TR_work_queue_python.sh
work_queue/test/TR_work_queue_ssl.sh
work_queue/test/TR_work_queue_tag.sh
work_queue/test/TR_work_queue_valgrind.sh

Wait for 15 seconds for various work queue programs to start.
Making the (slow) github/OSX tests a little more resilient.

WQ: Increase test timeouts.

---

parrot/test/TR_parrot_execve.sh

Several of our test cases are a little too parochial and fail when testing under Spack due to issues of dependencies, complex assumptions, etc.  This PR will fix a few of these things so we can get a clean test under Spack.
- Simplified execve test: python and all of its dependencies have becomee too complex to test reliably.

Infra: Fix Parrot Tests for Spack

---

work_queue/src/work_queue.c

- Fix notice messages for unfit tasks in available workers
- Fix fclose error checking

wq small fixes

---

work_queue/src/bindings/python3/work_queue.binding.py

added wait for tag in abstractions, but need to actually test to make sure it works first (works like normal, need to see what happens if i have another task in the middle)

WQ: Add wait_for_tag in Python abstractions

---

parrot/src/Makefile
parrot/src/parrot_test_dir.c
parrot/src/parrot_test_execve.c
parrot/test/TR_parrot_dir.sh
parrot/test/TR_parrot_execve.sh

This should fix the tests failing with spack.

compile parrot test programs as any other program

---

resource_monitor/src/resource_monitor.c
resource_monitor/src/rmonitor_file_watch.c

Fix for monitor not terminating all processes, as seen by @David-Simonetti-ND.
@David-Simonetti-ND, could you give this pr a try?

resource_monitor correct pgid

---

resource_monitor/src/resource_monitor.c

With the changes in 360a6da24a7, the monitor was forwarding terminations
signals to the main monitored process, even when attaching to an already
running process. This commit makes it so that termination signals
are not forwarded to the main process in such case.
Further, to handle unresponsive processes in the general case, the
monitor now terminates itself and any known process if two termination
signals are received in less than a second.

rmonitor: fix --pid mode

---

poncho/src/poncho_package_create

poncho_package_create: ignore version when looking at locally pip packages

---

work_queue/src/bindings/python3/work_queue.binding.py
work_queue/test/TR_work_queue_allocations.sh
work_queue/test/wq_alloc_test.py

During the weekend, the coffea test broke because of a bug in the wq python factory code. This test should catch such cases.

use python wq factory in wq_alloc_test.py

---

work_queue/src/function_handler.py
work_queue/src/network_function.py

@btovar here are the changes that I made so that we can try to figure out the performance impact

fork process and import handler module

---

deltadb/src/catalog_export.c
deltadb/src/catalog_export.h
deltadb/src/catalog_server.c
deltadb/src/deltadb.c
deltadb/src/deltadb.h
deltadb/src/deltadb_query.c

https://github.com/cooperative-computing-lab/cctools/issues/2800#issue-1117809035

DeltaDB: historical snapshots on catalog webpage

---

dttools/src/category.h
work_queue/src/work_queue.h

fix  work_queue_category_mode_t  documentation

---

poncho/src/poncho_package_create

The original method used for checking the user's pip version is being deprecated. Changed to preferred method.

Changed deprecated method for checking pip versions.

---

work_queue/src/work_queue_coprocess.c

Fixed buffer overflow causing invalid unicode characters

---

work_queue/src/work_queue.c

I'm not sure how to test it, but the codes are done.

wq: add input and output lines in the transaction log

---

work_queue/src/work_queue_coprocess.c
work_queue/src/work_queue_worker.c

This fixes some incorrect handling of systemcall return values.

Small fixes for running workers with factory

---

doc/manuals/jx/reference.md
dttools/src/jx2json.c
dttools/src/jx_eval.c
dttools/src/jx_eval.h
dttools/src/jx_function.c
dttools/src/jx_repl.c
dttools/src/jx_test.c
makeflow/src/makeflow.c

JX: Added flags to enable/disable external function calls.

---

work_queue/src/work_queue.c

- Add log synopsis for transfer log
- Replace worker_id with worker_addrport for transfer log

Fix transfer log

---

mkdocs.yml

Copyright info also needs to be updated here.

Update mkdocs.yml for copyright info 2022

---

doc/manuals/jx-workflow/jx.md

Another pipe is needed at the end of the line.

Fix broken table in jx.md

---

doc/manuals/work_queue/index.md
dttools/src/Makefile
dttools/src/file_link_recursive.c
dttools/src/file_link_recursive.h
dttools/src/hash_table.c
dttools/src/hash_table.h
dttools/src/itable.c
makeflow/src/makeflow.c
makeflow/src/parser.c
work_queue/src/Makefile
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/src/work_queue.h
work_queue/src/work_queue_cache.c
work_queue/src/work_queue_cache.h
work_queue/src/work_queue_process.c
work_queue/src/work_queue_process.h
work_queue/src/work_queue_protocol.h
work_queue/src/work_queue_sandbox.c
work_queue/src/work_queue_sandbox.h
work_queue/src/work_queue_worker.c
work_queue/test/wq_test.py

Working towards remote file access from tasks.  Collecting several cleanup tasks prior to making big changes.

WQ: Asynchronous Remote File Access

---

resource_monitor/src/resource_monitor.c

rm: fix dangling argv_sh ptr

---

dttools/src/catalog_query.c
makeflow/src/makeflow_module_fail_dir.c
parrot/src/pfs_main.cc

Fix misc pointer errors discovered by gcc-8.5.0

Misc Pointer Errors

---

work_queue/src/work_queue.c

wq: fix memory leal total resources summary

---

dataswarm/src/bindings/python3/dataswarm.binding.py
work_queue/src/bindings/python3/work_queue.binding.py

wq python: include major version in python executable

---

batch_job/src/work_queue_factory.c

wq: correctly use ssl and password, direct factory queries

---

dataswarm/src/manager/Makefile
dataswarm/src/manager/ds_manager.c
dataswarm/src/manager/ds_manager.h
dataswarm/src/manager/ds_remote_file_info.c
dataswarm/src/manager/ds_remote_file_info.h
dataswarm/src/manager/ds_task.c
dataswarm/src/manager/ds_worker.c
dataswarm/src/manager/ds_worker.h
dataswarm/src/worker/ds_cache.c
dataswarm/src/worker/ds_cache.h
dataswarm/src/worker/ds_gpus.c
dataswarm/src/worker/ds_gpus.h
dataswarm/src/worker/ds_process.c
dataswarm/src/worker/ds_process.h
dataswarm/src/worker/ds_sandbox.c
dataswarm/src/worker/ds_sandbox.h
dataswarm/src/worker/ds_transfer_server.c
dataswarm/src/worker/ds_transfer_server.h

Moving and renaming various structures for a more consistent (and smaller) ds_manager.c

DS Manager Factoring

---

dataswarm/src/bindings/python3/dataswarm.binding.py
dataswarm/src/manager/dataswarm.h
dataswarm/src/manager/ds_catalog.c
dataswarm/src/manager/ds_manager.c
dataswarm/src/manager/ds_manager.h
dataswarm/src/manager/ds_protocol.h
dataswarm/src/manager/ds_schedule.c
dataswarm/src/manager/ds_task.c
dataswarm/src/manager/ds_task.h
dataswarm/src/manager/ds_task_info.c
dataswarm/src/manager/ds_task_info.h
dataswarm/src/manager/ds_txn_log.c
dataswarm/src/manager/ds_worker_info.c
dataswarm/src/manager/ds_worker_info.h
dataswarm/src/scripts/ds_graph_workers
dataswarm/src/tools/ds_example.c
dttools/src/list.c
dttools/src/list.h

Simplified, reordered, and renamed some of the data structures in the manager.

DS: Manager Structures

---

doc/man/m4/condor_submit_workers.m4
doc/man/m4/pbs_submit_workers.m4
doc/man/m4/sge_submit_workers.m4
doc/man/m4/slurm_submit_workers.m4
doc/man/m4/torque_submit_workers.m4
doc/man/md/condor_submit_workers.md
doc/man/md/pbs_submit_workers.md
doc/man/md/sge_submit_workers.md
doc/man/md/slurm_submit_workers.md
doc/man/md/torque_submit_workers.md
work_queue/src/condor_submit_workers
work_queue/src/work_queue_submit_common

Also had to edit condor_submit_workers to not overwrite the submit_dir

Add scratch-dir option to work_queue_submit_common

---

dataswarm/src/bindings/python3/dataswarm.binding.py
dataswarm/src/examples/ds_example_blast.c
dataswarm/src/examples/ds_example_gutenberg.c
dataswarm/src/examples/ds_example_mosaic.c
dataswarm/src/manager/dataswarm.h
dataswarm/src/manager/dataswarm_json.c
dataswarm/src/manager/dataswarm_json.h
dataswarm/src/manager/ds_file.c
dataswarm/src/manager/ds_manager.c
dataswarm/src/manager/ds_manager_put.c
dataswarm/src/manager/ds_task.c
dataswarm/src/manager/ds_txn_log.c
dataswarm/src/worker/ds_process.c
dataswarm/src/worker/ds_sandbox.c
dataswarm/src/worker/ds_worker.c
dataswarm/test/ds_test.py
doc/cctools.doxygen
doc/cctools.doxygen.config

Add the DS API to doxygen, clean up several documentation issues, and rename several functions for clarity.

DS API Cleanup

---

dataswarm/src/bindings/python3/dataswarm.binding.py
dataswarm/src/bindings/python3/dataswarm.i
dataswarm/src/examples/ds_example_blast.c
dataswarm/src/examples/ds_example_gutenberg.c
dataswarm/src/examples/ds_example_mosaic.c
dataswarm/src/examples/ds_example_watch.c
dataswarm/src/manager/dataswarm.h
dataswarm/src/manager/ds_manager.c

Three log types now named and used consistenty:
- ds_specify_debug_log produces detailed manager behavior
- ds_specify_perf_log produces the performance log which can be graphed
- ds_specify_transaction_log produces the transactions of tasks and files.

DS Logging API

---

dataswarm/src/bindings/python3/dataswarm.binding.py
dataswarm/src/examples/ds_example_blast.c
dataswarm/src/examples/ds_example_gutenberg.c
dataswarm/src/examples/ds_example_mosaic.c
dataswarm/src/examples/ds_example_watch.c
dataswarm/src/manager/dataswarm.h
dataswarm/src/manager/dataswarm_json.c
dataswarm/src/manager/ds_catalog.c
dataswarm/src/manager/ds_manager.c
dataswarm/src/manager/ds_manager_get.c
dataswarm/src/manager/ds_manager_put.c
dataswarm/src/manager/ds_task.c
dataswarm/src/manager/ds_txn_log.c
dataswarm/src/manager/ds_txn_log.h
dataswarm/src/tools/ds_benchmark.c
dataswarm/src/tools/ds_status.c
dataswarm/src/worker/ds_worker.c
dataswarm/test/ds_test.py

Update file api to put input/output in the function name instead of DS_INPUT/DS_OUTPUT.

DS File API update

---

doc/manuals/taskvine/examples/vine_python_function.py
doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/bindings/python3/vine_futures.py
taskvine/src/examples/vine_example.py
taskvine/src/examples/vine_example_blast.c
taskvine/src/examples/vine_example_futures.py
taskvine/src/examples/vine_example_gutenberg.c
taskvine/src/examples/vine_example_mosaic.c
taskvine/src/examples/vine_example_pythontask.py
taskvine/src/examples/vine_example_watch.c
taskvine/src/manager/taskvine.h
taskvine/src/manager/taskvine_json.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_get.c
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/manager/vine_txn_log.c
taskvine/src/tools/vine_benchmark.c
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_watcher.c
taskvine/src/worker/vine_worker.c
taskvine/test/vine_alloc_test.py
taskvine/test/vine_python_task.py
taskvine/test/vine_test.py
taskvine/test/vine_test_tag.py

For #3004 
specify to add, set, and enable. 
I still need to go through each exposed function and maybe propose a better name (e.g. more regular names). But I think we can merge this one before the better names in order to reduce conflicts with other prs.

Vine api rename

---

batch_job/src/vine_factory.c

Added `--debug-workers` which now saves a separate log file for each worker, if you are trying to troubleshooting.

Vine: Improved Factory Debug

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_resources.c
taskvine/src/manager/vine_resources.h
taskvine/src/manager/vine_schedule.c
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h
taskvine/src/worker/vine_coprocess.c
taskvine/src/worker/vine_coprocess.h
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_process.h
taskvine/src/worker/vine_worker.c

This PR ports over all the serverless functionality from WQ to TaskVine. Still need to fix worker/task resources.

Taskvine Serverless

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/Makefile
taskvine/src/examples/poncho_package_run
taskvine/src/examples/python_example.py
taskvine/src/examples/vine_example_unponcho.c
taskvine/src/examples/vine_example_unponcho_task.c
taskvine/src/examples/vine_example_unponcho_worker.c
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c

added the function for a poncho unpack mini task

adds unponcho mini task

---

taskvine/src/manager/Makefile
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_remote_file_info.c
taskvine/src/manager/vine_remote_file_info.h
taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_transfer_server.c
taskvine/src/worker/vine_worker.c

Initial stages of implementing peer transfer in taskvine

TaskVine Peer Transfer

---

makeflow/src/starch
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c

Added mini-task for unpacking starch archives.

Vine: Unstarch File Wrapper

---

taskvine/src/manager/vine_txn_log.c
work_queue/src/work_queue.c

Vine/WQ: Write to transactions log with a single fprintf/fflush.

---

batch_job/src/work_queue_factory.c

Simplified to always run the worker contained in the image. This is a transitional change while we determine the best way to declare images in the factory for general use (not only in ND).
I also rewrote a shorter version runos in bash. The old runos was a python2 program, and python2 is not available in the rhel8 installations at ND. We could update it to python3, but then it wouldn't work in the machines still running rhel7. (So we end up needing a runos for runos...)

wq factory runos simplification

---

doc/manuals/taskvine/index.md

Bringing the Vine manual up to date with the current API.

Vine Manual Updates (WIP)

---

dttools/test/test_runner_common.sh
work_queue/src/work_queue_worker.c
work_queue/test/TR_work_queue_remotetask.sh

Also, num_coprocess to coprocess-total

wq: coprocess options _ to -

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example.py
taskvine/src/examples/vine_example_blast.py
taskvine/src/examples/vine_example_gutenberg.py
taskvine/src/examples/vine_example_map.py
taskvine/src/examples/vine_example_mosaic.py
taskvine/src/examples/vine_example_pair.py
taskvine/src/examples/vine_example_tree_reduce.py
taskvine/src/examples/vine_example_watch.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_manager.c

Changed work_queue, and queue in API doc and error messages.
Removed incorrect IOError try-except in all python examples.

py: vine examples fix error messages

---

poncho/src/poncho/package_create.py
poncho/src/poncho_package_create

Some of the initial Mamba additions for #2974 . Have to do some test to make sure everything is fleshed out.

Poncho: Use Mamba for Resolution

---

taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_task.c
taskvine/test/vine_test.py

Now works like this:
```
a = FileBuffer("input data")
b = FileBuffer()
...
t.add_input(a,"input.txt")
t.add_output(b,"output.txt")
...
print(b.contents())
```

Vine: Simplified Output Buffer API

---

taskvine/src/manager/vine_manager.c

fix issue with old substitute file getting scheduled

Vine: minitask input file transfer fix

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c

Feedback and naming suggestions welcome. Working properly.

Vine: Peer Transfer Flags in vine_file

---

taskvine/src/examples/vine_example_blast.py

Include Python but not C version so far.

Vine: More realistic Blast example

---

taskvine/src/manager/vine_manager.c

For worker replicas not yet declared at the manager the file structure does not exist. This cause a segfault when cleaning up the worker.

guard against worker replicas not yet declared at the manager

---

poncho/src/poncho/package_create.py
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_chirp.py
taskvine/src/examples/vine_example_map.py
taskvine/src/examples/vine_example_poncho.c
taskvine/src/examples/vine_example_pythontask.py
taskvine/src/examples/vine_example_xrootd.py
taskvine/src/manager/vine_file.c

Following #3208 but for poncho

Poncho run_in_env

---

poncho/src/poncho_package_serverize
taskvine/src/bindings/python3/taskvine.binding.py
taskvine/src/examples/vine_example_gradient_descent.py

Changed env_path to env to match rest of code.
Added command line arguments (e.g. --iterations) to example to easily test with one worker from command line.
Added missing cache=True to envs and library codes.

vine library: small changes to function docs, example with command line arguments

---

taskvine/src/tools/vine_plot_txn_log

As reported by @BarrySlyDelgado

vine plot: fix issue where ticks did not respect origin

---

poncho/src/poncho/package_serverize.py
taskvine/src/worker/vine_coprocess.c
taskvine/src/worker/vine_coprocess.h
taskvine/src/worker/vine_process.c

Serverless sandbox fix

---

dttools/src/category.c
dttools/src/category.h
makeflow/src/dag_node.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_txn_log.c
taskvine/test/TR_vine_auto_modes.sh
taskvine/test/auto_modes.py
work_queue/src/work_queue.c

Fix auto mode

---

taskvine/src/bindings/python3/taskvine.binding.py
work_queue/src/bindings/python3/work_queue.binding.py
work_queue/src/work_queue.c
work_queue/test/TR_work_queue_allocations.sh
work_queue/test/TR_work_queue_auto_modes.sh
work_queue/test/auto_modes.py
work_queue/test/wq_alloc_test.py

Backport some fixes from vine to wq:
- Specify manager in wq.Factory
- Add test for auto modes
- Correctly use proportional resources in all cases
- API to check if manager is using ssl

wq updates

---

taskvine/src/tools/vine_plot_txn_log

Add a mode to vine_plot_txn_log to show some statistics.

add stats mode to plot_txn_log

---

taskvine/src/examples/vine_example_gradient_descent.py

Changed around some resource allocations in the example and allowed the number of tasks to be passed as an argument on the command line.

Reproducibility edits to BGD example

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py

This allows remote debugging while task is running.

pythontask: explicit bring back stdout

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/manager/vine_manager.c

Each task graph gets a unique tag that can be waited with `wait_for_tag`.

Tag per task graph

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_put.c

Initial work on issue #3282 
Normal input files sent by the manager are properly considered for peer transfers now

Vine: Peer Transfer Fixups

---

work_queue/src/work_queue.c

backporting the recent optimization in taskvine to work queue

workqueue: use reduced rmsummary operations

---

doc/man/m4/vine_submit_workers.m4
doc/manuals/taskvine/index.md

Fix more docs and add man page for `vine_submit_workers`

Vine: Fix more vine doc

---

taskvine/src/manager/vine_task.c

For #3130. Adds environment variables to task json.

Task to json: add env variables

---

poncho/src/poncho/package_create.py

Remove a redundant closing parenthesis so code runs again.

poncho: fix typo

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/test/TR_vine_function_call.sh
taskvine/test/vine_function_call.py

This PR fixes issue #3417, updates example code, and adds test code.
Do all files with prefix `TR_` get tested? I'm not sure. The test code is very similar to `python_task` though.

TaskVine: fix FunctionCall API, update example, and add test

---

taskvine/src/worker/vine_transfer.c

This PR fixes #3448 and #3446.

Vine: make sure file is fsync'ed at worker

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_process.h
taskvine/src/worker/vine_worker.c

Laying the ground work to do clean handling of different process capabilities.

Vine: Explicit Process Type Field

---

taskvine/src/manager/vine_manager.c

removed remaining usage of task_state_any.
Will discuss if there is anything to do with task_state_any_with_tag

vine: avoid linear scheduling operations

---

taskvine/src/manager/vine_manager.c

- A failed library task goes into the RETRIEVED state, and then eventually into the DONE state in one place in vine_wait.
- A created library task goes into the master task table with an extra reference.  It is properly deleted twice, once in change_task_state when it is removed, and again in vine_wait when it goes to DONE.

Vine: Fix Handling of Failed Library Tasks

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Fix for - Vine: Make Tunable Values #3466

Fixed - Vine: Make Tunable Values #3466

---

.github/PULL_REQUEST_TEMPLATE.md

This text should help contributors be clear in explaining their changes.
Inspired by [this](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and [this](https://github.com/Parsl/parsl/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

Repo: add default text for PRs

---

taskvine/src/worker/vine_worker.c

This check is added to prevent seg faults when a regular task is unintentionally checked.

Vine: Add Library Check

---

taskvine/src/worker/vine_cache.c

delete uncached files on manager disconnect

---

environment.yml

environment.yml installs all relevant dependencies through local testing. Should be tested further
What is the best way to go about editing the documentation on the website, and for 'for developers' page

environment.yml 

---

taskvine/src/tools/vine_status.c

vine: vine_status bugfix

---

doc/manuals/install/index.md
environment.yml

Updated index.md to show installation of conda dependencies via environment.yml - will update CCTools documentation website

Update index.md and environment.yml

---

taskvine/src/tools/vine_plot_txn_log

This is a clean one without additional unrelated commits! 

Vine: dask-colors option

---

taskvine/src/worker/Makefile
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker.h
taskvine/src/worker/vine_workspace.c
taskvine/src/worker/vine_workspace.h

Factor out workspace creation and management, in order to set up some future work to better handle when/where files get cleaned up.

Vine: Refactor Workspace

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
doc/manuals/taskvine/index.md
taskvine/src/worker/vine_worker.c

- Add section to documentation describing how features (already present) work.
- Make worker display the GPU feature (already reported) on the console.
- Update Vine and WQ factories with `--feature` option that passes the same to the workers.

Vine: Make Task Features More Visible

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py

Fix doc, resource mode default value and error message.

Dask small fixes

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Daskvine call

---

poncho/src/poncho/package_analyze.py
poncho/src/poncho/package_create.py
poncho/src/poncho/package_serverize.py

Reformat poncho sources to the python standard so that it is easier to read/edit.

fix poncho package sources

---

taskvine/nopen/Makefile
taskvine/nopen/README.md
taskvine/nopen/lib-nopen.c
taskvine/nopen/lib-nopen.h
taskvine/src/bindings/python3/ndcctools/taskvine/task.py

* Added the files for nopen under the taskvine directory
* Added Read Me
* Added the ability to set environment variables to set how nopen handle violations
* Removed testing files from previous PR

adding nopen with python method

---

taskvine/src/tools/vine_plot_txn_log

vine: LIBRARY parsing issue with vine_plot_txn_log

---

configure
poncho/src/Makefile
poncho/src/poncho/library_network_code.py
poncho/src/poncho/setup.py
poncho/src/poncho/wq_network_code.py
resource_monitor/src/bindings/Makefile
resource_monitor/src/bindings/python3/example_client_with_decorator.py
resource_monitor/src/bindings/python3/example_deep_fork.py
resource_monitor/src/bindings/python3/example_simple_limit.py
resource_monitor/src/bindings/python3/ndcctools/__init__.py
resource_monitor/src/bindings/python3/ndcctools/resource_monitor.py
taskvine/src/bindings/python3/Makefile
taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/bindings/python3/ndcctools/taskvine/utils.py

Options to flake8 are set in a single place in the configure file. The number of exceptions have been reduced and python files have been fixed appropriately.

Lint consolidation

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Vine small fixes

---

work_queue/src/bindings/python3/ndcctools/work_queue_dask.py

wq: dask+wq ignore vine options to facilitate testing

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c

Factory: Use --poncho-env b/c it only takes poncho packages.

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Vine: set framework as dask when using DaskVine

---

taskvine/src/manager/vine_file.c

Remove a refcount cycle where the recovery task and the temp file pointed to each other.

vine: correctly gc temp files on refcount

---

poncho/src/poncho_package_run

Poncho: have poncho fail if mkdir fails

---

doc/man/md/poncho_package_create.md

regenerate poncho_package_create md

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py

vine: fix extra arg in remove_file

---

taskvine/src/tools/vine_graph_log

Rename WQPlot to VinePlot in vine_graph_log

WQPlot -> VinePlot

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_perf_log.c
taskvine/src/manager/vine_worker_info.h
taskvine/src/tools/vine_graph_log

aggregates the disk space used by the cache of all the workers

vine: adds stat inuse_cache

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
deltadb/src/catalog_export.c
deltadb/src/catalog_server.c

work_queue_factory and vine_factory now report owner and version to the catalog server,
in the same way as the manager process does.  Motivated to help with recent factory troubleshooting issue.

Factory: Report Owner and Version

---

deltadb/src/catalog_export.c
deltadb/src/catalog_server.c

- Accept a request where the connection is closed immediately.  (Apparently Safari does this.)
- Clean up a few HTML formatting issues.

Catalog: Misc Issues

---

doc/manuals/taskvine/index.md

add a taskvine/parsl example with a remote execution configuration

taskvine doc: add a parsl condor example

---

taskvine/src/tools/vine_graph_log

Adds -D to plot from first task dispatch and -l to plot logscale.

vine_graph_log: Plot from dispatch

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/file.py
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/test/vine_python_futures.py

vine: remove files as results are checkpointed in dask_executor

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Bug fix, call method from correct attribute.

vine: use _file.source instead of .source (dask executor)

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: drop task ref as soon as possible

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/examples/vine_example_dask_awk_array.py
taskvine/src/examples/vine_example_dask_graph.py

- Fixed some small issues on DaskVine library
- Updated an example on doc for DaskVine
- Fix #3666 

Vine: DaskVine Doc Example

---

taskvine/src/manager/vine_file_replica_table.c

Fix temp replica count to be able to replicate more than 1 copy

vine: fix replica count bug

---

taskvine/src/tools/vine_plot_txn_log

Instead of re-parsing the log for library ids, catch an exception when a task did not have a corresponding ready event.
Also add a fallback for incorrectly set start time.

vine: plot tx cleanup

---

taskvine/test/vine_python_future_funcall.py
taskvine/test/vine_python_future_pythontask.py

vine: use port range in futures test

---

taskvine/src/manager/vine_manager.c

Fix several aspects of handle_cache_invalid:
- Don't try to parse the transfer id, just read back the string.
- Both forms of cache-invalid should remove a replica from the table.
- An improperly formatted message should result in a failure.

Vine: Fix Up Handling of cache-invalid

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c

Library minor fixes

---

taskvine/src/manager/vine_manager.c

vine: chech start time in seconds

---

taskvine/src/manager/vine_file_replica_table.c

vine: fix peer_addr double free

---

taskvine/src/manager/vine_manager.c

vine: delete workflow files on worker disconnection

---

parrot/src/pfs_sys.cc

parrot: fix new compiler strict warnings

---

taskvine/src/manager/vine_manager.c

Replica sets were not being updated on worker removal.

vine: update replica sets when worker is removed

---

dttools/src/hash_table.c
dttools/src/set.c

guard div zero for random bucket starts

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: use environment for library tasks in dask_executor

---

doc/manuals/taskvine/index.md
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_file_replica.c
taskvine/src/manager/vine_file_replica.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_manager_put.c
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h

@colinthomas-z80: same as #3709
Couldn't add fixes to colin's master. 

Last transfer failure

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: only checkpoint DaskVineFile's

---

dttools/src/interfaces_address.c
taskvine/src/worker/vine_worker.c
work_queue/src/work_queue_worker.c

copy manager addrs with DOMAIN_NAME_MAX limit

---

taskvine/src/manager/vine_current_transfers.c
taskvine/src/manager/vine_current_transfers.h
taskvine/src/manager/vine_manager.c

vine: set transfer failure on cache invalid

---

taskvine/src/tools/vine_submit_workers
work_queue/src/condor_submit_workers

adds spool to wq condor_submit_workers

---

doc/manuals/taskvine/index.md

readthedocs mkdocs didn't find the files

vine doscs: directly include example code

---

dttools/src/link.c
dttools/src/link.h
taskvine/src/worker/vine_transfer_server.c
taskvine/src/worker/vine_transfer_server.h
taskvine/src/worker/vine_worker.c
taskvine/src/worker/vine_worker_options.c
taskvine/src/worker/vine_worker_options.h

Peer custom ports

---

configure

fix configure help message

---

doc/man/m4/resource_monitor.m4
doc/man/md/resource_monitor.md
resource_monitor/src/resource_monitor.c

rmonitor: update summary file as excutable runs with --update-summary

---

taskvine/src/worker/vine_worker.c
work_queue/src/work_queue_worker.c

vine: use worker start time in usecs as rand seed

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: add the extra input files to lib tasks

---

taskvine/src/manager/vine_task.c

vine: fix small mem leak when adding task context

---

taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_task.c
taskvine/src/worker/vine_worker.c

Also fixes a bug where if a task both required and provided a library, the scheduler would go into an infinite loop.

vine: task library to follow set/get convention.

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Daskvine ease taskvine

---

doc/manuals/taskvine/index.md

Update the documentation for the integration with Parsl as it has a new way to clean up resources once done.

Doc: fix documentation for Parsl integration

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Consider only q->attemp_schedule_depth temp files when requesting replicas.

vine: limit temp replica requests per cycle

---

environment.yml
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

vine: minor dask vine fixes

---

batch_job/src/condor_chaos_monkey

Condor: Chaos Monkey Small Fix

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

Fixes conflicts of #3804
(@colinthomas-z80, for your future prs please submit them from a branch different from master to make it easier to resolve conflicts.)

library_cleanup

---

resource_monitor/src/bindings/python3/ndcctools/resource_monitor.py

vine: do not hash functions with @monitored decorator

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/examples/vine_example_dask_graph.py
taskvine/src/examples/vine_example_dask_wrap_fn.py

Add a wrapper to dask calls for debugging (e.g. trace memory)

Daskvine instrument

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

Simplify by moving wrapping code into execute vertex.

vine: add wrapper to funcalls in dask executor

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

It does not play well with overcommitment.

vine: do not use rampdown heuristic by default (dask executor)

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_schedule.c

vine: Set library types

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py

otherwise it keeps using the buffer as the file is never vine_file_delete'd

vine: fn call write input to disk if output survives task

---

doc/manuals/taskvine/index.md
taskvine/src/bindings/python3/ndcctools/taskvine/futures.py

This PR fixes four of the six issues discussed in #3835 (specifically, 1, 2, 4, and 5).

vine: fix doc typos, code typos, and callback signatures for `FuturesExecutor`

---

.github/workflows/integration.yml
packaging/build-docker/generate-images

activate almalinux9

---

makeflow/example/example.README
makeflow/example/example.categories.makeflow
makeflow/example/example.json
makeflow/example/example.jx
makeflow/example/example.makeflow
makeflow/example/example.mount
makeflow/example/example.mount.makeflow
makeflow/example/makeflow_umbrella/convert_S.umbrella
makeflow/example/makeflow_umbrella/example.makeflow
makeflow/example/makeflow_umbrella/example_in_makefile.makeflow
makeflow/example/makeflow_umbrella/umbrella_specs/convert_S_category1.umbrella
makeflow/example/makeflow_umbrella/umbrella_specs/convert_S_category2.umbrella
makeflow/test/syntax/directives.makeflow
makeflow/test/syntax/directives_bad_value.makeflow
makeflow/test/syntax/directives_unsupported.makeflow
makeflow/test/syntax/remote_name.makeflow
makeflow/test/syntax/test.makeflow
makeflow/test/syntax/typo.makeflow

http to https makeflow examples

---

taskvine/src/manager/vine_manager.c

vine: correctly account for time/stats in no_wait

---

taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
taskvine/src/bindings/python3/ndcctools/taskvine/file.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/ndcctools/taskvine/task.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_fair.c
taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_runtime_dir.c
taskvine/src/manager/vine_runtime_dir.h

Only functions in taskvine.h are used in the python bindings.

Clean up swig bindings

---

taskvine/src/manager/vine_cached_name.c
taskvine/src/manager/vine_file.c

vine: compute hash only when cache level requires it

---

doc/manuals/taskvine/index.md
poncho/src/poncho/library_network_code.py
taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
taskvine/src/bindings/python3/taskvine.i
taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_runtime_dir.c
taskvine/src/manager/vine_task.c
taskvine/src/manager/vine_task.h
taskvine/src/worker/vine_process.c
taskvine/src/worker/vine_worker.c

vine: handle library failures

---

doc/manuals/taskvine/index.md
doc/manuals/work_queue/index.md

Give C compile command relative to CONDA_PREFIX
Fixes #2929

Doc: Fix Vine/WQ Compile Instructions

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
taskvine/src/manager/vine_manager.c
work_queue/src/work_queue.c

Both work_queue and vine_manager now report protocol versions to the catalog, which is checked by the factory, so as to avoid submitting incompatible workers.  Fixes #1341

Factory: Check protocol version before submitting workers.

---

doc/man/m4/chirp.m4
doc/man/m4/chirp_distribute.m4
doc/man/m4/chirp_fuse.m4
doc/man/m4/chirp_get.m4
doc/man/m4/chirp_put.m4
doc/man/m4/chirp_server.m4
doc/man/m4/chirp_stream_files.m4
dttools/src/auth_all.h

List all authentication methods in header docs.  Fixes #3182 

Doc: Add Auth Modes to Man Pages

---

batch_job/src/batch_job.c
batch_job/src/batch_job.h
batch_job/src/batch_job_condor.c
batch_job/src/batch_job_vine.c
batch_job/src/batch_job_work_queue.c
batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c
doc/man/m4/makeflow.m4
doc/manuals/makeflow/index.md
makeflow/src/makeflow.c

Added support for ssl key and cert in batch_job and makeflow. Fixes #2747 

Makeflow: Add SSL Key/Cert for WQ/Vine

---

.github/workflows/integration.yml

disable centos7

---

dttools/src/gpu_info.c

Update GPU detection to check exit status of nvidia-smi command.
Otherwise this can result in the perceived detection of a GPU called "Failed to initialize NVML".
(Happening on my machine this morning after an upgrade.)

Better error handling for GPU detection.

---

batch_job/src/batch_job_dryrun.c

fix calloc arguments, batch_job_dryrun

---

taskvine/src/worker/vine_worker.c

vine: fix task disk measurement

---

doc/man/m4/makeflow.m4
doc/man/md/makeflow.md

Add in man page entries that should have been in prior PR.

Makeflow: Man page bits for SSL.

---

doc/README.md
doc/man/md/allpairs_master.md
doc/man/md/sand_align_master.md
doc/man/md/sand_filter_master.md
doc/man/md/vine_factory.md
doc/man/md/vine_worker.md
doc/man/md/wavefront_master.md
doc/man/md/work_queue_factory.md
doc/man/md/work_queue_worker.md

Missed this earlier step in doc update.  Changes to the m4 files require checking in the changed output md files, so that they are easily incorporated into the readthedocs manual.

Doc: Update MD to match M4

---

batch_job/src/vine_factory.c
batch_job/src/work_queue_factory.c

fix bug in vine/wq factories omitting user specified resources 

batch job: set resources in wq/vine factories

---

work_queue/src/bindings/python3/Makefile

wq: install py example in correctd directory

---

taskvine/src/tools/vine_submit_workers

Added poncho package support to vine_submit_workers

---

batch_job/src/vine_factory.c

Added missing help options ins vine_factory

---

doc/manuals/taskvine/index.md

update doc to include task_mode for DaskVine

---

chirp/src/chirp_fuse.c
chirp/test/TR_chirp_fuse.sh
configure
doc/man/m4/chirp_fuse.m4
doc/man/md/chirp_fuse.md
grow/src/grow_fuse.c

Chirp to fuse3

---

taskvine/src/manager/vine_manager.c

This PR eliminates this warning message:

vine: send protocol version in manager_lean_to_jx

---

chirp/test/TR_chirp_fuse.sh

chrip_fuse: in test, do not recursevely rm

---

.github/PULL_REQUEST_TEMPLATE.md

Correct grammar in PR template and add some visibility to the text.

Enhancement: correct PR template on github

---

.github/workflows/testing.yml

macos amd 12 to 14

---

resource_monitor/src/Makefile

rmonitor: do no try to install when crosscompiling

---

taskvine/src/bindings/python3/ndcctools/taskvine/futures.py

fix bug where FuturePythonTask not added to table

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

This helps to relate a library log file to a task in `debug` file

vine: use taskid to name library log file

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_schedule.c

- Replace the `printf` statements with a better printing format using `debug(D_NOTICE)` 
- Add braces to some of the`if` statements

vine: replace printf with debug(D_NOTICE)

---

taskvine/src/worker/vine_worker.c

Fix bug: An async message larger than the total window size should be sent regardless, otherwise it would wait forever.
This does not fix any immediate problem that we have, but is a latent bug waiting to bite...

Vine: Latent Bug in Async Message Send

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h

vine: track running libraries on the worker

---

taskvine/src/bindings/python3/ndcctools/taskvine/__init__.py
taskvine/src/bindings/python3/ndcctools/taskvine/compat/__init__.py
taskvine/test/TR_vine_task_graph_compat.sh
taskvine/test/vine_task_graph_compat.py

PR to use daskvine compat mode if there is no dask, or if the dask too old.

Dask compat  fallback

---

taskvine/src/bindings/python3/ndcctools/taskvine/task.py

vine: python task: print traceback on error

---

doc/manuals/taskvine/index.md

vine manual spelling errors

---

taskvine/src/manager/vine_manager.c
work_queue/src/work_queue.c

wq: add protocol version to lean catalog report.

---

taskvine/src/bindings/python3/ndcctools/taskvine/display.py

manager status does not generate that info anymore

vine: remove largest from display

---

poncho/src/poncho/package_create.py

poncho: make sure conda is not interactive

---

taskvine/src/manager/vine_manager.c

vine: add time info to lean report as needed by web status

---

taskvine/src/worker/vine_cache.c

vine: trash transfer path properly

---

batch_job/src/vine_factory.c

vine: only set condor spool when appropriate

---

dttools/src/list.c

format: new clang version errors

---

taskvine/src/worker/vine_worker.c

I believe this was initially a typo ...

vine: chech p_future instead of p

---

taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h
taskvine/src/manager/vine_worker_info.c
taskvine/src/manager/vine_worker_info.h

vine: change `workers_with_complete_tasks` from table to list.

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_dag.py
taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

daskvine: fix how Alias is handled.

---

doc/manuals/taskvine/index.md

vine doc: typo outfile -> output

---

taskvine/src/manager/vine_runtime_dir.c

vine: increase buffer size for runtime_dir

---

taskvine/src/manager/vine_manager.c

vine: do not remove items when iterating hash_table

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_cache.h
taskvine/src/worker/vine_worker.c

vine: periodically process pending transfers

---

taskvine/src/worker/vine_cache.c

vine: Update cache on invalid xfer

---

taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py

update retry call to dictionary for new dask

---

taskvine/src/worker/vine_cache.c
taskvine/src/worker/vine_transfer.c
taskvine/src/worker/vine_transfer.h
taskvine/src/worker/vine_worker.c

vine: more detailed cache-invalid messages

---

taskvine/src/manager/vine_manager.c

Otherwise we get a notice message which is confusing as it seems that there is a problem with the monitor, rather than the tasks not running at all.

vine: do not try to read monitor info on missing input

---

.github/workflows/testing.yml

Nightly builds

---

.github/workflows/testing.yml

fix missing postfix name

---

.github/workflows/testing.yml

set branch vars

---

taskvine/src/manager/vine_file_replica_table.c

vine: fix double counting of replica size in vine_file_replica_table_insert

---

taskvine/src/manager/vine_file.c
taskvine/src/manager/vine_file.h
taskvine/src/manager/vine_manager.c

vine: record original task id for temp files

---

doc/manuals/taskvine/example-obspy.md
doc/manuals/taskvine/index.md
taskvine/src/examples/vine_example_obspy.py
taskvine/src/examples/vine_example_poncho_in_python.py

Added a taskvine example that uses ObsPy to process seismic data using some MiniSEED files available in the examples repository provided by ObsPy.
Also a small typo fix.

Vine: Added an obspy example

---

taskvine/src/manager/taskvine.h
taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager.h

vine: add testing parameters

---

taskvine/src/worker/vine_cache_file.c

For #4202
A quick fix but not sure if it's the solution

vine: check if f is valid

---

taskvine/src/manager/vine_txn_log.c

vine: use cached_name in transactions log

---

dttools/src/link.c

dttools: link handle port 0

---

taskvine/src/manager/vine_current_transfers.c
taskvine/src/worker/vine_cache.c

vine: ensure response for every unlink

---

devel/pledge/src/enforcer.c
devel/pledge/src/list_util.c
devel/pledge/src/list_util.h
devel/pledge/src/pledge.c
devel/pledge/src/util.c

- Now we can accept all the new flags and deal with them
- We can generate all new flags except list
- We can deal with the flags in the enforcer
- flag2letter() now uses a buffer and not chars
- We now use bitflags with enforce() and not chars
- Added remove() wrapper
- Tracer can now dump all types of accesses except list (getdents)
- We handle naming of contracts and logs properly now

Added new features:

---

taskvine/src/manager/vine_file_replica_table.c
taskvine/src/manager/vine_file_replica_table.h
taskvine/src/manager/vine_manager.c
taskvine/src/manager/vine_manager_get.c
taskvine/src/manager/vine_manager_put.c

vine: replicas struct created only in table

---

devel/pledge/README.md
devel/pledge/src/list_util.c
devel/pledge/src/list_util.h

This commit is to add the initial statistics about the I/O patterns, for now we have how many times a file has been accessed throughout the tracing process.

PLEDGE: Added initial path/file access statistics

---

.github/workflows/testing.yml

fix CI var typo

---

devel/pledge/README.md
devel/pledge/TODO
devel/pledge/src/enforcer.c
devel/pledge/src/list_util.c
devel/pledge/src/list_util.h
devel/pledge/src/pledge.c

- This parser saves every path in a line and lets us pick and choose which to save
- Statistics are accurate now ones to use

PLEDGE: New strace parser

---

taskvine/src/manager/vine_manager.c

Renamed several functions and cleaned up a few comments to facilitate understanding the source code.  Will be sending a few updates like this in advance of doing some more general code refactoring.

Vine: Source Code Clarifications
